### ISSUE TITLE
Allow generating license information in `.app`

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [ninenines/erlang.mk#1001]
As per what was discussed in https://github.com/ninenines/cowboy/issues/1651, this issue's goal is to be a reference for future discussion around implementing an `erlang.mk` "system" that allows populating `.app` with license information that can be used both by Hex.pm and `rebar3_sbom`, for example.

## Example expectation

It could look something like

```
# erlang.mk
LICENSE = ISC
```

after which e.g. target `ebin/$(PROJECT).app` could generate output such as

```erlang
{licenses, ["ISC"]}
```

## Further considerations

The license information could be detected from an existing `LICENSE` file (as proposed by @essen in the linked issue) and extracted using `licensee` and `jq`. It should also be possible to cache this information (and read from the cache, when available) so as to not call the same "system" over and over at compile time.

**Comment by paulo-ferraz-oliveira** [comment]
In the meantime, https://github.com/voltone/rebar3_sbom v0.8.0 came out, so we can already fetch info. from `hex_metadata.config` files, which e.g. Hex-based cowboy packs.

**Comment by essen** [comment]
Probably not worth adding to .app file in that case. For Hex we have the variable `HEX_TARBALL_EXTRA_METADATA` to add data and Cowboy already adds its license there. I don't think there's anything needed to do, do you agree?

**Comment by paulo-ferraz-oliveira** [comment]
I agree. This is closable. Thanks.
