### ISSUE TITLE
case_clause in dep_autopatch_rebar.erl when transforming git_subdir

### ISSUE THREAD

**Issue by rlipscombe** [ninenines/erlang.mk#1004]
Rebar 3.14 added `git_subdir` to its supported dependency formats. See https://rebar3.org/docs/configuration/dependencies/. These have 4 elements. This causes `dep_autopatch_rebar.erl` to fail with the following error:

```
Runtime terminating during boot ({{case_clause,{git_subdir,"https://github.com/whatsapp/eqwalizer.git",{branch,"main"},"eqwalizer_support"}},...
```

rebar.config references eqWAlizer, following the instructions here: https://github.com/whatsapp/eqwalizer?tab=readme-ov-file#using-it-with-rebar3-projects

In the case of eqwalizer, because it's only used at build-time, I can probably work around this with a rebar profile that erlang.mk will ignore. But with other `git_subdir` dependencies, such as opentelemetry-erlang, this won't be feasible.

**Comment by essen** [comment]
It should be straightforward to add support for `git_subdir` as we already have `git-subfolder` as a dependency fetch method. Would only need minor refactoring on top, if you want to do it. The action is here: https://github.com/ninenines/erlang.mk/blob/master/core/deps.mk#L463-L471

**Comment by essen** [comment]
Probably best to add a clause immediately above https://github.com/ninenines/erlang.mk/blob/master/core/deps.mk#L462 that matches on `git_subdir` and does the corresponding write.

**Comment by rlipscombe** [comment]
This is against erlang.mk, rather than deps.mk, but you're thinking something like this...?

```
@@ -3988,6 +3988,12 @@ define dep_autopatch_rebar.erl
 			GetHexVsn3Common(N, NP, S0);
 		(N, NP, S) -> {N, {hex, NP, S}}
 	end,
+	ConvertCommit = fun
+		({branch, C}) -> C;
+		({ref, C}) -> C;
+		({tag, C}) -> C;
+		(C) -> C
+	end,
 	fun() ->
 		File = case lists:keyfind(deps, 1, Conf) of
 			false -> [];
@@ -4003,16 +4009,15 @@ define dep_autopatch_rebar.erl
 							_ -> false
 						end of
 					false -> ok;
+					{Name, {git_subdir, Repo, Commit, SubDir}} ->
+						Write(io_lib:format("DEPS += ~s\ndep_~s = git-subfolder ~s ~s ~s~n", [Name, Name, Repo, ConvertCommit(Commit), SubDir]));
 					{Name, Source} ->
 						{Method, Repo, Commit} = case Source of
 							{hex, NPV, V} -> {hex, V, NPV};
 							{git, R} -> {git, R, master};
-							{M, R, {branch, C}} -> {M, R, C};
-							{M, R, {ref, C}} -> {M, R, C};
-							{M, R, {tag, C}} -> {M, R, C};
 							{M, R, C} -> {M, R, C}
 						end,
-						Write(io_lib:format("DEPS += ~s\ndep_~s = ~s ~s ~s~n", [Name, Name, Method, Repo, Commit]))
+						Write(io_lib:format("DEPS += ~s\ndep_~s = ~s ~s ~s~n", [Name, Name, Method, Repo, ConvertCommit(Commit)]))
 				end end || Dep <- Deps]
 		end
 	end(),
```

**Comment by essen** [comment]
Yes something like this.
