### ISSUE TITLE
Git subfolder deps can not be compiled

### ISSUE THREAD

**Issue by luos** [ninenines/erlang.mk#1012]
Hi,

I am not exactly sure what is causing it, but we have some RabbitMQ plugins which can not be compiled with the latest `erlang.mk`. 

The cause is I think most probably this commit: https://github.com/ninenines/erlang.mk/commit/7bf0e7b5f6bd82b5af76d375fb0bf1ffc7ac2b72 

The error is: 

```
root@d591ea7b5989:/repo/plugin-name# gmake
 DEP    rabbit (v3.13.6-plugin-name)
ln -s /repo/plugin-name/.erlang.mk/rabbitmq-server/deps/ /repo/plugin-name/deps/;
ln: failed to create symbolic link '/repo/plugin-name/deps/deps': File exists
gmake: *** [erlang.mk:1285: /repo/plugin-name/deps/rabbit] Error 1
```

Seems to me that it somehow tries to link `rabbitmq-server/deps` to be `plugin/deps` but it should try to link `rabbitmq-server-deps/rabbit` to be `deps/rabbit`. 

Going back to commit `ERLANG_MK_COMMIT=66e970fdbce823f84fce855bb48c2d1fabfcf0ff` fixes the issue.

**Comment by essen** [comment]
Thank you for the feedback! I will address it today.

**Comment by luos** [comment]
Thank you! Did you manage to reproduce it with your plugins? I was not sure if it's caused  because of some custom setup - but last week the same thing worked and I don't think we do anything special. 🙂

**Comment by essen** [comment]
I just pushed the fix. It's custom in the sense that RabbitMQ functions make use of one deprecated define that was removed. I have added it back. I will work on updating the RabbitMQ plugins at a later time. The offending lines are in rabbitmq-components.mk. `dep_name` must be replaced with `query_name`, basically.

**Comment by essen** [comment]
And yes I reproduced it with the delayed exchange message plugin.

**Comment by essen** [comment]
I assume it is fixed. Closing, thanks!
