### ISSUE TITLE
erlang.mk assumes projects with no `Makefile` are `erlang.mk` compatible

### ISSUE THREAD

**Issue by talentdeficit** [ninenines/erlang.mk#146]
this breaks any project that declares required compiler options in `rebar.config`

**Comment by essen** [comment]
1729811327320b0f64e54331d3f469399c6898da added an autopatch feature with a basic set of "patches" to be applied. Testing and feedback will do the rest. Closing this as this is more an open discussion and we have taken steps toward resolution. Thanks to everyone involved!

**Comment by expelledboy** [comment]
Sorry didnt see this. It didnt work. Have actually started using mix as an erlang build tool :) its has a feature where you can define the compile command/script, which allows for flexible building of arbitrary deps. Interesting solution.
