### ISSUE TITLE
Ability to run tests without dependencies update checks

### ISSUE THREAD

**Issue by zamotivator** [ninenines/erlang.mk#171]
Sometime I work without internet from my laptop.

For build application I use "make app", because "make all" trying to check dependencies updates.
But I have no way to run tests without internet, because "make tests" trying to find updates for dependencies.

Can you please do on of the following:
1. Relax make tests dependencies
2. Make explicit command for check dependencies updates and do not update if dependency checked out already
?

**Comment by essen** [comment]
Done in f458e45abf7e114a55272bd494d6a5c13f7c85bc. Thanks!
