### ISSUE TITLE
Cross Compilation

### ISSUE THREAD

**Issue by mbsmith** [ninenines/erlang.mk#174]
Looking for a way to cross compile with this.  Meaning to compile a release for say arm gnuabihf on a x86-64 system.  Including C ports, and such.

I know this probably isn't the place for questions, but Essen asked me to post this as an issue.

Thanks.

**Comment by essen** [comment]
Hey, any news on your efforts?

**Comment by mbsmith** [comment]
I'm in this phase of the project now.  Will have an update within a day or so.

**Comment by essen** [comment]
Awesome. Good luck!

**Comment by essen** [comment]
Any news? :-)

**Comment by essen** [comment]
Cleaning up my tabs, found this: https://erlangcentral.org/wiki/index.php?title=Cross_compiling

**Comment by benoitc** [comment]
Is there anything needed? @mbsmith ping :)

**Comment by essen** [comment]
Out of curiosity what are the source/target platforms you are looking into?

**Comment by benoitc** [comment]
armv7 using  arm-linux-gnueabi. I think. (this is for raspberry 3)

**Comment by essen** [comment]
I see. I don't have this particular hardware but from what I understand, assuming you set the appropriate variables (CC=/usr/bin/that-arm-gcc, possibly others) then `make` should just work. With a project simple enough I could try things out. Any suggestions?

I think Erlang.mk could automate the building of cross-compiled Erlang/OTP and automate their use when building releases, but (and correct me if I'm wrong) I don't think cross-compiling it is needed otherwise so it can come as a second step.

**Comment by essen** [comment]
Actually I just did a try with the NIF we build for testing Erlang.mk (it's not doing much) and it cross-compiles fine, in this case I tried targetting mingw64. The only issue is:

```
priv/test_c_src_nif.so: PE32+ executable (DLL) (console) x86-64, for MS Windows
```

As you can see the file is correct but the file extension isn't.

Erlang.mk does allow you to define `C_SRC_OUTPUT_SHARED_EXTENSION` though.

```
$ CC=/usr/bin/x86_64-w64-mingw32-gcc C_SRC_OUTPUT_SHARED_EXTENSION=.dll make
 DEPEND test_c_src_nif.d
 ERLC   test_c_src_nif.erl
 APP    test_c_src_nif
 C      test_c_src_nif.c
[... bunch of warnings]
 LD     test_c_src_nif.dll

$ file priv/test_c_src_nif.dll                                              
priv/test_c_src_nif.dll: PE32+ executable (DLL) (console) x86-64, for MS Windows
```

Not perfect but at least it seems more than possible with what we have today.

**Comment by benoitc** [comment]
Looks interesting, I can live with that. Last thing, but how do you tell to
erlang.mk where to find a cross compiled erlang? Is theer any variable that
can be given to it?

**Comment by essen** [comment]
That's the part I'm not sure about, though I think it only matters when you are going to build a release, not when building the files.

Other than that I think to solve this ticket we need to write a lot of docs and examples.

**Comment by essen** [comment]
Updated previous comment.

**Comment by essen** [comment]
It works! That's really all there is to it then. I'll document it this week.

**Comment by essen** [comment]
This was done and will be pushed later today or tomorrow.
