### ISSUE TITLE
Support for RabbitMQ AMQP client library

### ISSUE THREAD

**Issue by jhw** [ninenines/erlang.mk#197]
I would love to see a solution that allows erlang.mk to work with rabbitmq client libraries. 

https://www.rabbitmq.com/erlang-client.html

"The Erlang AMQP client library and tests depends on the server and the code-generation library modules"

So: [Makefile]

DEPS = lager cowboy rabbitmq_erlang_client rabbitmq_server rabbitmq_codegen
dep_rabbitmq_erlang_client = hg http://hg.rabbitmq.com/rabbitmq-erlang-client/ default
dep_rabbitmq_server = hg http://hg.rabbitmq.com/rabbitmq-server/ default
dep_rabbitmq_codegen = hg http://hg.rabbitmq.com/rabbitmq-codegen/ default

But:

make[1]: *** No rule to make target `rabbit_common.app', needed by `dist/rabbit_common-0.0.0.ez'. Stop.
make[1]: *** No rule to make target `codegen/amqp_codegen.py', needed by `src/rabbit_framing_amqp_0_9_1.erl'. Stop.

The alternative seems to be to install ampq_client-XX.XX.XX.ez and rabbitmq_common-XX.XX.XX.ez from the same page

https://www.rabbitmq.com/erlang-client.html

What chance being able to install ez deps via wget ?

Right now it's back to rebar. Sad bunny :-(

**Comment by jhw** [comment]
Or failing direct support for .ez files, maybe there's a way to add a hook into the erlang.mk dependency process that allows you to work with non- standard dependencies ? Stuff that isn't git / mercurial based ?

**Comment by essen** [comment]
Considering the error, have you tried downloading from hg and typing "make"? Does it give you the same error?

**Comment by jhw** [comment]
make: *** No rule to make target `rabbit_common.app', needed by `dist/rabbit_common-0.0.0.ez'. Stop.

**Comment by essen** [comment]
Right, I have the same error. And to be sure I followed exactly the instructions at https://www.rabbitmq.com/build-erlang-client.html

Guess you can open a ticket there. :-)

**Comment by jhw** [comment]
Oh, okay. Fair enough. Sorry for the trouble.

**Comment by jhw** [comment]
Apologies for reopening this; if this isn't the right forum for these type of questions then please let me know.

rabbitmq-erlang-client build instructions are as follows

$ hg clone http://hg.rabbitmq.com/rabbitmq-codegen
$ hg clone http://hg.rabbitmq.com/rabbitmq-server
$ hg clone http://hg.rabbitmq.com/rabbitmq-erlang-client
$ cd rabbitmq-erlang-client
$ make

https://www.rabbitmq.com/build-erlang-client.html

So rabbit-codegen and rabbitmq-server seem to be dependencies that do no need to be built.

Could something like this be handled by erlang.mk ?

TIA

**Comment by essen** [comment]
Don't know, and it's not going to do much good if following those exact commands result in an error. :-)

**Comment by jhw** [comment]
But there's no error now. I can build this fine on my machine following the steps above (I didn't do it correctly before; specifically I didn't clone rabbitmq-server and rabbitmq-codegen before building rabbitmq-erlang-client).

What error are you getting ?

**Comment by essen** [comment]
```
essen@alice (0) % cd tmp/rabbit 
essen@alice (0) % hg clone http://hg.rabbitmq.com/rabbitmq-codegen
destination directory: rabbitmq-codegen
requesting all changes
adding changesets
adding manifests
adding file changes
added 310 changesets with 275 changes to 23 files (+5 heads)
updating to branch default
13 files updated, 0 files merged, 0 files removed, 0 files unresolved
essen@alice (0) % hg clone http://hg.rabbitmq.com/rabbitmq-server 
destination directory: rabbitmq-server
requesting all changes
adding changesets
adding manifests
adding file changes
added 14324 changesets with 22279 changes to 479 files (+35 heads)
updating to branch default
235 files updated, 0 files merged, 0 files removed, 0 files unresolved
essen@alice (0) % hg clone http://hg.rabbitmq.com/rabbitmq-erlang-client
destination directory: rabbitmq-erlang-client
requesting all changes
adding changesets
adding manifests
adding file changes
added 1886 changesets with 3617 changes to 154 files (+11 heads)
updating to branch default
41 files updated, 0 files merged, 0 files removed, 0 files unresolved
essen@alice (0) % cd rabbitmq-erlang-client 
essen@alice (0) % make -j1
rm -f deps.mk
echo src/amqp_gen_connection.erl:src/amqp_rpc_client.erl:src/amqp_connection_sup.erl:src/amqp_gen_consumer.erl:src/amqp_channel_sup.erl:src/uri_parser.erl:src/amqp_sup.erl:src/amqp_connection_type_sup.erl:src/amqp_direct_connection.erl:src/amqp_network_connection.erl:src/amqp_uri.erl:src/amqp_rpc_server.erl:src/amqp_selective_consumer.erl:src/amqp_direct_consumer.erl:src/amqp_channel_sup_sup.erl:src/amqp_channels_manager.erl:src/rabbit_routing_util.erl:src/amqp_connection.erl:src/amqp_channel.erl:src/amqp_main_reader.erl:src/amqp_client.erl:src/amqp_auth_mechanisms.erl:include/rabbit_routing_prefixes.hrl:include/amqp_client.hrl:include/amqp_gen_consumer_spec.hrl:include/amqp_client_internal.hrl: | escript ../rabbitmq-server/generate_deps deps.mk ebin
escript  ../rabbitmq-server/generate_app rabbit_common.app.in rabbit_common.app src
sed 's/%%VSN%%/0.0.0/' rabbit_common.app > rabbit_common.app.tmp && mv rabbit_common.app.tmp rabbit_common.app
mkdir -p dist
rm -f dist/rabbit_common-0.0.0.ez
make -C ../rabbitmq-server
make[1]: Entering directory '/home/essen/tmp/rabbit/rabbitmq-server'
Makefile:400: deps.mk: No such file or directory
python codegen.py body ../rabbitmq-codegen//amqp-rabbitmq-0.9.1.json ../rabbitmq-codegen//credit_extension.json src/rabbit_framing_amqp_0_9_1.erl
  File "codegen.py", line 110
    %%"""
        ^
SyntaxError: invalid syntax
Makefile:159: recipe for target 'src/rabbit_framing_amqp_0_9_1.erl' failed
make[1]: *** [src/rabbit_framing_amqp_0_9_1.erl] Error 1
make[1]: Leaving directory '/home/essen/tmp/rabbit/rabbitmq-server'
Makefile:93: recipe for target 'dist/rabbit_common-0.0.0.ez' failed
make: *** [dist/rabbit_common-0.0.0.ez] Error 2
essen@alice (2) % 
```

A Python error apparently? Running Python 3.4.0.

**Comment by jhw** [comment]
Any chance you could try Python 2.7.X ? Builds fine for me (Ubuntu 14.04)

**Comment by essen** [comment]
Yeah it works if I switch to python2, and then later fails due to missing "zip" program, whatever that is (I can guess what it's for). So I suppose it works.

As for making it work with erlang.mk, I suppose you could if you did it manually. Something like adding a target like this in your Makefile after include erlang.mk:

``` Makefile
deps::
    cd deps && hg clone http://hg.rabbitmq.com/rabbitmq-codegen
    cd deps && hg clone http://hg.rabbitmq.com/rabbitmq-server
    cd deps && hg clone http://hg.rabbitmq.com/rabbitmq-erlang-client
    cd deps/rabbitmq-erlang-client && make
```

**Comment by jhw** [comment]
Thanks; but - 

Makefile:11: *** target file `deps' has both : and :: entries. Stop.

**Comment by essen** [comment]
Sounds like you put `deps:` in your file instead of `deps::`. :-)

**Comment by jhw** [comment]
Hmm, I don't think so. Here's the Makefile:

PROJECT = hello_mk
DEPS = cowboy tinymq
dep_tinymq = git https://github.com/jhw/tinymq master

include erlang.mk

deps::
    cd deps && hg clone http://hg.rabbitmq.com/rabbitmq-codegen
    cd deps && hg clone http://hg.rabbitmq.com/rabbitmq-server
    cd deps && hg clone http://hg.rabbitmq.com/rabbitmq-erlang-client
    cd deps/rabbitmq-erlang-client && make

Here's the result:

Makefile:8: *** target file `deps' has both : and :: entries. Stop.

**Comment by jhw** [comment]
Got it. Makefile tabbing error. Rookie mistake. Thank you once again for your help.

**Comment by jhw** [comment]
Sorry. Me again.

So I managed to get amqp_client (and rabbit_common) added as dependencies using:

deps::
	# amqp_client
	curl -o deps/amqp_client-3.4.3.ez https://www.rabbitmq.com/releases/rabbitmq-erlang-client/v3.4.3/amqp_client-3.4.3.ez
	unzip -o -d deps deps/amqp_client-3.4.3.ez
	mv deps/amqp_client-3.4.3 deps/amqp_client
	rm deps/amqp_client-3.4.3.ez

I can see amqp_client in deps, with ebin, include subdirs etc

But then on 'make rel', amqp_client never makes it into the release lib along with other dependencies.

Is there some other magic the standard deps command does to register each dependency, get it added into the release ?

Many thanks.

but then on 'make rel', the amqp_client library doesn't make it into the release alon

**Comment by essen** [comment]
Did you forget perhaps to add amqp_client to your application's .app.src file to indicate that this is a dependency of this application? The erlang.mk deps are for building, release tools use the .app file.

**Comment by jhw** [comment]
I did forget. Thank you. Apologies for dumb question.

**Comment by zuiderkwast** [comment]
For the record. Here is an erlank.mk-friendly (also rebar-friendly) re-packaging of amqp_client that i've used successfully: https://github.com/jbrisbin/amqp_client. It has a dependency only on a similar re-packing of rabbit_common (using its own erlang.mk deps) so it doesn't need the full rabbitmq-server as a dep. It works lika a charm.
