### ISSUE TITLE
git 'Dependency not available'

### ISSUE THREAD

**Issue by jhw** [ninenines/erlang.mk#198]
I'm trying to add a git dependency as follows:

DEPS = lager cowboy tinymq
dep_tinymq = git https://github.com/ChicagoBoss/tinymq master

tinymq/rebar.config contains the following git sub- dependency:

{deps, [
    {tiny_pq, ".*", {git, "git://github.com/ChicagoBoss/tiny_pq.git", {tag, "v0.8.9"}}}
  ]}.

When I try and build the erlang.mk project, I get the following:

==> tinymq (compile)
Dependency not available: tiny_pq-.* ({git,
                                       "git://github.com/ChicagoBoss/tiny_pq.git",
                                       {tag,"v0.8.9"}})

This looks to me like a rebar error; as if erlang.mk tried to load the sub- dependency (using rebar ?) but couldn't find it. However the sub- dependency definitely exists:

https://github.com/ChicagoBoss/tiny_pq/tree/v0.8.9

tinymq/pq is somewhat old (2 yrs); so am left wondering, is the dependency somehow mis- specified ? If I look in rebar dependency management

https://github.com/rebar/rebar/wiki/Dependency-management

It seems that maybe specifying a "git://" scheme means the sub- dependency is "raw" (ie a library module rather than an application) and maybe needs specifying as such ? 

[Yes I will fork tinymq/pq and try these but am interested if someone could shed some light on what might be happening]

Many thanks.

**Comment by essen** [comment]
Try updating the rebar inside tinymq. A bug was fixed in rebar since then that should fix your issue.

**Comment by jhw** [comment]
Thx
