### ISSUE TITLE
Issue with Erlang 17.3

### ISSUE THREAD

**Issue by pseudorandumb** [ninenines/erlang.mk#206]
When running make I get: 
```{"init terminating in do_boot",{badarg,[{erlang,halt,[{failed_connect,[{to_address,{"github.com",443}},{inet,[inet],{eoptions,{{{badmatch,<<0 bytes>>},[{ssl_handshake,dec_hello_extensions,2,[{file,"ssl_handshake.erl"},{line,1737}]},{ssl_handshake,decode_handshake,3,[{file,"ssl_handshake.erl"},{line,926}]},{tls_handshake,get_tls_handshake_aux,3,[{file,"tls_handshake.erl"},{line,155}]},{tls_connection,next_state,4,[{file,"tls_connection.erl"},{line,433}]},{gen_fsm,handle_msg,7,[{file,"gen_fsm.erl"},{line,503}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]},{gen_fsm,sync_send_all_state_event,[<0.53.0>,{start,infinity},infinity]}}}}]}],[]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,657}]},{erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,121}]},{init,start_it,1,[]},{init,start_em,1,[]}]}}```

Updating Erlang to 17.4 fixes the issue.

**Comment by essen** [comment]
Yep not much we can do about that, it's a bug in Erlang directly.

**Comment by pseudorandumb** [comment]
Yea, just created the issue in hopes that google will index it so other people can find the fix.

**Comment by essen** [comment]
Thanks. Closing now, search engines probably have it by now.
