### ISSUE TITLE
Adding 'chef_certgen' causes dialyzer to fail(!)

### ISSUE THREAD

**Issue by rlipscombe** [ninenines/erlang.mk#207]
Adding 'chef_certgen' (from https://github.com/chef/chef_certgen) to DEPS causes my build to fail with 

```
dialyzer: Could not read PLT file /home/roger/Private/Source/rlipscombe/auth_spike/.auth_spike.plt: no_such_file

make[1]: *** [dialyzer] Error 1
make[1]: Leaving directory `/home/roger/Private/Source/rlipscombe/auth_spike/deps/chef_certgen'
make: *** [deps] Error 2
```

This appears to be because 'chef_certgen' has a Makefile, with an 'all' target, that invokes dialyzer.

Any ideas how I can get past this?

**Comment by essen** [comment]
Try adding this line:

```
AUTOPATCH += chef_certgen
```

It's a new feature.

**Comment by essen** [comment]
Hope it worked. Closing, thanks!
