### ISSUE TITLE
How to change VM arguments

### ISSUE THREAD

**Issue by ethrbh** [ninenines/erlang.mk#210]
hello,

I'm a beginner in erlang.mk world. First of all I would say, this is a very cool tool.
I could make my first own project, I also could create a release package what is fine. Now I would like to change the vm arguments what are set in the rel/vm.args file. I'm interesting how to change the cookie and the name of the erlang node. I have read the README, and I saw there is a way to change VM arguments by set ESCRIPT_EMU_ARGS. I did this my Makefile:

	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/microchip-pic/aws_erlang$ cat Makefile 
	PROJECT = aws_erlang
	ESCRIPT_EMU_ARGS = -sname apple
	include erlang.mk
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/microchip-pic/aws_erlang$ 

I made a release, but the vm.args does not changed, this is still looks like this:

	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/microchip-pic/aws_erlang$ cat rel/vm.args 
	-name aws_erlang@127.0.0.1
	-setcookie aws_erlang
	-heart
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/microchip-pic/aws_erlang$ 

I would like to ask you, did I miss understand something or did I something wrong?

If you have time, pelase try help me.

thanks,
/Robi

**Comment by essen** [comment]
Do you want to create a release or an escript? They are a little different things. The option you set is for escripts, while vm.args is for releases. If releases, then you need to edit vm.args directly.

**Comment by essen** [comment]
I will close this ticket as this is not an issue per se. Feel free to respond to it though and I will gladly reply.
