### ISSUE TITLE
Dependency with no makefile

### ISSUE THREAD

**Issue by darelf** [ninenines/erlang.mk#213]
Specifically the pgsql from semiocast.  At some point, it seemed to me that erlang.mk would automatically handle dependencies with no makefile, but it fails with: "*** No rule to make target `app'. Stop."

I worked around this temporarily by adding a Makefile that just reads "app: ./rebar compile" but I swear this was working at one point automatically.  It's possible at some point I updated erlang.mk and this is no longer handled, but the readme still says that it does handle it.

**Comment by essen** [comment]
Try adding AUTOPATCH += pgsql to your Makefile.

**Comment by darelf** [comment]
That works!  Thanks.
