### ISSUE TITLE
riak-erlang-client breaks

### ISSUE THREAD

**Issue by building39** [ninenines/erlang.mk#221]
I'm trying to add riak-erlang-client as a dependency, and get a "Dependency ... not reachable" error when running make. This is easily recreatable by bootstrapping a new project and adding riak-erlang-client as a dependency:

Makefile:
PROJECT = myapp
DEPS = riak-erlang-client
dep_riak-erlang-client = git git@github.com:basho/riak-erlang-client.git 2.0
include erlang.mk

myapp.app.src:
{application, myapp, [
	{description, ""},
	{vsn, "0.1.0"},
	{id, "git"},
	{modules, []},
	{registered, []},
	{applications, [
		kernel,
		stdlib,
                riak-erlang-client
	]},
	{mod, {myapp_app, []}},
	{env, []}
]}.

My relx version is 1.1.0, and this also seems to be a problem in relx version 1.2.0 as well.

**Comment by essen** [comment]
The application is actually called "riakc" so rename the deps/riak-erlang-client directory to that.

**Comment by building39** [comment]
The riak-client-erlang I got from github had an old version of rebar. Upgrading rebar fixed the problem

**Comment by essen** [comment]
Closing if it works for you, cheers.
