### ISSUE TITLE
Add support for compiling autotools projects

### ISSUE THREAD

**Issue by essen** [ninenines/erlang.mk#225]
Example: https://github.com/klacke/yaws

**Comment by essen** [comment]
Been done for a day or two.

**Comment by peffis** [comment]
Cool! I will check it out when I get back online again (in no-Internet land). I am very grateful. 

Thanks
Stefan

**Comment by essen** [comment]
The only one I did not manage to compile like this so far is ejabberd (server). I will take a look again later though.
