### ISSUE TITLE
Add a reloader plugin

### ISSUE THREAD

**Issue by essen** [ninenines/erlang.mk#235]
The question comes back often: how do I manually test my project? Releases are nice for production but clumsy for development. *They don't have to be.*

The adventurous developer would start using relx' `{dev_mode, true}` along with a reloader of sorts. This can be fine for some projects but you always run in some issues, either because you use NIFs, or have a yecc parser or other fancy things.

Now, something people don't always know is that releases allow you to run Erlang code directly from your unix shell. How about issuing commands to reload what we just compiled if the release is running? We *know* what we just compiled, after all.

``` bash
./hello_world_example rpcterms io write hello .
```

A solution like this would be very practical, require absolutely no setup, but should be optional. I propose to use the variable R to enable it (similar to V):

``` bash
$ R=1 make
```

This command would reload any file that changed, perhaps also issuing `application:load(App)` for all modified applications, to ensure that the running release is kept up to date every time you run make. It would *not* require you to use relx' dev_mode, though you probably want it if dealing with static files too.

Thoughts welcome.

**Comment by essen** [comment]
Specifically it would be great if it was done as part of the new 'make run' command. Perhaps by loading Erlang code from inside erlang.mk somehow.

**Comment by bullno1** [comment]
I created something similar: https://github.com/bullno1/reload.mk. It is not exactly what you described here but you can do `make reload` to recompile and reload modules. The `reload` target depends on `app` so all files that compiles to beam would work (e.g: .dtl, .yrc, .proto...).  There's also `auto-reload` which watches some directories using `inotifywait`. It does require using `overrides` in `relx.config` as I could not figure out how to pass anything more complex than a string through nodetool and `dev_mode` is practically undocumented.

You said: "We _know_ what we just compiled, after all", but it is not clear to me how a plugin can obtain such information.

Regarding `application:load(App)`, this is from Erlang doc:

> Note that the function does not load the actual Erlang object code

It is still useful to know if the app has changed (modules added/removed) but what then? Should it be restarted or should we just load new modules and purge old ones?

**Comment by essen** [comment]
I will get back to you when I come around to this. Feel free to add reload.mk to the package index though.

**Comment by essen** [comment]
Closing since the external plugin does the work well enough for now.

**Comment by essen** [comment]
I have added a built-in `make RELOAD=1` that will reload modules in a release started with `make run`. Experimental/undocumented for now.

It works differently than reload.mk in that it uses the eval command of the extended start script to update modules, but requires a more recent relx and also Erlang/OTP 20+ (I think) because of the function it uses. It was a 5 lines addition though so I feel it's the way to go moving forward. It'll work regardless of how the beam files have been built as long as the one the release is using has been modified on disk.
