### ISSUE TITLE
Cover improvements

### ISSUE THREAD

**Issue by essen** [ninenines/erlang.mk#236]
Here's a list of things to look at:
- Add documentation
- <s>Perhaps don't keep coverdata files in the main directory</s>
- <s>Add a way to cover compile more than the current application (for example Cowboy + Cowlib)</s>
- Using Smother as an alternative to cover
- <s>Add cover support to Triq/Proper</s>

**Comment by essen** [comment]
Might be interesting to steal for cover-report: https://github.com/erlang/otp/pull/721

**Comment by wizardjedi** [comment]
Hi, check new commit. I've added links with anchors to line numbers. It could be usefull to send link to code somebody. During codereview, for example.

I think it'll be usefull too:
 * hightlight erlang code for HTML-code coverage report
 * check coverage for methods and modules (see: https://cms-assets.tutsplus.com/uploads/users/45/posts/20442/image/HTMLCoverageClassWithCode.png  sample screenshot for modules: https://cms-assets.tutsplus.com/uploads/users/45/posts/20442/image/SynetoCoverage.png )
 * not only covers how much time each line was reached, but what test cases covers each line. It could be usefull to create test for untestable code.
 * Maybe it'll be usefull to exclude functions/modules from coverage. Or get another case - specify module or function that covers with this test case

**Comment by essen** [comment]
All interesting ideas, though not sure you wanted to post here rather than on your ticket.

Also take a look at Smother for a more powerful code coverage tool. It tells you a lot more than just lines.

**Comment by wizardjedi** [comment]
I've already checked Smother. It looks nice. Especially with execution graph feature. But, unfortunatly there is no test case names. :(

**Comment by larrycai** [comment]
@wizardjedi : great idea for "what test cases covers each line. It could be usefull to create test for untestable code."

**Comment by wizardjedi** [comment]
Unfortunatly erlang has very poor support for unit testing. And there is a lot of hard work to make erlang code testable.

For example.
```erlang
method1()->
    some_hard_work(),
    method2(),
    another_part_of_work().

method2()->
    hard_work().
```

We could'not create mock for method2() with meck. More precise we can create mock for whole module, but meck will mock only fully qualified calls like ```?MODULE:func()```. So, testing becomes too hard to test such code, or rewrite code with using ```?MODEUL:``` even for local calls (but we have performance penalties). :(

**Comment by essen** [comment]
You are incorrect in that last statement. The community is interested and has created a very strong testing environment for Erlang. Just not a unit testing environment.

The two main ways to test Erlang code is through functional/system testing (common_test) and through property based testing (quickcheck/proper/triq). When you got those two, unit testing is only good for regression testing or to make sure textbook examples work, and even then it's mostly for documentation. You should really look at common_test and a property based testing tool if you are serious in testing your programs.

**Comment by essen** [comment]
I've submitted https://github.com/erlang/otp/pull/2048 to add the link to HTML cover output to make linking easier.

**Comment by essen** [comment]
I've changed the default for `COVER_DATA_DIR` to be the same as `COVER_REPORT_DIR`, the main directory is no longer polluted needlessly.

**Comment by essen** [comment]
I fixed building of smother.

**Comment by essen** [comment]
One issue is https://github.com/ramsay-t/Smother/issues/14

This means that smother can't be used as a drop-in replacement for cover at the moment.

The project seems to have had little activity since 2015 as well.

**Comment by essen** [comment]
I've documented code coverage (and PropEr at the same time, it was missing). I think I'm done for now. Maybe revisit later on to add smother, would definitely welcome a contribution for that one at least. Closing, thanks!
