### ISSUE TITLE
Add more Erlang VMs to make ci

### ISSUE THREAD

**Issue by essen** [ninenines/erlang.mk#240]
We currently only allow the normal OTP. We should also allow other things like hipe, ling or perhaps even Erjang if there's some interest.

**Comment by opensam** [comment]
Wow. Congrats. I just wanted to suggest today a ling/Xen target feature and I'm discovering this already opened issue (since May). I like your generalisation. Yes to rel, hipe, ling, erjang and maybe rel-linux, rel-windows, etc (cross ERTS). Have fun.

**Comment by essen** [comment]
Yep this is a longer term goal, and of course I will probably start with HiPE. Most of everything tagged "Feature request" will come after I complete the docs/test suite though.

**Comment by essen** [comment]
FYI I tried erjang and it doesn't work here. Either way we probably should start with hipe.

**Comment by essen** [comment]
HiPE is already done, and so is the HiPE LLVM backend. Both Ling and Erjang seems inactive (might be wrong) and there doesn't seem to be much interest in them for Erlang.mk. Closing this for the time being.
