### ISSUE TITLE
NIF libraries are compiled with wrong output names

### ISSUE THREAD

**Issue by lsowen** [ninenines/erlang.mk#248]
I have two deps which compile NIF libraries.  Both use rebar, so dep_autopatch_rebar replaces the existing Makefile with an erlang.mk one.

The libraries compile correctly, but have the wrong output filenames (<library>.so instead of <library>_nif.so), so the NIF loader fails at run time.

The deps in question:  
* https://github.com/fdmanana/snappy-erlang-nif
* https://github.com/szktty/erlang-lz4

What is the proper way to use erlang.mk to compile these to the proper lib names?

**Comment by essen** [comment]
I am in the process of adding proc_specs support, so I suppose this will fix it. :-)

**Comment by essen** [comment]
I have a patch written, compiling everything again to make sure I didn't break something.

**Comment by lsowen** [comment]
@essen that is great news, thank you!

**Comment by essen** [comment]
cfe5f82bd52e241d9d3dc37d023bb0d568875495 should fix those cases.

I still have to handle cases where there are 2+ port_specs (2+ .so files generated in a single project, like mongooseim's exml), but that requires a different solution as erlang.mk isn't conceived to allow building more than one. I will generate a Makefile in c_src for that and erlang.mk can handle those.

Closing, thanks!

**Comment by lsowen** [comment]
This worked great.  Really appreciate your quick response.  Thanks!
