### ISSUE TITLE
Bundle the packages inside the erlang.mk file

### ISSUE THREAD

**Issue by essen** [ninenines/erlang.mk#249]
Since we are now testing that all packages build properly, our erlang.mk file is deeply tied with the package file. An addition to the package file might not imply that older erlang.mk builds it.

It might be interesting to just bundle the list of packages directly inside erlang.mk, so that it gets updated with erlang.mk when we do "make erlang-mk". This way we know that there is no possible mismatch.

**Comment by crownedgrouse** [comment]
Hi Loïc,
Interesting. Could the package list be tagged with the version of Erlang.mk ? And Erlang.mk dowload it ?

**Comment by crownedgrouse** [comment]
Another wish would be to have a unstable/stable/testing package list, a la debian repo. Master tag should be only for testing. Stable might be with x.y.z version. Mho.

**Comment by crownedgrouse** [comment]
I mean if the package list is tied to a version of Erlang.mk and contain packages with tag=master, it does really make sens as far we will download the last commit and the project might not be compatible. A dev/stable list should nice, otherwise an option or env variable in Erlang.mk should forbid to download a master in a stable project.

**Comment by essen** [comment]
OK so this is just a small step in a larger vision.

There are 3 large steps:

* Compile everything
* Give everything a stable version
* Make everything on the same version level

When you say a project might not be compatible, the fix would be step 3, and it's very hard to get on all packages. It's already very hard to give everything a stable version considering the lack of tags on some projects.

However I do want, after the package list is added to erlang.mk itself, to add a curated/unstable information to packages. For example I could maintain a set of, say, 30 packages that are known to work together. For all others you'd be on your own.

Over time other people could join in in maintaining these packages and make the 30 packages list grow but that requires some kind of commitment that is rare in the Erlang community.

As for making erlang.mk download a tagged package list, not much point. When you install or update erlang.mk, we download the repository entirely, so we might as well take the package list with us. Bundling it inside the erlang.mk file also has the advantage of simplifying working with it.

**Comment by crownedgrouse** [comment]
Yes, I know that x.y.z version is rare, starting, with my own projects ;-). The bundle could start with packages which propose x.y.z version, so an Erlang.mk version is pin to it. It is however in contradiction with the possibility to update easily Erlang.mk... This way would be simple as a 'grep -v master' In the right column...

**Comment by crownedgrouse** [comment]
I add that it would be a motivation to set a x.y.z version to project by their maintainers.

**Comment by essen** [comment]
I don't think we have this kind of influence yet.

Also it doesn't matter if there are tags or not, the curated list will have to use commit hashes if there's nothing else.

Having compilable packages pinned to an erlang.mk version is the idea, so having versions pinned is the next step.

However rather than go with projects that have tags, I think it's best if you maintain what you use so I would do that with mostly web related projects and someone would have to step up for other kinds of projects.

**Comment by crownedgrouse** [comment]
A commit hash can vanish due to a rebase, it is a risk, but you are aware of this. And it is git centric.
I agree that a 'pin' command could be nice, and by thinking to this, maybe sufficient, because deps can be overriden in Makefile to precise version or hash Even if master is in the package list.

**Comment by crownedgrouse** [comment]
BTW I m an Erlang.mk enthousiaste,  and if I can help...

**Comment by essen** [comment]
If a commit, tag or repository vanishes, I probably won't keep using the project very long.

It's not git centric. Same is true for hg, svn and we don't support other things yet but you get the idea. Everything has a per-commit identifier.

For your own project, see the ticket about locking. This would basically create a lock.mk file with all the right dep_ lines automatically whenever one doesn't exist. You can commit it with your project and erlang.mk will use it.

You can download erlang.mk and run "make check" and see if there's anything that doesn't compile. In a few days you can read the upcoming docs and submit patches if needed. More help will be needed when we get in the curated step.

**Comment by crownedgrouse** [comment]
great. count me in.

**Comment by essen** [comment]
The package index is now part of the erlang.mk file. Enjoy!

**Comment by crownedgrouse** [comment]
Hi Loïc, 
Great.
I think adding meta/keywords on packages could be great too. Because name or description is rarely sufficient to understand the goal of a package.

**Comment by essen** [comment]
Yep, I have some notes around, I will make a ticket from them during the week, and we can add values over time.

**Comment by crownedgrouse** [comment]
Note debian did some work on this, based on faceted classification ...

https://wiki.debian.org/Debtags/TaggingGuidelines

**Comment by crownedgrouse** [comment]
The complete list https://anonscm.debian.org/viewvc/debtags/vocabulary/trunk/debian-packages?view=markup   . A good start ;)
