### ISSUE TITLE
Can't install yamerl as dependency

### ISSUE THREAD

**Issue by jhw** [ninenines/erlang.mk#254]
https://github.com/yakaz/yamerl

'make clean' gives me 

make[1]: Entering directory `/home/justin/work/myapp/deps/yamerl'
make[2]: *** No rule to make target `app'. Stop.
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/justin/work/myapp/deps/yamerl'
make: *** [deps] Error 2

:-(

Am guessing there is some Makefile magic I am missing :-)

TIA

**Comment by essen** [comment]
Is it a recent erlang.mk? Try updating it with: "make distclean erlang-mk" and then try "make" again. It works for me with the most recent erlang.mk.

**Comment by jhw** [comment]
Now I have a different problem, this time with eredis

https://github.com/wooga/eredis

justin@justin-ThinkPad-X240:~/work/hfs$ make
 DEP    cowboy
 DEP    eredis
fatal: repository 'git' does not exist

:-(

Works fine with old erlang.mk (last updated 2 months ago)

Also other dependencies seem to work fine (haven't tried yamerl yet)

**Comment by essen** [comment]
eredis works fine for me, can you show me your dep_eredis line?

Otherwise, both are going to be added to the index in a few minutes so you won't need the dep_eredis or dep_yamler lines anymore.

**Comment by jhw** [comment]
// top of Makefile

PROJECT = hfs
DEPS = cowboy eredis erlcloud jsx lager
dep_eredis = git https://github.com/wooga/eredis
dep_erlcloud = git https://github.com/gleber/erlcloud master
include erlang.mk

// continued

**Comment by jhw** [comment]
If you are adding stuff to the index then maybe I can ask for erlcloud as well

**Comment by jhw** [comment]
Oops! Missing 'master' on the eredis line. Will try that

**Comment by essen** [comment]
Yep that's it. And erlcloud is already in, you don't need the dep_ line. :-)

**Comment by jhw** [comment]
OK eredis and erlcloud now work, but not yamerl; is that because it's not part of the index yet ?

**Comment by essen** [comment]
What's the error? Do you have the dep_ line? I am pushing in about five minutes.

**Comment by essen** [comment]
Pushed. You should only need "make distclean" followed by "make" this time. dep_ line won't be needed for most of anything you want to add as a dep. Try "make pkg-list" to print the whole list.

**Comment by jhw** [comment]
DEP    cowboy
 DEP    eredis
 DEP    erlcloud
 DEP    jsx
 DEP    lager
 DEP    yamerl
 AUTO   yamerl
/bin/sh: 1: autoreconf: not found
make: *** [/home/justin/work/hfs/deps/yamerl] Error 127

**Comment by jhw** [comment]
That's having updated erlang-mk and using the following (no dep_line)

PROJECT = hfs
DEPS = cowboy eredis erlcloud jsx lager yamerl
include erlang.mk

**Comment by essen** [comment]
Ah well yes, yamerl requires autotools, like a few other packages. Install it in your OS. :-)

**Comment by jhw** [comment]
Got it; works; thank you very much (again)

**Comment by essen** [comment]
Enjoy!
