### ISSUE TITLE
badmatch on single dependency fetching

### ISSUE THREAD

**Issue by jpuigm** [ninenines/erlang.mk#263]
Hi,

I have a single dependency ([hamcrest-erlang](https://github.com/hyperthunk/hamcrest-erlang)), that is failing to be fetched.

```
$ make deps
 DEP    hamcrest
{"init terminating in do_boot",{{badmatch,error},[{erl_eval,expr,3,[]}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
```
I've noticed that the repository is fetched and the directory is created accordingly (apparently). I haven't managed to debug the cause of the badmatch yet, any ideas so far?

**Comment by essen** [comment]
You're not alone, it's on my todo list. The comment I put alongside it is "plugin rebar_config crap probably" and I don't really remember the details. :-)

If you want to help, you can easily test a project by first adding it to erlang.mk's packages.v2.tsv file (tabs between the things):

hamcrest   git https://github.com/hyperthunk/hamcrest-erlang   master  https://github.com/hyperthunk/hamcrest-erlang   Erlang port of Hamcrest

And then run 'make check p=hamcrest'.

Just finding the reason why it crashes would already help, haven't investigated much yet.

**Comment by jpuigm** [comment]
This is our dep line,

```
$ grep hamcrest .ovn.packages 
hamcrest        git     https://github.com/hyperthunk/hamcrest-erlang   master  https://github.com/hyperthunk/hamcrest-erlang   Erlang port of Hamcrest
```

I've also noticed `erlang.mk` does autopatching of the repo, even if it's not part of my `AUTOPATCH` variable, i.e: I see a `Makefile` and a `Makefile.orig.mk`.

**Comment by essen** [comment]
Yes the AUTOPATCH feature is not needed anymore, now erlang.mk will patch projects that need it automatically. Instead you can *disable* the behavior with NO_AUTOPATCH.

The autopatch is pretty good so far but won't be able to do everything. For the other cases, I plan to add a way to provide project-specific patches, I need it with tsung and perhaps others.

**Comment by jpuigm** [comment]
This is what I got,

```
--2015-06-03 12:23:16--  https://raw.githubusercontent.com/rebar/rebar/791db716b5a3a7671e0b351f95ddf24b848ee173/src/rebar_log.erl
Resolving internet.visa.com... 10.55.24.12
Connecting to internet.visa.com|10.55.24.12|:443... connected.
Proxy request sent, awaiting response... 200 OK
Length: 3337 (3.3K) [text/plain]
Saving to: “/home/vagrant/dev/src/erlang.mk/test/tmp/rebar_log.erl”

100%[=====================================================================================================================================================================================================>] 3,337       --.-K/s   in 0s      

2015-06-03 12:23:17 (277 MB/s) - “/home/vagrant/dev/src/erlang.mk/test/tmp/rebar_log.erl” saved [3337/3337]

{"init terminating in do_boot",{{badmatch,error},[{erl_eval,expr,3,[]}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
make[2]: *** [/home/vagrant/dev/src/erlang.mk/test/app1/deps/hamcrest] Error 1
make[2]: Leaving directory `/home/vagrant/dev/src/erlang.mk/test/app1'
make[1]: *** [pkg-hamcrest] Error 2
make[1]: Leaving directory `/home/vagrant/dev/src/erlang.mk/test'
make: *** [check] Error 2
Exit 2
```

**Comment by jpuigm** [comment]
I will try with NO_AUTOPATCH hoping this pluging won't kick

**Comment by essen** [comment]
Yep it looks fine until the crash. I can take a closer look tomorrow.

**Comment by essen** [comment]
I pinpointed the problem, should be an easy fix. Breakfast first though.

**Comment by essen** [comment]
Nevermind, there's something much more complex after that. Will get back to you later today.

**Comment by essen** [comment]
I think I got it to work. However I need to test that I didn't break everything else first.

**Comment by essen** [comment]
Should be fixed in the most recent version. To update and try again: make distclean erlang-mk; make

Reopen if it's still not working for you. Enjoy!

**Comment by jpuigm** [comment]
Thank you, will check tomorrow!
