### ISSUE TITLE
Project X doesn't compile/work

### ISSUE THREAD

**Issue by essen** [ninenines/erlang.mk#265]
This is a meta ticket referencing the current dependency compilation issues. While all projects in the index compile just fine, a small number of projects can't be added yet because we are not compatible with them yet. This issue comment will be updated with all known issues. Everyone is invited to contribute patches that make those projects work, or knowledge of a "better fork" if it has fixed the issues and is also maintained.

**If you need a project on this list, please post a comment requesting a fix for it. We will do our best to help.**
- [abnfc](https://github.com/nygge/abnfc) has hardcoded ERL and ERLC in its Makefile
- [amoc](https://github.com/esl/amoc) has a makefile which is not patched
- [autohelp](https://github.com/stolen/autohelp) just doesn't compile
- [avz](https://github.com/synrc/avz) depends on an old Cowboy that uses 'pkg' dep format
- [axiom](https://github.com/tsujigiri/axiom) uses a pre-erlang.mk Cowboy that has warnings as errors; waiting for an update as per tsujigiri/axiom#20
- [barrel](https://github.com/barrel-db/barrel) works with js185 package installed; but we need to add dependencies not the top-level project
- [cassanderl](https://github.com/lpgauth/cassanderl) depends on a very old jsx which has a makefile file that fails; asking if project will be eventually updated in lpgauth/cassanderl#22
- [chatterbox](https://github.com/joedevivo/chatterbox) rebar detection fails, rebar is in an included Makefile
- [chef-server](https://github.com/chef/chef-server) has its own directory structure, not sure much can be done about it
- [concuerror](https://github.com/parapluu/Concuerror) is falsely detected as a rebar project; also has a dep in its Makefile that is fetched to the wrong location
- [czmq](https://github.com/gar1t/erlang-czmq) has 2 issues: the 'check' target uses 1 colon instead of 2; and a C dependency fails to compile with recent gcc as per gar1t/erlang-czmq#33
- [dht](https://github.com/jlouis/dht_bt) requires Erlang 18+
- [ejabberd](https://github.com/processone/ejabberd) has various errors during autopatch of dependencies
- [elixir](https://github.com/elixir-lang/elixir) has an elixir directory structure with a Makefile at the bottom but it uses rebar which is patched out so compilation ends up failing; needed for #237 and probably needs to wait project-specific patches
- [enacl](https://github.com/jlouis/enacl) requires dirty schedulers
- [enet](https://github.com/archaelus/enet) requires manual user intervention for building
- [epb](https://github.com/seancribbs/epb) has a .yrl file that includes another file and the compiler can't find it
- [ephp](https://github.com/altenwald/ephp) has a rebar dependency ezic with a Makefile used only in hooks; rebar detection fails
- [eraft](https://github.com/djui/eraft) depends on stdlib2 and tulib which have GNUmakefile that aren't patched
- [erlang-algorithms](https://github.com/aggelgian/erlang-algorithms) has no .app file
- [erlang_mesos](https://github.com/mdevilliers/erlang-mesos) requires specific versions of the mesos and protocol buffers library to build; the ones for my system are too recent
- [erlson](https://github.com/alavrik/erlson) is a clusterfuck; I am not even sure where to start to make it work; works fine in rebar
- [erlyberly](https://github.com/andytill/erlyberly) is JAVA
- [erlyssh](https://github.com/NetEase/erlyssh) requires you to install it to run it
- [escalus](https://github.com/esl/escalus) ends up in an infinite loop while trying to determine the contents of the COMPILE_FIRST variable
- [etcd](https://github.com/marshall-lee/etcd.erl) depends on broken **lhttpc**
- [evins](https://github.com/okebkal/evins) has a very old erlang.mk
- [exmpp](https://github.com/processone/exmpp) compiles fine, but the list of modules is autopatched (when it shouldn't)
- [ezic](https://github.com/drfloob/ezic) has manual steps required; proposal for adding them to the Makefile is at drfloob/ezic#22
- [fgraph](https://github.com/psyeugenic/fgraph) has a .app.src file that isn't patched properly
- [forge](https://github.com/jlouis/forge) forces a default goal that doesn't fetch required dependencies
- [fubar](https://github.com/jinnipark/fubar) has a broken dependency as per jinnipark/fubar#4
- [gen_client](https://github.com/bokner/gen_client) is Emakefile based and rely on missing dependency exmpp
- [i18n](https://github.com/erlang-unicode/i18n) preprocess rebar hook sets environment variables with os:putenv
- [ircbot](https://github.com/gdamjan/erlang-irc-bot) compiles fine, but the list of modules in the .app.src should be autopatched (but isn't)
- [katt](https://github.com/for-GET/katt) depends on broken **lhttpc**
- [leptus](https://github.com/s1n4/leptus) depends on an old Cowboy/erlang.mk; project is in the process of being updated as per s1n4/leptus#36 so wait and see
- [lhttpc](https://github.com/esl/lhttpc) has UTF-8 encoding issues; it is also not supported anymore so an upstream fix is unlikely
- [logplex](https://github.com/heroku/logplex) has a default rebar.config that doesn't work for anyone; the good one is public.rebar.config so we need to move it before attempting to patch the project normally
- [luvviescript](https://github.com/hypernumbers/LuvvieScript)... I'm not even sure
- [meshup](https://github.com/klarna/meshup) has a GNUmakefile which isn't patched
- [mzbench](https://github.com/machinezone/mzbench) has a non-standard directory structure
- [ngerlguten](https://github.com/CarlWright/NGerlguten) has its own or sinan's directory structure; can't do much about it until we can fetch subdirectories of repositories
- [nksip](https://github.com/kalta/nksip) depends on an old Cowboy that uses 'pkg' dep format; waiting for an update as per kalta/nksip#47
- [ns_server](https://github.com/membase/ns_server) has a configure script that requires an option
- [numer](https://github.com/vascokk/NumEr) requires CUDA and is missing instructions for Linux
- [piqi](https://github.com/alavrik/piqi-erlang) throws an emfile when trying to patch it, probably while trying to determine the contents of the COMPILE_FIRST variable
- [poxa](https://github.com/edgurgel/poxa-erlang) has a dependency unreachable (cannot read remote repository [uuid](https://gitorious.org/avtobiff/erlang-uuid) hosted on gitorious, which has been shut down and is now hosted graciously and read-only, with all that implies)
- [pusherman](https://github.com/inaka/pusherman) depends on an old Cowboy before erlang.mk which depends on a Ranch that uses rebar; waiting for an update as per inaka/pusherman#3
- [py](https://github.com/lfex/py) requires LFE compilation support
- [rabbitmq_webhooks](https://github.com/jbrisbin/rabbitmq-webhooks) depends on broken **lhttpc**
- [rcouch](https://github.com/rcouch/rcouch)'s couch dependency has hardcoded paths back to rcouch
- [rtpproxy](https://github.com/lemenkov/erlrtpproxy) requires include file from "rtplib" which isn't set as a dependency
- [scm](https://github.com/the-concurrent-schemer/scm) ends up in an infinite loop while trying to determine the contents of the COMPILE_FIRST variable
- [snarl](https://github.com/project-fifo/snarl) has an 'apps' project structure
- [spell1](https://github.com/rvirding/spell1) probably needs LFE support first
- [stdlib2](https://github.com/cannedprimates/stdlib2) has a GNUmakefile which isn't patched
- [sumo_db](https://github.com/inaka/sumo_db) has one of its dependencies use a Gun version that breaks current erlang.mk; waiting for an update as per inaka/sumo_db#166
- [tsung](https://github.com/processone/tsung) has 3 OTP applications inside a single OTP directory structure; requires a project-specific patch (either separate or make everything under 'tsung' depending on what works best)
- [tulib](https://github.com/klarna/tulib) has a GNUmakefile which isn't patched
- [ubf](https://github.com/ubf/ubf) has an issue with COMPILE_FIRST, and then a parse_transform error; works fine in rebar
- [uriak_pool](https://github.com/unisontech/uriak_pool) has riak_pb dependency use an old protobuffs that doesn't work with erlang.mk; updating protobuffs makes it work though; might be further issues
- [wings](https://github.com/bjorng/wings) requires manual setup
- [wpi](https://github.com/klajo/wpi) requires the WiringPi library for the Raspberry Pi
- [yawndb](https://github.com/selectel/yawndb) uses ecirca which has a rebar hook that needs env variable set (CC, ERL_CFLAGS)
- [zeta](https://github.com/tel/zeta) depends on a repository 'eqc' which doesn't exist; also has a name conflict, unrelated projects
- [zotonic](https://github.com/zotonic/zotonic) has its own Makefile, and while it pulls the dependencies in the right place, it fails to compile them because of "warnings_as_error" (a new gcc warning is the culprit at the time of writing, but it could be anything)

The following projects have a name that conflict with another package in the index. Down the line the index will allow different projects to have the same name.
- [active](https://github.com/synrc/active) is more or less the same as the one in the index
- [mysql](https://github.com/mysql-otp/mysql-otp) is probably a much better option than what we currently have in the index, as per mysql-otp/mysql-otp#19
- [sqerl](https://github.com/chef/sqerl) is not the same kind of project as the one we got in the index
- [syslog](https://github.com/jkvor/erlang_syslog) is more or less the same as the one in the index
- [uuid](https://github.com/avtobiff/erlang-uuid) is more or less the same as the other uuid projects
- [uuid](https://github.com/travis/erlang-uuid) is more or less the same as the other uuid projects

The following projects are in the index but experience some issues:
- aberth: a dependency was replaced overnight (barrel) and broke the project entirely; PR opened as a13x/aberth#5
- cl: I need to get confirmation that it actually works as intended
- dhtcrawler: seems to have a dependency that's broken and requires auth
- mcerlang: doesn't seem to load anything

See #281 and #282 for OSX and FreeBSD issues with packages that are currently in the index.

**Comment by essen** [comment]
Project verx has been fixed upstream and is now part of the index.

**Comment by essen** [comment]
Project evum has been fixed upstream and is now part of the index.

**Comment by essen** [comment]
Project antidote has been fixed upstream and is now part of the index.

**Comment by essen** [comment]
Project color has been fixed upstream and is now part of the index.

**Comment by essen** [comment]
The poxa project seems to be broken on all platforms.

**Comment by essen** [comment]
cloudi_service_db_pgsql and cloudi_service_oauth1 have been fixed upstream and are now part of the index.

**Comment by jhw** [comment]
amqp_client + rabbit_common; many thanks.

**Comment by jhw** [comment]
#ihavenoideawhatimdoingwithmakefiles

# https://github.com/ninenines/erlang.mk/issues/197
# https://www.rabbitmq.com/erlang-client.html
# https://www.rabbitmq.com/erlang-client-user-guide.html

RABBITMQ_VERSION=3.4.2

deps::	
	# amqp_client	
	if [ -d "deps/amqp_client" ]; then \
		echo "==> amqp_client"; \
	else \
		curl -o deps/amqp_client-$(RABBITMQ_VERSION).ez https://www.rabbitmq.com/releases/rabbitmq-erlang-client/v$(RABBITMQ_VERSION)/amqp_client-$(RABBITMQ_VERSION).ez; \
		unzip -o -d deps deps/amqp_client-$(RABBITMQ_VERSION).ez; \
		mv deps/amqp_client-$(RABBITMQ_VERSION) deps/amqp_client; \
		rm deps/amqp_client-$(RABBITMQ_VERSION).ez; \
	fi
	# rabbit_common
	if [ -d "deps/rabbit_common" ]; then \
		echo "==> rabbit_common"; \
	else \
		curl -o deps/rabbit_common-$(RABBITMQ_VERSION).ez https://www.rabbitmq.com/releases/rabbitmq-erlang-client/v$(RABBITMQ_VERSION)/rabbit_common-$(RABBITMQ_VERSION).ez; \
		unzip -o -d deps deps/rabbit_common-$(RABBITMQ_VERSION).ez; \
		mv deps/rabbit_common-$(RABBITMQ_VERSION) deps/rabbit_common; \
		rm deps/rabbit_common-$(RABBITMQ_VERSION).ez; \
	fi

**Comment by essen** [comment]
amqp_client now works! All you have to do is define RABBITMQ_CLIENT_PATCH and erlang.mk will fetch the corresponding repositories for you (only tracking master at this point, I want to get feedback).

**Comment by essen** [comment]
rabbit (rabbitmq-server) was also added today. You need to define RABBITMQ_SERVER_PATCH.

**Comment by essen** [comment]
See #281 and #282 for OSX and FreeBSD issues with packages that are currently in the index.

**Comment by essen** [comment]
actordb_thrift was fixed as soon as it was added, pushing!

**Comment by essen** [comment]
gut has just been fixed, and rebar3/relx have been fixed a few days ago.

**Comment by sata** [comment]
when adding [eper](https://github.com/massemanet/eper) to SHELL_DEPS and  calling make shell. The expected behaviour of beams being compiled to deps/eper/ebin doesn't happen. 

Not 100% sure but the dep_target define does run the autoreconf and configure, which generates Makefiles in eper, eper/src and priv/bin/.  The generated Makefiles isn't what I expect when I compare for instance the result in sync dep. 

Easy to replicate, adding dep_eper with github path, then SHELL_DEPS = eper, make shell.

**Comment by essen** [comment]
Opened ticket: https://github.com/massemanet/eper/issues/40

**Comment by essen** [comment]
Will need to look into lhttpc, it's normally been fixed as per: https://github.com/esl/lhttpc/pull/43#event-420680865

**Comment by essen** [comment]
Closing because it needs reactualizing.
