### ISSUE TITLE
make elvis doesn't support {elvis_style, dont_repeat_yourself, #{min_complexity => 10}}

### ISSUE THREAD

**Issue by lc3t35** [ninenines/erlang.mk#271]
ERLANG_MK_VERSION = 1.2.0-564-g178e214
If I add {elvis_style, dont_repeat_yourself, #{min_complexity => 10}} in elvis.config, it is not recognized by the installed 0.2.3 version of elvis.

**Comment by essen** [comment]
So in short we need to update elvis?

**Comment by lc3t35** [comment]
and elvis.config too

**Comment by essen** [comment]
Waiting on the next update from @elbrujohalcon and then should be good.

**Comment by essen** [comment]
This has been merged, everything should be well now. :-)
