### ISSUE TITLE
erlang.mk versions vs. create symlink

### ISSUE THREAD

**Issue by ethrbh** [ninenines/erlang.mk#275]
hello,

Few days ago I have reported an issue in cowboy project (https://github.com/ninenines/cowboy/issues/835), about installation problem. The final conclusion was the symbolic link creation does not work in some cases in Virtualbox. There are number of forums about it, but no exact solution yet, at least none of them could help for me. 

Anyway, I have an own project, where I use erlang.mk already, and I could use it on the Virtualbox environment, on the same shared folder to where I could try the cowboy. 

Later on I tried investigate it a bit deeply and I realized, to do "make" on my own project will fails if I use another project as dependency where almost the latest erlang.mk version is used. So if the erlang.mk version is "ERLANG_MK_VERSION = 1.2.0-514-gcb184ee" the make fails, if "ERLANG_MK_VERSION = 1", make works fine, not problem at all.

I'm just guessing that one of the changes in erlang.mk between these versions was tho use symbolic link instead of copy the erlang.mk file. If so, is there any risk to use the older version (=1)? I mean are there "critical" bug fixes in the newer release of erlang.mk?

Right now it is a little bit annoying me that my project is located in a shared folder (hosted by Windows), but I develop in Ubuntu running within Virtualbox, and I try integrate cowboy webserver, but I cannot do this because by default it cannot be compiled :-(

thanks for your help, and sorry if the issue description was too long

thanks for your help,
/Robi

**Comment by essen** [comment]
I think I can try something to remove the need for the symbolic link. I'll get back to you.

**Comment by ethrbh** [comment]
hello Essen,

That would be grate :-) 

thanks fro your help,
/Robi

**Comment by essen** [comment]
I have a solution for that being tested but it will take 2 or 3 hours to make sure I didn't break anything.

**Comment by ethrbh** [comment]
hello Essen,

Cool :-) Do not hurry, right now I moved temporary to the guest OS's local filesystem.

thanks for your help again,
/Robi

**Comment by essen** [comment]
Done. Try again. :-)

**Comment by ethrbh** [comment]
hello Essen,

Thanks for your grate support.

I have replaced the erlang.mk with the newer version and the whole flow looks much-much better, except the following lines. These comes the dependencies are going to be install.

ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/aws(aws_on_rpi_erlangmk)> make deps
 DEP    erlang_ale
Branch all_in set up to track remote branch all_in from origin.
 DEP    cowboy
Branch 1.0.x set up to track remote branch 1.0.x from origin.
/bin/sh: 5: cannot create /mnt/ethrbh/private/projects/github/aws/.erlang.mk/deps.log: Directory nonexistent
m

I would like to ask you, did I something wrong, or ? 

thanks for your help,
/Robi

**Comment by essen** [comment]
The deps.log line should be harmless.

**Comment by ethrbh** [comment]
hello,

Get it. I really would like to thanks for your grate support.

thanks,
/Robi

**Comment by essen** [comment]
No problem.
