### ISSUE TITLE
Project X doesn't compile/work on OSX

### ISSUE THREAD

**Issue by essen** [ninenines/erlang.mk#281]
The following projects work on Linux but not on OSX.
- **cberl** has a make error (-bundle can't be used with -dynamiclib)
- **cloudi_service_zeromq** has a make error (-bundle can't be used with -dynamiclib)
- **eredis_pool** has a make error (illegal mkdir option)
- **exml** has a make error (NIF related symbols not found)
- **ling** has a make error; currently supports Linux only
- **mongooseim** depends on failing **exml**
- **nifty**, well, I seem to run into issues trying to install llvm/clang using homebrew; [this could be a hint](https://github.com/Golevka/emacs-clang-complete-async/issues/18), but yeah, no clue

You can help improve support on OSX by cloning erlang.mk and running "make check". You need homebrew and the following tools and libraries to build some of the packages:
- autoconf
- automake
- erlang
- git
- libcouchbase
- libgit2
- libtool
- libyaml
- mercurial
- pip (easy_install pip)
- virtualenv (pip install virtualenv)

**Comment by cabol** [comment]
Hello.

I was getting the make error related with "-bundle can't be used with -dynamiclib". Apparently is something related with clang and '-shared' flag, but not sure what is the real cause of this. So what I did meanwhile (workaround) was remove '-shared' option when 'darwin' is set (within define dep_autopatch_rebar.erl section), replacing 'case' clause from line:

https://github.com/ninenines/erlang.mk/blob/master/core/deps.mk#L389

by:

```
case {filename:extension(Output), $(PLATFORM)} of
	{[], _} -> "\n";
	{_, darwin} -> "\n";
	_ -> " -shared\n"
end
```

Of course, probably is not the right way, but maybe could help.

Thanks.

C. Andres

**Comment by essen** [comment]
It's probably "right enough". Thanks I'll take a look soon. :-)

**Comment by nacmartin** [comment]
I ran into the same issue of `-bundle` of today. To add more information, looks like in OSX you can have a loadable module with `-bundle` or a shared library with `-shared`, but not both. Related link: http://docstore.mik.ua/orelly/unix3/mac/ch05_03.htm

The suggested workaround works for me, but I guess it can happen that some c package does not specify `-bundle` and then we end up not having `-bundle` nor `-shared`.

**Comment by essen** [comment]
Very nice link, thanks.

**Comment by elbrujohalcon** [comment]
PR #437 _fixes_ *erlpass* and *bcrypt* with what @cabol described above

**Comment by essen** [comment]
The bcrypt, erlpass, and ierlang projects have been fixed by the above PR. Thanks!

**Comment by essen** [comment]
Also removing dhtcrawler from the list since it has been removed from the index for now (probably shouldn't have been added in the first place, my bad).

**Comment by essen** [comment]
Closing because it needs reactualizing.
