### ISSUE TITLE
Project X doesn't compile/work on FreeBSD

### ISSUE THREAD

**Issue by essen** [ninenines/erlang.mk#282]
The following projects work on Linux but not on FreeBSD.

enm failure, unsure:
- enm: make error

can't find g++ (note: rebar seems to use clang? but fails anyway) (https://github.com/basho/eleveldb/issues/97):
- antidote: make error
- edis: make error
- eleveldb: make error
- lasp: make error
- nkbase: make error
- plumtree: make error
- riak_core: make error
- riak_ensemble: make error
- riak_pg: make error
- riak_pipe: make error
- vmq_server: make error
- zab_engine: make error

doesn't find expat.h in /usr/local/include:
- ejabberd: make error
- exml: make error
- mongooseim: make error

not sure how to install libouchbase, manually?:
- cberl: make error

bash required by erlsha2 (PR merged https://github.com/vinoski/erlsha2/pull/13 but dep not updated):
- ejwt: make error
- gossiperl: make error

erlzmq not compatible with freebsd, uses 'make' instead of 'gmake':
- cloudi_service_zeromq: make error
- ierlang: make error

need wx:
- eplot: make error

erlang_js calls 'make':
- erlang_cep: make error
- erlang_js: make error
- luwak: make error
- riak_kv: make error

g++ not found:
- exec: make error

afunix_drv error:
- exometer: make error

doesn't find git2.h in /usr/local/include:
- geef: make error

doesn't build; does on Linux but seems nothing loads:
- ldap: make error

no FreeBSD support?
- ling: make error

compiles but doesn't seem to load anything:
- mcerlang: make error

needs clang include file, not sure how to install:
- nifty: make error

not quite sure, something not found:
- purity: make error

unicode/ucol.h not found:
- ucol_nif: make error

libvirt/libvirt.h not found (linux only?):
- vert: make error

You can help improve support on FreeBSD by cloning erlang.mk and running "make check". You need the following tools and libraries to build some of the packages:
- autoconf
- automake
- erlang
- git
- libgit2
- libtool
- libxslt
- mercurial
- python
- py27-virtualenv
- zip

**Comment by jj1bdx** [comment]
I remember on sfmt NIF and HiPE do not coexist, but maybe I need to recheck. Thanks.

**Comment by essen** [comment]
It's not a build error, it's a load error, so it might just be a bug in the erlang.mk autopatch functionality.

**Comment by essen** [comment]
erlsha2's patch has been merged, need to open tickets for the projects using it.

**Comment by essen** [comment]
Fixed evum, gen_icmp, gen_unix, iota, procket, tunctl, verx, cloudi_service_quorum, locker, rec2json.

**Comment by essen** [comment]
Fixed boss, detest, erlydtl, merl, sfmt.

**Comment by essen** [comment]
Closing because it needs reactualizing.
