### ISSUE TITLE
what is the correct way to build a release with erlang.mk and relx for multi-application project?

### ISSUE THREAD

**Issue by RomanShestakov** [ninenines/erlang.mk#288]
Hello,
thanks a lot for building erlang.mk - this is the most complicated make file I have ever seen!

Is there a way to use erlang.mk to build releases for multi-app projects?

these projects have root/apps
                                               /app1
                                               /app2
 structure.

I found this snippet  : https://gist.github.com/RJ/6977165 
which allows to define a top level Makefile which calls Makefiles in each of the applications living under root/apps but it doesn't allow to package them all up into a single release.

I wander if there is a way to do it?

or  it is best to avoid multi-app projects?

Regards, Roman

**Comment by essen** [comment]
I want to add a way to have a folder that works like deps/ but isn't automatically wiped with distclean. I thought I had a ticket for it, but guess not, I don't see it anymore. :-)

I can look into it soon if you want, shouldn't be too difficult. :-)

**Comment by RomanShestakov** [comment]
awesome! thank you very much! I think it might be very useful.

**Comment by RomanShestakov** [comment]
so, with the recent fixes erlang.mk is almost perfect for all my projects :-).  The only missing feature is the support for multi-app projects. Any ideas when it could be added?

**Comment by essen** [comment]
Not sure. Have a few more tickets for customers. Currently improving Erlang.mk for RabbitMQ.

Will probably get around to that at most when I document deps, I have a comment for that in my notes.

**Comment by RomanShestakov** [comment]
thank you very much!

**Comment by essen** [comment]
This is now in: https://github.com/ninenines/erlang.mk/commit/fe5c42fb818acf9ad6ca6589ea182dfbfbaa5427

Feedback welcome!

Closing, thanks!

**Comment by RomanShestakov** [comment]
many thanks for the fast turnaround!
