### ISSUE TITLE
Building project with new wersion of erlang.mk

### ISSUE THREAD

**Issue by andrAnat-b** [ninenines/erlang.mk#292]
When i try to build my project i got this message.

===> Starting relx build process ...
===> Resolving OTP Applications from directories:
          /home/andranat/IdeaProjects/aaaa/my_project/ebin
          /home/andranat/IdeaProjects/aaaa/my_project/deps
          /usr/lib/erlang/lib

=ERROR REPORT==== 2-Jul-2015::11:38:37 ===
Error in process <0.616.0> with exit value: {function_clause,[{rlx_app_info,parse_version,[{cmd,"echo `cat VERSION`"}],[{file,"/home/tristan/Devel/relx/_build/default/lib/relx/src/rlx_app_info.erl"},{line,197}]},{rlx_app_info,new,6,[{file,"/home/tristan/Deve... 

escript: exception exit: {function_clause,
                    [{rlx_app_info,parse_version,
                         [{cmd,"echo `cat VERSION`"}],
                         [{file,
                              "/home/tristan/Devel/relx/_build/default/lib/relx/src/rlx_app_info.erl"},
                          {line,197}]},
                     {rlx_app_info,new,6,
                         [{file,
                              "/home/tristan/Devel/relx/_build/default/lib/relx/src/rlx_app_info.erl"},
                          {line,98}]},
                     {rlx_app_discovery,get_vsn,3,
                         [{file,
                              "/home/tristan/Devel/relx/_build/default/lib/relx/src/rlx_app_discovery.erl"},
                          {line,298}]},
                     {rlx_dscv_util,discover_dir,3,
                         [{file,
                              "/home/tristan/Devel/relx/_build/default/lib/relx/src/rlx_dscv_util.erl"},
                          {line,97}]},
                     {lists,map,2,[{file,"lists.erl"},{line,1237}]},
                     {ec_plists,'-local_runmany/3-fun-0-',3,
                         [{file,
                              "/home/tristan/Devel/relx/_build/default/lib/erlware_commons/src/ec_plists.erl"},
                          {line,753}]}]}
  in function  ec_plists:handle_error/3 (/home/tristan/Devel/relx/_build/default/lib/erlware_commons/src/ec_plists.erl, line 900)
  in call from ec_plists:local_runmany/3 (/home/tristan/Devel/relx/_build/default/lib/erlware_commons/src/ec_plists.erl, line 764)
  in call from rlx_dscv_util:do/2 (/home/tristan/Devel/relx/_build/default/lib/relx/src/rlx_dscv_util.erl, line 52)
  in call from rlx_app_discovery:resolve_app_metadata/2 (/home/tristan/Devel/relx/_build/default/lib/relx/src/rlx_app_discovery.erl, line 103)
  in call from rlx_prv_app_discover:do/1 (/home/tristan/Devel/relx/_build/default/lib/relx/src/rlx_prv_app_discover.erl, line 54)
  in call from relx:run_provider/2 (/home/tristan/Devel/relx/_build/default/lib/relx/src/relx.erl, line 286)
  in call from lists:foldl/3 (lists.erl, line 1261)
  in call from relx:run_providers/1 (/home/tristan/Devel/relx/_build/default/lib/relx/src/relx.erl, line 266)

**Comment by essen** [comment]
Hm well it looks like a relx issue but let me try first.

**Comment by essen** [comment]
No it works fine here, let me ping @tsloughter maybe he knows.

**Comment by andrAnat-b** [comment]
Ok, thank You.

**Comment by tsloughter** [comment]
This issue looks to be you have `"echo cat VERSION"` as the version of a built application, which relx can't parse.

**Comment by essen** [comment]
Can you show your Makefile, or at least the relevant part? Or if any, the .app.src file.

**Comment by andrAnat-b** [comment]
Sorry but i back to previous version of project (without erlang.mk & relx) and i have no store changes. I can say my project contains wery old depencies not rebarised.I was surprised when I saw the path to the folder that do not exist on my local PC. Overall, it was an attempt to translate the old system to the new assembly . Thank you , the problem is exhausted .
