### ISSUE TITLE
Make erlang.mk work on Windows

### ISSUE THREAD

**Issue by essen** [ninenines/erlang.mk#294]
Here's a series of things to do and/or comments based on my local copy:

Easy to solve
----------------

    core/core.mk:48:UNAME_S := $(shell uname -s)
Detect windows; explained here http://www.oreilly.com/openbook/make3/book/ch07.pdf

    core/core.mk:138:ifeq ($(shell which wget 2>/dev/null | wc -l), 1)
Only use erlang for fetching files; prefer using git rather than plain files

    core/core.mk:169:# On Windows: $(shell dir /B $(1)); make sure to handle when no file exists.
    core/core.mk:170:core_ls = $(filter-out $(1),$(shell echo $(1)))
Do the thing above on windows

    core/erlc.mk:74:    $(eval GITDESCRIBE := $(shell git describe --dirty --abbrev=7 --tags --always --first-parent 2>/
It probably works fine on windows as long as it's in the path

    plugins/cover.mk:94:EUNIT_HRL_MODS = $(subst $(space),$(comma),$(shell \
     95     grep -e '^\s*-include.*include/eunit\.hrl"' src/*.erl \
     96     | sed "s/^src\/\(.*\)\.erl:.*/'\1'/" | uniq))
Probably detect those from within erlang directly

    plugins/cover.mk:121:   Date = "$(shell date -u "+%Y-%m-%dT%H:%M:%SZ")",
Probably do that from within erlang directly also

Harder to solve
------------------

    core/erlc.mk:92:        find include/ src/ -type f -name \*.hrl -newer ebin -exec touch $(shell find src/ -type f -n
Yeah; we should probably handle dependencies as advertised by erlc or something

    core/deps.mk:66:        if [ 0 != `grep -c "include ../\w*\.mk" $(DEPS_DIR)/$(1)/Makefile` ]; then \
    core/deps.mk:68:        elif [ 0 != `grep -ci rebar $(DEPS_DIR)/$(1)/Makefile` ]; then \
    core/deps.mk:70:        elif [ -n "`find $(DEPS_DIR)/$(1)/ -type f -name \*.mk -not -name erlang.mk | xargs -r grep 
Autopatch stuff; not exactly sure what to do about this yet

    test/Makefile:57:   $t [ `grep -E "{modules, *\['m'\]}" app1/ebin/app1.app | wc -l` == 1 ]
    test/Makefile:173:  $t [ `grep 'Total: 100%' app1/cover/index.html | wc -l` -eq 1 ]
    test/Makefile:203:  $t [ "`ls app1/doc/`" == "" ]
We should probably use ct to run tests to be honest

**Comment by CharlesOkwuagwu** [comment]
"erlang.mk will NOT work if the path contains spaces."

Please is there a simple way to allow directory names with spaces?

in particular "Program Files", as this is he default directory most of us would set up Erlang (and elixir) into.

Case in point:

C:\Projects\Elixir\pt>mix compile
==> sfmt
make[1]: Entering directory 'c:/Projects/Elixir/pt/deps/sfmt'
 APP    sfmt.app.src
 APP    sfmt.app.src
**cc.exe: error: Files/erl7.0/erts-7.0/include/: No such file or directory**
erlang.mk:573: recipe for target 'app' failed
make[1]: *** [app] Error 1
make[1]: Leaving directory 'c:/Projects/Elixir/pt/deps/sfmt'
Makefile:12: recipe for target 'all' failed
make: *** [all] Error 2
==> pt
** (Mix) Could not compile dependency sfmt, make command failed. If you want to recompile this dependency, please run: mix deps.compile sfmt

**Comment by CharlesOkwuagwu** [comment]
Ok, Got it to work. 
just used single quotes around the offending path '$(PATH)'

'$(ERTS_INCLUDE_DIR)' now correctly expands to  'c:/Program Files/erl7.0/erts-7.0/include/'

**Comment by essen** [comment]
This is the kind of thing you can fix for Windows, yes. There are more tricky issues however that exist due to namespace limitations. I do not think it will be a huge problem however since most people will work from C:\Users\Identifier\ or similar. Erlang being in "Program Files" has not been a big problem and this kind of thing can easily be corrected.

Do you know if for your issue it also works with double quotes also?

**Comment by essen** [comment]
Useful link: https://stackoverflow.com/questions/3228306/portable-makefile-creation-of-directories

**Comment by CharlesOkwuagwu** [comment]
thanks man.

**Comment by essen** [comment]
It should be trivial to add support for https://msys2.github.io

Even if we add stock Windows support later on, it'll be good to have this for a start.

**Comment by essen** [comment]
See #357.

**Comment by crownedgrouse** [comment]
Hi Loïc,
for your 'Harder to solve' (find -newer) , did you had a look to :
http://gnuwin32.sourceforge.net/packages/findutils.htm  ?
erlang.mk could maybe come with this on Windows, in a .erlang.mk.bin/  directory or whatever...

**Comment by essen** [comment]
I added support for MSYS2. Windows support is documented (with gotchas) and remaining issues can be fixed in new tickets. Right now, all tests currently written pass, except for the bootstrap_rel test that I will look into soon.

Experiments and tickets more than welcome! Note that as I'm going through writing the new docs and their associated tests, I may not take care of a ticket until I reach that part of the docs.

I'll therefore be closing this ticket as we're about done here. :-)

**Comment by CharlesOkwuagwu** [comment]
Trying to use this: http://dbeck.github.io/Using-Ranch-From-Elixir/ on windows and the mix deps.compile step still breaks for ranch on windows.

see here:

http://stackoverflow.com/questions/33080894/what-are-the-steps-to-successfully-run-ranch-elixir-on-windows

**Comment by essen** [comment]
Sounds like you aren't running this in an msys2 environment. See https://github.com/ninenines/erlang.mk/blob/master/doc/src/guide/installation.asciidoc#on-windows

**Comment by CharlesOkwuagwu** [comment]
ah, ok will try now

**Comment by CharlesOkwuagwu** [comment]
So this worked before now, sometime in October. but on a fresh windows machine today following the same steps brings a new erlang.mk error on line 68

**Comment by essen** [comment]
As you can see it tells you to show me the output of `uname -a`. :-)

**Comment by CharlesOkwuagwu** [comment]
sorry bro,

Charles@PAPERLESS-ONE MSYS /d/elixir/tcp_eval
$ uname -a
MSYS_NT-10.0 PAPERLESS-ONE 2.4.0(0.292/5/3) 2015-11-23 08:33 x86_64 Msys

**Comment by essen** [comment]
Hm weird, what's `uname -o`?  And what's `uname -o | wc -c`?

**Comment by CharlesOkwuagwu** [comment]
Charles@PAPERLESS-ONE MSYS /d/elixir/tcp_eval
$ uname -o
Msys

Charles@PAPERLESS-ONE MSYS /d/elixir/tcp_eval
$ uname -o | wc -c
5

Charles@PAPERLESS-ONE MSYS /d/elixir/tcp_eval

**Comment by essen** [comment]
In the Erlang.mk file, what's above the line 68? Like the block that ends with line 68.

**Comment by CharlesOkwuagwu** [comment]
# Platform detection.
# @todo Add Windows/Cygwin detection eventually.

ifeq ($(PLATFORM),)
UNAME_S := $(shell uname -s)

ifeq ($(UNAME_S),Linux)
PLATFORM = linux
else ifeq ($(UNAME_S),Darwin)
PLATFORM = darwin
else ifeq ($(UNAME_S),SunOS)
PLATFORM = solaris
else ifeq ($(UNAME_S),GNU)
PLATFORM = gnu
else ifeq ($(UNAME_S),FreeBSD)
PLATFORM = freebsd
else ifeq ($(UNAME_S),NetBSD)
PLATFORM = netbsd
else ifeq ($(UNAME_S),OpenBSD)
PLATFORM = openbsd
else
$(error Unable to detect platform. Please open a ticket with the output of uname -a.)
endif

export PLATFORM
endif

**Comment by essen** [comment]
That Erlang.mk seems to predate Windows support entirely. :-)

**Comment by CharlesOkwuagwu** [comment]
That sucks as all these are pulled down for us directly by mix deps.get when we specify Ranch as a dependency in Elixir Mix

**Comment by essen** [comment]
Ah I see. And Mix uses Erlang.mk to compile Ranch? Or is that a rule you set?

**Comment by essen** [comment]
If you have any kind of hook after Ranch has been fetched, "make erlang-mk" will update Erlang.mk automatically and get you up and running without my involvement. Otherwise I can update it upstream, but it will be only on master.

**Comment by CharlesOkwuagwu** [comment]
```
defmodule TCPEval.Mixfile do
  use Mix.Project

  def project do
    [app: :tcp_eval,
     version: "0.0.1",
     elixir: "~> 1.2-rc",
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     deps: deps]
  end

  # Configuration for the OTP application
  #
  # Type "mix help compile.app" for more information
  def application do
    [applications: [:logger, :ranch],
     mod: {TCPEval, []}]
  end

  # Dependencies can be Hex packages:
  #
  #   {:mydep, "~> 0.3.0"}
  #
  # Or git/path repositories:
  #
  #   {:mydep, git: "https://github.com/elixir-lang/mydep.git", tag: "0.1.0"}
  #
  # Type "mix help deps" for more examples and options
  defp deps do
    [{:ranch, "~> 1.2"}]
  end
end
```

**Comment by CharlesOkwuagwu** [comment]
I don't understand the internals of mix at all

**Comment by essen** [comment]
OK. I will update it in Ranch.

**Comment by essen** [comment]
Done. Depend on the following commit and all should be good: https://github.com/ninenines/ranch/commit/666e5398cee49cad985bfe522e9b9b9bf0032417 - It's exactly 1 commit after 1.2.0.

Next time please open a new ticket. :-)

**Comment by CharlesOkwuagwu** [comment]
my bad.
