### ISSUE TITLE
Including external port code in project

### ISSUE THREAD

**Issue by jhw** [ninenines/erlang.mk#295]
Another question/suggestion.

My Erlang project contains a port to some Golang code (it's for a simulation, need a static language, Erlang is too slow). Right now I have a 'go' directory within the project; 'go/src' contains the src and 'go/bin' the compiled code; I have a separate compilation task for the Golang code and then use a relx overlay to include 'go/bin' in the Erlang release.

Everything works fine but ideally I'd like to have the Golang code in a separate Git repo and then pull it in via erlang.mk; but then I guess erlang.mk would have to recognise it as a non- Erlang project and treat it appropriately.

Any thoughts on this ? Am guessing the way I am currently doing things is super- sub-optimal

Thanks!

**Comment by essen** [comment]
If it has a makefile it should work just fine to specify a Go project as dependency.

**Comment by jhw** [comment]
Works! Amazed [by my own ignorance]. Thanks once again.
