### ISSUE TITLE
getting deps on CentOS error: "Unknown or invalid dependency: ranch."

### ISSUE THREAD

**Issue by vesperusiak** [ninenines/erlang.mk#298]
I'm trying to compile cowboy on CentOS 6.6 and i'm getting error such like that in the title.
I have installed wget v1.12.
Here is whole make command output:
"DEP    cowlib
--2015-07-06 15:43:52--  https://raw.githubusercontent.com/ninenines/erlang.mk/master/packages.v2.tsv
Resolving raw.githubusercontent.com... 23.235.44.133
Connecting to raw.githubusercontent.com|23.235.44.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 56 [text/plain]
Saving to: “/opt/livechat/webserv/cowboy/.erlang.mk.packages.v2”

100%[=============================================================>] 56          --.-K/s   in 0s      

2015-07-06 15:43:52 (9.22 MB/s) - “/opt/livechat/webserv/cowboy/.erlang.mk.packages.v2” saved [56/56]

 DEP    ranch
Unknown or invalid dependency: ranch. Please consult the erlang.mk README for instructions.
make: *** [/opt/livechat/webserv/cowboy/deps/ranch] Error 78"

It should download ranch dep address from index, but it seems like it doesn't. 
It's the latest master version of cowboy, and on OSX everything works fine.

**Comment by essen** [comment]
Update erlang.mk and it will work, we needed to transition to the new way to handle packages and unfortunately I was a moron when I did the Cowboy Makefile months ago.

If the erlang.mk is recent enough, 'make erlang-mk' will be all you need.

**Comment by vesperusiak** [comment]
Sadly i got the same error, the only difference is that output is trimmed to last 3 lines.

**Comment by essen** [comment]
I mean update erlang.mk of the top-level project, if you are using Cowboy as a dependency.

**Comment by essen** [comment]
Hope this fixed you. If not, please reopen. :-)
