### ISSUE TITLE
unsafe download of plugin binaries with core_http_get?

### ISSUE THREAD

**Issue by sata** [ninenines/erlang.mk#299]
From my understanding of core.mk, if you have wget available on your system[1] you are going to download plugin binaries without checking the certificate, set them as executable then execute them. 

This is being used in Elvis[2], CI[3] and xref[4]. If you don't have wget installed then core.mk tries to use httpc which would use ssl for https[5].

Any specific reason why erlang.mk is running with `--no-check-certificate` per default? 

A suggestion to change is having a flag to disable certificate check if a user is too lazy to configure it's root certificates. 
 
Or have I misunderstood something?

[1] https://github.com/ninenines/erlang.mk/blob/0eb54a71605a955df14c5df793ebe676c86259f9/core/core.mk#L142-L144
[2] https://github.com/ninenines/erlang.mk/blob/0eb54a71605a955df14c5df793ebe676c86259f9/plugins/elvis.mk#L29-L30
[3] https://github.com/ninenines/erlang.mk/blob/0eb54a71605a955df14c5df793ebe676c86259f9/plugins/ci.mk#L46-L47
[4] https://github.com/ninenines/erlang.mk/blob/0eb54a71605a955df14c5df793ebe676c86259f9/plugins/xref.mk#L31-L32
[5] https://github.com/ninenines/erlang.mk/blob/0eb54a71605a955df14c5df793ebe676c86259f9/core/core.mk#L147-L158

**Comment by essen** [comment]
Yep, fully aware. The plan is to switch to downloading them using git directly from the package: ie only enable the plugin if it is found in the list of deps (we probably need a special "BUILD_DEPS" or something for these things).

As for kerl, I am not sure yet, but I figure checking the sha1 should be good enough. If not, tell me.

**Comment by essen** [comment]
By the way the problem also exists with the Erlang thing because it's apparently unsafe by default.

**Comment by sata** [comment]
@essen: care to elaborate on the last comment? Which Erlang thing is apparently unsafe by default?

**Comment by essen** [comment]
Fixing wget would only do half the work, the inets/httpc code is also vulnerable. Doing something secure would probably amount to more pain than needed; better use git directly instead where we can. This only leaves kerl, and I think we can survive with storing 1 sha1 hash in Erlang.mk. And if not, just implement the kerl build stuff directly in Erlang.mk. :-)

**Comment by essen** [comment]
The idea to check the deps is dropped because it is too impractical for relx.

Instead, kerl is now fetched using git (tracking master by default, not foreseeing much problems for that, it's pretty stable); and relx, xrefr and Hex packages using curl (with certificate validation).

Everything still lacks hash check (and even more so signature check, but nothing offers it at the moment). But this can be the subject of a new ticket. Closing, thanks!
