### ISSUE TITLE
erlang.mk/index/couch.mk is not couch

### ISSUE THREAD

**Issue by rnewson** [ninenines/erlang.mk#300]
Hi,

We kindly request that erlang.mk/index/couch.mk not refer to the `opencouch` project as `couch` as it can be confused with the Apache CouchDB project.

In our opinion, `couch.mk` should refer to the Apache CouchDB project.

Thanks
Robert Newson
CouchDB PMC

**Comment by essen** [comment]
OK so there's two things: the package name and the application name.

The application name can only be couch. This is a requirement of OTP. If the name is to be changed, it has to be done in the upstream project.

The package name is no problem however. It is currently couch because previously the package name and application name were identical, but this is not true anymore.

I have plans for a naming convention to handle conflicts, I am not sure exactly what form it will take but probably something like $(APP)-$(VARIANT), so in this case it would be couch-opencouch. If that's OK tell me and I will do in a few days (won't have much computer time until the 15th so please be patient :-).

**Comment by rnewson** [comment]
Hi @essen, thanks for responding. I don't think `couch-opencouch` is a fix.

As it happens, I think `opencouch` is now called `cowdb` (the PMC directly addressed the `opencouch` name in another forum).

 I suggest couch.mk refer to Apache CouchDB at `https://git-wip-us.apache.org/repos/asf/couchdb.git` and a new cowdb.mk point to the successor to `opencouch`.

We do appreciate your efforts here.

**Comment by rnewson** [comment]
I also note that `https://git-wip-us.apache.org/repos/asf/couchdb-couch.git` is the equivalent of `opencouch`, being the core functionality of couchdb, and is, happily, also an erlang application named `couch`.

**Comment by essen** [comment]
There's already cowdb in the index.

I can add the couchdb-couch package in the index as 'couch' (and at the same time I will look into adding the rest of the couch_* deps).

As for opencouch, can you elaborate on why couch-opencouch is not adequate?

**Comment by rnewson** [comment]
@essen sure, because `opencouch` is not couchdb and `couch-opencouch` implies even more strongly that `opencouch` is a component of couchdb, and it isn't. `opencouch` was renamed to `cowdb` to remove this confusion (and to resolve a trademark-related issue).

**Comment by benoitc** [comment]
opencouch and cowdb are different project.  While the future of opencouch is still undecided these are 2 different projects and opencouch exists by itself. 

As for the trademark, the only trademark owned by the apache foundation is "Apache CouchDB" and its usage.

**Comment by benoitc** [comment]
I would suggest to rename it opencouch.mk anyway so no confusion can happen.

**Comment by rnewson** [comment]
+1 to rename to opencouch.mk for now. @benoitc you know the PMC doesn't agree that `opencouch` is non-infringing, but that's not for here.

**Comment by rnewson** [comment]
bump

**Comment by benoitc** [comment]
note that whiile i'm ok for the namespace opencouch i also do think that
the apache couchdb project should be namespaced to avoid any conflating
name.

For opencouch i will send a PR by tomorrow.

**Comment by essen** [comment]
I'm unavailable for a few more days, sorry. Got married last week.

-- 
Loïc Hoguin
http://ninenines.eu

-------- Original Message --------

**Comment by rnewson** [comment]
@benoitc thanks! opencouch is at least better than couch.
@essen an excellent reason, congrats!

**Comment by essen** [comment]
Hello, I'm sorry it took so long but this is now done. The couch package has been renamed to opencouch. Do note that the opencouch application name is still "couch", but that I have no control over that.

Closing then, thanks for your patience!

**Comment by rnewson** [comment]
thanks!
