### ISSUE TITLE
Rename rel/ into config/?

### ISSUE THREAD

**Issue by essen** [ninenines/erlang.mk#308]
From inaka blog post. This could very well be a better name for it, since rel/ contains only vm.args and sys.config (plus user files).

**Comment by ingwinlu** [comment]
maybe `rel_config` is an even better choice, as it is used for releases, not for 'normal' configuration

**Comment by essen** [comment]
What other kind of configuration is there?

**Comment by ingwinlu** [comment]
other configuration does not need to exist. the case I had in mind was if someone is not familiar with the structure it might be expected that changes in config effect a normal build while it would only influence releases.

**Comment by essen** [comment]
If you are not using releases, this folder doesn't exist. If you are using releases, they *are* your normal build. :-)

**Comment by essen** [comment]
Should probably load a sys.config if present when running 'make shell', to be honest.

**Comment by essen** [comment]
Done the rename. Closing, thanks!
