### ISSUE TITLE
Parallel make fails

### ISSUE THREAD

**Issue by kennethlakin** [ninenines/erlang.mk#310]
The two times I have tried to use erlang.mk with a make job count higher than one, it has failed. The first time was with a home-grown cowboy app that was dependant on jiffy.  The app would sporadically fail to compile because erlang.mk decided to built all of its targets at once, rather than building all the deps, then building the app. Sadly, I don't have logs.

The second time is with the fiar project and its included erlang.mk: https://github.com/inaka/fiar .
It appears to be failing for the same reasons. 

Logs from a fiar build attempt with make -j1 and make -j3 -l 3.0 are here: https://gist.github.com/kennethlakin/08a8e2977c52f3fd9605 Notice that the -j1 attempt build fails because erlang.mk also treats warnings as errors in dependent projects, but gets *much* further along in the build process.

**Comment by essen** [comment]
Yep warning as error fix is already pushed so it should work for you (assuming you update it: make erlang-mk).

Thanks for the ticket, I will keep track of this issue as I improve things.

**Comment by kennethlakin** [comment]
No problemo. Good luck!

**Comment by essen** [comment]
> Would it be relatively easy to make erlang.mk force serial builds until
> you've all of the kinks worked out of build target ordering?

Actually that's what it should have done for all the cases where it's known to not work. Clearly that broke.

**Comment by essen** [comment]
Will spend most of the rest of the day thinking long and hard about this. Will start by writing up a dependency tree.

**Comment by essen** [comment]
Hello, Erlang.mk allows parallel Make again. All tests pass. Enjoy!
