### ISSUE TITLE
erlang.mk incorrectly compiles nif in https://github.com/erlang-unicode/i18n

### ISSUE THREAD

**Issue by brigadier** [ninenines/erlang.mk#315]
when `https://github.com/erlang-unicode/i18n` is included as a dep into another erlang.mk app - `dep_i18n = https://github.com/erlang-unicode/i18n`, erlang.mk compiles the nif with no errors, but it will throw an error on `erlang:load_nif`.

It is possible to make erlang.mk compile the app correctly by manually copying content of  `setenv.mk` into `Makefile` of the parent app.

**Comment by essen** [comment]
Yep it's one of the projects listed in #265.

**Comment by essen** [comment]
It works fine now, right? Closing.

**Comment by essen** [comment]
Nevermind.

**Comment by essen** [comment]
It's not compiling at all for me at the moment (even without erlang.mk) so I'll leave it aside for now.
