### ISSUE TITLE
Fails to build dependencies with nothing to compile.

### ISSUE THREAD

**Issue by jinnipark** [ninenines/erlang.mk#317]
Make fails after encountering a dependency without makefile -- header only library.
Expected to skip it.

**Comment by essen** [comment]
Yep that's a todo.

-- 
Loïc Hoguin
http://ninenines.eu

-------- Original Message --------

**Comment by essen** [comment]
Do you have an example?

**Comment by essen** [comment]
Can you try #353 and tell me if this fixes your issue?

**Comment by essen** [comment]
Tested with ninenines.github.io repo, works fine. Closing, thanks!

**Comment by essen** [comment]
Clearly something doesn't work yet. Reopening.

**Comment by essen** [comment]
Sorry for the spam, it was indeed fixed. It was my test being incorrect. Closing for good this time!
