### ISSUE TITLE
"xargs -r" doesn't work on OSX

### ISSUE THREAD

**Issue by Cloven** [ninenines/erlang.mk#318]
commit 754530904901304f55716db3bf164795343e99c5 introduced the use of 'xargs -r', which is a GNU-only extension.  On OSX this causes errors while attempting to do a 'make deps' that pulls cowboy, ranch, or cowlib:

 DEP    cowboy
xargs: illegal option -- r
usage: xargs [-0opt] [-E eofstr] [-I replstr [-R replacements]] [-J replstr]
             [-L number] [-n number [-x]] [-P maxprocs] [-s size]
             [utility [argument ...]]

**Comment by essen** [comment]
Think we have a PR changing into an -exec, might already be merged. Limited net access atm.

-- 
Loïc Hoguin
http://ninenines.eu

-------- Original Message --------

**Comment by Cloven** [comment]
yep; and that pull request looks to work.  Hope you're enjoying your vacation!
