### ISSUE TITLE
.app generated modules

### ISSUE THREAD

**Issue by jbothma** [ninenines/erlang.mk#319]
Modules not generated by means known to erlang.mk don't end up in the .app file. Even when they're in the .app.src file, they won't be in the .app file.

How about the .app file's modules attribute being the union of what's currently in the .app file and whatever's in the .app.src file? That way app developers can at least ensure that generated modules end up in the .app file (and thus get loaded in releases via the boot file) but still don't have to worry about most modules.

An example of this is mimetypes_disp in https://github.com/spawngrid/mimetypes where I did a workaround of making an empty mimetypes_disp module for the time being.

**Comment by essen** [comment]
Will think about it. :-)

**Comment by essen** [comment]
There was a bug introduced not too long ago that could have been a problem. Anyway once it is resolved, I believe generating the beam files *before* should work fine. ie add another line for:

ebin/$(PROJECT).app:: 

After that erlang.mk should fetch all beam files it finds in ebin and put them in the .app file.

**Comment by jbothma** [comment]
That sounds like a good solution and pretty much what one would expect to
see.

The only issue I see with this is if you have beam files lying around
during development when renaming or deleting a module, but I don't think
that case is that big a deal, at least for this feature.

**Comment by essen** [comment]
make clean app :-)

**Comment by essen** [comment]
Closing then if that's OK, I will cover that in the docs.

**Comment by jbothma** [comment]
Thanks!
