### ISSUE TITLE
Error compiling .yrl files

### ISSUE THREAD

**Issue by davecaos** [ninenines/erlang.mk#322]
Hi! I tried to add erlang.mk to this repo https://github.com/inaka/aleppo/tree/dave.erlang.mk_error, and I got this error when erlang.mk compile .yrl files .
```
bash-3.2$ V=10  make
....
..
.
erlc -v -Werror +debug_info +warn_export_vars +warn_shadow_vars +warn_obsolete_guard  -o ebin/ -pa ebin/ -I include/ src/aleppo.erl
erlc -v -o ebin/ src/aleppo_parser.yrl
Parse action conflict scanning symbol '(' in state 91:
   Reduce to Macro from '?' MacroName (rule 31 at line 96)
      vs.
   shift to state 94, adding right sisters to MacroName.
Conflict resolved in favor of shift.
...
..
.
```
I think is related with the folder that erlang.mk use to compile .yrl files, but i am not 100% sure.
Thanks!

**Comment by essen** [comment]
Doesn't look like an error? What's the rest of the output?

**Comment by essen** [comment]
The log above is just yecc saying it encountered conflicts and it resolved them by choosing itself. Unless you provide a better log I can't see where the problem lies, so closing for now. Thanks!
