### ISSUE TITLE
Non-git dependency sources require third argument

### ISSUE THREAD

**Issue by thwg** [ninenines/erlang.mk#324]
```
dep_ex1 = cp /path/to/dep
```

will be treated like as a git repository with remote URL 'cp', resulting in the error:
```
fatal: repository 'cp' does not exist
```

This is somewhat of a cryptic error.  To make it work, you can use a third garbage argument:
```
dep_ex1 = cp /path/to/dep some_string
```

I think some type of detection of arguments should be done to determine the correct fetch operation.  Would checking if the first argument is path-like (e.g. contains string `/` or `\`) work? (edit: probably also `:` for non-GitHub scp-like syntax, e.g. user@server:project.git).  If it appears to be a path or URL, use the default git action, otherwise use the following:
```
$(call dep_fetch,$(1),$(word 1,$(dep_$(1)))
```

If not, then possibly give a warning message to the user on failure -- "It appears you are trying to use *command*, which requires a third argument." and print an example.

The current handling also appears to break the svn examples listed in the README.

edit: Appears this is a duplicate of #306

**Comment by essen** [comment]
Yep #306 it is. I am going to fix it this week-end.

The solution I am thinking of is to have 3 functions like get_method, get_repo, get_commit and then call a function for each specific method that would do the right action depending on repo and potentially empty commit.

**Comment by essen** [comment]
I have pushed a bugfix.

Please update erlang.mk and retry: make erlang-mk; make distclean; make

Closing as I believe this is fixed. Thanks!
