### ISSUE TITLE
Add coloring of output

### ISSUE THREAD

**Issue by essen** [ninenines/erlang.mk#325]
Because why not? Should be optional, with customizable colors.

Should be interesting: https://wiki.archlinux.org/index.php/Color_Bash_Prompt#List_of_colors_for_prompt_and_Bash

**Comment by crownedgrouse** [comment]
Hi Loïc, 

Found this in my Firefox favorite urls :
http://jamesdolan.blogspot.fr/2009/10/color-coding-makefile-output.html?m=1

But never had time to test...

**Comment by essen** [comment]
I'll close this for now, not personally interested and have to focus on more important issues.
