### ISSUE TITLE
erlang.mk fails to compile riak_control (erlydtl templates compilation error?) 

### ISSUE THREAD

**Issue by RomanShestakov** [ninenines/erlang.mk#332]
hello,

I am trying to move away from rebar and use erlang.mk for all my new projects. One issue I just ran into is related to compiling riak_control. erlang.mk is able to successfully build riak_core, it seems to be choking up on riak_control.

e.g. the following min case:

    #makefile     
    PROJECT = test
     DEPS = riak_control
     dep_riak_control = git https://github.com/basho/riak_control.git 2.1
     include erlang.mk

fails with the following trace (error seems to be related to compiling erlydtl templates): 

erlc -v +debug_info +'{parse_transform, lager_transform}' -o ebin/ -pa ebin/ -I include/ src/base64url.erl src/riak_control.erl src/riak_control_app.erl src/riak_control_ring.erl src/riak_control_routes.erl src/riak_control_security.erl src/riak_control_session.erl src/riak_control_sup.erl src/riak_control_wm_cluster.erl src/riak_control_wm_gui.erl src/riak_control_wm_nodes.erl src/riak_control_wm_partitions.erl
erl +A0 -noinput -boot start_clean -pa ebin/ /Users/romanshestakov/development/magma/deps/erlydtl/ebin/ -eval ' Compile = fun(F) -> S = fun (1) -> re:replace(filename:rootname(string:sub_string(F, 11), ".dtl"), "/",  "_",  [{return, list}, global]); (0) -> filename:basename(F, ".dtl") end, Module = list_to_atom(string:to_lower(S(0)) ++ "_dtl"), {ok, _} = erlydtl:compile(F, Module, [{out_dir, "ebin/"}, return_errors, {doc_root, "templates"}]) end, _ = [Compile(F) || F <- string:tokens("templates/index.dtl", " ")], halt().'
{"init terminating in do_boot",{{badmatch,ok},[{erl_eval,expr,3,[]}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
make[1]: *** [ebin/riak_control.app] Error 1
make: *** [deps] Error 2

any ideas?

Regards, Roman

**Comment by essen** [comment]
Have to go now but I'll check when I get back.

**Comment by Gatzy118** [comment]
I think this has to do with the ErlyDTL plugin appending  "_dtl" to the module before compilation. 
This should probably configurable as DTL_SUFFIX ?= _dtl
Also, the templates dir is hard-coded to the root, where lots of projects have this within priv

**Comment by essen** [comment]
It's just the interface of erlydtl that changed. Writing a patch now.

**Comment by essen** [comment]
I will use this opportunity to add riak_control to the package index, and to do some maintenance work on the plugin. :-)

**Comment by essen** [comment]
Pushed something to master, please try and confirm that it works.

@Gatzy118 While I used this opportunity to add variables for folder and suffix, please open a separate ticket next time instead of hijacking others. :-)

Closing, thanks!

**Comment by RomanShestakov** [comment]
fantastic! thank you very much Luic! Everything works now as expected!
Regards, Roman
