### ISSUE TITLE
riak_control package is missing auto-generated js scripts in priv/admin/templates/generated

### ISSUE THREAD

**Issue by RomanShestakov** [ninenines/erlang.mk#333]
hello - thanks again for fixing the issue with erlydtl - https://github.com/ninenines/erlang.mk/issues/332#issuecomment-135056911

unfortunately I have discovered another issue:
though erlang files for riak_control are generated correctly now but the package also depends on autogenerated js scripts as well. They supposed to go to priv/admin/templates/generated 

in the rebar.config for riak_control there is some complicated action going on to build priv/admin/templates/generated/templates.js and priv/admin/templates/generated/vendor.js script.

this stuff seems to be generated by rebar_js plugins:
{plugins, [rebar_js_handlebars_plugin,
           rebar_js_stylus_plugin,
           rebar_js_concatenator_plugin]}

which are shipped with riak_control in plugins directory.

**Comment by essen** [comment]
Hm weird they should have been picked up. I'll look when I get a minute.

**Comment by essen** [comment]
Try again with current master: make erlang-mk; make distclean; make.

It generates two files here, sounds like what it must do. Closing, thanks!

**Comment by RomanShestakov** [comment]
fantastic - it solved the problem! much appreciate your help
