### ISSUE TITLE
ESCRIPT_SYS_CONFIG missing quotes

### ISSUE THREAD

**Issue by Gatzy118** [ninenines/erlang.mk#337]
When overriding ESCRIPT_SYS_CONFIG I only get it to work when I do something like this:

ESCRIPT_SYS_CONFIG="\"path/to/config.config\""

Need quotes in ESCRIPT_RAW template around the var

**Comment by Gatzy118** [comment]
Whilst testing, it seems like the current implementation might be broken in other ways. The escript executable doesn't seem to load any configs at all, even when using the default path rel/sys.config.

**Comment by essen** [comment]
The current implementation is most likely broken in various ways. I was hoping to receive a patch from @Cloven about a new implementation but it hasn't happened yet. Perhaps I will tackle it in a few weeks myself.

**Comment by essen** [comment]
New implementation is at https://github.com/ninenines/erlang.mk/commit/01efaa6764088ee0df0d1ec6e5f561707af5ebe0

And the mentioned variable was removed. Extra files can be added by extending escript-zip target instead.

Closing, thanks!
