### ISSUE TITLE
Cannot use mirrored github.com if dependency relies on rebar for build

### ISSUE THREAD

**Issue by sata** [ninenines/erlang.mk#338]
We rely on a internal github.com mirror for fetching dependencies. In dev it's been working quite well but in more strict network environments, where we don't have external access to github.com we can't build dependencies.

In [1] where the autopatch is defined github.com is hard coded[2]. 

I got it to work by replacing L123 with `git clone -q -n -- $(GITHUB_URL)/rebar/rebar $(ERLANG_MK_TMP)/rebar; \`

where GITHUB_URL is defined to be the previously hard coded value with ?= operator so one can override it. 

I'm not sure where in the core.mk the variable should be defined to fit other needs and the same goes for the naming convention.

What are your thoughts?

[1] https://github.com/ninenines/erlang.mk/blob/a0563a428a2eb2d842dada83437b971ccc8b9fb5/core/deps.mk#L120-L129
[2] https://github.com/ninenines/erlang.mk/blob/a0563a428a2eb2d842dada83437b971ccc8b9fb5/core/deps.mk#L123

**Comment by essen** [comment]
Git itself has a URL rewriting feature, would that not fit your use case? See "Git URLs" section of "man git clone".

Otherwise, it's probably a good idea for Erlang.mk to take the rebar URL from the package index directly, where you could easily override it.

**Comment by sata** [comment]
Yes, I tried to avoid using the git url rewriting feature since it would affect all jenkins jobs shared across our build server. I think I can use $XDG_CONFIG_HOME env variable to store the gitconfig in a different spot and/or initiate discussions to make this global change.

Our approach in dealing with internal mirror is flawed in the sense of how auto patching works. 

We've listed all dependencies of our dependencies in Makefile which points to our git mirror. This works fine as long as no auto patching is done. Since auto patching will review the rebar.config of the dependency to figure out what the dep_name target url should be - which of course doesn't contain any information about our mirror.

I will see if I can let git deal with git stuff :)

Thanks

**Comment by essen** [comment]
I understand. I'm open to improving this if you do not find a solution on your hand. And if you do, I'm open in hearing what you did. :-)

**Comment by sata** [comment]
I tried with XDG_CONFIG_HOME environment but unfortunately the Git version packaged on the build server is 1.7.1 where the XDG_CONFIG_HOME support was added in 2.4.3[1].

I don't want to compile and build git locally on the machine and the repositories provided by the distribution doesn't have such a new version. So I'm going to use the ~/.gitconfig location once everyone is fine with such a change on our build server. 

Only downside with the above approach is, everyone who wants to use the internal repo has to rewrite url to ensure that the auto patching is fetching refs from internal git mirror rather than from github.com. Which isn't so nice. 

For now I've resorted to patching erlang.mk.  It was a lot easier than expected to understand how auto patch works! 

I added this function 
```
	RewriteGithubUrl = fun (Repo) ->
		re:replace(Repo, "^git://github.com", "$(GITHUB_URL)", [global, {return, list}])
	end,
````

and changed the Write call where the dep_name is being outputted to:
``` 					Write(io_lib:format("DEPS += ~s\ndep_~s = ~s ~s ~s~n", [Name, Name, Method, RewriteGithubUrl(Repo), Commit]))````

In my opinion, it would be preferable if dep_autopatch_rebar.erl had knowledge about 'deps of deps' defined in Makefile to take the repository url from there instead of relying on rebar.config in the given dep. 

[1] https://github.com/git/git/commit/ea19289bc82351b7ac20ea2fd877e2bdde97ae34

**Comment by essen** [comment]
Alright. Thanks for the feedback, I will think about it a bit.

**Comment by essen** [comment]
Something that would work better is us simply getting rebar from the dependencies (defaulting to package index one, same as what we currently get), in which case you could use dep_rebar = ... to update it.

**Comment by essen** [comment]
About your comment on "deps of deps", that's something you can do using BUILD_DEPS: it will fetch them but not add them as application dependencies.

About rebar origin being hardcoded, I'm all for having an AUTOPATCH_REBAR_URL and AUTOPATCH_REBAR_COMMIT configuration variables or something. Would that work for you?

**Comment by essen** [comment]
To be honest the simplest way to look at it for these kinds of problems is to simply copy `.erlang.mk/rebar` when initializing your environment. Erlang.mk doesn't care where it came from, only that it's there. In the Makefile that can be done by adding a `deps::` line for example.

Closing then, thanks!
