### ISSUE TITLE
depend projects include erlang.mk relatively

### ISSUE THREAD

**Issue by refactor** [ninenines/erlang.mk#344]
deps' Makefile may be changed to include erlang.mk with absolute path, can it use relative path, sometimes the whole project may be moved to another path or copied to another host.

**Comment by essen** [comment]
I just pushed a function which will allow doing this, however I will need to write a test for it before I implement it.

**Comment by essen** [comment]
I was sitting on the fix for this way too long. It's in.

Do "make distclean; make erlang-mk; make" to get things in order.

Thanks!
