### ISSUE TITLE
Add support for additional ASN.1 compiler options

### ISSUE THREAD

**Issue by dannmartens** [ninenines/erlang.mk#346]
What would be the best way to add support for additional ASN.1 compiler options? Would it make sense to have them per ASN.1 specification? If I am not mistaken compile_asn just compiles without any additional options. Would it be feasible to use a technique similar to the .asn1config file? Or add a map in the make configuration which binds specific option lists to specific ASN.1 specifications?

**Comment by essen** [comment]
Can you link me to the documentation about this .asn1config file and/or any other document that can help me understand what you would like to achieve? I'm not very knowledgeable with regard to ASN.1.

**Comment by dannmartens** [comment]
I've got this from http://www.erlang.org/documentation/doc-5.2/lib/asn1-1.4/doc/html/asn1_ug.html#1.3.1 - 'Compile-time Functions'. 

There seems to be an opportunity to insert an $(ASN1_OPTS) variable in compile_asn1, but this would mean all the ASN.1 specifications would receive the same options.

There's a pattern used in http://erlang.org/doc/man/asn1ct.html#compile-2 where, if a flag asn1config is turned on, the ASN.1 compiler goes look for a file which has the same name as the ASN.1 specification, but with extension .asn1config. It customizes the specific decoder.

I was thinking about whether it would make sense to use the same pattern, using an extension .asn1compile, to specify individual compiler options.

I am not an ASN.1 expert either, but somehow I would expect that not all ASN.1 specifications would share the same encoder/decoder configuration in a project, which means their specifications would need to be compiled with different options.

**Comment by dannmartens** [comment]
I already got quite far just using $(ASN1_OPTS). Supporting compiler options per file are probably too much trouble for what it is worth.

**Comment by essen** [comment]
Good to know.

I'll welcome a patch for that. Should be fairly easy to add a test for it also (just copy the existing asn1 test and define ASN1_OPTS in the test project's Makefile.

**Comment by essen** [comment]
OK well we've had `ERLC_ASN1_OPTS` for a while and there has been no other interest in per-file so I'll close this. Thanks!
