### ISSUE TITLE
rebar as a dependency is failed to build

### ISSUE THREAD

**Issue by ddosia** [ninenines/erlang.mk#347]
Hi there. my project is depends on *covertool*, which itself is depends *rebar* (2.5.1 to be precise, but I tried with 2.6.0 with no luck).
As far as I understood *erlang.mk* does some modifications in *rebar*'s `Makefile`, which prevents it from successful build.

```erlang
dchurikov ~/work/my_proj/deps/rebar $ make
 DEPEND rebar.d
{"init terminating in do_boot",{undef,[{epp,parse_file,["src/rebar.erl",[{includes,["include/"]}]],[]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,569}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,243}]},{erl_eval,eval_lc1,6,[{file,"erl_eval.erl"},{line,595}]},{erl_eval,eval_generate,7,[{file,"erl_eval.erl"},{line,624}]},{erl_eval,eval_lc,6,[{file,"erl_eval.erl"},{line,581}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,364}]},{erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,118}]}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
make: *** [rebar.d] Error 1
```

**Comment by ddosia** [comment]
I suppose it is some how related to *autopatch* feature, but as far as I can tell `AUTOPATCH` var is empty during build, so I don't know why *erlang.mk* modifies anything.

**Comment by essen** [comment]
The autopatch feature changed and is applied for all projects now. The opposite variable is available to disable it for some projects: `NO_AUTOPATCH = rebar`

A bit surprised that rebar2 doesn't work, there's nothing special about it. It also works fine here (master rebar2 master erlang.mk).

I will have to see about covertool itself, can you link me to what you're using?

Thanks.

**Comment by ddosia** [comment]
[Covertool](https://github.com/idubrov/covertool)

**Comment by essen** [comment]
OK so it's the same that we have in the index and it also works here.

*Wait.*

Do you have Erlang on your path, and if you do, can you tell me what's the output of 'm(epp).' in the shell?

Also what version you are using? Maybe I went with a function not available in your Erlang version.

**Comment by ddosia** [comment]
I put `NO_AUTOPATCH = rebar covertool` before *erlang.mk* inclusion and still modifications happens.
*erlang.mk* taken from master, `2d46e25`.

erlang is installed through kerl:

```
erl
Erlang R16B03-1 (erts-5.10.4) [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V5.10.4  (abort with ^G)
1> m(epp).
Module epp compiled: Date: January 23 2014, Time: 16.56
Compiler options:  [{outdir,"/net/isildur/ldisk/daily_build/r16b03-1_prebuild_opu_o.2014-01-23_17/otp_src_R16B03-1/lib/stdlib/src/../ebin"},
                    {i,"/net/isildur/ldisk/daily_build/r16b03-1_prebuild_opu_o.2014-01-23_17/otp_src_R16B03-1/lib/stdlib/src/../include"},
                    {i,"/net/isildur/ldisk/daily_build/r16b03-1_prebuild_opu_o.2014-01-23_17/otp_src_R16B03-1/lib/stdlib/src/../../kernel/include"},
                    warnings_as_errors,debug_info]
Object file: /home/dchurikov/devel/otp/R16B03-1/lib/stdlib-1.19.4/ebin/epp.beam
Exports: 
close/1                       open/5
default_encoding/0            parse_erl_form/1
encoding_to_string/1          parse_file/1
format_error/1                parse_file/3
interpret_file_attribute/1    read_encoding/1
macro_defs/1                  read_encoding/2
module_info/0                 read_encoding_from_binary/2
module_info/1                 read_encoding_from_binary/1
normalize_typed_record_fields/restore_typed_record_fields/1
open/2                        scan_erl_form/1
open/3                        set_encoding/1
ok
```

**Comment by essen** [comment]
Yeah it looks like epp:parse_file/2 is too recent, I changed the code to use parse_file/3. Can you confirm it works now?

You can quickly test with `make erlang-mk ; make distclean ; make` from your top-level project.

About NO_AUTOPATCH, can you open a separate ticket? Thanks.

**Comment by ddosia** [comment]
@essen thanks, it works!

**Comment by essen** [comment]
Cheers!

I'll open a ticket to test older Erlang versions.
