### ISSUE TITLE
NO_AUTOPATCH doesn't work

### ISSUE THREAD

**Issue by ddosia** [ninenines/erlang.mk#349]
There is no docs about `NO_AUTOPATCH` feature in README file, but according to #347 setting this variable should prevent project's `Makefile` modifications.
But seems it doesn't work.

**Comment by essen** [comment]
Thanks. It'll be documented when I get to write the dependencies part of the new documentation (see doc/src/guide/book.asciidoc).

**Comment by essen** [comment]
This is fixed and now covered by tests. Run: "make distclean; make erlang-mk; make". Thanks!
