### ISSUE TITLE
Remove $(ERLANG_MK_TMP) directory on "make distclean"

### ISSUE THREAD

**Issue by essen** [ninenines/erlang.mk#356]
Looks like it's not done yet. Oops!

**Comment by ingwinlu** [comment]
would a simple distclean-tmp target be enough that calls `rm -rf $(ERLANG_MK_TMP` or did you have something more sophisticated in mind?

**Comment by essen** [comment]
This is pretty much what I have in mind, except it should be defined in core/core.mk since it's for more than deps.
