### ISSUE TITLE
MSYS2: Unable to detect platform

### ISSUE THREAD

**Issue by zsoltm** [ninenines/erlang.mk#357]
I'm using [MSYS2](http://msys2.github.io/) on Windows, and got `unable to detect platform` message.

Uname output:

    MSYS_NT-6.3 My-Host-Name 2.1.2(0.287/5/3) 2015-05-05 18:25 x86_64 Msys

or:

    MINGW64_NT-6.3 My-Host-Name 2.1.2(0.287/5/3) 2015-05-05 18:25 x86_64 Msys

**Comment by essen** [comment]
Thanks.

First time I hear about msys2, I suspect you will run into more issues than just that though. Try disabling the $(error ...) call and see how far you get.

**Comment by zsoltm** [comment]
Fortunately it works pretty well so far!
After the initial report I felt courageous and changed it like:

     PLATFORM = darwin
     else ifeq ($(UNAME_S),SunOS)
     PLATFORM = solaris
    +else ifeq ($(UNAME_S),MINGW64_NT-6.3)
    +PLATFORM = gnu
     else ifeq ($(UNAME_S),GNU)
     PLATFORM = gnu

Works like a charm with the [getting started guide](http://ninenines.eu/docs/en/cowboy/1.0/guide/getting_started/) from cowboy. I get a warning like:

    ===> Missing beam file elf_format <<"c:/erl6.4/lib/hipe-3.11.3/ebin/elf_format.beam">>

... but make / make dep / make rel etc. seems to be fine.

**Comment by essen** [comment]
Color me surprised, but highly interested (it's shades of blue and green).

The hipe warning is understandable if hipe support wasn't compiled for Windows.

I will have to try it when I get back. Does it produce binaries that can only be run in msys2, or can they be run in Windows directly?

**Comment by essen** [comment]
Wonder if you can get the most recent Erlang.mk repo, run "make", do your small fix, and run "make check" to see how much it passes. :-)

**Comment by essen** [comment]
I did, and everything except releases seem to work (for what has been tested, anyway, which isn't everything).

It's pretty interesting. Seems like other than uname and a mismatch between paths in and out of the msys2 terminal everything should work.

**Comment by essen** [comment]
Pushed a slightly different platform detection (one that works regardless of windows version). So considering this ticket done and closing. Further improvements will be tracked by ticket #294, or, if you run into issues, please open new tickets. :-)

Thanks!
