### ISSUE TITLE
<appname>.d file

### ISSUE THREAD

**Issue by ingwinlu** [ninenines/erlang.mk#358]
After upgrading from `1.2.0-649-ga0563a4` to `1.2.0-702-g5c5c928` I suddenly get a <appname>.d file in my application root directory.

```
cat rsfo.d
src/rsfo_xml.erl:: src/rsfo_xml.hrl; @touch $@
```

**Comment by essen** [comment]
https://github.com/ninenines/erlang.mk/blob/master/doc/src/guide/app.asciidoc#dependency-tracking

It's something good!

You can either add it to gitignore or commit it, depending on how stable your project is.

**Comment by ingwinlu** [comment]
i see, thank you
