### ISSUE TITLE
improve appup and relup support

### ISSUE THREAD

**Issue by ingwinlu** [ninenines/erlang.mk#369]
- [x] do not simply rm -rf ebin, .appup files could be contained in there
- [x] make rel currently runs distclean-relx-rel which hinders the generation of relups, #371

**Comment by essen** [comment]
Oh oops I guess rm -rf ebin isn't good enough anymore even for the .app file. :-)

**Comment by ingwinlu** [comment]
this also extends a bit further as `_rel` is purged on new runs of make (when we need to retain the old output to make relups).
`distclean-relx-rel` should not delete old releases in _rel

**Comment by essen** [comment]
Well distclean should, but not when running `make rel`.

**Comment by ingwinlu** [comment]
resolved

**Comment by essen** [comment]
\o/
