### ISSUE TITLE
Verbosity is not passed to relx

### ISSUE THREAD

**Issue by ingwinlu** [ninenines/erlang.mk#373]
`relx -V 2` default
`relx -V 3` full output

Similarly verbosity could be muted during some tests to not clutter the output via a smaller verbosity setting

**Comment by essen** [comment]
Makes sense.

**Comment by essen** [comment]
I've added `-V 3` when Erlang.mk has `V=1`. Not sure about muting, probably not as useful, let's see if it becomes necessary later.
