### ISSUE TITLE
Applications in APPS_DIR not compiled in correct order

### ISSUE THREAD

**Issue by cmkarlsson** [ninenines/erlang.mk#380]
I am trying out the new APPS_DIR folder.

I have empty top project with dependencies in deps and internal OTP applications under lib. However, the OTP applications under lib do depend on each other so may need both compilation order and the other applications to be included with -I for include files.

Assume I have lib/A, lib/B and lib/C. App A and app B include C/include/C.hrl and depend on C being compiled first.

In rebar2 I specify {lib_dirs, [C, B, A]} and that works.
In rebar3 they deduce it from app.src files and rebar.config in individual apps.

Cheers

**Comment by essen** [comment]
Yep the plan is to deduce it from the Makefile info too (LOCAL_DEPS).

On the other hand, the includes themselves should work fine, don't they? I'll add a test either way.

**Comment by cmkarlsson** [comment]
No it doesn't seem to find includes

make[1]: Entering directory `<SCRUBBED>/app'
 ERLC   <SCRUBBED.erl>
src/mod1.erl:46: can't find include lib "app2/include/app2.hrl"
src/mod1.erl:47: can't find include lib "app3/include/app3.hrl"

**Comment by essen** [comment]
Alright. I'll add a test. Thanks! :-)

**Comment by essen** [comment]
The include issue has been fixed thanks to a generous contribution. The compile order remains.

**Comment by essen** [comment]
Should be fixed. Thanks!
