### ISSUE TITLE
Hackney does not build

### ISSUE THREAD

**Issue by strange** [ninenines/erlang.mk#384]
This started out as an aborted build process when adding hackney as a dep.

Essen worked some magic and now the build proceeds without errors.

But hackney cannot start after the build has finished because no ebin directory has been created for one of hackney's deps (certifi).

**Comment by dmitriid** [comment]
Latest versions of hackney build without errors. However:
- a wrong version of certifi is used
- certifi is not built
- relx fails to create a release
- also. re-running `make deps` forces certifi to download a .pem certificate again, even though it's already present

Steps to reproduce:

```sh
> mkdir erlmk
> cd erlmk
> wget https://raw.githubusercontent.com/ninenines/erlang.mk/master/erlang.mk
> make -f erlang.mk bootstrap
```

Edit Makefile:

```Makefile
PROJECT = erlmk

DEPS = hackney
## note, hackney version doesn't really matter. It can be master
dep_hackney = git https://github.com/benoitc/hackney 1.4.4

include erlang.mk
```

Then build as usual

```sh
> make deps
DEP    hackney
./bootstrap
Recompile: src/rebar
....
==> rebar (compile)
==> rebar (escriptize)
Congratulations! You now have a self-contained script called "rebar" in
your current working directory.

 DEP    idna
 DEP    mimerl
 DEP    certifi
 DEP    ssl_verify_hostname
Recompile: src/punycode
...
mv cacerts.pem priv/
 DEPEND ssl_verify_hostname.d
 ERLC   ssl_verify_hostname.erl
 APP    ssl_verify_hostname.app.src
 DEPEND hackney.d
 ERLC   hackney.erl
...
 APP    hackney.app.src
```

If you go into `deps/hackney`, you'll see the following.

Hackney's `rebar.config` contains the following:

```erl
{deps, [
        {idna, "1.0.2"},
        {mimerl, "1.0.0"},
        {certifi, "0.1.1"},
        {ssl_verify_hostname, "1.0.5"}
       ]}.
```

The new Makefile created by `erlang.mk` contains

```Makefile
DEPS += certifi
dep_certifi = git https://github.com/certifi/erlang-certifi 0.1.0
```

If you go into `deps/certifi`, you'll see that there's no `ebin` directory, the dep wasn't built.

So, if you add a relx config:

```erl
{ release
, {relname, "0.1"}
, [ erlmk
  ]
}.

{extended_start_script, true}.
```

relx will fail:

```sh
> make rel
 GEN    distclean-relx-rel
 GEN    /Users/dmitriid/Projects/temp/erlmk/relx
===> Starting relx build process ...
===> Resolving OTP Applications from directories:
          /Users/dmitriid/Projects/temp/erlmk/deps
          /usr/local/Cellar/erlang/18.1/lib/erlang/lib
          /Users/dmitriid/Projects/temp/erlmk/apps
Failed to solve release:
 Dependency erlmk is specified as a dependency but is not reachable by the system.

make: *** [relx-rel] Error 127
```

**Comment by essen** [comment]
That certifi doesn't build is not a surprise (its Makefile doesn't build the project, not sure if it should be patched upstream or something else). The version is however "correct" as per the rebar.config.script (https://github.com/benoitc/hackney/blob/master/rebar.config.script) which differs from rebar.config; this is something @benoitc should fix. It would also help if the certifi Makefile would have a default target that actually builds the project (even if it just does "rebar compile", as that'd be enough for erlang.mk to understand it's not a custom Makefile).

**Comment by dmitriid** [comment]
a-ha! thanks for the clarification!

**Comment by essen** [comment]
Fixed by @benoitc upstream. Closing, thanks!

**Comment by dmitriid** [comment]
Awesome! Thank you as well :)
