### ISSUE TITLE
Changes to apps/$(APP)/src/$(APP).app.src doesn't cause apps/$(APP)/ebin/$(APP).app to be regenerated

### ISSUE THREAD

**Issue by ahf** [ninenines/erlang.mk#385]
Currently changes to the .app.src file doesn't cause the .app file to be regenerated upon build. It requires you to do a clean before building again.

**Comment by ahf** [comment]
Same goes for .app files generated from variables in the Makefile.

**Comment by essen** [comment]
Figured. Alright, thanks.

**Comment by essen** [comment]
Same for Makefile.

**Comment by essen** [comment]
Done in 7f1ace7622a5a9e046b8ae10accc8169ab59b047. Thanks!
