### ISSUE TITLE
port_env not expanded properly

### ISSUE THREAD

**Issue by lpgauth** [ninenines/erlang.mk#389]
erlang.mk doesn't expand the rebar.config port_env properly:

```
{port_env, [
    {"CFLAGS", "$CFLAGS $(pkg-config --cflags domain-classifier 2>/dev/null)"},
    {"LDFLAGS", "$LDFLAGS $(pkg-config --libs domain-classifier 2>/dev/null)"}
]}.
```

becomes:

```
CFLAGS =  $()(pkg-config --cflags domain-classifier 2>/dev/null)
LDFLAGS =  $()(pkg-config --libs domain-classifier 2>/dev/null)
```

**Comment by essen** [comment]
Do you have an example application I can easily test this against?

**Comment by lpgauth** [comment]
Unfortunately this is happening in a private repository...

Problem seems to come from the following line: https://github.com/ninenines/erlang.mk/blob/master/core/deps.mk#L324

ShellToMk with debug:

	ShellToMk = fun(V) ->
		io:format("debug: ~p~n", [V]),
		V2 = re:replace(V, "(\\\\$$$$)(\\\\w*)", "\\\\1(\\\\2)", [global]),
		io:format("debug: ~p~n", [V2]),
		V3 = re:replace(V2, "-Werror\\\\b", "", [{return, list}, global]),
		io:format("debug: ~p~n", [V3]),
		V3
	end,

gives:

    debug: " $(pkg-config --cflags adgear-geo 2>/dev/null)"
    debug: [<<" ">>,
        [<<"$">>,<<"(">>,<<>>,<<")">>]|
        <<"(pkg-config --cflags adgear-geo 2>/dev/null)">>]
    debug: " $()(pkg-config --cflags adgear-geo 2>/dev/null)"

**Comment by essen** [comment]
Ah yes, makes sense of course.

Try with this instead:

```
V2 = re:replace(V, "(\\\\$$$$)(?![(])(\\\\w*)", "\\\\1(\\\\2)", [global]).
```

If it works for you I will commit and push it.

**Comment by lpgauth** [comment]
Works.

    debug1: " $(pkg-config --libs adgear-geo 2>/dev/null)"
    debug2: " $(pkg-config --libs adgear-geo 2>/dev/null)"
    debug3: " $(pkg-config --libs adgear-geo 2>/dev/null)"

**Comment by essen** [comment]
Thanks for the quick feedback! I'll have it in before I sleep tonight.

**Comment by essen** [comment]
Wait, does it really work? Shouldn't it be $(shell pkg-config ...)?

**Comment by lpgauth** [comment]
No, this works.

    echo "$(pkg-config --cflags adgear-geo 2>/dev/null)"
    -I/usr/local/include

**Comment by essen** [comment]
In the shell yes, but we're putting this in a Makefile.

**Comment by lpgauth** [comment]
Right, I tested in the makefile and it should be be $(shell pkg-config ...).

**Comment by essen** [comment]
OK I'll get back to work on this, thanks. :-)

**Comment by lpgauth** [comment]
Hey, do you have a fix for this one?

**Comment by essen** [comment]
Not yet. You are welcome to provide it. :-)

**Comment by essen** [comment]
I've fixed this in my local copy. I'll push it later today. Sorry it took so long! Closing, thanks!

**Comment by lpgauth** [comment]
Mieux vaut tard que jamais!
