### ISSUE TITLE
ErlyDTL does not build

### ISSUE THREAD

**Issue by dervism** [ninenines/erlang.mk#399]
I have a Cowboy-project with ErlyDTL. On my Mac its building, but on my Raspberry (Linux raspberrypi2 4.1.7+) I am getting this error:

DEP    cowboy

make[1]: Entering directory '/home/pi/erlang_raspberrypi_temperature_sensor/deps/erlydtl'
make[1]: *** No targets.  Stop.
make[1]: Leaving directory '/home/pi/erlang_raspberrypi_temperature_sensor/deps/erlydtl'
erlang.mk:4047: recipe for target 'deps' failed
make: *** [deps] Error 2

Anyone who knows how to fix this?

**Comment by essen** [comment]
I haven't tested on a Pi yet. Can you post the full log when running "make V=1"? You might need to do a "make distclean" first to reset things back.

**Comment by dervism** [comment]
I ran "make distclean" on Raspberry Pi then did "make" and now it works :) Thank you very much @essen!

I noticed that after the distclean command erlang.mk triggered rebar when it started to process ErlyDTL.

Heres my repo if you like to take a look, or if it will help others: https://github.com/dervism/erlang_raspberrypi_temperature_sensor

**Comment by essen** [comment]
Yes when Erlang.mk fetches a project it patches rebar out (using rebar) and fixes a few small things. Guess it wasn't done before that.

Closing then, thanks!
