### ISSUE TITLE
erlang.mk fails to build yaws 

### ISSUE THREAD

**Issue by peffis** [ninenines/erlang.mk#403]
With the current erlang.mk (2.0.0-pre.1-23-gfed9ce4) and a Makefile like

``` Makefile
PROJECT = test
DEPS = yaws 

include erlang.mk 
```

, erlang.mk will build yaws but it will not invoke the existing Makefile rules in yaws (yaws has its own existing Makefile) that swaps out values in the ebin/yaws.app. This results in a ebin/yaws.app that looks like the following:

``` erlang
{application,yaws,
             [{description,"yaws WWW server"},
              {vsn,{cmd,"sed -ne '1,/^YAWS_VSN=/s/^YAWS_VSN=//p' vsn.mk 2>/dev/null"}},
              {modules, ['haxe','json','json2','jsonrpc','mime_type_c','mime_types','yaws','yaws_api','yaws_app','yaws_appmod_cgi','yaws_appmod_dav','yaws_appmod_fcgi','yaws_cgi','yaws_compile','yaws_config','yaws_ctl','yaws_debug','yaws_dime','yaws_exhtml','yaws_generated','yaws_html','yaws_jsonrpc','yaws_log','yaws_log_file_h','yaws_logger','yaws_ls','yaws_multipart','yaws_outmod','yaws_pam','yaws_revproxy','yaws_rpc','yaws_rss','yaws_runmod_lock','yaws_sendfile','yaws_server','yaws_session_server','yaws_shaper','yaws_soap12_lib','yaws_soap_lib','yaws_soap_srv','yaws_sse','yaws_stats','yaws_sup','yaws_sup_restarts','yaws_ticker','yaws_trace','yaws_vdir','yaws_websockets','yaws_xmlrpc','yaws_zlib']},
              {registered,[]},
              {mod,{yaws_app,[]}},
              {env,[]},
              {applications,[kernel,stdlib@APPDEPS@]}]}.
```

relx will later complain first about the {cmd, "...."} part in vsn and then it will not be able to resolve the dependency to stdlib@APPDEPS@. 

When building yaws manually with

``` bash
$ git clone https://github.com/klacke/yaws
$ cd yaws
$ autoreconf -Wall -vif -I m4
$ ./configure
$ make
```

the ebin/yaws.app will instead look like the following: 

``` erlang
{application,yaws,
 [{description,"yaws WWW server"},
  {vsn, "2.0.2"},
  {modules,[
            yaws,
            yaws_app,
            yaws_ticker,
            yaws_config,
            yaws_server,
            yaws_sup,
            yaws_api,
            yaws_log,
            yaws_trace,
            yaws_logger,
            yaws_ls,
            yaws_debug,
            yaws_compile,
            yaws_ctl,
            yaws_cgi,
            yaws_zlib,
            mime_type_c,
            yaws_session_server,
            yaws_outmod,
            yaws_revproxy,
            yaws_html,
            yaws_log_file_h,
            yaws_rss,
            yaws_appmod_dav,
            yaws_runmod_lock,
            yaws_pam,
            json,
            json2,
            jsonrpc,
            yaws_jsonrpc,
            yaws_xmlrpc,
            haxe,
            yaws_rpc,
            yaws_soap_srv,
            yaws_soap_lib,
            yaws_soap12_lib,
            yaws_appmod_cgi,
            yaws_appmod_fcgi,
            yaws_sendfile,
            yaws_sup_restarts,
            yaws_stats,
            yaws_vdir,
            yaws_multipart,
            yaws_shaper,
            yaws_dime,
            yaws_exhtml,
            yaws_sse,
            yaws_websockets,
            yaws_generated,
            mime_types
            ]},
  {registered, []},
  {mod,{yaws_app,[]}},
  {env, [
         % {config, undefined},           % undefined | filename()
         % {debug, false},                % true | false
         % {trace, false},                % http | traffic | false
         % {traceoutput, false},          % true | false
         % {conf, "/etc/yaws.conf"},      % string()
         % {runmod, mymodule},            % atom()
         % {embedded, false},             % true | false
         % {id, "default"},               % string()
         % {pam_service, "system-auth"},  % string()
         % {pam_use_acct, true},          % true | false
         % {pam_use_sess, true}           % true | false
        ]},
  {applications,[kernel,stdlib]}]}.
```

Note how vsn and @APPDEPS@ have both been substituted (and it seems some other processing has been done as well). 

I have not figured out how erlang.mk deals with the existing Makefile. It creates some Makefile.orig.mk it seems. But somehow erlang.mk seems to decouple the logic in the yaws build system that does the substitution required for ebin/yaws.app which breaks relx when you later would like to create the release.

**Comment by essen** [comment]
Yes the yaws Makefile is ignored because it mentions rebar and Erlang.mk assumes it's just a thin Makefile for running rebar commands. I suppose rebar detection needs to be improved again, I have not been able to come up with perfect rules for that. I suppose though that detection should look for the word rebar (with whitespace around) or ./rebar, instead of the string rebar (regardless of what's around).

Interestingly, I see a load error with yaws only on recompiles in the test suite (make check p=yaws V=3). I will have to add a check to the individual keys to make sure they are of expected type.

Alternatively, while waiting for a solution, you can add yaws to NO_AUTOPATCH and then add a rule to run the configure steps after fetching everything (you can define deps:: and add commands to be done after deps have been fetched and compiled, only need to worry about running them once).

**Comment by peffis** [comment]
Thank you! I will try out the NO_AUTOPATCH method then.

**Comment by peffis** [comment]
I am a bit confused now to be honest. I added "NO_AUTOPATCH += yaws" in the beginning of my Makefile and, without me adding any explicit dep rules or anything the Makefile fetch yaws and build it with automake, configure and make and actually build everything perfectly. So I followed your instructions above but I did not have to do anything to invoke configure - it just works :) 

So the changed test Makefile to reproduce this is: 
```Makefile
NO_AUTOPATCH += yaws
PROJECT = test
DEPS = yaws 

include erlang.mk 
```

**Comment by essen** [comment]
My bad, I forgot the configure steps were outside the autopatch steps. Cool then. :-)

**Comment by peffis** [comment]
No probs :) I guess, per definition, that an issues log includes mostly negative feedback, but I do hope that you know that you are doing really good stuff Loïc that we are all very grateful for.

**Comment by essen** [comment]
I think this works then? Closing, thanks!
