### ISSUE TITLE
Autopatch Makefile should use relative paths

### ISSUE THREAD

**Issue by jonasrichard** [ninenines/erlang.mk#407]
I am using vagrant and I shared my project folder with the VM.

So on the host OS I am in `/home/richard/project/whatever` and in the guest OS I am in `/home/vagrant/whatever`. It is the same directory because vargrant (VirtualBox) just makes it possible to expose the directory to the guest OS.

If I build the project on my host OS, the guest OS cannot run that because it generated lines in the deps Makefiles like:

```
...
include /home/richard/project/whatever/erlang.mk
```

So in the guest OS, I cannot run tests, anything, since the deps are broken. If autopatch generates something like this:

```
...
include ../../erlang.mk
```

it should work.

**Comment by essen** [comment]
I was sitting on the fix for this way too long. It's in.

Do "make distclean; make erlang-mk; make" to get things in order.

Thanks!
