### ISSUE TITLE
Cover can fail with 'badarith' error

### ISSUE THREAD

**Issue by hdima** [ninenines/erlang.mk#409]
In my project I have a module which doesn't contain any functions but only defines a behaviour so cover fails with `badarith` error at https://github.com/ninenines/erlang.mk/blob/master/plugins/cover.mk#L106 because `Y` and `N` are both 0 for the module and it tries to do `round(100 * 0 / (0 + 0))`.

**Comment by essen** [comment]
Nice, thanks for the report!

**Comment by hdima** [comment]
A quick fix is to replace `round(100 * Y / (Y + N))` with `case Y + N of 0 -> 0; S -> round(100 * Y / S) end`.

**Comment by essen** [comment]
Probably going to be the one merged, can you send a PR?

**Comment by hdima** [comment]
OK, I'll send a PR little bit later today

**Comment by hdima** [comment]
To add little bit of confusion, we discussed it in the team and some people said that the final coverage for the module without any functions should be 100% (instead of 0%).

**Comment by essen** [comment]
Makes sense.

**Comment by essen** [comment]
Closing as the PR has long been merged. Thanks again!
