### ISSUE TITLE
app.src not generated

### ISSUE THREAD

**Issue by AlexCHowle** [ninenines/erlang.mk#414]
Simple make -f bootstrap does not create app.sr file in src directory.  Supervisor and main app module are created.

Erlang 18.1

**Comment by essen** [comment]
It's normal: http://erlang.mk/guide/ch06.html#_application_resource_file

If you really need a .app.src, then use "make -f bootstrap LEGACY=1". But you probably don't, even for compatibility with rebar. See http://erlang.mk/guide/ch11.html#_erlang_mk_projects_as_rebar_dependencies
