### ISSUE TITLE
Recompile deps

### ISSUE THREAD

**Issue by refactor** [ninenines/erlang.mk#416]
Sometime we need recompile the deps, for example, recompile with a different erlang/otp OR after updated some dep.
Is there anyway to recompile deps, rather than using distclean-deps to remove the whole deps dir

**Comment by essen** [comment]
Not yet. For updating deps I plan to have a "make update" (should be a ticket). For different Erlang/OTP, it's probably safer to distclean.

**Comment by essen** [comment]
Closing as duplicate and/or no current plans as explained in previous comment. Thanks!
