### ISSUE TITLE
Compile deps with specific target

### ISSUE THREAD

**Issue by jonasrichard** [ninenines/erlang.mk#418]
There is this part of `erlang.mk`:

```makefile
ifneq ($(SKIP_DEPS),)
deps::
else
deps:: $(ALL_DEPS_DIRS)
ifndef IS_APP
	$(verbose) for dep in $(ALL_APPS_DIRS) ; do \
		$(MAKE) -C $$dep IS_APP=1 app || exit $$?; \
	done
endif
```

Sometimes the default target for a dependency is good. For example, we are using neo4j and its default (even after erlang.mk autopatch is all) which tries to build a release. But since it is a dependant application, the deps folder doesn't contain the dependencies - and we don't want them to be fetched.

So if you can specify something like:
```makefile
dep_neo4j_target = app
```
that erlang.mk snippet would call something like this:
```makefile
$(MAKE) -C $$dep IS_APP=1 ${dep_$$dep_target} || exit $$?;
```

If it is missing, no problem. Otherwise it will build the dependency with the specified target. We also can pass additional paramters to make there.

**Comment by essen** [comment]
I'll need to check what neo4j does exactly. I'm not convinced about the solution. It shouldn't try to build a release with recent Erlang.mk if used as a dep, but perhaps there's a bug somewhere.

**Comment by jonasrichard** [comment]
The problem is not with erlang.mk but the default build target of the dependency. neo4j wants to build a release by default, but it fails since deps/neo4j/deps/... isn't used as dependency folder. It would be good to execute a `make -C deps/neo4j app` instead of building the full release. It is probably because neo4j is not a library application but a release.

**Comment by essen** [comment]
This one? https://github.com/dmitriid/neo4j-erlang

**Comment by jonasrichard** [comment]
Yes, we are using a fork but yes.
In the meantime a possible solution is:
```
DEPS = ...
IGNORE_DEPS = neo4j
include erlang.mk
deps::
    make -C deps/neo4j app
```
Can be the solution. So after building every dependency (it fetches neo4j, too), we build neo4j with that special target.

**Comment by essen** [comment]
Well like I said earlier, it should *not* build a release, unless there is a bug. (Recent, at least) Erlang.mk behaves slightly differently for projects built as a dependency and releases are never built in that case.

There should be no need to define the target, if it doesn't work and you are using the current Erlang.mk, then it's just a bug that needs fixing.

**Comment by jonasrichard** [comment]
The funny thing is that a test application works. So I just created this makefile and copied erlang.mk there an executed a `make deps` and it was successful (even make ran).

```makefile
PROJECT = t
DEPS = neo4j

# dep_neo4j = git git@github.com:dmitriid/neo4j-erlang.git
dep_neo4j = git git@github.com:zsoci/neo4j-erlang.git dialyzeabit

include erlang.mk
```

... in the meantime I think I know what is the issue. In our complex Makefile I customized the `make rel` target because we need to generate sys.config with scripts.

So I wrote:

```makefile
...
rel:: deps app
    $(gen_verbose) the-generator-script.sh

include erlang.mk
...
```

And since neo4j is using **this** erlang.mk (include ../../erlang.mk) I redefined the default target. Since rel is the first target, it is the default. So executing a vanilla `make` in neo4j resulted in a `make deps app rel` invocation.

But the thing is that I want to write this rel:: before including erlang.mk, since I want to generate sys.config before relx can be executed. Maybe I need to start my makefile with `all: deps app rel` ? Which is the first target in erlang.mk.

**Comment by essen** [comment]
Try to add:

```
.DEFAULT_GOAL = all
```

**Comment by jonasrichard** [comment]
Thanks. It solved my problem. So the morale of the story: don't overwrite the default target, or if you do, at least specify it.
Otherwise I like this double-colon rules, without them I cannot solve many of my problems.

**Comment by essen** [comment]
Cheers. :-)
