### ISSUE TITLE
Hiccup with amqp_client dep build

### ISSUE THREAD

**Issue by jhw** [ninenines/erlang.mk#421]
Makefile as follows:

---------------------------------------
PROJECT = pubsub
DEPS = amqp_client 
RABBITMQ_CLIENT_PATCH = 1
include erlang.mk
---------------------------------------

$ make
make[1]: Entering directory `/home/justin/work/pubsub/deps/amqp_client'
 DEP    rabbit_common
fatal: could not create work tree dir '/home/justin/work/pubsub/deps/rabbit_common'.: File exists
/bin/sh: 1: cd: can't cd to /home/justin/work/pubsub/deps/rabbit_common
make[1]: Leaving directory `/home/justin/work/pubsub/deps/amqp_client'
make: *** [deps] Error 2
$ 
------------------------------

So: 

$ rm deps/rabbit_common [symlink]

Then works fine

?

**Comment by essen** [comment]
Disable RABBITMQ_CLIENT_PATCH if using a recent RabbitMQ, as it now uses Erlang.mk directly and the patch is no longer needed. Enjoy! :-)

**Comment by jhw** [comment]
Good job!
