### ISSUE TITLE
If I use erlang.mk - I can`t  solve the problem of Observer crash: 

### ISSUE THREAD

**Issue by OlegUm** [ninenines/erlang.mk#422]
I can`t  solve the problem of Observer crash.  

Eshell V7.1  (abort with ^G)
(debud@127.0.0.1)1> 
=ERROR REPORT==== 16-Nov-2015::14:10:48 ===
    node: 'static_world_example@127.0.0.1'
    call: {observer_backend,sys_info,[]}
    reason: {badrpc,
                {'EXIT',
                    {undef,
                        [{observer_backend,sys_info,[],[]},
                         {rpc,'-handle_call_call/6-fun-0-',5,
                             [{file,"rpc.erl"},{line,206}]}]}}}

1) I have Ubuntu 14.04.

2) sudo gedit /etc/hosts
127.0.0.1	localhost oleg.dom

3) sudo gedit /etc/hostname
oleg.dom

4) mkdir tmp_cowboy
 cd  tmp_cowboy
 git clone git://github.com/ninenines/cowboy/
 cd cowboy/examples/static_world

 5) ... cowboy/examples/static_world$ make run
...
(Erlang/OTP 18 [erts-7.1] [source] [64-bit] [smp:4:4] [async-threads:10] [kernel-poll:false]

Eshell V7.1  (abort with ^G)
(static_world_example@127.0.0.1)1>

6) let's run test node: 
Ctrl+Alt+t
$erl -name test -setcookie static_world_example
Eshell V7.1  (abort with ^G)
(test@oleg.dom)1> 

7) let's run Observer: 
Ctrl+Alt+t
$ erl -name observer -hidden -setcookie static_world_example  -run observer

Eshell V7.1  (abort with ^G)
(observer@oleg.dom)1> 

8) In  Observer I can switch to the test@oleg.dom node!  But I can`t switch to the static_world_example@127.0.0.1 node!

=ERROR REPORT==== 16-Nov-2015::14:10:48 ===
node: 'static_world_example@127.0.0.1'
call: {observer_backend,sys_info,[]}
reason: {badrpc,
{'EXIT',
{undef,
[{observer_backend,sys_info,[],[]},
{rpc,'-handle_call_call/6-fun-0-',5,
[{file,"rpc.erl"},{line,206}]}]}}}

9) What options I have started static_world_example@127.0.0.1 in erlang.mk ?  
Where can I see the list of options? How can I change them?

**Comment by OlegUm** [comment]
How can I start node  (static_world_example@oleg.dom or static_world_example@oleg)  instead of static_world_example@127.0.0.1?

**Comment by essen** [comment]
To use observer you need to add 'runtime_tools' to the release. Simply add it to the list at the end of this line: https://github.com/ninenines/cowboy/blob/master/examples/hello_world/relx.config#L1

Enjoy!

**Comment by OlegUm** [comment]
Hi, Essen!

{release, {static_world_example, "1"}, [static_world, runtime_tools]}.
{extended_start_script, true}.

That's right?
----------------------------------------------

I'm sorry but it does not work :(

oleg@oleg:~$ erl -name observer -hidden -setcookie static_world_example  -run observer
Erlang/OTP 18 [erts-7.1] [source] [64-bit] [smp:4:4] [async-threads:10] [kernel-poll:false]

Eshell V7.1  (abort with ^G)
(observer@oleg.dom)1> 
=ERROR REPORT==== 16-Nov-2015::19:03:01 ===
    node: 'static_world_example@oleg.dom'
    call: {observer_backend,sys_info,[]}
    reason: {badrpc,nodedown}

Maybe the problem in domain  name static_world_example@127.0.0.1? 
Why it`s not  static_world_example@oleg.dom (or  static_world_example@oleg)?

**Comment by essen** [comment]
You might need more configuration than that, but I don't know offhand. I'll ping @tsloughter if he wants to help since it's more his domain now and nothing to do with Erlang.mk.

**Comment by OlegUm** [comment]
OK! Maybe some Ubuntu users  faced with this problem and solved it.

**Comment by tsloughter** [comment]
@OlegUm did you try using `-sname` instead of `-name` in your `vm.args`?

**Comment by OlegUm** [comment]
If I change /home/oleg/stat_word/cowboy/examples/static_world/_rel/static_world_example/releases/1/vm.args
---------------------
## Name of the node
-sname static_world_example@127.0.0.1

## Cookie for distributed erlang
-setcookie static_world_example
------------------------

and then go:  $ ... cowboy/examples/static_world$ make run

make rewrites  stat_word/cowboy/examples/static_world/_rel/static_world_example/releases/1/vm.args back  to the:
------------------
...
-name static_world_example@127.0.0.1
...
------------


Where is the true vm.args to change it?

**Comment by essen** [comment]
The Cowboy example doesn't come with one, so you get the one generated by relx.
