### ISSUE TITLE
Problem with erlang_oauth

### ISSUE THREAD

**Issue by jhw** [ninenines/erlang.mk#426]
Makefile:

PROJECT = twitter_streaming
DEPS = erlang_oauth erlang_oauth_examples
LOCAL_DEPS = crypto ssl inets
dep_erlang_oauth = git git@github.com:tim/erlang-oauth.git master
dep_erlang_oauth_examples = git git@github.com:tim/erlang-oauth-examples.git master
include erlang.mk

----------------------------------------------------------------

$ make 
make[1]: Entering directory `/home/justin/work/twitter_streaming/deps/erlang_oauth'
Recompile: src/oauth
src/oauth.erl:144: Warning: crypto:sha_mac/2 is deprecated and will be removed in in a future release; use crypto:hmac/3
make[1]: Leaving directory `/home/justin/work/twitter_streaming/deps/erlang_oauth'
make[1]: Entering directory `/home/justin/work/twitter_streaming/deps/erlang_oauth_examples'
make[1]: Leaving directory `/home/justin/work/twitter_streaming/deps/erlang_oauth_examples'
===> Starting relx build process ...
===> Resolving OTP Applications from directories:
          /home/justin/work/twitter_streaming/ebin
          /home/justin/work/twitter_streaming/deps
          /usr/lib/erlang/lib
          /home/justin/work/twitter_streaming/apps
===> Missing beam file elf_format <<"/usr/lib/erlang/lib/hipe-3.12/ebin/elf_format.beam">>
Failed to solve release:
 Dependency erlang_oauth is specified as a dependency but is not reachable by the system.

make: *** [relx-rel] Error 127
justin@justin-ThinkPad-X240:~/work/twitter_streaming$ 

-----------------------------------------------------------

.app file (autogenerated)

{application, twitter_streaming, [
	{description, ""},
	{vsn, "rolling"},
	{modules, ['twitter_streaming_app','twitter_streaming_sup']},
	{registered, [twitter_streaming_sup]},
	{applications, [kernel,stdlib,crypto,ssl,inets,erlang_oauth,erlang_oauth_examples]},
	{mod, {twitter_streaming_app, []}}
]}.

Thanks!

**Comment by essen** [comment]
The application is called "oauth", not "erlang_oauth". Switch the latter with the former and it should work.

**Comment by jhw** [comment]
Thank you guru
