### ISSUE TITLE
triq/property testing support in unclear state

### ISSUE THREAD

**Issue by Cloven** [ninenines/erlang.mk#429]
Hi Löic!  

I'm having a hard time trying to figure out from the code whether or not triq support is in yet.  It looks like it partially is, but hasn't changed in a while and has some inscrutable ifdefs around it.  Is it working now, planned, or future?

**Comment by essen** [comment]
I use it in Cowlib. Most of the code in Erlang.mk hasn't changed in a while, that's just the nature of Makefiles. I suspect there will be some small changes (removing some rough edges mostly) when I get to documenting and testing it. I'm doing this with Dialyzer right now. Triq is probably fourth or fifth in the todo list.

Have you tried it and ran into problem or? The plugin enables itself after you add `TEST_DEPS = triq` in your Makefile. Then you can decide to run triq over everything, or just a module, or just a property.

**Comment by Cloven** [comment]
aha, didn't figure out that TEST_DEPS = triq thing.

When I add that, though:

 GEN    test-build
Escripting
{"init terminating in do_boot",{{badmatch,{error,{1,erl_parse,["syntax
error before: ","'end'"]}}},[{init,start_it,1,[]},{init,start_em,1,[]}]}}

Crash dump is being written to: erl_crash.dump...done

is there some other special magic I'm missing, like maybe the
everything/module/property selector?

**Comment by essen** [comment]
Not sure where this "Escripting" output comes from.

**Comment by essen** [comment]
Hey, have you figured out where the "Escripting" line comes from? There is no such line in Erlang.mk.

Closing until I know more, thanks!

**Comment by Cloven** [comment]
it was a debug printf in my branch; when I get back to this issue I'll make
sure I'm reset to master and check again.  Thanks Loic!

**Comment by essen** [comment]
When you do, give me an output with `V=1` in the make commands you run.
