### ISSUE TITLE
DTL fails with {error,[{"templates/index.dtl",[{none,erlydtl_beam_compiler,{write_file,enoent}}]}],[]}},[{erl_eval,expr,3,[]}]}}

### ISSUE THREAD

**Issue by rlipscombe** [ninenines/erlang.mk#434]
I've got a multiple application project that uses erlydtl. It fails with:

```
 DTL    index.dtl
{"init terminating in do_boot",{{case_clause,{error,[{"templates/index.dtl",[{none,erlydtl_beam_compiler,{write_file,enoent}}]}],[]}},[{erl_eval,expr,3,[]}]}}
```

**Comment by rlipscombe** [comment]
...but apparently, I can't attach .tar.gz files. Wait one.

**Comment by rlipscombe** [comment]
It turns out that I'm missing an `ebin` directory. Should `erlang.mk` be ensuring that exists before invoking erlydtl?

**Comment by essen** [comment]
Definitely should. The fix should be trivial if you want to do it; if not I will take it up when I get to documenting/testing erlydtl.

**Comment by essen** [comment]
Should be fixed in most recent commit. Closing, thanks!

**Comment by essen** [comment]
I have changed my fix for this as it was breaking parallel builds. Still works as expected for me.
