### ISSUE TITLE
"make eunit" fails for multi-app project

### ISSUE THREAD

**Issue by rlipscombe** [ninenines/erlang.mk#438]
If I have:

```
top/
     apps/
          foo/
          bar/
```

...and I run `make eunit` at the top level, make fails with `No rule to make target 'top.d' needed by 'test-build'`.

If I try to work around this by `touch top.d`, then it seems to get further, but then fails with `No rule to make target 'app-build'`.

Any ideas?

**Comment by essen** [comment]
Haven't come around to eunit yet so not too surprised. It should work from each individual application for now.

**Comment by essen** [comment]
This should work in most recent Erlang.mk: "make erlang-mk; make eunit". Thanks!
