### ISSUE TITLE
Compat plugin ?

### ISSUE THREAD

**Issue by crownedgrouse** [ninenines/erlang.mk#440]
Hi Loïc,
I would add a plugin to erlang.mk using my project geas  https://github.com/crownedgrouse/geas
this can help to know on which Erlang releases the whole project, in particular with external dependancies, can run.
Is it something possible ? I thought to  'make compat' but I can see that you are using this term in your own project.

**Comment by essen** [comment]
If the tool is named geas, the target should probably be geas also, or something alike.

Don't send a PR adding this functionality however. Instead, add the plugin functionality directly in your project (following http://erlang.mk/guide/ch22.html), and then submit a PR for the documentation and tests if you want them included with Erlang.mk (we can figure it out together).

**Comment by crownedgrouse** [comment]
ok,
i should probably create a escript that do the output of result, like some of already existing plugins.
will be easier to create the plugin. 
I will work my side and come back to you once I got something compatible with your guideline.

**Comment by essen** [comment]
Note that the elvis plugin will eventually be moved as a third party plugin and the xref plugin will most likely be changed so as to not require an escript like it does now (current functionality can of course be moved as a third party plugin).

Similarly, erlydtl and protobuffs would be better as third party plugins, Cowboy templates will be moved inside Cowboy as a third party plugin and so on.

**Comment by crownedgrouse** [comment]
I'm clusty with this for the moment, and did not really understood your last comment. let me read your guide before.

**Comment by crownedgrouse** [comment]
clumsy, not clusty. you propably undestood.

**Comment by essen** [comment]
In short, don't look in current plugins for what trend to follow, most of the third party stuff will eventually be moved out, and the stuff that stays in will not use escripts anymore. :-)

**Comment by crownedgrouse** [comment]
do you have a link to a project that use the new plugin 'way of life' ? an example is always helpfull ...

**Comment by essen** [comment]
The related tests may help: https://github.com/ninenines/erlang.mk/blob/master/test/core_plugins.mk

Run the tests and check the produced repos.

But really other than the oddity about `THIS := ...` plugins are just normal Makefile that is loaded dynamically.

**Comment by crownedgrouse** [comment]
I understand now the philosophy, but have however a question.
Plugins are coming from declared dependencies, but geas do not have to go in a final relx release. It is only a local tool for the developer.  Do I missed something ?

**Comment by essen** [comment]
That's where BUILD_DEPS come from.

**Comment by crownedgrouse** [comment]
the plugins.mk file is now pushed in my repo. 
I did some test on cowboy and see that cowboy can run only starting R15B01 due to use of crypto:hash/2 in deps/cowlib/ebin/cow_ws.beam .

**Comment by essen** [comment]
Sounds correct!

**Comment by crownedgrouse** [comment]
I need to add the plugin for the offending functions. As far geas is working on Beam files I should probably add 'all' as dependance target.
My test on cowboy was done with a crapy workaround. I still cannot figure how to add geas as local plugin. BUILD_DEPS look to be not available in all erlang.mk versions. 
What are the tests you would see be done ?
Where do you expect the documentation be done ? I did not saw this explained.

**Comment by essen** [comment]
If you depend on beam files you should add either 'app' or 'app deps', as 'all' might include building the release and you don't care about that.

You do need a recent-ish Erlang.mk, but then again you do need a recent-ish Erlang.mk to use external plugins, so I don't see a problem there. Just update your Erlang.mk (or Cowboy's, if testing against it) using "make erlang-mk".

For tests, well I suppose one test that shows something expected (like against Cowboy 1.0 that you mentioned above) is enough. "Does the plugin run properly" kind of test.

Documentation, add a new asciidoc file in doc/src/guide/ and in book.asciidoc you can link to this file under the "third party plugin" section, after the chapter currently there.

**Comment by crownedgrouse** [comment]
hum, by writing correctly BUILD_DEPS (not BUILD_DEP ,stupid me) , works fine.
```
   R15                   18.1       Geas database       
---Min--------Arch-------Max----------------------------------------------------
   R15B01                           cowboy               
                                    cowlib               
                                    geas                 
                                    ranch                
                                    test                 
--------------------------------------------------------------------------------
   R15B01                18.1       Global project       

/home/eric/git/test/deps/cowboy/ebin/cowboy_websocket.beam
R15B01    crypto:hash/2
```

**Comment by crownedgrouse** [comment]
I need to remove geas from result, then, because not part of the project.

**Comment by crownedgrouse** [comment]
Note that geas can help  to compose your packages list status on erlank.mk website #387 .
With geas you can avoid to try to compile projects on erlang version not compatible. My 50 cents. My PR wil probably happen this WE.

**Comment by essen** [comment]
Could be useful, thanks.

**Comment by crownedgrouse** [comment]
Some results you may appreciates ;>) 

```
   R15                   18.1       Geas database       
---Min--------Arch-------Max----------------------------------------------------
   R15B03-1                         yaws                 
                                    test                 
--------------------------------------------------------------------------------
   R15B03-1              18.1       Global project       

/home/eric/git/test/deps/yaws/ebin/yaws.beam
R15B03-1  inet:parse_strict_address/1


   R15                   18.1       Geas database       
---Min--------Arch-------Max----------------------------------------------------
   R16B                             mochiweb             
   R16B01                           webmachine           
                                    test                 
--------------------------------------------------------------------------------
   R16B01                18.1       Global project 

/home/eric/git/test/deps/webmachine/ebin/webmachine_util.beam
R16B01    application:ensure_all_started/1
```

**Comment by essen** [comment]
About to push so closing this. Thanks!
