### ISSUE TITLE
Infinite loop when using tabs with zsh

### ISSUE THREAD

**Issue by jeromer** [ninenines/erlang.mk#441]
Zsh runs indefinitely when typing for example ```make dist<Tab>``` and after quite some times it quits with the following error message:
> _make-parseMakefile:40: job table full or recursion limit exceeded

This comes from ```erlang.mk``` but I did not find the root cause of the problem in the file.

Here is how I reproduced the problem with stock zsh, default configuration:

Test one : 
```
foo:
	echo "foo"
```
Then ```make fo<Tab>``` works fine and returns what's expected : 
> gimli% make foo 
echo "foo"
foo

Now with erlang.mk included:
```
PROJECT = example

include erlang.mk
```

Then ```make he<Tab>``` takes ages and finally stops after zsh returns with the error message stated at the top of this ticket.

Reproduced with erlang.mk from master branch, the one downloadable as described in the guide : https://raw.githubusercontent.com/ninenines/erlang.mk/master/erlang.mk

**Comment by jeromer** [comment]
If I user ```make he<tab>``` as a test case, it seems that commenting code from line 5190 to line 5206 does not make zsh go completely nuts : 

```
ifdef SP
define bs_Makefile
PROJECT = $p
PROJECT_DESCRIPTION = New project
PROJECT_VERSION = 0.0.1

# Whitespace to be used when creating files from templates.
SP = $(SP)

include erlang.mk
endef
else
define bs_Makefile
PROJECT = $p
include erlang.mk
endef
endif
```
This seems to code from the bootstrap plugin : https://github.com/ninenines/erlang.mk/blob/master/plugins/bootstrap.mk#L52-L68

**Comment by essen** [comment]
I was going to suggest commenting things but you're much faster than me.

I'm also using zsh so this issue has been annoying me for a while, I thought it was just me...

It's possibly the SP = $(SP) line specifically.

**Comment by essen** [comment]
That or the include erlang.mk parts.

**Comment by jeromer** [comment]
Most likely the ```include erlang.mk``` part I think.

**Comment by jeromer** [comment]
Confirmed, the problem comes from this line : https://github.com/ninenines/erlang.mk/blob/master/plugins/bootstrap.mk#L61

**Comment by essen** [comment]
There might be a way to escape it that will still work for ZSH (maybe put in a variable or something).

**Comment by essen** [comment]
I fixed this using a work around. Update and try: "make erlang-mk; make <TAB>". Closing, thanks!
