### ISSUE TITLE
only one app in 'apps/' dir + deps: 'make tests' fails

### ISSUE THREAD

**Issue by jeanparpaillon** [ninenines/erlang.mk#443]
Hi,
I have an application with only one app in 'apps/' and several deps.
'make tests' fails with:
make: *** No rule to make target 'erocci.d', needed by 'test-build'.  Stop.

Source code: https://github.com/erocci 

In the doc, it is not clear if deps should be declared in <PROJECT_ROOT>/Makefile or in 'apps/erocci/Makefile'. May this cause my trouble ?

**Comment by essen** [comment]
The trouble is that this part isn't tested yet, unfortunately, and so bugs are not too surprising. Everything not documented in the guide is also not tested. Will look into it.

**Comment by jeanparpaillon** [comment]
Refinement
Precisely:
- the 'eunit' target fails with "No rule to make target '<app>.d'...'
- 'ct' does not run ct for apps in 'apps/'

**Comment by essen** [comment]
The eunit target now runs EUnit against all apps in apps/. The ct target currently still doesn't run them. So this is only half fixed.

**Comment by essen** [comment]
Common Test has also been fixed. Please update with "make erlang-mk" and then "make tests" to try again. Thanks!
