### ISSUE TITLE
'make edoc' builds .erlang.mk/rebar edoc 

### ISSUE THREAD

**Issue by jeanparpaillon** [ninenines/erlang.mk#444]
When running 'make edoc', erlang.mk tries to build rebar doc in '.erlang.mk'

**Comment by essen** [comment]
Can you try with `EDOC_OPTS=no_subpackages make edoc`?

**Comment by jeanparpaillon** [comment]
same thing

I will try to play with edoc options and let you know

**Comment by jeanparpaillon** [comment]
Following pr could solve this issue (given that default values for edoc options are ok):
https://github.com/ninenines/erlang.mk/pull/445

**Comment by essen** [comment]
Now that edoc has tests, including one test with edown (which requires fetching rebar in .erlang.mk/rebar), I tried to look into this. However when I run "make edoc", it doesn't try to build the docs for rebar, even if I try a few times (just in case it wouldn't on first try).

I need more details to reproduce this.

**Comment by essen** [comment]
Closing until I get instructions to reproduce.
