### ISSUE TITLE
include_lib does not see all apps in APPS_DIR and DEPS_DIR

### ISSUE THREAD

**Issue by goertzenator** [ninenines/erlang.mk#447]
I have several apps in my `APPS_DIR`, and one of them `-include_lib`s a header from a sibling app.  This results in a `can't find include lib ...` compile error.

Consider this excerpt from the code loader documentation:

"The environment variable `ERL_LIBS` (defined in the operating system) can be used to define additional library directories that will be handled in the same way as the standard OTP library directory described above, *except that directories that do not have an ebin directory will be ignored.*" (emphasis mine)

So I look at the application where the header is coming from, and sure enough it has not been compiled yet and there is no `ebin` directory.  I create a empty `ebin` directory for this app, and every then compiles properly.

Looking at the verbose build output, I see that DEPS are built before the current app.  Perhaps LOCAL_DEPS should be handled similarly?

**Comment by essen** [comment]
Correct. I think there was a similar ticket not too long ago.

**Comment by goertzenator** [comment]
Oops.  It must be issue #380.

**Comment by essen** [comment]
That's it. More info is always helpful though. Closing, thanks!
