### ISSUE TITLE
Can't use ":" rules for generating source code

### ISSUE THREAD

**Issue by goertzenator** [ninenines/erlang.mk#448]
I have an application that generates one of it's source files.  After recently upgrading my erlang.mk, it broke with the error:

`Makefile:10: *** target file 'src/srpc_generated.erl' has both : and :: entries.  Stop.`

My Makefile is

```
PROJECT = srpc
BUILD_DEPS := yamler

app::src/srpc_generated.erl

include ../../dep_sources.mk
include ../../erlang.mk

src/srpc_generated.erl: priv/generate_erl deps
    priv/generate_erl <priv/srpcapi.yaml >$@

clean::
    rm -f src/srpc_generated.erl
```

Inspection of erlang.mk shows [this](https://github.com/ninenines/erlang.mk/blob/master/core/erlc.mk#L194) recent change is likely the cause.

I changed my rule from ":" to "::" and it seemed to work.  I can live with this, but I found the situation unsettling.  I assumed I had the full power of `make` at my disposal, but now erlang.mk was now somehow leaking into my rules.  It feels like a coupling/cohesion violation.  Are there other less intrusive options to manage rebuilds on Makefile changes?

**Comment by essen** [comment]
I'm open to suggestions. :-)

**Comment by goertzenator** [comment]
I will ponder this then. ;)

**Comment by essen** [comment]
I may have an idea. Instead of having this clause there, perhaps we can have this added to the .d file, switch it back to use a single colon and then it should be good. Needs more thoughts but I think it's a possibility.

**Comment by goertzenator** [comment]
Shortly after I posted this issue I experimented with making `$(MAKEFILE_LIST)` a dependency of the .d and then the .app file, but that didn't seem to work at all.  I confess I haven't fully wrapped my head around how `erlc.mk` works.

**Comment by essen** [comment]
Erlang.mk already automatically rebuilds on Makefile changes so this should no longer be an issue. Erlang.mk still prevents using single `:` targets for files but I've not seen it being an issue recently (maybe the element of surprise remains). This is all covered by various tests generating files or rebuilding on Makefile changes. Closing, thanks!
