### ISSUE TITLE
Add a method to fetch a sub directory of a git repos

### ISSUE THREAD

**Issue by essen** [ninenines/erlang.mk#450]
This would allow fetching individual applications from repositories which follow the APPS_DIR method.

This is one way to do this:

https://stackoverflow.com/questions/600079/is-there-any-way-to-clone-a-git-repositorys-sub-directory-only/13738951#13738951

**Comment by essen** [comment]
Link is probably not what we want. An alternative would be to clone and just copy the directory we want, or clone and `ln -s` the directory we want.

**Comment by fleximus** [comment]
To fetch only a subdirectory of a git repo I'd use these commands:
<pre><code>git clone -n https://github.com/username/repo
cd repo  
git checkout HEAD path/to/fetch</code></pre>
Let me know if that's a proper solution for you.

**Comment by essen** [comment]
Right but this still doesn't fetch the directory in the right location.

**Comment by essen** [comment]
I've made a first implementation of this. Push soon!
