### ISSUE TITLE
Adding a new dependency to already created project fails 

### ISSUE THREAD

**Issue by presci** [ninenines/erlang.mk#455]
I have the project that we are building using erlang.mk. I want to add new dependency to the project while it successfully gets the new dependency from the git and builds it. Any function that I invoke on the the new dependency fails with 
exception error: undefined function

when I run the project
i.e. ./_rel/bub_release/bin/bub_release console
(bub@127.0.0.1)1> jiffy:decode(<<"{\"foo\": \"bar\"}">>).
** exception error: undefined function jiffy:decode/1

But when I create the new project with all the dependency it successfully executes the function. The problem is with old project. Is there a work around for this.

**Comment by essen** [comment]
It sounds like you have a project with a `src/bub.app.src` file. You need to add jiffy in the `applications` key inside this file in order to have it included in the release.

If this is annoying, consider switching to having all such configuration in the Makefile, delete the .app.src and let Erlang.mk do it for you automatically: http://erlang.mk/guide/ch06.html#_application_resource_file

**Comment by presci** [comment]
Thanks for quick response, Following is my Makefile 
PROJECT = bub
DEPS = cowboy jiffy
dep_jiffy = git https://github.com/davisp/jiffy master
include erlang.mk

jiffy is the new thing that I added and it gives me the undefined error when I invoke the function.

So I created a new project and added the jiffy after doing *make bootstrap bootstrap-rel* and it worked fine.
The problem is with existing project. I did distclean, deleted all the rel, ebin, rel, _rel, deps folder manually but nothing seems to work.

**Comment by essen** [comment]
New projects don't have the .app.src anymore, which is why it works there without any extra operations. On the old project, simply deleting `src/bub.app.src` should also fix it.

**Comment by presci** [comment]
I updated the bub.app.src file 
plication, bub, [
{description, "Hello Erlang!"},
{vsn,"0.1.0"},
{modules,[]},
{registered,[]},
{applications,[
kernel,
stdlib,
mnesia,
jiffy,
cowboy
]},
{mod,{bub_app,[]}},
{env,[]}
]}.


and it worked thanks essen

**Comment by essen** [comment]
Enjoy!
