### ISSUE TITLE
Problem with custom_tags in erlydtl

### ISSUE THREAD

**Issue by brigadier** [ninenines/erlang.mk#457]
Looks like there's an issue with erlydtl templates which load custom tags libraries. Sometimes templates get compiled as if the tag libraries modules files would not exist, even though they are included in the COMPILE_FIRST directive. In my project the sure way to make templates compiled without the custom tags is to `make` everything after `make clean`. I then have to change something in the templates and do `make` again for the second time to make templates compiled correctly.
The following Makefile row
`export ERLYDTL_COMPILER_OPTIONS=[debug_compiler, return_errors, {doc_root, "templates/"}, {libraries, [{mydtltags, mydtltags}, {myotherdtltags, myotherdtltags}]}, {default_libraries, [myotherdtltags, mydtltags]}]`
would make erlydtl compiler use custom tags and modules from mydtltags.erl and myotherdtltags.erl and autoload both in all dtl templates. These library modules could be taken both from deps and from the current app.
I expect it happens because of parallel compilation or something like that.
There's no such problem in august-september versions of erlang.mk

**Comment by essen** [comment]
Hey, I have seen and fixed an issue with erlydtl + parallel building yesterday or the day before. Does it still happen with most recent Erlang.mk? Maybe I missed something.

**Comment by brigadier** [comment]
I use the most recent erlang.mk, right after make erlang-mk

**Comment by essen** [comment]
At some point since the august-september version you had, DTL files compilation was moved *before* Erlang file compilation. This probably did it.

**Comment by philipcristiano** [comment]
Is there a workaround that can be set in the Makefile that doesn't require double running of make?

**Comment by essen** [comment]
Try editing https://github.com/ninenines/erlang.mk/blob/master/build.config

and move the erlydtl line sometimes after the core/erlc line.

Then report back. If it still works, tests still pass and so on then perhaps this is the way to go.

**Comment by philipcristiano** [comment]
Thanks! I'll give that a try

**Comment by philipcristiano** [comment]
Moving `erlydtl` down worked for my project. I'm still looking through the tests. At the moment they fail for me at the same point on `master` as they do with my change.

**Comment by essen** [comment]
If "make check c=erlydtl" passes then it's all good I believe and we should fix it that way.

**Comment by philipcristiano** [comment]
Ah, that's a whole bunch faster/easier. Tests appear to pass, PR added.

**Comment by essen** [comment]
Fix will be pushed soon. Closing, thanks!
