### ISSUE TITLE
Automatic DEPS / LOCAL_DEPS dispatch ?

### ISSUE THREAD

**Issue by jeanparpaillon** [ninenines/erlang.mk#461]
Hi,
In the case a depandancy is installed globally (for instance cowboy from a Debian package), I like to use it rather than fetching into 'deps/'.
The following Makefile code detect the presence of an application and put the dependancy in DEPS or LOCAL_DEPS depending on the result:

```make
define localdep =
$(shell erl -noshell -eval "case application:ensure_all_started($1) of {ok, _} -> halt(0); _ -> halt(1) end." && echo ok || true)
endef

ALL_DEPS = cowboy getopt
$(foreach dep,$(ALL_DEPS),$(if $(call localdep,$(dep)),$(eval LOCAL_DEPS+=$(dep)),$(eval DEPS+=$(dep))))
```

I submit it in case we would like to include it as an erlang.mk feature.

**Comment by essen** [comment]
No plans for that.

As long as you have an easy enough solution, I'm happy. :-)
