### ISSUE TITLE
any way to automate edown doc generation?

### ISSUE THREAD

**Issue by benoitc** [ninenines/erlang.mk#463]
Is there any way right now to automate the build of the documentation using edown?

**Comment by essen** [comment]
Try this:

``` make
DOC_DEPS = edown
EDOC_OPTS = {doclet, edown_doclet}

distclean:: distclean-edown
distclean-edown:
	rm -rf doc/*.md
```

First two should be before include erlang.mk, others don't matter (they're not required, but it's nice to clean up generated files on 'make distclean').

**Comment by benoitc** [comment]
Thanks. works perfectly :+1:
