### ISSUE TITLE
Documentation errata

### ISSUE THREAD

**Issue by skvamme** [ninenines/erlang.mk#465]
In http://ninenines.eu/docs/en/cowboy/1.0/guide/getting_started/ there is a reference to src/hello_erlang.app.src but it doesn't exist. And my suggestion is to change the getting started guide to let the user edit ebin/client.app directly.

**Comment by essen** [comment]
There's no need to edit anything anymore. I will fix the Cowboy getting started soon.

**Comment by skvamme** [comment]
Thanks :)
