### ISSUE TITLE
Missing link in compat.asciidoc

### ISSUE THREAD

**Issue by crownedgrouse** [ninenines/erlang.mk#466]
compat.asciidoc refer to this missing document : 
https://github.com/ninenines/erlang.mk/blob/master/doc/src/guide/sanity_check.asciidoc

but it is maybe normal for futur document creation...

**Comment by essen** [comment]
Yes it's a planned feature (check-deps): https://github.com/ninenines/erlang.mk/issues/305

**Comment by essen** [comment]
Posted your comment in the other ticket, closing this. Thanks!
