### ISSUE TITLE
Missing link in app.asciidoc

### ISSUE THREAD

**Issue by crownedgrouse** [ninenines/erlang.mk#467]
https://github.com/ninenines/erlang.mk/blob/master/doc/src/guide/relx.asciidoc

for memory, too

**Comment by crownedgrouse** [comment]
maybe it should be https://github.com/ninenines/erlang.mk/blob/master/doc/src/guide/releases.asciidoc  ?

**Comment by essen** [comment]
Yes. Patch welcome.

**Comment by crownedgrouse** [comment]
will do it, but this evening.
