### ISSUE TITLE
Specify a single test in a common test suite without the need for a group

### ISSUE THREAD

**Issue by dmitriid** [ninenines/erlang.mk#469]
Quite often a test suite will not contain groups. We might still need to run a single test case from that suite.

As per discussion here: https://twitter.com/dmitriid/status/682184868827103232

Possible alternatives:
- `t=:case` with an empty group. Because `t=group` is already taken
- Or maybe use a `c=case`

**Comment by essen** [comment]
I've implemented the second one. Will push soon. Thanks!
