### ISSUE TITLE
Plugin crash

### ISSUE THREAD

**Issue by glejeune** [ninenines/erlang.mk#470]
when creating a plugin containing the word "rebar", erlang.mk generates a crashdump while loading the plugin. You can reproduce this bug by creating a simple plugin with just a comment :

```
# error_plugin.mk
# rebar.config
```

Then load this plugin. You will see something like that : 

```
 DEP    error_plugin.mk
{"init terminating in do_boot",{{badmatch,{error,{1,erl_parse,["syntax error before: ","'.'"]}}},[{init,start_it,1,[]},{init,start_em,1,[]}]}}

Crash dump is being written to: erl_crash.dump...done
init terminating in do_boot ()
```

Note that this error message does not predict that the plugin does not work. Indeed, the plugin works fine. You can do a more complete test using https://github.com/botsunit/elixir.mk

**Comment by essen** [comment]
Probably the funniest bug of the year. Just in time...

The simplest would be to ignore plugins.mk when doing the rebar check I suppose. It will take me a while to make sure this doesn't break anything.

**Comment by essen** [comment]
I've added a test locally. Seems this was fixed a while ago. Closing, thanks!
