### ISSUE TITLE
idna keeps recompiling when using hackney dep

### ISSUE THREAD

**Issue by rlipscombe** [ninenines/erlang.mk#471]
```
PROJECT = foo
DEPS = hackney

include erlang.mk
```

[Hackney](https://github.com/benoitc/hackney) depends on idna, which is recompiled unnecessarily when using erlang.mk. The following 5 modules are recompiled every time I run `make`:

```
make[1]: Entering directory `/home/roger/Source/foo/deps/hackney'
make[2]: Entering directory `/home/roger/Source/foo/deps/idna'
Recompile: src/punycode
Recompile: src/idna_unicode_data
Recompile: src/idna_unicode
Recompile: src/idna_ucs
Recompile: src/idna
```

Using rebar 2.6.1 against hackney itself, this doesn't happen.

**Comment by rlipscombe** [comment]
Actually, looks like a bug (?) in idna: https://github.com/benoitc/erlang-idna/blob/master/Makefile#L1

**Comment by essen** [comment]
Yes I don't think I can do much about that. I know @benoitc was playing with Erlang.mk recently, maybe he'll be interested to convert that one.

**Comment by benoitc** [comment]
this has been fixed in hackney 1.4.8. Sorry for that.

**Comment by essen** [comment]
Awesome! Closing, thanks!

**Comment by rlipscombe** [comment]
It doesn't appear to work correctly, because `rebar.config.script` still references idna 1.0.2, and it looks like erlang.mk is using rebar 2.x. If I add the following to my top-level Makefile, it works, but it's not seamless:

```
PROJECT = foo
DEPS = hackney idna
dep_idna = git https://github.com/benoitc/erlang-idna 1.0.3
dep_hackney = git https://github.com/benoitc/hackney 1.4.8
```

**Comment by benoitc** [comment]
please open a ticket in the appropriate place. i will fix it.

**Comment by rlipscombe** [comment]
Sure; I posted here to (a) maybe get some confirmation about how erlang.mk deals with rebar.config.script, and (b) because of the workaround. I'll raise an issue against hackney.

**Comment by essen** [comment]
Yes, Erlang.mk runs rebar.config.script.
