### ISSUE TITLE
[question] why no an app.src with the bootstrap command

### ISSUE THREAD

**Issue by benoitc** [ninenines/erlang.mk#472]
It seems odd to not have a `.app.src` or an `ebin/smth.app` created during bootstrap.. It forces me to create one just to register some specific files and add some metadata to the .app .

This is not a big issue, but I am actually wonder why? Any reason for this?

**Comment by essen** [comment]
See this section: http://erlang.mk/guide/building.html#_application_resource_file

The .app is generated from the Makefile itself. It currently has all values available for configuration except env (a ticket is already open for that).

You can still use the old method of .app.src by adding LEGACY=1 to your bootstrap command. It's not going away, it's just less practical for most projects.

**Comment by benoitc** [comment]
I missed that part. Sorry :) Closing the issue it's all clear now thanks!
