### ISSUE TITLE
erlang.mk is not downloading the deps recursively for hex projects

### ISSUE THREAD

**Issue by elbrujohalcon** [ninenines/erlang.mk#473]
Check [this repo](https://github.com/elbrujohalcon/hexample).
It has one dependency, [lager](hex.pm/packages/lager):

``` Makefile
dep_lager = hex 3.0.2
```

As you can see in hex.pm, lager has `goldrush 1.7.0` as dependency itself, but erlang.mk does not download it.

**Comment by essen** [comment]
Looks like the rebar.config in hex.pm is different than the one in basho/lager. It uses the form `{deps, [goldrush]}` which I'm not sure how it should be interpeted, considering it doesn't even have a tag. Does that ring a bell?

**Comment by essen** [comment]
Oh yeah it's in rebar.lock, I see. Well I guess we need to add support for that then.

**Comment by essen** [comment]
Added support for that a while ago.
