### ISSUE TITLE
project.d prevents app from getting compiled when one of includes moved to another location

### ISSUE THREAD

**Issue by brigadier** [ninenines/erlang.mk#474]
the `app.d` file prevents app from getting compiled when one of included hrl files gets moved to another location.
When I move `lib.hrl` to another app and change `-include("lib.hrl").` to `-include_lib("app/include/lib.hrl").` make would fail with with error `No rule to make target include/lib.hrl, needed by src/module.erl`.until .d file is deleted.

**Comment by essen** [comment]
Can I have the Erlang.mk output when that happens?

**Comment by brigadier** [comment]
$ make
make[1]: Entering directory '/home/evgeny/projects/mk/deps/app'
make[1]: Leaving directory '/home/evgeny/projects/mk/deps/app'
make: *** No rule to make target 'include/test.hrl', needed by 'src/mk_app.erl'.  Stop.

https://github.com/brigadier/mk - example, `test.hrl` included in `src/mk_app.erl`

**Comment by essen** [comment]
Thanks! It looks like we could avoid this issue by defining a target for the include files (and I'm guessing, the other file dependencies too). I'll need to do an extensive test for that so I'll get back to you when it's done.

**Comment by essen** [comment]
Sounds like it yes.

**Comment by essen** [comment]
This should be fixed in my local copy which will be pushed in a few. Thanks!
