### ISSUE TITLE
Ignore rebar3 plugins

### ISSUE THREAD

**Issue by yurrriq** [ninenines/erlang.mk#477]
Projects using rebar3 plugins, namely [lfe-compile](https://github.com/lfe-rebar3/compile), fail to build, due to the incompatibility of rebar and rebar3.

Ignoring rebar3 plugin settings should remedy the situation.

**Comment by essen** [comment]
Thanks, I will try to get it done this week. This might take time because I have to make sure I don't break other packages by doing this change.

**Comment by essen** [comment]
It's possible that we may need to enhance autopatch to detect deps that have LFE files and add the plugin automatically, otherwise it probably won't be used right now.

**Comment by yurrriq** [comment]
Sounds good to me. I'm happy to adopt whatever best practices arise on my ports of the cowboy examples.

**Comment by essen** [comment]
More on that last point: we should allow plugins to hook into the autopatch system to add more things if they need to. Maybe the autopatch script could be split up into different variables and the plugins could add to that list. This would also allow a user to customize what parts of autopatch are actually executed.

While I'm confident ignoring rebar3 plugins can be done pretty quickly, doing a proper autopatch might take more time. I'll get back to you.

**Comment by yurrriq** [comment]
:+1:

**Comment by essen** [comment]
I've added the ignore of plugins when the plugin is not given as an atom, and independently from that I've also added the loading of lfe.mk automatically when the lfe-compile plugin is specified. It was successful for clj (and seemed to be good with others that depend on lutil but I got compile errors on that). Please experiment and open tickets so we can fix any issues that pop up.
