### ISSUE TITLE
Is it possible to skip compiling dependencies (DEPS_DIR) but still compile APPS_DIR?

### ISSUE THREAD

**Issue by gatesn** [ninenines/erlang.mk#478]

**Comment by essen** [comment]
`SKIP_DEPS=1` doesn't do that?

**Comment by Gatzy118** [comment]
I think the ifneq needs an endif between lines 54/55 of core/deps.mk. Otherwise the ALL_APPS_DIR builds only get run if SKIP_DEPS is not set

**Comment by essen** [comment]
Alright.

**Comment by essen** [comment]
I think this was fixed a while ago.
