### ISSUE TITLE
ERLC_OPTS strips only first comma/space not multiple

### ISSUE THREAD

**Issue by Gatzy118** [ninenines/erlang.mk#479]
I believe line 9 or core/compat.mk should be changed from

compat_prepare_erlc_opts = $(shell echo "$1" | sed 's/, */,/')

to 

compat_prepare_erlc_opts = $(shell echo "$1" | sed 's/, */,/g')

This line fails:
ERLC_OPTS += +'{parse_transform, lager_transform}' +'{lager_truncation_size, 20480}' +warn_missing_spec

But this succeeds (note the removal of second comma/whitepsace)

ERLC_OPTS += +'{parse_transform, lager_transform}' +'{lager_truncation_size,20480}' +warn_missing_spec

**Comment by essen** [comment]
Sounds good, please send a PR. You can easily update the following test to make sure it doesn't get broken again: https://github.com/ninenines/erlang.mk/blob/master/test/core_compat.mk#L208

**Comment by essen** [comment]
Think I merged your PR. Closing, thanks!
