### ISSUE TITLE
hook to run before compiling c_sources

### ISSUE THREAD

**Issue by brigadier** [ninenines/erlang.mk#485]
Is it possible to run a shell executable file every time before erlang.mk compiles c_src and before it cleans the results? I see in the docs an example on how to generate source files and make them depend on shell file, but how to run a shell file without having to create an another makefile in c_src?

**Comment by essen** [comment]
You can override the app and clean rules by doing something like this:

```
app::
    ./myshell.sh

clean::
    ./myshell.sh clean

include erlang.mk
```

Anything before the erlang.mk include is run before, after the include is run after.

Note that in this solution it will run everytime even if the C source doesn't need to be recompiled.

**Comment by brigadier** [comment]
thank you!
