### ISSUE TITLE
Add a switch to also Dialyze tests

### ISSUE THREAD

**Issue by essen** [ninenines/erlang.mk#487]
A discussion on IRC made me realize it's not easy enough to dialyze tests currently. It's a shame because it's really useful to include those from time to time. It should be made easier.

**Comment by elbrujohalcon** [comment]
[inaka.mk](http://github.com/inaka/inaka.mk) already has support for this. You can see it [here](https://github.com/inaka/inaka.mk/blob/master/plugins.mk#L28)

**Comment by essen** [comment]
It's already very easy to add to the Makefile, so not really necessary.
