### ISSUE TITLE
Make erlang.mk build ejabberd

### ISSUE THREAD

**Issue by leoliu** [ninenines/erlang.mk#488]
As suggested in the subject.

**Comment by essen** [comment]
I think that's the line making it fail: https://github.com/processone/ejabberd/blob/master/rebar.config#L125

But seems there's no c_src directory anymore.

**Comment by katsel** [comment]
ejabberd could be added to the list in #265 for completeness.

**Comment by essen** [comment]
Added to the main ticket. Closign this one, thanks!
