### ISSUE TITLE
Is it intended that applications in the APPS_DIR share a DEPS_DIR?

### ISSUE THREAD

**Issue by Gatzy118** [ninenines/erlang.mk#489]
Should the local applications share a deps directory <proj>/deps, or have individual ones in <proj>/apps/<app>/deps ?

Both seem reasonable for different reasons

**Comment by essen** [comment]
It is intended to have a single deps directory. One reason for that is that there can be only one version of an application running anyway. It is also arguably simpler.

Nevertheless, if you really want to have more than one deps directory, you can override DEPS_DIR in each individual app. But some functionality of Erlang.mk expects the root DEPS_DIR be where the applications are.

**Comment by essen** [comment]
Closing since answered.
