### ISSUE TITLE
Optimize

### ISSUE THREAD

**Issue by essen** [ninenines/erlang.mk#493]
Erlang.mk has grown slow. There are a few reasons for that, one being that it really only has one optimization (one erlc call to compile all Erlang files) and has never been optimized much otherwise. Another reason is because of makedep, which while it is a very important feature to reduce compile times, also increases compile times in some cases.

The speed can be restored and even improved by looking into a number of things. My initial experiments show we can get back to the early days speed by doing just a few tiny changes.

The general ideas are as follow:
- Done. This is enabled via V=3. <s>Run `make target SHELL="/bin/sh -x"` and find patterns in the commands. Sometimes the same command is repeated, sometimes we can group commands.</s>
- Use := instead of = where shell commands are run to avoid repeating them.
- <s>Do a single find of all files in the src/ directory and then filter what we need in separate variables.</s>
- Experiment with lazy only-once initialization of variables where it could be benefitial.
- <s>Write a ccache-like plugin for Erlang.mk.</s>
- <s>Provide a guile version of makedep. It should be doable because we only look at forms and have limited needs for parsing Erlang.</s>

All points except the last two are trivial and should provide great improvements on small targets. The last two points provide great improvements to compile time. The last point is probably crazy and not necessary if we get a ccache-like up and running.

**Comment by essen** [comment]
The shell thing should probably be made a debug option.

**Comment by essen** [comment]
Useful links: http://www.oreilly.com/openbook/make3/book/ch10.pdf and https://ccache.samba.org/manual.html

**Comment by crownedgrouse** [comment]
Running make with the -d flag outputs debugging information outlining exactly what make is doing and in what order, as well as why it is doing it. I don't know if you already use it, but can help...

**Comment by essen** [comment]
Make has a few flags, yes. And we also have V=2 which shows what the shell is going to run exactly. But these are more interesting for debugging purposes rather than optimization I think.

**Comment by crownedgrouse** [comment]
I did not check in the code, but do you remove default buitins rules done by make ?
https://ftp.gnu.org/old-gnu/Manuals/make-3.79.1/html_chapter/make_toc.html#TOC95

This can be remove by : 
```
MAKEFLAGS += --no-builtin-rules

.SUFFIXES:
.SUFFIXES: .you .own .here
```
and should probably increase speed on big project.

**Comment by essen** [comment]
I don't see any change with or without them. You can try on your projects if you want, use "time make -r".

**Comment by crownedgrouse** [comment]
I noticed a gain of 0,02 s in average on some projects, after doing comparison for a while. It is obviously hard to be sure of this, due to the fact that computer do lot of thing in parallel, but the time is almost always less of equal than without -r. Not that great, but maybe to keep in mind.

**Comment by essen** [comment]
I'm up for it regardless of performance improvements.

**Comment by essen** [comment]
The ccache stuff is probably not worth it. There's a lot of pitfalls and it's not going to help too many people. The guile makedep can be left out for now.

**Comment by essen** [comment]
The `V=3` I've added is pretty good to figure out what runs.

**Comment by essen** [comment]
Made a few optimizations locally, will push later today. Haven't figured out where to use lazy initialization unfortunately, but I'm keeping the link around. Closing, thanks!
