### ISSUE TITLE
Offering package 'slack' if you'd like to add it

### ISSUE THREAD

**Issue by DonBranson** [ninenines/erlang.mk#498]
It's a very minimalist approach to do slack notifications. https://github.com/DonBranson/slack

slack.mk:

    PACKAGES += slack
    pkg_slack_name = slack
    pkg_slack_description = Minimal slack notification OTP library.
    pkg_slack_homepage = https://github.com/DonBranson/slack
    pkg_slack_fetch = git
    pkg_slack_repo = https://github.com/DonBranson/slack.git
    pkg_slack_commit = master

**Comment by essen** [comment]
Yes, though it would go quicker with a PR: http://erlang.mk/guide/contributing.html#_packages

Either way not before tomorrow. Thanks!

**Comment by essen** [comment]
Closing because PR. Thanks!
