### ISSUE TITLE
Compile error with Debian

### ISSUE THREAD

**Issue by GeneveyC** [ninenines/erlang.mk#505]
Hi, i meet a issue with the compilation : 

make[1]: Entering directory '/root/Documents/cowboy/deps/cowlib'
../../erlang.mk:4041: The variable OTP_DEPS is deprecated in favor of LOCAL_DEPS.
../../erlang.mk:4041: The variable OTP_DEPS is deprecated in favor of LOCAL_DEPS.
make[1]: Leaving directory '/root/Documents/cowboy/deps/cowlib'
make[1]: Entering directory '/root/Documents/cowboy/deps/ranch'
make[1]: Leaving directory '/root/Documents/cowboy/deps/ranch'
 ERLC   cowboy.erl cowboy_app.erl cowboy_bstr.erl cowboy_clock.erl cowboy_constraints.erl cowboy_handler.erl cowboy_http2.erl cowboy_loop.erl cowboy_middleware.erl cowboy_protocol.erl cowboy_req.erl cowboy_rest.erl cowboy_router.erl cowboy_spdy.erl cowboy_static.erl cowboy_stream.erl cowboy_sub_protocol.erl cowboy_sup.erl cowboy_tls.erl cowboy_websocket.erl
src/cowboy_req.erl:1206: illegal use of variable 'Atom' in map
src/cowboy_req.erl:1209: illegal use of variable 'Atom' in map
src/cowboy_req.erl:1212: illegal use of variable 'Atom' in map
src/cowboy_req.erl:1233: illegal use of variable 'Key' in map
src/cowboy_req.erl:1244: illegal use of variable 'Key' in map
erlang.mk:4956: recipe for target 'ebin/cowboy.app' failed
make[1]: *** [ebin/cowboy.app] Error 1
erlang.mk:4774: recipe for target 'app' failed
make: *** [app] Error 2

I have check the other issue in github about the compile error but any solution solve my problem.
So if someone can tell me what is my problem and help me to solve my problem
Thanks

**Comment by essen** [comment]
You are trying to compile Cowboy master which requires Erlang 18+. Either use Cowboy 1.0 or update your Erlang version.

**Comment by GeneveyC** [comment]
Thanks,
I use Cowboy 1.0 and it's work!
