### ISSUE TITLE
poolboy dep fails

### ISSUE THREAD

**Issue by StuartHickey** [ninenines/erlang.mk#508]
Hi,

I've been following the ninenines tutorial for cowboy along with your video presentation last year at the Erlang user conference. 

I'm doing the install on a ubuntu 14.04 cloud server. 
Erlang is installed: Erlang/OTP 18 [erts-7.2] [source] [64-bit] [async-threads:10] [kernel-poll:false]
make version: 3.81
Makefile is:

PROJECT = hello_erlang
PROJECT_DESCRIPTION = New project
PROJECT_VERSION = 0.0.1
DEPS = cowboy cpg erlydtl riak_core
include erlang.mk

when I try and run make I get a failing compile on the poorboy dependancy

hello_erlang$ make
make[1]: Entering directory `/home/ubuntu/hello_erlang/deps/cowboy'
make[2]: Entering directory `/home/ubuntu/hello_erlang/deps/cowlib'
make[2]: Leaving directory `/home/ubuntu/hello_erlang/deps/cowlib'
make[2]: Entering directory `/home/ubuntu/hello_erlang/deps/ranch'
make[2]: Leaving directory `/home/ubuntu/hello_erlang/deps/ranch'
make[1]: Leaving directory `/home/ubuntu/hello_erlang/deps/cowboy'
make[1]: Entering directory `/home/ubuntu/hello_erlang/deps/cpg'
make[2]: Entering directory `/home/ubuntu/hello_erlang/deps/trie'
make[2]: Leaving directory `/home/ubuntu/hello_erlang/deps/trie'
make[2]: Entering directory `/home/ubuntu/hello_erlang/deps/quickrand'
make[2]: Leaving directory `/home/ubuntu/hello_erlang/deps/quickrand'
make[1]: Leaving directory `/home/ubuntu/hello_erlang/deps/cpg'
make[1]: Entering directory `/home/ubuntu/hello_erlang/deps/erlydtl'
make[1]: Leaving directory `/home/ubuntu/hello_erlang/deps/erlydtl'
make[1]: Entering directory `/home/ubuntu/hello_erlang/deps/riak_core'
make[2]: Entering directory `/home/ubuntu/hello_erlang/deps/lager'
make[3]: Entering directory `/home/ubuntu/hello_erlang/deps/goldrush'
make[3]: Leaving directory `/home/ubuntu/hello_erlang/deps/goldrush'
make[2]: Leaving directory `/home/ubuntu/hello_erlang/deps/lager'
make[2]: Entering directory `/home/ubuntu/hello_erlang/deps/poolboy'
 ERLC   poolboy.erl poolboy_sup.erl poolboy_worker.erl
src/poolboy.erl:25: type queue() undefined
make[3]: *** [ebin/poolboy.app] Error 1
make[2]: *** [app] Error 2
make[2]: Leaving directory `/home/ubuntu/hello_erlang/deps/poolboy'
make[1]: *** [deps] Error 2
make[1]: Leaving directory `/home/ubuntu/hello_erlang/deps/riak_core'
make: *** [deps] Error 2

Any assistance much appreciated. I'm probably missing something very obvious. 

thanks

**Comment by essen** [comment]
I suspect the poolboy you are trying to compile doesn't work with Erlang/OTP 18, considering the error. If it's coming as a dep from riak_core, then know that Riak doesn't work with 18, you'll need 17 at most.

**Comment by StuartHickey** [comment]
Ahh ok thanks ... so either remove risk_core or drop down a version of Erlang. Removed the risk_core dep and it compiles. Many thanks. Feel free to close the issue. 

PS Also going to buy your book today! ;-)

**Comment by essen** [comment]
Cheers.
