### ISSUE TITLE
Track dependencies between apps

### ISSUE THREAD

**Issue by ingwinlu** [ninenines/erlang.mk#510]
while toying with multi-application repositories where I have a bunch of applications that optionally depend on each other (so I had to set `APPS_DIR` to `../`) I found out that I would have to add the name of that subapplication (`$(PROJECT)`) to IGNORE_DEPS so it gets ignored during the deps phase of the build cycle.

A simple fix could be changing IGNORE_DEPS in core/deps.mk:

```
-IGNORE_DEPS ?=
+IGNORE_DEPS ?= $(PROJECT)
```

**Comment by essen** [comment]
OK I'm not sure I get everything.

* Why did you have to set APPS_DIR to `../`?
* How did you specify the dependencies? LOCAL_DEPS? Or?

**Comment by ingwinlu** [comment]
The `APPS_DIR` helped out in my case with the compilation order that was needed to actually compile all apps. Now after looking even more into it I guess it was just accidentally fixing the problem I was having and is not the way forward to help with similar problems.

What is needed is tracking dependencies between apps. So they get compiled in the right order. I think that is already mentioned in other open Issues so you can close this one.

**Comment by ingwinlu** [comment]
In case anybody else stumbles upon on it here is a workaround that seems to work fine for me:

To have an easier time describing let's define some applications with dependencies between them:
* service
* service_xml (depends on service)
* service_json (depends on service)

To ensure the correct build order we can use locally fetched dependencies. I.e. service_xml would define
```
DEPS = service
dep_service = cp ../service
```
which results in apps/service getting copied to deps. Deps get build BEFORE apps. So it should be available in the right order.

**Comment by essen** [comment]
Dependencies should now be tracked between apps. Thanks!
