### ISSUE TITLE
Mentioning rebar in Makefile comment causes erlang.mk to autopatch when it's not needed

### ISSUE THREAD

**Issue by sata** [ninenines/erlang.mk#512]
Scenario:

Project Foo has dependency Bar which has this arbitrary line in Makefile

>  # fetching down rebar from internal repos

This causes erlang.mk to invoke dep_autopatch where 
> 		elif [ 0 != `grep -ci rebar $(DEPS_DIR)/$(1)/Makefile` ]; then \

clause will be true since the grep doesn't consider comments. End result is dep_autopatch_gen is invoked which overwrites the existing Bar Makefile with the tiny template one, thus breaking any erlc compiler flags Bar might have.

Perhaps possible to use egrep with regex to filter out lines starting with #? 

Thought I raise this anyway.

**Comment by essen** [comment]
I suppose it could be doable to filter out comments, good idea! Patch welcome. :-)

**Comment by essen** [comment]
@sata I have a patch for this, do you know an open source project that has this or is it something private?

**Comment by sata** [comment]
@essen: it's a private repo. I completely forgot about this ticket! What's the patch and I can give it a go locally.

**Comment by essen** [comment]
``` diff
diff --git a/core/deps.mk b/core/deps.mk
index 16a2f88..aadacd0 100644
--- a/core/deps.mk
+++ b/core/deps.mk
@@ -88,7 +88,7 @@ define dep_autopatch
    elif [ -f $(DEPS_DIR)/$(1)/Makefile ]; then \
        if [ 0 != `grep -c "include ../\w*\.mk" $(DEPS_DIR)/$(1)/Makefile` ]; then \
            $(call dep_autopatch2,$(1)); \
-       elif [ 0 != `grep -ci rebar $(DEPS_DIR)/$(1)/Makefile` ]; then \
+       elif [ 0 != `grep -ci "^[^#].*rebar" $(DEPS_DIR)/$(1)/Makefile` ]; then \
            $(call dep_autopatch2,$(1)); \
        elif [ -n "`find $(DEPS_DIR)/$(1)/ -type f -name \*.mk -not -name erlang.mk -exec grep -i rebar '{}' \;`" ];
            $(call dep_autopatch2,$(1)); \
```

**Comment by essen** [comment]
@sata see previous comment (just in case, don't really know how the github emails work :-)

**Comment by essen** [comment]
Hello, does my patch fixes your issue?

**Comment by sata** [comment]
After upgrading erlang.mk I couldn't reproduce the bug :) I'm closing the ticket. Cheers
