### ISSUE TITLE
eunit question or maybe bug

### ISSUE THREAD

**Issue by crownedgrouse** [ninenines/erlang.mk#522]
I have 2 eunit test functions in a separated ...._tests.erl  file but when running tests :

```
$> make eunit
 GEN    eunit
  All 4 tests passed.
```

Output does not make sens to me. The only thing I can imagine is that 4 is the number of beam files in ebin/  but only 3 'real' beam files and a fourth for eunit tests.
bug or feature ?

**Comment by crownedgrouse** [comment]
hum, by adding a third function, I get now : 
```  
   All 6 tests passed.
```
Looks like result is x 2  ?

**Comment by essen** [comment]
Sounds like it's ran twice.

**Comment by crownedgrouse** [comment]
eunit.mk line 55  maybe ?
`` EUNIT_EBIN_MODS = $(notdir $(basename $(ERL_FILES) $(BEAM_FILES)))``

**Comment by essen** [comment]
Add $(info $(EUNIT_EBIN_MODS)) on the next line and see.

**Comment by crownedgrouse** [comment]
I get twice the prefix of all my 4 src/beam files (but only one containing tests), one time before 
DEPEND xxx.d
and another one time before
ERLC   (source files)

but need more time to understand the code...

**Comment by crownedgrouse** [comment]
by using V=1 I can see that finally  all my four src/beam files  are given to eunit:test(['www', 'xxx','yyy','zzz']).  I do not know if this is intentional or not.

**Comment by crownedgrouse** [comment]
So by doing manually in 'make shell' :   "All 6 tests passed." is raised by eunit:test ... So probably not an erlang.mk bug.

**Comment by crownedgrouse** [comment]
```
1> eunit:test(['xxxx_tests'],[]).
  All 3 tests passed.
ok
2> eunit:test(['xxxx'],[]).      
  All 3 tests passed.
3> eunit:test(['xxxx_tests','xxxx'],[]).
  All 6 tests passed.
```

but no tests in 'xxxx' !!!  ...

**Comment by crownedgrouse** [comment]
will open a ticket on erlang bugs, i'm not sure it is intentional... In any way tests should not be done twice. I do not close this ticket for now, waiting for OTP team answer.

**Comment by crownedgrouse** [comment]
``  eunit:test(fred)
runs all tests in the module fred and also any tests in the module fred_tests, if that module exists.``

so erlang.mk should remove _tests modules  for now and eunit should not run twice tests if both modules given.

**Comment by essen** [comment]
Erlang.mk removes _tests and there's tests for it, that's why I ask for the output of info above.

**Comment by crownedgrouse** [comment]
EUNIT_MODS = 'geas' 'geas_db' 'geas_doc' 'geas_tests'    
filter-out look to not exclude _tests modules maybe due to ' ' around ?

**Comment by essen** [comment]
'' is added later. What's the info for EUNIT_EBIN_MODS and EUNIT_TEST_MODS?

**Comment by crownedgrouse** [comment]
EUNIT_EBIN_MODS =  geas geas_db geas_doc geas_tests
EUNIT_TEST_MODS =

**Comment by essen** [comment]
Ah you have the tests in src, I understand now. That one is currently not covered by tests and this is definitely a bug. We should filter out regardless of the test module being in src/ or test/. Currently we only filter-out those in test/. Thanks!

**Comment by crownedgrouse** [comment]
is test/ something official or erlang.mk.ish ?

**Comment by essen** [comment]
https://github.com/erlang/otp/tree/maint/lib/eunit/test should answer your question. :-)

**Comment by essen** [comment]
But it is true that the module can be put in src/ and that's something we should support.

**Comment by crownedgrouse** [comment]
https://github.com/erlang/otp/tree/maint/lib/eunit/test  is a directory for common_test I thinks. eunits tests are in eunit/src/  .  Am I wrong ?

**Comment by essen** [comment]
There's two modules containing eunit tests in that directory.

**Comment by crownedgrouse** [comment]
hum . never noticed that. Thanks

**Comment by crownedgrouse** [comment]
Reminder : Still waiting this bug to be fixed in Erlang : https://bugs.erlang.org/browse/ERL-97

**Comment by essen** [comment]
Closing in favor of the OTP ticket.

**Comment by crownedgrouse** [comment]
43 bugs closed in three days. Glad to see erlang.mk having some love. Is there some roadmap for this project upcoming ?

**Comment by essen** [comment]
I'm just closing as many tickets as I can in the next few days/weeks, fixing bugs mostly and removing wishlist-type of things. I'd like to remove the old package index as well but I'm still required to accept the hex.pm CoC to use it and I don't want to do that so I'm at an impasse there.

Roadmap, I don't know, I'm very happy with the current state otherwise, I don't really have bigger plans, just small improvements to the existing functionality.
