### ISSUE TITLE
BusyBox/Alpine grep -E causes error on app-build target

### ISSUE THREAD

**Issue by JoelPM** [ninenines/erlang.mk#523]
Attempting to build ranch on Alpine linux results in the following error:

```
grep: bad regex '^[^%]*{\s*modules\s*,': Invalid contents of {}
Empty modules entry not found in ranch.app.src. Please consult the erlang.mk README for instructions.
erlang.mk:4898: recipe for target 'ebin/ranch.app' failed
```

This appears to be caused by the -E option on https://github.com/ninenines/ranch/blob/master/erlang.mk#L4907

```
bash-4.3# grep -E '^[^%]*{\s*modules\s*,' src/ranch.app.src
grep: bad regex '^[^%]*{\s*modules\s*,': Invalid contents of {}
```

If I try the regex in the shell without the extended option it works:

```
bash-4.3# grep '^[^%]*{\s*modules\s*,' src/ranch.app.src
        {modules, []},
```

For reference:
```
bash-4.3# grep -v
BusyBox v1.24.1 (2015-12-16 08:00:02 GMT) multi-call binary.
```

I'm attempting to compile and package an elixir app using the Elixir Docker Image Builder (https://github.com/edib-tool/elixir-docker-image-builder). It is based on Alpine 3.3 which is where the grep binary seems to be coming from.

Thanks,
Joel

**Comment by ingwinlu** [comment]
http://www.gnu.org/software/grep/manual/grep.html#Basic-vs-Extended
```
3.6 Basic vs Extended Regular Expressions

In basic regular expressions the meta-characters ‘?’, ‘+’, ‘{’, ‘|’, ‘(’, and ‘)’ lose their special meaning; instead use the backslashed versions ‘\?’, ‘\+’, ‘\{’, ‘\|’, ‘\(’, and ‘\)’.

Traditional egrep did not support the ‘{’ meta-character, and some egrep implementations support ‘\{’ instead, so portable scripts should avoid ‘{’ in ‘grep -E’ patterns and should use ‘[{]’ to match a literal ‘{’.

GNU grep -E attempts to support traditional usage by assuming that ‘{’ is not special if it would be the start of an invalid interval specification. For example, the command ‘grep -E '{1'’ searches for the two-character string ‘{1’ instead of reporting a syntax error in the regular expression. POSIX allows this behavior as an extension, but portable scripts should avoid it.
```

**Comment by essen** [comment]
I'm all for using something else but can't confirm it will work, what should I use?

**Comment by ingwinlu** [comment]
you should be able to install busybox and just test changes to the regex via 'busybox grep' 

different solutions can be used, either drop the -E as I do not think it is needed, or encapsulate { into [{] so it is not interpreted as 'grouping'

**Comment by JoelPM** [comment]
I can confirm that removing the -E works on busybox grep and on OS X.

**Comment by arvidkahl** [comment]
In my Elixir docker container, adding a `RUN apk --update add grep` prior to running the mix tasks and `RUN apk del grep` afterwards solved this solution for me. It pretty much installs a *real* grep.
