### ISSUE TITLE
/apps local dependencies gets "made" again for each other dependency given

### ISSUE THREAD

**Issue by KoFish** [ninenines/erlang.mk#531]
After having split up some parts of my application into local dependencies I noticed that when running `make deps` each local dependencies directory gets entered by make before each remote dependency is entered. It should suffice with each local dependency being compiled after all remote dependencies.

**Comment by essen** [comment]
I think it's that way because we need to compile the applications in the correct order. We need to either figure out the order or not recompile apps/ that were already compiled (probably easier considering parallel building, and I think we already do this for DEPS).

**Comment by essen** [comment]
Should be fixed! Thanks.
