### ISSUE TITLE
`make ct` with specific CT_SUITES fails if local dependency lacks /test catalogue

### ISSUE THREAD

**Issue by KoFish** [ninenines/erlang.mk#532]
The title says it all. Steps to replicate:
- Setup new project
- Add a common test suite `foobar_SUITE`
- Add new /apps application `subapp` with just a `src/` and `Makefile`
- execute `CT_SUITES=foobar make ct`

This should then fail with the message `{'EXIT',{error,{invalid_directory,"/project/apps/subapp/test"}}`

**Comment by essen** [comment]
I guess we shouldn't define app-ct-* if there are no apps/*/test/*_SUITE.erl. Thanks!

**Comment by essen** [comment]
Seems like this was fixed 2 years ago, and we already have a test for this specific scenario. Closing, thanks!
