### ISSUE TITLE
clean does not delete escript

### ISSUE THREAD

**Issue by ingwinlu** [ninenines/erlang.mk#534]
Would it be more sensible that clean deletes the `make escript` generated file?

Currently it only gets deleted via distclean.

**Comment by essen** [comment]
I don't know. Would it? :-)

**Comment by ingwinlu** [comment]
I expected it to. Seeing as clean does [delete everything 'local' to the project](https://github.com/ninenines/erlang.mk/blob/1ceffe2a00b9f329b14518cc5b64230acd956cdc/core/erlc.mk#L259).

**Comment by essen** [comment]
OK. What about releases? I think they're not deleted on clean either, because they're the end result and we generally want to keep them around. I followed the same line of thought for escripts.

**Comment by crownedgrouse** [comment]
@ingwinlu You can extend clean target with clean:: in your own Makefile

**Comment by essen** [comment]
Yeah his question is what should be the default though.

**Comment by crownedgrouse** [comment]
Yes, it is easier to remove a file by extending a clean target than wanting to keep it while clean remove it by default. So current behaviour make sens to me.

**Comment by essen** [comment]
Let's keep it like this for now. As @crownedgrouse said it's easier to ask for forgiveness than permission. Thanks!
