### ISSUE TITLE
live reloading ?

### ISSUE THREAD

**Issue by jhw** [ninenines/erlang.mk#538]
So back in the day (2009) I used mochiweb a lot and it had this ace feature whereby it would detect changes to the source code (1 second timer), compile them if could and load them into the current VM, so you had this very reactive live- reloading thing going on. 

Now mochiweb wasn't doing any release building. But I find myself doing an awful lot of 'q(); make run; test(); q()'  and wonder if at some point something like this might be feasible with erlang.mk ?

Thx!

**Comment by essen** [comment]
There's a few different libraries to do it depending on your needs (sync, tddreloader, maybe more).

**Comment by jhw** [comment]
thank you
