### ISSUE TITLE
Setting ERLC_OPTS does not seem to impact building deps

### ISSUE THREAD

**Issue by fenollp** [ninenines/erlang.mk#539]
We are building [couchbeam](https://github.com/benoitc/couchbeam/tree/1.3.0) with erlang.mk.
We want to activate `-DWITH_JIFFY` so that couchbeam would use jiffy instead of ejson.

[Here is how we are trying to pass this compiler flag down to our dependencies.](https://github.com/2600hz/kazoo/blob/master/make/deps.mk)

`V=3 make deps | grep JIFFY` catches nothing and running couchbeam I can see WITH_JIFFY wasn't activated.

**Comment by essen** [comment]
To do the equivalent of what rebar is doing, you need to export ERLC_OPTS. Note that all ERLC_OPTS settings will apply to all dependencies. But this doesn't work for couchbeam because autopatch just does `=` instead of `?=`. You can try changing this line: https://github.com/ninenines/erlang.mk/blob/master/core/deps.mk#L193

I am interested in doing a more targeted way to do this but there aren't that many examples so I am not sure what form it should take.

Either way I am traveling today so won't be able to help more until tomorrow.

**Comment by fenollp** [comment]
I am playing with this right now.
Ultimately I think having the possibility to have per-dependency ERLC_OPTS is necessary (lots of deps use that).

Could this turn into something along the lines of `dep_couchbeam_ERLC_OPTS = -DWITH_JIFFY`?

Do you know you can get all makefile-env variables with `$(.VARIABLES)` like I did [here](https://github.com/fenollp/erl-mk/blob/master/erl.mk#L14)?

**Comment by essen** [comment]
I know about .VARIABLES yes, but with all the variables Erlang.mk sets it's perhaps not the most efficient. :-)

I am definitely open to having the possibility to override ERLC_OPTS in dependencies. I think there's different things we need to support though. We may want to override ERLC_OPTS completely; we may want to add something to it (your case) or we may want to remove an option (like +debug_info for people who want to ship software without it). And I guess we may want to do this also on either one dep or everything.

I'd be happy if we get the one way fitting your use case for now. But considering the possible different use cases I'd recommend a name that indicates we add something to it.

Experimentation is welcome. :-)

**Comment by crownedgrouse** [comment]
Could pattern matching variable usefull ?

https://ftp.gnu.org/old-gnu/Manuals/make-3.79.1/html_chapter/make_6.html#SEC70

**Comment by essen** [comment]
@fenollp Any feedback on experimentation? :-)

**Comment by fenollp** [comment]
Played with https://github.com/ninenines/erlang.mk/commit/d5fc780598f856fc820bfc4cc6318bb2969a5d73 bug got stuck when erlang.mk was defining maps_support=1 twice for jsx (couchbeam's dep)
wat do?

**Comment by essen** [comment]
maps_support=1 is set automatically through the rebar.config.script when using 18+. Is the second one coming from your experiment?

**Comment by fenollp** [comment]
Not from my code no, the second one comes from jsx

**Comment by essen** [comment]
Then where does the first one come from? Both from jsx?

**Comment by fenollp** [comment]
Yep.

Stuff (my version of erlang.mk) generated

```Makefile
IGNORE_DEPS += edown eper eunit_formatters meck node_package rebar_lock_deps_plugin rebar_vsn_plugin reltool_util
C_SRC_DIR = /path/do/not/exist
C_SRC_TYPE = rebar
DRV_CFLAGS = -fPIC
export DRV_CFLAGS
ERLANG_ARCH = 64
export ERLANG_ARCH
ERLC_OPTS ?= +debug_info
export ERLC_OPTS
ERLC_OPTS += -Dmaps_support=1



rebar_dep: preprocess pre-deps deps pre-app app

preprocess::

pre-deps::

pre-app::

include ../../erlang.mk
```

```shell
erlc -v +debug_info -Dmaps_support=1 -Dmaps_support=1 -o ebin/ -pa ebin/ -I include/ src/jsx.erl src/jsx_config.erl src/jsx_consult.erl src/jsx_decoder.erl src/jsx_encoder.erl src/jsx_parser.erl src/jsx_to_json.erl src/jsx_to_term.erl src/jsx_verify.erl
```

**Comment by essen** [comment]
I'm sorry I still don't get it. On the Makefile generated there's only one (as expected). I don't see where the second one comes from.

**Comment by fenollp** [comment]
No idea. These are the only matches for grep.
Build command is `git clean -xdff && V=3 make deps | tee _`.
My env has no $ERLC_OPTS defined.

```
0 kazoo.git master (18.2.1) ∀ grep -rI maps_support .                                                                                                                                                                             
./_:674:erlc -v +debug_info -Dmaps_support=1 -Dmaps_support=1 -o ebin/ -pa ebin/ -I include/ src/jsx.erl src/jsx_config.erl src/jsx_consult.erl src/jsx_decoder.erl src/jsx_encoder.erl src/jsx_parser.erl src/jsx_to_json.erl src/jsx_to_term.erl src/jsx_verify.erl
./_:675:src/jsx.erl: redefining macro 'maps_support'
./deps/jsx/Makefile:10:ERLC_OPTS += -Dmaps_support=1
./deps/jsx/src/jsx_to_term.erl:47:-ifndef(maps_support).
./deps/jsx/src/jsx_to_term.erl:58:-ifdef(maps_support).
./deps/jsx/src/jsx_to_term.erl:168:-ifndef(maps_support).
./deps/jsx/src/jsx_to_term.erl:201:-ifdef(maps_support).
./deps/jsx/src/jsx_to_term.erl:369:-ifdef(maps_support).
./deps/jsx/src/jsx.erl:32:-export([maps_support/0]).
./deps/jsx/src/jsx.erl:46:-ifndef(maps_support).
./deps/jsx/src/jsx.erl:55:-ifdef(maps_support).
./deps/jsx/src/jsx.erl:185:-spec maps_support() -> boolean().
./deps/jsx/src/jsx.erl:187:-ifndef(maps_support).
./deps/jsx/src/jsx.erl:188:maps_support() -> false.
./deps/jsx/src/jsx.erl:190:-ifdef(maps_support).
./deps/jsx/src/jsx.erl:191:maps_support() -> true.
./deps/jsx/src/jsx_encoder.erl:42:-ifndef(maps_support).
./deps/jsx/src/jsx_encoder.erl:46:-ifdef(maps_support).
./deps/jsx/src/jsx_encoder.erl:79:-ifdef(maps_support).
./deps/jsx/src/jsx_consult.erl:38:-ifndef(maps_support).
./deps/jsx/src/jsx_consult.erl:49:-ifdef(maps_support).
./deps/jsx/CHANGES.md:77:* add `maps_support/0` call to determine whether `jsx` was compiled
./deps/jsx/mix.exs:22:    [d: :maps_support] ++ force_maps
./deps/jsx/rebar.config.script:7:           true -> [{d, maps_support}|Def0];
./deps/jsx/README.md:42:  - [`maps_support/0`](#maps_support0)
./deps/jsx/README.md:634:#### `maps_support/0` ####
./deps/jsx/README.md:637:maps_support() -> true | false
```

Only diff from 2600hz/kazoo master is

```patch
diff --git a/Makefile b/Makefile
index b687048..f622324 100644
--- a/Makefile
+++ b/Makefile
@@ -44,11 +44,12 @@ clean-deps:
        $(if $(wildcard deps/), $(MAKE) -C deps/ clean)
        $(if $(wildcard deps/), rm -r deps/)
 
-.erlang.mk: ERLANGMK_VERSION = '2.0.0-pre.2'
+.erlang.mk: ERLANGMK_VERSION = 'master'
 .erlang.mk:
-       wget 'https://raw.githubusercontent.com/ninenines/erlang.mk/$(ERLANGMK_VERSION)/erlang.mk' -O $(ROOT)/erlang.mk
+       wget 'https://raw.githubusercontent.com/fenollp/erlang.mk/$(ERLANGMK_VERSION)/erlang.mk' -O $(ROOT)/erlang.mk
 
 deps: deps/Makefile
+       export ERLC_OPTS='-DWITH_JIFFY'
        $(MAKE) -C deps/ all
 deps/Makefile: .erlang.mk
        mkdir -p deps
diff --git a/make/Makefile.deps b/make/Makefile.deps
index 3c9af82..e36f7a5 100644
--- a/make/Makefile.deps
+++ b/make/Makefile.deps
@@ -1,7 +1,6 @@
 ROOT = ..
 
 DEPS_DIR = $(CURDIR)
-ERLC_OPTS += +debug_info -DWITH_JIFFY=1
 
 clean::
        $(if $(wildcard ./*/), rm -rf ./*/)
```

**Comment by essen** [comment]
Thanks, I will investigate.

**Comment by essen** [comment]
> Could this turn into something along the lines of `dep_couchbeam_ERLC_OPTS = -DWITH_JIFFY`?

I think this makes sense to have. I will experiment.

**Comment by essen** [comment]
I think the solution to this is rather to have https://github.com/ninenines/erlang.mk/issues/586 done where it'll allow hooking right after fetching and/or autopatch (you could then add any option or change anything you want).

**Comment by essen** [comment]
Done. Once I push you can add something like this to your Makefile and it'll add the options:

``` make
autopatch-couchbeam::
   printf "\nERLC_OPTS += -DWITH_JIFFY\n" >> $(DEPS_DIR)/couchbeam/Makefile
```
