### ISSUE TITLE
include in Makefile

### ISSUE THREAD

**Issue by skvamme** [ninenines/erlang.mk#540]
http://erlang.mk/guide/getting_started.html

Missing include erlang.mk in Makefile in documentation

**Comment by essen** [comment]
Do you mean a manual example of a Makefile with the include erlang.mk file?

**Comment by skvamme** [comment]
Just to match the level of detail in chapter 2:
$ mkdir hello_joe
$ cd hello_joe
$ touch Makefile

and then edit the Makefile, adding include erlang.mk

**Comment by essen** [comment]
Fair enough.

**Comment by essen** [comment]
Done. Updating the website in a few seconds. Thanks!
