### ISSUE TITLE
dependency behaviour

### ISSUE THREAD

**Issue by benoitc** [ninenines/erlang.mk#542]
Is it possible to tell to `erlang.mk` to not fetch any dependencies but just use what it find in the deps/ folder ? So eventually this folder could be filled by an extra tool? 

I guess it is but then how does it works when we ignore a dependancy or such? How does work `erlang.mk` in that case? From the documentation it seems that all dependancies are fetched but it ignores them at build time if `IGNORE_DEPS` is set and build them when we activate them for `eunit` and other commands.  Is my understanding correct?

**Comment by essen** [comment]
To skip deps entirely (fetching and building), there's SKIP_DEPS=1. To ignore a dep when fetching (to avoid fetching extraneous deps, there's IGNORE_DEPS. And Erlang.mk only fetches a dep if it's not in the DEPS_DIR directory already.

**Comment by essen** [comment]
Not sure what action to take so closing for now. If it was more than just a question, or if you need behavior that is currently not possible, please reopen with additional details. Thanks!

**Comment by benoitc** [comment]
thanks! I had my answer. sorry got distracted...
