### ISSUE TITLE
eunit issue with code:priv_dir

### ISSUE THREAD

**Issue by crownedgrouse** [ninenines/erlang.mk#544]
Hi,
I found something strange with my eunit tests of one of my projects.
I grab some data from project priv_dir .

Actually make eunit fails as far code:priv_dir  return {error, bad_name} .
Works only when setting : 

```
EUNIT_ERL_OPTS = -pa $(shell pwd)/priv -pa $(shell pwd)/ebin
```
Looks like priv_dir is not found when giving  ebin directory in relative path , while work when giving fullpath...
I do not know if it could be an Erlang bug, but it is maybe a good idea to add full path for ebin in erlang.mk  for eunit target at least.  Adding priv/ is not necessary mandatory in most case, so setting EUNIT_ERL_OPTS in such case make sens.

thoughts ?

**Comment by essen** [comment]
You're right in that the code is currently incorrect. Instead of

```
EUNIT_ERL_OPTS += -pa $(TEST_DIR) $(DEPS_DIR)/*/ebin $(APPS_DIR)/*/ebin ebin
```

It should be

```
EUNIT_ERL_OPTS += -pa $(TEST_DIR) $(DEPS_DIR)/*/ebin $(APPS_DIR)/*/ebin $(CURDIR)/ebin
```

The reason for that is that Erlang expects a certain folder structure, including a matching application and folder name, and if you give only "ebin" it doesn't try to resolve it. Please try and if it works submit a PR. Thanks!

**Comment by crownedgrouse** [comment]
yes work now by adding only priv/ in EUNIT_ERL_OPTS.  I will propose a PR.

**Comment by essen** [comment]
No adding priv is not correct. Try the one I gave.

**Comment by crownedgrouse** [comment]
Yes I understood,
 I add your code in erlang.mk, and set EUNIT_ERL_OPTS = -pa $(shell pwd)/priv  only in my own Makefile.

**Comment by crownedgrouse** [comment]
sorry, not necessary; forget

**Comment by crownedgrouse** [comment]
PR #545

**Comment by crownedgrouse** [comment]
note, erlang.mk build fails with 
awk: cannot open core/index.mk (No such file or directory)

**Comment by essen** [comment]
Thanks. Adding a test that does code:priv_dir would be good to avoid issues in the future.

**Comment by crownedgrouse** [comment]
done.

**Comment by crownedgrouse** [comment]
Closing after merge of PR #545

**Comment by crownedgrouse** [comment]
Closing after merge of PR #545
