### ISSUE TITLE
Roadmap and feature list expected for 2.0 release?

### ISSUE THREAD

**Issue by jpuigm** [ninenines/erlang.mk#546]
Hi! I am looking for the most stable (and yet) recent version of erlang.mk. Release [2.0.0-pre.2](https://github.com/ninenines/erlang.mk/releases/tag/2.0.0-pre.2) dates from Nov, 2015. Do you have a brief roadmap set for the final 2.0? 

I understand there's no planned releases between [1.2.0](https://github.com/ninenines/erlang.mk/releases/tag/1.2.0) and the final `2.0`. Is this right?

**Comment by essen** [comment]
We're doing rolling releases so versions don't have much meanings. 2.0 will be when the user guide is finished writing, along with the test suite matching the documentation and all tests passing. Past 2.0, I don't even know.

As far as roadmaps go, the tickets and PRs have it all. There's no exact plans, it all depends on who needs what and whether there's a workaround available. Commenting whenever a feature is missed or a bug is problematic helps decide priorities.

**Comment by essen** [comment]
Note that when you do "make erlang-mk" to update Erlang.mk, it always fetches the latest version from master.

**Comment by jpuigm** [comment]
Ok, so short answer, whenever the guide and tests are complete. Thanks.
