### ISSUE TITLE
init terminating in do_boot otp 18.3

### ISSUE THREAD

**Issue by eugeniykh** [ninenines/erlang.mk#548]
I'm using proxy, and have the bug 

{"init terminating in do_boot",{badarg,[{erlang,halt,[{failed_connect,[{to_address,{"github.com",443}},{inet,[inet],closed}]}],[]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,670}]},{erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,122}]},{init,start_it,1,[]},{init,start_em,1,[]}]}}

when running a hello world application on erlang otp 18.3 erl version 7.3

**Comment by essen** [comment]
There's currently no proxy support unfortunately. Maybe it would work if you make it go through SOCKS5, if you have that available?

**Comment by eugeniykh** [comment]
ok, thank you!

**Comment by DamienPetrilli** [comment]
Hi,
I have the exact same problem while using 'make release'. 
Do you know which call fail so I can try to track it down?

Almost everything is working behind a proxy but the relx part. I saw that they added unix OS proxy support to rebar3 5 days ago. IDK if it's related or not.

**Comment by essen** [comment]
There's a core_http_get function in core/core.mk, which would be the beginning of a compiled erlang.mk file.

**Comment by crownedgrouse** [comment]
try by creating a .wgetrc  file with this : 
http_proxy = http://your_proxy:port_proxy/
use_proxy = on
wait = 15

**Comment by DamienPetrilli** [comment]
Hi,

Seems I can go one step further, however it stills fails

===> Evaluating config script "rebar.config.script"
===> Expanded command sequence to be run: [{default,app_discovery},
                                                  {default,install_deps},
                                                  {default,lock},
                                                  {default,compile}]
===> Error loading package registry: {read_error,
                                             {file_error,
                                              "/Users/xxxx/.cache/rebar3/hex/default/registry",
                                              enoent}}
===> Package eini-1.2.1 not found. Fetching registry updates and trying again...
===> Updating package registry...
===> Fetching registry from "https://repo.hex.pm:443/registry.ets.gz?"
===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace
===> Uncaught error: {badmatch,
                             {error,
                              {rebar_prv_update,package_index_download}}}
===> Stack trace to the error location: [{rebar_packages,
                                                 handle_missing_package,3,
                                                 [{file,
                                                   "/private/tmp/rebar3-20160517-15131-1p4amro/rebar3-3.1.1/_build/default/lib/rebar/src/rebar_packages.erl"},
                                                  {line,85}]},
                                                {rebar_app_utils,
                                                 update_source,3,
                                                 [{file,
                                                   "/private/tmp/rebar3-20160517-15131-1p4amro/rebar3-3.1.1/_build/default/lib/rebar/src/rebar_app_utils.erl"},
                                                  {line,184}]},
                                                {rebar_app_utils,dep_to_app,
                                                 7,
                                                 [{file,
                                                   "/private/tmp/rebar3-20160517-15131-1p4amro/rebar3-3.1.1/_build/default/lib/rebar/src/rebar_app_utils.erl"},
                                                  {line,162}]},
                                                {rebar_app_utils,
                                                 '-parse_deps/6-lc$^0/1-0-',6,
                                                 [{file,
                                                   "/private/tmp/rebar3-20160517-15131-1p4amro/rebar3-3.1.1/_build/default/lib/rebar/src/rebar_app_utils.erl"},
                                                  {line,98}]},
                                                {rebar_app_discover,
                                                 '-do/2-fun-0-',3,
                                                 [{file,
                                                   "/private/tmp/rebar3-20160517-15131-1p4amro/rebar3-3.1.1/_build/default/lib/rebar/src/rebar_app_discover.erl"},
                                                  {line,31}]},
                                                {lists,foldl,3,
                                                 [{file,"lists.erl"},
                                                  {line,1262}]},
                                                {rebar_app_discover,do,2,
                                                 [{file,
                                                   "/private/tmp/rebar3-20160517-15131-1p4amro/rebar3-3.1.1/_build/default/lib/rebar/src/rebar_app_discover.erl"},
                                                  {line,27}]},
                                                {rebar_prv_app_discovery,do,
                                                 1,
                                                 [{file,
                                                   "/private/tmp/rebar3-20160517-15131-1p4amro/rebar3-3.1.1/_build/default/lib/rebar/src/rebar_prv_app_discovery.erl"},
                                                  {line,38}]}]

**Comment by essen** [comment]
Seems to be rebar3 running and crashing. Not sure what's that doing here. :-)

**Comment by DamienPetrilli** [comment]
Yes! But somebody gave me a tip to try on this issue so I just followed up ;)

Just continuing to dig in, but yes, seems to be more a rebar3 issue than erlang.mk.

**Comment by crownedgrouse** [comment]
you need to set-up proxy in rebar as well (do not how however, see documentation). the tip I gave you was to let wget used in erlang.mk  to deal with a proxy.

**Comment by crownedgrouse** [comment]
as rebar use git, simply add a  .gitconfig:

[http]
    proxy = http://your_proxy:proxy_port

**Comment by DamienPetrilli** [comment]
ok, I will have to dig further but so far all my git calls are working through the proxy already including erlang.mk. My issues are limited to the rebar3 part.

But I need to see if their changes to support the proxy made it to the version grabbed by erlang.mk.

Thanks.

**Comment by essen** [comment]
If you mean the rebar3 dep, not sure it got updated to the new repo but github probably redirects; and the default commit is 'master'. If you mean something else, not sure what is meant, Erlang.mk doesn't depend on rebar3.

**Comment by crownedgrouse** [comment]
proxy things are maybe set-up in all your git repo in .git/config. But .gitconfig is a global setting for git commands and should be created in your HOME, otherwise considere using /etc/gitconfig but needs root access. But as you mention, issue is maybe rebar3 related.

**Comment by DamienPetrilli** [comment]
Yes I am talking about the rebar3 dep. The only issue I have with erlang.mk is when I try to build a release which relies on it.

**Comment by essen** [comment]
The switch to curl allows you to enable proxies through the `~/.curlrc` file for all HTTP requests. Closing this, thanks!
