### ISSUE TITLE
Add option for only making tests for base application in multi-app project

### ISSUE THREAD

**Issue by KoFish** [ninenines/erlang.mk#552]
This can currently be done by running tests with IS_APP=1 but then nothing in `APPS_DIR` gets compiled.

**Comment by essen** [comment]
Sorry to ask so late. Do you have more details on this? I'm not sure what you mean exactly.

**Comment by binarin** [comment]
I think I have exactly the same problem. Suppose we have a project with following structure:

    src/...
    test/...
    apps/app1/src/...

We have two apps here: one is in top-level `src` , the second one is `app1`. `app1` doesn't contain `test/` sub-folder. Intention is to run only tests from top-level `test/`, but:
- `make ct` complains like this
    `{'EXIT',{error,{invalid_directory,"bla-bla/apps/app1/test"}}}`
- `make ct IS_APP=1` runs tests, but doesn't compile `app1` automatically
- Even if `apps/app1/test/` is created, specifying `CT_SUITES`  with some test from top-level app is broken - as `app1` doesn't contain a test-suite with the same name.

**Comment by essen** [comment]
Sending a PR with a test similar to this one: https://github.com/ninenines/erlang.mk/blob/master/test/plugin_ct.mk#L53 that covers your issues would go a long way.

**Comment by binarin** [comment]
PR contains reproduction of the third scenario

**Comment by essen** [comment]
This has been fixed two years ago, closing, thanks!
