### ISSUE TITLE
Question around LOCAL_DEPS and releases

### ISSUE THREAD

**Issue by jordan0day** [ninenines/erlang.mk#555]
I've inherited an existing project that uses erlang.mk and many applications in one repository (though no apps/ folder, all the applications are just immediate children of the main folder). So the layout is something like

.
| - project_a/
| - project_b/
| - project_...
| - project_common/
| - shared.mk

Where each project has its own Makefile that does `include ../shared.mk` and project_a and project_b both list `project_common` in their `LOCAL_DEPS` section.

I'm seeing a behavior where if `project_a/_rel/project_a/lib/project_common` exists (so I've built project_a before building project_b, basically), it's *that* version of `project_common` that winds up in `project_b/_rel/project_b/lib/project_common` after project_b is built, rather than what's at `./project_common`.

So if I modify the code in `./project_common` and try to test my changes by rebuilding project_b, the modified version doesn't actually get used unless I get rid of project_a's `_rel` folder first.

While I'm sure this project is just set up in a weird fashion, I was wondering if there is a good way to make sure each project references the "root" project_common, in its' build? I'm still fairly new to Erlang and especially new to erlang.mk, so apologies if I'm missing some key piece of info somewhere.

**Comment by essen** [comment]
Yes it's weird. :-)

Am I correct when I say that project_a and project_b are supposed to be separate releases in your case?

Either way you can probably solve it by defining ERL_LIBS and pointing it to your root folder (maybe ERL_LIBS=.. would be enough?)

**Comment by jordan0day** [comment]
Yes, you're correct, they build separate releases. 

The existing shared.mk already has ERL_LIBS set to `$(CURDIR)/..:$(ERL_LIBS)`. I've tried explicitly prepending both just `..` and `../project_common`, but to no avail.

I'll keep digging -- hopefully I reach a level of understanding where I'm comfortable potentially re-arranging the project structure into a slightly-less-weird form. Thanks!
