### ISSUE TITLE
shorter download url

### ISSUE THREAD

**Issue by Fstub42** [ninenines/erlang.mk#557]
Could you host a subdomain like https://get.erlang.mk/ that redirects to https://raw.githubusercontent.com/ninenines/erlang.mk/master/erlang.mk ?

Typing and rembering the long url is a pain :/

**Comment by essen** [comment]
I can do http://erlang.mk/erlang.mk

I can't do https because it's on github pages and I don't think they allow https yet.

**Comment by essen** [comment]
You can now use http://erlang.mk/erlang.mk as a shorter URL. I will update the guide with it, but will continue to mention the https URL as that's a safer alternative.

**Comment by essen** [comment]
I've found an interesting article on using CloudFlare to make github pages secure: https://www.benburwell.com/posts/configuring-cloudflare-universal-ssl/

**Comment by essen** [comment]
I have setup a CloudFlare account and must now play the wait game while everything switches to it. Then I should be able to force HTTPS, and can update the guide with a short, HTTPS-only URL.

**Comment by essen** [comment]
OK it turns out I didn't properly change the DNS servers a couple days ago. I have now figured it out and we should be good sometimes tomorrow.

**Comment by essen** [comment]
https://erlang.mk/erlang.mk should work, as long as your DNS is updated. Now I can update the documentation. :-)

**Comment by crownedgrouse** [comment]
firefox propose me to download a binary file and do not open an https page. Bad header ?

**Comment by essen** [comment]
If you mean the URL https://erlang.mk/erlang.mk, that's supposed to send the erlang.mk file as a download over HTTPS.

```
$ curl https://erlang.mk/erlang.mk
# Automated update.

ERLANG_MK_BUILD_CONFIG ?= build.config
ERLANG_MK_BUILD_DIR ?= .erlang.mk.build

erlang.mk: bootstrap
	git clone https://github.com/ninenines/erlang.mk $(ERLANG_MK_BUILD_DIR)
	if [ -f $(ERLANG_MK_BUILD_CONFIG) ]; then cp $(ERLANG_MK_BUILD_CONFIG) $(ERLANG_MK_BUILD_DIR); fi
	cd $(ERLANG_MK_BUILD_DIR) && $(MAKE)
	cp $(ERLANG_MK_BUILD_DIR)/erlang.mk ./erlang.mk
	rm -rf $(ERLANG_MK_BUILD_DIR)

.PHONY: bootstrap
bootstrap: ;
```

**Comment by crownedgrouse** [comment]
sorry, I thought the filename could be propose with a 
```Content-Disposition: attachment; filename="erlang.mk"```
but yes this is only for command line download.

**Comment by essen** [comment]
I have no control over the media type AFAIK, this is just the file put on github pages.

**Comment by crownedgrouse** [comment]
OK, forget, was just cosmetic

**Comment by Fstub42** [comment]
FYI: https://github.com/blog/2186-https-for-github-pages

**Comment by essen** [comment]
This only works for github.io URLs. Current solution is fine anyway.

**Comment by essen** [comment]
I have updated the documentation. Closing, thanks!
