### ISSUE TITLE
How to specify the build order of multiple apps in one project?

### ISSUE THREAD

**Issue by emqplus** [ninenines/erlang.mk#558]
The project's structure:

```
apps/
    core_app
    extend_app1
    extend_app2
```

The extend_app1 and extend_app2 depend on core_app. How to ensure the core_app is built first? Thanks.

**Comment by essen** [comment]
Did you try adding LOCAL_DEPS=core_app to both extend applications? I'm not sure this works yet.

**Comment by emqplus** [comment]
@essen, Thanks for your quick reply. The LOCAL_DEPS cannot work, which is only used to generate the .app file:

```
define app_file
{application, $(PROJECT), [
        {description, "$(PROJECT_DESCRIPTION)"},
        {vsn, "$(PROJECT_VERSION)"},$(if $(IS_DEP),
        {id$(comma)$(space)"$(1)"}$(comma))
        {modules, [$(call comma_list,$(2))]},
        {registered, []},
        {applications, [$(call comma_list,kernel stdlib $(OTP_DEPS) $(LOCAL_DEPS) $(DEPS))]}
]}.
endef 
```

**Comment by essen** [comment]
Right it's not been implemented yet. That's how it will eventually work though so do put them there.

If it's a blocker I can try to get it fixed in the afternoon.

**Comment by emqplus** [comment]
Hi @essen, I add a 'LOCAL_DEPS_DIRS' variable in erlang.mk to work around this issue. Please check the patch:

```
diff --git a/erlang.mk b/erlang.mk
index 01da469..42bb8f1 100644
--- a/erlang.mk
+++ b/erlang.mk
@@ -4090,7 +4090,8 @@ dep_repo = $(patsubst git://github.com/%,https://github.com/%, \
        $(if $(dep_$(1)),$(word 2,$(dep_$(1))),$(pkg_$(1)_repo)))
 dep_commit = $(if $(dep_$(1)_commit),$(dep_$(1)_commit),$(if $(dep_$(1)),$(word 3,$(dep_$(1))),$(pkg_$(1)_commit)))

-ALL_APPS_DIRS = $(if $(wildcard $(APPS_DIR)/),$(filter-out $(APPS_DIR),$(shell find $(APPS_DIR) -maxdepth 1 -type d)))
+LOCAL_DEPS_DIRS = $(foreach a,$(LOCAL_DEPS),$(if $(wildcard $(APPS_DIR)/$(a)),$(APPS_DIR)/$(a)))
+ALL_APPS_DIRS = $(filter-out $(LOCAL_DEPS_DIRS), $(if $(wildcard $(APPS_DIR)/),$(filter-out $(APPS_DIR),$(shell find $(APPS_DIR) -maxdepth 1 -type d))))
 ALL_DEPS_DIRS = $(addprefix $(DEPS_DIR)/,$(foreach dep,$(filter-out $(IGNORE_DEPS),$(BUILD_DEPS) $(DEPS)),$(call dep_name,$(dep))))

 ifeq ($(filter $(APPS_DIR) $(DEPS_DIR),$(subst :, ,$(ERL_LIBS))),)
@@ -4125,6 +4126,9 @@ ifneq ($(IS_DEP),1)
        $(verbose) rm -f $(ERLANG_MK_TMP)/deps.log
 endif
        $(verbose) mkdir -p $(ERLANG_MK_TMP)
+       $(verbose) for dep in $(LOCAL_DEPS_DIRS) ; do \
+               $(MAKE) -C $$dep IS_APP=1 || exit $$?; \
+       done
        $(verbose) for dep in $(ALL_DEPS_DIRS) ; do \
                if grep -qs ^$$dep$$ $(ERLANG_MK_TMP)/deps.log; then \
                        :; \
```

Thanks for your help. Hope we could support LOCAL_DEPS to define dependencies between multiple applications in the same project soon:)

**Comment by essen** [comment]
Yep that should work for now (with the caveat that Erlang.mk might try to compile a LOCAL_DEPS app twice; but the second time it'll just run make and exit almost immediately).

I'll work on a patch that does things similar to deps (where dependencies are only compiled once).

Thanks!

**Comment by emqplus** [comment]
erlang.mk is really a great project for Erlang applications. I donated 34$ to your account on http://ninenines.eu/ :)

**Comment by essen** [comment]
Ah that was you, thanks. :-)

**Comment by geogriff** [comment]
i took @emqplus's patch further in the above pull request. does that look like it'll work without side-effects?

**Comment by essen** [comment]
Yes I think that's the way to go.

**Comment by essen** [comment]
Been merged locally so will be pushed later today, closing! Thanks everyone.
