### ISSUE TITLE
erlang.mk doesn't see releases built with rebar3

### ISSUE THREAD

**Issue by alexshavelev** [ninenines/erlang.mk#562]
I use [lib pkt](https://github.com/msantos/pkt). erlang.mk succes compiled it

alex_shavelev@lucky:~/deps/pkt$ tree
.
├── _build
│   └── default
│       └── lib
│           └── pkt
│               ├── ebin
│               │   ├── pkt_802_1q.beam
│               │   ├── pkt.app
│               │   ├── pkt_arp.beam
│               │   ├── pkt.beam
│               │   ├── pkt_dlt.beam
│               │   ├── pkt_ether.beam
│               │   ├── pkt_gre.beam
│               │   ├── pkt_icmp6.beam
│               │   ├── pkt_icmp.beam
│               │   ├── pkt_igmp.beam
│               │   ├── pkt_ipproto.beam
│               │   ├── pkt_ipv4.beam
│               │   ├── pkt_ipv6_ah.beam
│               │   ├── pkt_ipv6.beam
│               │   ├── pkt_ipv6_dstopts.beam
│               │   ├── pkt_ipv6_esp.beam
│               │   ├── pkt_ipv6_fragment.beam
│               │   ├── pkt_ipv6_hopopts.beam
│               │   ├── pkt_ipv6_routing.beam
│               │   ├── pkt_linux_cooked.beam
│               │   ├── pkt_llc.beam
│               │   ├── pkt_lldp.beam
│               │   ├── pkt_null.beam
│               │   ├── pkt_sctp.beam
│               │   ├── pkt_tcp.beam
│               │   ├── pkt_udp.beam
│               │   └── pkt_vrrp.beam
│               ├── include -> ../../../../include
│               ├── priv -> ../../../../priv

but 'make' finished with error 'src/api/test.erl:15: can't find include lib "pkt/include/pkt.hrl"

ERLANG_MK_VERSION = 1

**Comment by essen** [comment]
Try updating Erlang.mk (make erlang-mk), then make distclean and make again. It's supposed to patch the dependency to make it compatible with Erlang.mk. At no point should rebar3 be necessary.

**Comment by alexshavelev** [comment]
@essen thanks! it works
