### ISSUE TITLE
dependency riakc doesn't compile well with erlang.mk

### ISSUE THREAD

**Issue by kansi** [ninenines/erlang.mk#563]
when riakc is added as a dep to project then riak_pb which is a dep to riakc doesn't compile well i.e. the .app.src file generated after compilation should have the following modules

```
{modules,[riak_dt_pb,riak_kv_pb,riak_pb,riak_pb_codec,
          riak_pb_dt_codec,riak_pb_kv_codec,riak_pb_messages,
          riak_pb_search_codec,riak_search_pb,
          riak_yokozuna_pb]}
```

but erlang.mk generated .app.src has only following modules.

```
{modules,['riak_pb_codec','riak_pb_dt_codec','riak_pb_kv_codec','riak_pb_messages','riak_pb_search_codec']}]}.
```

**Comment by essen** [comment]
Right, the plugin for protobuff doesn't add them.

https://github.com/ninenines/erlang.mk/blob/master/plugins/protobuffs.mk should be made more like https://github.com/ninenines/erlang.mk/blob/master/plugins/erlydtl.mk (the BEAM_FILES += ... is what adds the modules to the .app file).

**Comment by essen** [comment]
Note that as a workaround you can easily patch the riakc Makefile to have a BEAM_FILES line with the missing modules.

**Comment by orotemo** [comment]
having your makefile look like this is a nice workaround which gets it all right:

```makefile
DEPS = protobuffs riakc ...
```

**Comment by essen** [comment]
I have fixed the BEAM_FILES issue a few days ago. @orotemo's suggestion is the missing link to make it build properly. You might prefer using `BUILD_DEPS` however so that it won't be included in the release:

```
DEPS = riakc
BUILD_DEPS = protobuffs
```

Closing, thanks!
