### ISSUE TITLE
SKIP_DEPS behavour

### ISSUE THREAD

**Issue by kansi** [ninenines/erlang.mk#570]
Compiling project using `make SKIP_DEPS=1` also skips compilation for subapps. A gentle suggestion would be to have to variables SKIP_DEPS (which will skip deps folder) and SKIP_APPS (which will skip apps folder).

**Comment by essen** [comment]
Waiting for #576 to be completed before doing this.

**Comment by essen** [comment]
I think this was fixed a while ago.
