### ISSUE TITLE
plugin build artifacts cleaned before test

### ISSUE THREAD

**Issue by goertzenator** [ninenines/erlang.mk#573]
The `test-build` rule in [core/test.mk](https://github.com/ninenines/erlang.mk/blob/cba40ae35bd3d63eaffde194b48f380bfc91f379/core/test.mk#L34) invokes a `clean` before going
off and doing some building.  External plugins get injected into the Makefile _before_ core/test.mk
therefore any plugin `test-build` rules immediately get wiped out by the following `test-build:: clean`
rule.

The [`c_src.mk`](https://github.com/ninenines/erlang.mk/blob/master/plugins/c_src.mk#L78) happens to work because it is statically included _after_ `core/test.mk`.  My external plugin [`rust.mk`](https://github.com/goertzenator/rust.mk/blob/master/plugins.mk#L67) isn't so lucky.

Standby for PR.

**Comment by essen** [comment]
FYI your plugin is now included after `core/test.mk` too, so perhaps it will "just work" now. Can you try?

**Comment by essen** [comment]
Already fixed. Thanks!
