### ISSUE TITLE
download

### ISSUE THREAD

**Issue by skvamme** [ninenines/erlang.mk#577]
when I try download with wget I get an error message:

Valkyrie:tmp2 skvamme$ wget https://erlang.mk/erlang.mk
--2016-07-13 23:05:30--  https://erlang.mk/erlang.mk
Resolving erlang.mk... 104.28.21.247, 104.28.20.247
Connecting to erlang.mk|104.28.21.247|:443... connected.
OpenSSL: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
Unable to establish SSL connection.

**Comment by essen** [comment]
Works here. Try with curl instead?

**Comment by skvamme** [comment]
when I try download with curl I get the contents of the file rather than the file itself:
Valkyrie:tmp2 skvamme$ curl https://erlang.mk/erlang.mk
# Automated update.

ERLANG_MK_BUILD_CONFIG ?= build.config
ERLANG_MK_BUILD_DIR ?= .erlang.mk.build

erlang.mk: bootstrap
	git clone https://github.com/ninenines/erlang.mk $(ERLANG_MK_BUILD_DIR)
	if [ -f $(ERLANG_MK_BUILD_CONFIG) ]; then cp $(ERLANG_MK_BUILD_CONFIG) $(ERLANG_MK_BUILD_DIR); fi
	cd $(ERLANG_MK_BUILD_DIR) && $(MAKE)
	cp $(ERLANG_MK_BUILD_DIR)/erlang.mk ./erlang.mk
	rm -rf $(ERLANG_MK_BUILD_DIR)

.PHONY: bootstrap
bootstrap: ;

**Comment by essen** [comment]
Of course, you're supposed to either redirect or use the -o option, for example:

curl https://erlang.mk/erlang.mk -o erlang.mk

**Comment by skvamme** [comment]
Your documentation needs an update then

The next step is therefore to download it:

$ wget https://erlang.mk/erlang.mk
Or:

$ curl https://erlang.mk/erlang.mk

**Comment by skvamme** [comment]
Can I help?

**Comment by essen** [comment]
Sure, the file should be https://github.com/ninenines/erlang.mk/blob/master/doc/src/guide/getting_started.asciidoc

It looks like it's mentioned twice in that document.

I'm off to sleep, cheers!

**Comment by skvamme** [comment]
:)

**Comment by essen** [comment]
Fixed, thanks!
