### ISSUE TITLE
===> release successfully created! But it wasn't

### ISSUE THREAD

**Issue by skvamme** [ninenines/erlang.mk#578]
after make everything looks great but code changes did not "take" so I did make distclean and got this message when make was run again:
===> Failed to solve release:
 Dependency api is specified as a dependency but is not reachable by the system.

When I removed LOCAL_DEPS = ASN-1 crypto public_key from Makefile it compiled again and a release was created.

Suggestion: delete beam files in release ebin dir when running make

**Comment by essen** [comment]
IIRC we don't want that because this messes up with building release upgrades (something we don't support directly yet, but will).

It's curious though, I don't think I've seen this problem and I recompile releases regularly. I think we don't have a test case though so I'll add it. What's the platform/Erlang version?

**Comment by skvamme** [comment]
Tested a little bit and the error is fully reproducable. It seems to be the asn-1 dependency.
LOCAL_DEPS = asn-1 and it looks as if it works but the release is not re-created. LOCAL_DEPS = public_key works fine. 
I'm running Erlang/OTP 18 [erts-7.1] [source-2882b0c] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] on OSX 10.11.5 El Capitan

**Comment by skvamme** [comment]
Update: asn1 works fine but not asn-1

**Comment by skvamme** [comment]
Update2: Misspellings usually gives an error, like this on cryptox, but not asn-1
===> Failed to solve release:
 Dependency cryptox is specified as a dependency but is not reachable by the system.

**Comment by essen** [comment]
Interesting. Thanks for the clarifications!
