### ISSUE TITLE
make: *** [relx-rel] Error 127

### ISSUE THREAD

**Issue by ginahagg** [ninenines/erlang.mk#582]
Just today, make started failing. i have updated erlang.mk from 2.0.0-pre.1-37-gb7ccb2e to 2.0.0-pre.2-130-gc6fe5ea to see if it would create the release. It still fails. Erlang is
Erlang/OTP 18 [erts-7.1] (18.1). 

=ERROR REPORT==== 29-Jul-2016::00:43:42 ===
Error in process <0.1599.0> with exit value:
{function_clause,[{rlx_app_info,parse_version,
                                [{cmd,"git describe --always --tags --match '[0-9]*.[0-9]*'"}],
                                [{file,"src/rlx_app_info.erl"},{line,197}]},
                  {rlx_app_info,new,6,
                                [{file,"src/rlx_app_info.erl"},{line,98}]},
                  {rlx_app_discovery,get_vsn,3,
                                     [{file,"src/rlx_app_discovery.erl"},
                                      {line,236}]},
                  {rlx_dscv_util,discover_dir,3,
                                 [{file,"src/rlx_dscv_util.erl"},{line,95}]},
                  {lists,map,2,[{file,"lists.erl"},{line,1238}]},
                  {ec_plists,'-local_runmany/3-fun-0-',3,
                             [{file,"src/ec_plists.erl"},{line,738}]}]}
escript: exception exit: {function_clause,
                    [{rlx_app_info,parse_version,
                         [{cmd,
                              "git describe --always --tags --match '[0-9]*.[0-9]*'"}],
                         [{file,"src/rlx_app_info.erl"},{line,197}]},
                     {rlx_app_info,new,6,
                         [{file,"src/rlx_app_info.erl"},{line,98}]},
                     {rlx_app_discovery,get_vsn,3,
                         [{file,"src/rlx_app_discovery.erl"},{line,236}]},
                     {rlx_dscv_util,discover_dir,3,
                         [{file,"src/rlx_dscv_util.erl"},{line,95}]},
                     {lists,map,2,[{file,"lists.erl"},{line,1238}]},
                     {ec_plists,'-local_runmany/3-fun-0-',3,
                         [{file,"src/ec_plists.erl"},{line,738}]}]}
  in function  ec_plists:handle_error/3 (src/ec_plists.erl, line 885)
  in call from ec_plists:local_runmany/3 (src/ec_plists.erl, line 749)
  in call from rlx_dscv_util:do/2 (src/rlx_dscv_util.erl, line 52)
  in call from rlx_app_discovery:resolve_app_metadata/2 (src/rlx_app_discovery.erl, line 56)
  in call from rlx_prv_discover:do/1 (src/rlx_prv_discover.erl, line 46)
  in call from relx:run_provider/2 (src/relx.erl, line 277)
  in call from lists:foldl/3 (lists.erl, line 1262)
  in call from relx:run_providers/1 (src/relx.erl, line 265)
make: *** [relx-rel] Error 127

**Comment by essen** [comment]
I think more recent relx dropped support for older git versions. See if updating git fixes it.

**Comment by ginahagg** [comment]
my git version is 2.9.0. i will update and try again. Thank you.

**Comment by essen** [comment]
Probably not the issue then. :-)

**Comment by essen** [comment]
It sounds like an issue in relx itself. Just to be sure, you should `rm -rf relx .erlang.mk` and try again before opening a ticket there.

Wondering why it would do this though? Do you have a .app file with `{vsn, git}` by any chance?

**Comment by ginahagg** [comment]
yes, i saw that issue with git/vsn..I don't have either of them in my .app file. This happens when i freshly clone my project. it works fine if build it in an existing directory. I was alerted by dev-ops that this was happening on docker containers. I haven't heard anyone else complain, since developers usually don't do a fresh clone each time. Yes, it is a relx issue.. Some reason, i always relate relx to you. I will open up the issue with them. Thank you so much for all your help.

**Comment by essen** [comment]
No problem. :-)
