### ISSUE TITLE
It may be nice to have a "lager2" and "lager3" dep name "built in"

### ISSUE THREAD

**Issue by chatterbeak** [ninenines/erlang.mk#583]
lager is commonly used, and it has forked! And if you have some deps / apps that use lager2 and some that use lager3, it won't work well.

The default "lager" in erlang.mk takes branch "master" which is the latest 3.x.x. Since Lager is so widely used, and many people still use 2.x.x, it may make sense to have a separate lager2 and lager3 dep name defined.

**Comment by essen** [comment]
I'm not against a lager2 and/or lager3 but it won't solve the problem of dependencies using different lager versions, the same one will still be picked as before.

**Comment by chatterbeak** [comment]
Yeah! I think the lager people need to fix this and just warn when
someone's logging with '2' protocol when the '3' server is running (and
vice-versa).

I'll bug them!

**Comment by essen** [comment]
Closing, thanks!
