### ISSUE TITLE
Targets dependencies need improvement for deps

### ISSUE THREAD

**Issue by essen** [ninenines/erlang.mk#586]
For example there's no easy way current to hook yourself after fetching but before compiling a dependency. If we did have this, we could have autopatch and others separate and do a much cleaner job at patching dependencies.

**Comment by dumbbell** [comment]
Perhaps #362 can help here?

**Comment by essen** [comment]
Not sure how. I think what's needed is that $(ALL_DEPS_DIR) uses `::` instead of `:`.

**Comment by essen** [comment]
This is done locally. I have added a target `autopatch-$(dep)` (for example autopatch-ranch) that can be extended to run commands before/after Erlang.mk's autopatch. I've also documented it.
