### ISSUE TITLE
Env in .app

### ISSUE THREAD

**Issue by nevar** [ninenines/erlang.mk#587]
In .app.src we can define env (for default value, or some other use-case).
For now .app.src is legacy and all app define got to Makefile.
What about env?

**Comment by essen** [comment]
There's been some discussions about it. The question is what form should this take. A variable in the Makefile? A separate file?

**Comment by essen** [comment]
Perhaps we can find a solution that makes it easy to generate a "default" sys.config file afterwards.

**Comment by crownedgrouse** [comment]
.app.src.script was an interesting approach by rebar. This could make more compliant both tools ?

**Comment by essen** [comment]
.app.src is pretty bad, .app.src.script is even worse. All the .script things are very error prone, hard to debug and require too much maintenance whenever rebar changes again.

To be honest a variable in the Makefile is probably enough, considering Make 4 and above allow you to do something like `var = $(file cowboy.env)` should you want a separate file.

**Comment by nevar** [comment]
Make PR for PROJECT_ENV?

**Comment by essen** [comment]
PROJECT_ENV sure, additional keys though which ones do you refer to? The ones that are left are so rarely used I'm not sure it's worth adding until someone complains.

**Comment by nevar** [comment]
PROJECT_$(KEY) = $(VALUE) =>
```erl
{application, name, [ {$(KEY), $(VALUE)}]}
```

**Comment by essen** [comment]
That makes no sense. If you're going to want this you can just use a .app file.

The only keys not configurable right now, excluding env, are maxP, maxT, included_applications, start_phases and runtime_dependencies. The first four are exceedingly rare, and the last one I've never seen outside OTP's applications. The only thing we miss is env.

**Comment by nevar** [comment]
okay. Then I will make PR for PROJECT_ENV.

**Comment by dumbbell** [comment]
Hi!

@nevar: I played a bit with your patches (#588 + #589) and it works well. Thank you!

I was wondering, should the scope of this issue be wider to allow users to put any keys in the `.app` file? Or should other keys (like the less used ones or the non-standard ones used in RabbitMQ master branch) be handled by another variable, eg. `PROJECT_APP_EXTRA`? I don't have a strong opinion on either way.

**Comment by essen** [comment]
Can you link to some variables RabbitMQ uses?

**Comment by dumbbell** [comment]
Sure, here is an example, taken from [rabbitmq-shovel](https://github.com/rabbitmq/rabbitmq-shovel/blob/master/src/rabbitmq_shovel.app.src#L13):
```erlang
{application, rabbitmq_shovel,
 [...
  {broker_version_requirements, []},
  ...
```

**Comment by essen** [comment]
Yeah another variable working just like PROJECT_ENV would do I guess.

**Comment by essen** [comment]
Both have been merged. Thanks!

@dumbbell Feel free to open a new PR/ticket for the separate variable for custom keys.

**Comment by dumbbell** [comment]
Thank you!
