### ISSUE TITLE
Separate dev/prod relx.config files

### ISSUE THREAD

**Issue by jhw** [ninenines/erlang.mk#590]
Hi,

Trying to get set up with sync -

https://github.com/rustyio/sync

as per this thread -

http://erlang.org/pipermail/erlang-questions/2015-June/085015.html

All sounds fine, but I only want sync to run on dev/localhost, not on prod/AWS. Possibly a dumb question but is there a way of specifying separate relx.config files for each realm; or an alternative way to get sync started in one but not the other ?

Thanks!

**Comment by essen** [comment]
You can define RELX_CONFIG conditionally to point at one or the other for example.

**Comment by essen** [comment]
I believe defining RELX_CONFIG differently depending on what you want is enough at the moment. Closing, thanks!
