### ISSUE TITLE
Problem building app with amqp_client, rabbit_common deps

### ISSUE THREAD

**Issue by jhw** [ninenines/erlang.mk#601]
Hi,

Trying to build an old project on a new machine. Erlang and erlang.mk up to date, had no problem building on old machine, now getting the following 

src/rabbit_ct_broker_helpers.erl:19: can't find include lib "common_test/include/ct.hrl"

@essen can you help ? Big problem as I have a demo on Monday. 

Many thanks

--- 

jhw@jhw-ThinkPad-X220:~/work/cricket_trader$ make
make[1]: Entering directory '/home/jhw/work/cricket_trader/deps/go_fibonacci'
go install main/echo
go install main/fibonacci
make[1]: Leaving directory '/home/jhw/work/cricket_trader/deps/go_fibonacci'
make[1]: Entering directory '/home/jhw/work/cricket_trader/deps/amqp_client'
make[2]: Entering directory '/home/jhw/work/cricket_trader/deps/rabbit_common'
make[3]: Entering directory '/home/jhw/work/cricket_trader/deps/lager'
make[4]: Entering directory '/home/jhw/work/cricket_trader/deps/goldrush'
make[4]: Leaving directory '/home/jhw/work/cricket_trader/deps/goldrush'
make[3]: Leaving directory '/home/jhw/work/cricket_trader/deps/lager'
 ERLC   app_utils.erl code_version.erl credit_flow.erl gen_server2.erl lager_forwarder_backend.erl mirrored_supervisor.erl mochijson2.erl mochinum.erl pmon.erl priority_queue.erl rabbit_amqqueue.erl rabbit_auth_backend_dummy.erl rabbit_auth_backend_internal.erl rabbit_auth_mechanism.erl rabbit_authn_backend.erl rabbit_authz_backend.erl rabbit_backing_queue.erl rabbit_basic.erl rabbit_binary_generator.erl rabbit_binary_parser.erl rabbit_channel.erl rabbit_channel_interceptor.erl rabbit_command_assembler.erl rabbit_control_misc.erl rabbit_ct_broker_helpers.erl rabbit_ct_helpers.erl rabbit_data_coercion.erl rabbit_error_logger_handler.erl rabbit_event.erl rabbit_exchange_decorator.erl rabbit_exchange_type.erl rabbit_framing_amqp_0_8.erl rabbit_framing_amqp_0_9_1.erl rabbit_health_check.erl rabbit_heartbeat.erl rabbit_misc.erl rabbit_msg_store_index.erl rabbit_net.erl rabbit_networking.erl rabbit_nodes.erl rabbit_password_hashing.erl rabbit_policy_validator.erl rabbit_queue_collector.erl rabbit_queue_decorator.erl rabbit_queue_master_locator.erl rabbit_reader.erl rabbit_registry.erl rabbit_registry_class.erl rabbit_runtime_parameter.erl rabbit_types.erl rabbit_writer.erl supervisor2.erl
src/rabbit_ct_broker_helpers.erl:19: can't find include lib "common_test/include/ct.hrl"
src/rabbit_ct_broker_helpers.erl:140: undefined macro 'config/2'
src/rabbit_ct_broker_helpers.erl:295: undefined macro 'config/2'
src/rabbit_ct_broker_helpers.erl:344: undefined macro 'config/2'
src/rabbit_ct_broker_helpers.erl:362: undefined macro 'config/2'
src/rabbit_ct_broker_helpers.erl:371: undefined macro 'config/2'
src/rabbit_ct_broker_helpers.erl:401: undefined macro 'config/2'
src/rabbit_ct_broker_helpers.erl:454: undefined macro 'config/2'
src/rabbit_ct_broker_helpers.erl:486: undefined macro 'config/2'
src/rabbit_ct_broker_helpers.erl:506: undefined macro 'config/2'
src/rabbit_ct_broker_helpers.erl:517: undefined macro 'config/2'
src/rabbit_ct_broker_helpers.erl:531: undefined macro 'config/2'
src/rabbit_ct_broker_helpers.erl:567: undefined macro 'config/2'
src/rabbit_ct_broker_helpers.erl:589: undefined macro 'config/2'
src/rabbit_ct_broker_helpers.erl:601: undefined macro 'config/2'
src/rabbit_ct_broker_helpers.erl:643: undefined macro 'config/2'
src/rabbit_ct_broker_helpers.erl:666: undefined macro 'config/2'
src/rabbit_ct_broker_helpers.erl:670: undefined macro 'config/2'
src/rabbit_ct_broker_helpers.erl:680: undefined macro 'config/2'
src/rabbit_ct_broker_helpers.erl:692: undefined macro 'config/2'
src/rabbit_ct_broker_helpers.erl:703: undefined macro 'config/2'
src/rabbit_ct_broker_helpers.erl:722: undefined macro 'config/2'
src/rabbit_ct_broker_helpers.erl:746: undefined macro 'config/2'
src/rabbit_ct_broker_helpers.erl:23: function enable_dist_proxy/1 undefined
src/rabbit_ct_broker_helpers.erl:23: function enable_dist_proxy_on_node/3 undefined
src/rabbit_ct_broker_helpers.erl:23: function get_node_config/3 undefined
src/rabbit_ct_broker_helpers.erl:23: function get_node_configs/1 undefined
src/rabbit_ct_broker_helpers.erl:23: function get_node_configs/2 undefined
src/rabbit_ct_broker_helpers.erl:23: function node_uri/3 undefined
src/rabbit_ct_broker_helpers.erl:23: function rabbitmqctl/3 undefined
src/rabbit_ct_broker_helpers.erl:23: function rewrite_node_config_file/2 undefined
src/rabbit_ct_broker_helpers.erl:129: function run_make_dist/1 undefined
src/rabbit_ct_broker_helpers.erl:131: function share_dist_and_proxy_ports_map/1 undefined
src/rabbit_ct_broker_helpers.erl:212: function init_nodename/3 undefined
src/rabbit_ct_broker_helpers.erl:213: function init_config_filename/3 undefined
src/rabbit_ct_broker_helpers.erl:215: function write_config_file/3 undefined
src/rabbit_ct_broker_helpers.erl:216: function do_start_rabbitmq_node/3 undefined
src/rabbit_ct_broker_helpers.erl:226: function move_nonworking_nodedir_away/1 undefined
src/rabbit_ct_broker_helpers.erl:277: function update_tcp_ports_in_rmq_config/2 undefined
src/rabbit_ct_broker_helpers.erl:469: function get_node_configs/1 undefined
src/rabbit_ct_broker_helpers.erl:478: function cluster_nodes/3 undefined
src/rabbit_ct_broker_helpers.erl:496: function rabbitmqctl/3 undefined
src/rabbit_ct_broker_helpers.erl:562: function get_node_configs/1 undefined
src/rabbit_ct_broker_helpers.erl:563: function stop_rabbitmq_node/2 undefined
src/rabbit_ct_broker_helpers.erl:657: function rabbitmqctl/3 undefined
src/rabbit_ct_broker_helpers.erl:673: function get_node_configs/1 undefined
src/rabbit_ct_broker_helpers.erl:674: function get_node_config1/2 undefined
src/rabbit_ct_broker_helpers.erl:676: function get_node_configs/1 undefined
src/rabbit_ct_broker_helpers.erl:697: function replace_entire_node_config/3 undefined
src/rabbit_ct_broker_helpers.erl:718: function get_node_configs/1 undefined
src/rabbit_ct_broker_helpers.erl:719: function nodename_to_index1/3 undefined
src/rabbit_ct_broker_helpers.erl:733: function node_uri/3 undefined
src/rabbit_ct_broker_helpers.erl:843: function get_node_configs/2 undefined
src/rabbit_ct_broker_helpers.erl:853: function get_node_config/3 undefined
src/rabbit_ct_broker_helpers.erl:878: function get_node_config/3 undefined
src/rabbit_ct_broker_helpers.erl:885: function get_node_configs/2 undefined
src/rabbit_ct_broker_helpers.erl:889: function get_node_configs/2 undefined
src/rabbit_ct_broker_helpers.erl:901: function do_start_rabbitmq_node/3 undefined
src/rabbit_ct_broker_helpers.erl:925: function stop_rabbitmq_node/2 undefined
src/rabbit_ct_broker_helpers.erl:1031: function get_node_configs/2 undefined
src/rabbit_ct_broker_helpers.erl:1043: function get_node_configs/2 undefined
src/rabbit_ct_broker_helpers.erl:495: Warning: function cluster_nodes1/4 is unused
src/rabbit_ct_broker_helpers.erl:546: Warning: function rotate_config_file/1 is unused
src/rabbit_ct_broker_helpers.erl:549: Warning: function rotate_config_file/3 is unused
src/rabbit_ct_broker_helpers.erl:769: Warning: function format_ipaddr_for_uri/1 is unused
erlang.mk:5062: recipe for target 'ebin/rabbit_common.app' failed
make[3]: *** [ebin/rabbit_common.app] Error 1
erlang.mk:4870: recipe for target 'app' failed
make[2]: *** [app] Error 2
make[2]: Leaving directory '/home/jhw/work/cricket_trader/deps/rabbit_common'
../../erlang.mk:4171: recipe for target 'deps' failed
make[1]: *** [deps] Error 2
make[1]: Leaving directory '/home/jhw/work/cricket_trader/deps/amqp_client'
erlang.mk:4169: recipe for target 'deps' failed
make: *** [deps] Error 2

**Comment by jhw** [comment]
I think this was related to my Erlang release not being up to date. Closed and apologies.

**Comment by essen** [comment]
No problem. Also for some reasons I didn't receive an email when you opened the ticket, would have helped you earlier otherwise.

**Comment by jhw** [comment]
Thank you. Separate issue now submitted; hope you may be able to help.
