### ISSUE TITLE
Module 'localtime' duplicated in erlang_localtime and qdate_localtime

### ISSUE THREAD

**Issue by jhw** [ninenines/erlang.mk#602]
Since I last built this app, qdate has gone and included 'localtime' from erlang_localtime as a local source file, without renaming it as 'qdate_localtime' or something sensibly similar. So now I get - 

===> Errors generating release 
          Duplicated modules: 
	localtime_dst specified in qdate_localtime and erlang_localtime
	localtime specified in qdate_localtime and erlang_localtime
	ibuild specified in qdate_localtime and erlang_localtime

qdate is a dependency in my Makefile but erlang_localtime is not; it must be being pulled in by another dep. Is there a simple way around this anyone can suggest ?

Thanks!

**Comment by jhw** [comment]
I guess the obvious answer is clone qdate and fix the module naming conflict ?

**Comment by jhw** [comment]
OK am just going to pull in a specific qdate commit which pre- dates the creation of qdate_localtime. And post a message on qdate issues saying he should probably change the module name. Thx - closed

**Comment by essen** [comment]
It looks like I missed this one also; just started receiving github emails. Thanks for the heads up!
