### ISSUE TITLE
MSYS2/Windows erlang.mk and rebar

### ISSUE THREAD

**Issue by mm-tfx** [ninenines/erlang.mk#607]
Hi,
I am trying to build my Erlang project.
I have Cowboy and Jsx as dependencies. When I run make I get such error:
"escript: exception error: no match of right hand side value Could not find <some_path>\.erlang.mk\\rebar\\ebin\\rebar.beam"
Is this a know issue as I found this in User Guide: "Erlang.mk needs to be fixed to pass the right paths when running Erlang scripts."

Regards
Marcin

**Comment by essen** [comment]
It's not a known issue. Can I have the full log when doing "make V=1" (you might need to run "make distclean" first to clean things up).

**Comment by mm-tfx** [comment]
I have run make distclean.
Here is the full log from "V=1 make all" command.
[log.txt](https://github.com/ninenines/erlang.mk/files/517119/log.txt)

The same project on my other other Computer running Ubuntu works just fine.

**Comment by mm-tfx** [comment]
I have now cloned rebar repo to check if this could be rebar issue but when I run bootstrap script everything is as it should.
Still my project has a problem with running bootstrap in .erlang.mk/rebar

MSYS /e/WORK/eps/.erlang.mk/rebar
$ ./bootstrap
escript: exception error: no match of right hand side value "Could Not Find E:\\WORK\\eps\\.erlang.mk\\rebar\\ebin\\rebar.beam\r\n"

**Comment by essen** [comment]
Yep, thanks, I'll investigate.

**Comment by essen** [comment]
OK so this is a problem I fixed a few days ago in https://github.com/ninenines/erlang.mk/commit/d387560fa0e3c4188b86f12e69774c3bf0c064bc

If you update Erlang.mk (make erlang-mk) you will have the most recent version which fixes this issue.

Closing, thanks!

**Comment by mm-tfx** [comment]
Thanks a lot. Now it works.
