### ISSUE TITLE
Dependency XXX is specified as a dependency but is not reachable by the system.

### ISSUE THREAD

**Issue by jhw** [ninenines/erlang.mk#610]
I'm sure this is probably a simple thing but can't figure it out; everything thing working fine, but then I suddenly noticed changes to the src code weren't getting updated in the release. Make clean didn't solve the problem. So I then deleted _rel. Now I get the following, where XXX is the name of the project I am developing. 

Any ideas ? 

Many thanks in advance

---------------------------

===> Failed to solve release:
 Dependency XXX is specified as a dependency but is not reachable by the system.

erlang.mk:6337: recipe for target 'relx-rel' failed
make: *** [relx-rel] Error 127
jhw@jhw-ThinkPad-X220:~/work/XXX$

**Comment by essen** [comment]
Is the dependency actually compiled? Is there a .app file for example.

**Comment by jhw** [comment]
Yes; plenty of .beam files in /ebin and a .app file also

??

**Comment by jhw** [comment]
Seems to be the relx build stage that is failing

===> Starting relx build process ...
===> Resolving OTP Applications from directories:
          /home/jhw/work/cricket_trader/ebin
          /home/jhw/work/cricket_trader/deps
          /usr/lib/erlang/lib
          /home/jhw/work/cricket_trader/apps
          /home/jhw/work/cricket_trader/_rel
===> Failed to solve release:
 Dependency cricket_trader is specified as a dependency but is not reachable by the system.

erlang.mk:6337: recipe for target 'relx-rel' failed
make: *** [relx-rel] Error 127

**Comment by essen** [comment]
Try from scratch, "make distclean; make", just in case?

**Comment by essen** [comment]
By from scratch i mean just run the two commands I gave.

**Comment by jhw** [comment]
No luck, sorry :-(

This is probably a wild goose chase for you. Don't spend too much time on it. I think I will just have to go back to the previous build. Only 1 hr work lost. Sigh. Thanks -

**Comment by essen** [comment]
It's hard to debug without testing myself. :-)

Make a patch with changes, revert, then apply patch, perhaps.

**Comment by jhw** [comment]
Thanks anyway!

**Comment by Sumitforyou** [comment]
Did you find the solution ?

**Comment by essen** [comment]
I don't see this error by following these steps.
