### ISSUE TITLE
New erlware_commons dep conflict between qdate and amqp_client

### ISSUE THREAD

**Issue by jhw** [ninenines/erlang.mk#613]
Everything working fine for ages, then suddenly (make distclean)

===> Errors generating release 
          Duplicated modules: 
	ec_semver_parser specified in erlware_commons and rabbit_common
	ec_semver specified in erlware_commons and rabbit_common

erlware_commons is being pulled in by qdate master, rabbit_common by amqp_client master

Do I have any other option than to specify particular versions of the above ?

Thank you :-)

**Comment by essen** [comment]
I don't know honestly. That's a question for relx.

I would also recommend opening a ticket in rabbit_common so we fix this name clash.

**Comment by jhw** [comment]
OK so this is a bona fide name clash which needs to fixed ? Not my fault ?

**Comment by jhw** [comment]
https://github.com/rabbitmq/rabbitmq-common/issues/139

**Comment by essen** [comment]
RabbitMQ's fault I believe. :-) But maybe relx has ways to deal with this.

**Comment by jhw** [comment]
I should use an older version of amqp client then maybe ?

**Comment by essen** [comment]
They seem pretty recent so that would work for the time being. Define rabbit_common on the commit before they were added and it should be fine.

**Comment by jhw** [comment]
Just to be clear: add a rabbit common dep for a specific commit to the
Erlang.mk makefile for my top level project ?

**Comment by essen** [comment]
Yep:

```
BUILD_DEPS = rabbit_common
dep_rabbit_common = git https://github...rabbit-common commit-hash
```

**Comment by jhw** [comment]
Thank you very much. Will close issue when next at laptop
