### ISSUE TITLE
src/.app.src file does not created

### ISSUE THREAD

**Issue by ethrbh** [ninenines/erlang.mk#619]
hello Essen,

Sorry for this, but I am not sure about what did I wrong.

I would create a new OTP application with erlang-mk. For this to not make any mistake, I followed the step-by-step guied, https://erlang.mk/guide/getting_started.html#_getting_started_with_otp_applications.

So I create a new, empty folder, test

	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/test> ls
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/test> 

Then I followed by the "2.6. Getting started from scratch"

	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/test> curl https://erlang.mk/erlang.mk -o erlang.mk
	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
									 Dload  Upload   Total   Spent    Left  Speed
	100   444  100   444    0     0    636      0 --:--:-- --:--:-- --:--:--   986
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/test> echo "include erlang.mk" > Makefile
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/test> make
	git clone https://github.com/ninenines/erlang.mk .erlang.mk.build
	Cloning into '.erlang.mk.build'...
	remote: Counting objects: 6652, done.
	remote: Compressing objects: 100% (279/279), done.
	remote: Total 6652 (delta 169), reused 0 (delta 0), pack-reused 6350
	Receiving objects: 100% (6652/6652), 3.23 MiB | 866 KiB/s, done.
	Resolving deltas: 100% (4131/4131), done.
	if [ -f build.config ]; then cp build.config .erlang.mk.build; fi
	cd .erlang.mk.build && make
	make[1]: Entering directory '/mnt/ethrbh/private/projects/github/test/.erlang.mk.build'
	awk 'FNR==1 && NR!=1{print ""}1' core/core.mk index/*.mk core/index.mk core/deps.mk plugins/erlydtl.mk plugins/protobuffs.mk core/erlc.mk core/docs.mk core/rel.mk core/test.mk core/compat.mk plugins/asciidoc.mk plugins/bootstrap.mk plugins/c_src.mk plugins/ci.mk plugins/ct.mk plugins/dialyzer.mk plugins/edoc.mk plugins/escript.mk plugins/eunit.mk plugins/relx.mk plugins/shell.mk plugins/triq.mk plugins/xref.mk plugins/cover.mk plugins/sfx.mk core/deps-tools.mk \
		| sed 's/^ERLANG_MK_VERSION = .*/ERLANG_MK_VERSION = 2016.10.21-38-g49952d7/' > erlang.mk
	make[1]: Leaving directory '/mnt/ethrbh/private/projects/github/test/.erlang.mk.build'
	cp .erlang.mk.build/erlang.mk ./erlang.mk
	rm -rf .erlang.mk.build
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/test> 
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/test> 
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/test> ls
	erlang.mk  Makefile

Next, I followed by calling bootstrap and bootstrap-rel make targets

	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/test> make -f erlang.mk bootstrap bootstrap-rel
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/test> ls
	erlang.mk  Makefile  rel  relx.config  src
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/test> tree
	.
	├── erlang.mk
	├── Makefile
	├── rel
	│   ├── sys.config
	│   └── vm.args
	├── relx.config
	└── src
		├── test_app.erl
		└── test_sup.erl

	2 directories, 7 files

Make the project

	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/test> make
	 DEPEND test.d
	 ERLC   test_app.erl test_sup.erl
	 APP    test
	===> Starting relx build process ...
	===> Resolving OTP Applications from directories:
			  /mnt/ethrbh/private/projects/github/test/ebin
			  /home/ethrbh/tools/erlang_otp_18.3/lib/erlang/lib
			  /mnt/ethrbh/private/projects/github/test/apps
			  /mnt/ethrbh/private/projects/github/test/deps
	===> Resolved test_release-1
	===> Including Erts from /home/ethrbh/tools/erlang_otp_18.3/lib/erlang
	===> release successfully created!
	===> tarball /mnt/ethrbh/private/projects/github/test/_rel/test_release/test_release-1.tar.gz successfully created!
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/test> 

Unfortunately I do not see the src/test.app.src. I though this file will be created automatically by erlang-mk. Could you please confirm this? Or do I missed something, and .app file must be  created by me?

thanks for you help,
/Robi

**Comment by essen** [comment]
Erlang.mk does not use a .app.src file by default, all the configuration is in the Makefile file. It takes this information to create a .app (which it did if you check now, otherwise the release wouldn't work). See https://erlang.mk/guide/building.html#_application_resource_file

If you prefer a .app.src file you can use `make -f erlang.mk bootstrap LEGACY=1` instead.

**Comment by ethrbh** [comment]
hello Essen,

Thanks for lighting me. Now I can see what should I do.

br,
/Robi
