### ISSUE TITLE
make escript fails on Ubuntu

### ISSUE THREAD

**Issue by DamienPetrilli** [ninenines/erlang.mk#620]
Hi,

I upgraded to the latest erlang.mk and since, the command "make escript" doesn't work anymore and fails with the following output.

GEN    escript-zip
/bin/sh: 1: 7z: not found
erlang.mk:6236: recipe for target 'escript-zip' failed

7z command doesn’t exist on Ubuntu, I believe the command is 7zr (I assume after installing p7zip). 

I created an alias from 7zr to 7z on Ubuntu, then I got the following failure.
GEN    escript-zip
erlang.mk:6236: recipe for target 'escript-zip' failed
make: *** [escript-zip] Error 2

Not sure if I am doing something wrong.

However I don’t understand why p7zip is used instead of tar. Tar is the mainstream on all unixes and installed by default.

Thanks!

**Comment by DamienPetrilli** [comment]
Hi,

I ran the command. Here is the last lines of the output.

```
make[1]: Leaving directory '/home/ubuntu/project/deps/iso8601'
make --no-print-directory app-build
:
mkdir -p ./ ./ ./ ./ ./
rm -f /home/ubuntu/project/.erlang.mk/escript.zip
cd .. && 7z a -tzip -mx=9 -mtc=off  /home/ubuntu/project/.erlang.mk/escript.zip project/ebin/*

7-Zip (A) [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
p7zip Version 9.20 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,1 CPU)

Error:
Unsupported archive type
erlang.mk:6278: recipe for target 'escript-zip' failed
make: *** [escript-zip] Error 2
```

I will dig further on the package I have installed. May be I got the wrong one.

**Comment by ingwinlu** [comment]
7zr != 7z, see https://wiki.archlinux.org/index.php/P7zip#Differences_between_7z.2C_7za_and_7zr_binaries

you might want p7zip-full on ubuntu

**Comment by essen** [comment]
Ah!

Good to know. Maybe you have 7za and that one is enough though?

**Comment by essen** [comment]
OK 7za/7z are only in full. I will document this.

**Comment by DamienPetrilli** [comment]
Yes, that was it. I installed the p7zip package which looked like the regular package. 
Now I got the p7zip-full and it indeed comes with 7z!

Thanks!

**Comment by essen** [comment]
Documented all this in https://erlang.mk/guide/escript.html#_requirements

Thanks!
