### ISSUE TITLE
vm.args seems to be ignored when using make rel

### ISSUE THREAD

**Issue by DamienPetrilli** [ninenines/erlang.mk#621]
Hi,

I modified the vm.args file in the rel/ folder (after using _make bootstrap-rel_). However, when I unzip the archive created by _make rel_, the vm.args is showing the default template file instead of the modified one in the rel/ folder.

I believe it's supposed to use the modified one?

Thanks

**Comment by essen** [comment]
Try `rm -rf _rel` and `make` again?

**Comment by DamienPetrilli** [comment]
It works perfectly, I was copying another archive... My bad.
