### ISSUE TITLE
OSX Setup info incomplete or bug in scripts

### ISSUE THREAD

**Issue by DamienPetrilli** [ninenines/erlang.mk#622]
Hi,

I followed the installation guildeline (https://erlang.mk/guide/installation.html) after I upgraded erlang.mk to install the gnu make 4. However, after installing it, erlang.mk is still not happy and seems to use the system make.

Errors shown below.

$ brew install homebrew/dupes/make
Warning: homebrew/dupes/make-4.2.1 already installed
$ make
erlang.mk:24: Please upgrade to GNU Make 4 or later: https://erlang.mk/guide/installation.html
../../erlang.mk:24: Please upgrade to GNU Make 4 or later: https://erlang.mk/guide/installation.html
../../erlang.mk:24: Please upgrade to GNU Make 4 or later: https://erlang.mk/guide/installation.html
../../erlang.mk:24: Please upgrade to GNU Make 4 or later: https://erlang.mk/guide/installation.html
../../erlang.mk:24: Please upgrade to GNU Make 4 or later: https://erlang.mk/guide/installation.html
../../erlang.mk:24: Please upgrade to GNU Make 4 or later: https://erlang.mk/guide/installation.html

Is erlang.mk supposed to detect it's installed and switch to the brew one? 
Or do I need to do something more?

**Comment by essen** [comment]
The one installed by brew is named `gmake`.

**Comment by essen** [comment]
We should probably mention what the executable is called in the docs.

**Comment by DamienPetrilli** [comment]
ok I see, it works indeed with gmake. thanks

**Comment by essen** [comment]
I have clarified the docs about this. Thanks!
