### ISSUE TITLE
Erlang releases and Javascript reloads

### ISSUE THREAD

**Issue by jhw** [ninenines/erlang.mk#623]
[Apologies if this is a dumb question]

So I have a Cowboy app with a JS front end. I find myself doing the following dance the whole time

- stop app
- change JS file
- make app/release
- start app
- clear browser cache
- reload browser page to see changes

I really want to be able to watch the JS files and rebuild the app on changes. I'm guessing I'm not going to be able to do that :-( But any tips for short- circuiting the above dance ?  Copying updated JS files into the release ?

TIA.

**Comment by essen** [comment]
Relx has an option which is I believe `{dev_mode, true}` to put in relx.config which results in creating symlinks to the files instead of copying them. Therefore all you should need after that is to reload the page to update the JS.

**Comment by jhw** [comment]
Ooh great. Thank you. I will take a look.

**Comment by jhw** [comment]
Jesus Christ. This has just officially saved my life :-) :-) :-) :-)
