### ISSUE TITLE
Documentation for equivalent of rebar3 profiles

### ISSUE THREAD

**Issue by jhw** [ninenines/erlang.mk#624]
Hi,

Interested to understand how to do something like the following with erlang.mk -

https://www.rebar3.org/docs/profiles

As I understand it you can do the following  - 

ifeq ($(PROFILE),prod)
RELX_CONFIG = rel/prod.config
else
RELX_CONFIG = rel/dev.config
endif

make PROFILE=prod

Would be great to have this documented properly. 

Thanks!

**Comment by essen** [comment]
I've done this on my local copy. Push soon, thanks!
