### ISSUE TITLE
Create upg package failed

### ISSUE THREAD

**Issue by ethrbh** [ninenines/erlang.mk#625]
hello Essen,

Sorry about me, butI still need some kind of help for make upgrade package by erlang-mk. I tried follow the instructions described in https://erlang.mk/guide/relx.html, but it looks, I missed something. Please find below the steps I did, and the outcome.

I made a clean project with two Erlang source file and with one include file. Once all these was ready, made the relase package first

	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/erlang_upg_test(master)> make
	 DEPEND erlang_upg_test.d
	 ERLC   erlang_upg_test_app.erl erlang_upg_test_sup.erl m1.erl m2.erl
	 APP    erlang_upg_test
	===> Starting relx build process ...
	===> Resolving OTP Applications from directories:
			  /mnt/ethrbh/private/projects/github/erlang_upg_test/ebin
			  /home/ethrbh/tools/erlang_otp_18.3/lib/erlang/lib
			  /mnt/ethrbh/private/projects/github/erlang_upg_test/apps
			  /mnt/ethrbh/private/projects/github/erlang_upg_test/deps
			  /mnt/ethrbh/private/projects/github/erlang_upg_test/_rel
	===> Resolved erlang_upg_test-0.0.1
	===> Including Erts from /home/ethrbh/tools/erlang_otp_18.3/lib/erlang
	===> release successfully created!
	===> tarball /mnt/ethrbh/private/projects/github/erlang_upg_test/_rel/erlang_upg_test/erlang_upg_test-0.0.1.tar.gz successfully created!
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/erlang_upg_test(master)> cat Makefile 
	PROJECT = erlang_upg_test
	PROJECT_DESCRIPTION = Example for how to upgrade Erlang/OTP application
	PROJECT_VERSION = 0.0.1

	# List of Erlang/OTP applications this project depends on, excluding erts, 
	# kernel and stdlib, or list of dependencies local to this repository.
	LOCAL_DEPS = sasl tools observer runtime_tools

	include erlang.mk
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/erlang_upg_test(master)> tree _rel/erlang_upg_test/lib/erlang_upg_test-0.0.1/
	_rel/erlang_upg_test/lib/erlang_upg_test-0.0.1/
	├── ebin
	│   ├── erlang_upg_test.app
	│   ├── erlang_upg_test_app.beam
	│   ├── erlang_upg_test_sup.beam
	│   ├── m1.beam
	│   └── m2.beam
	├── include
	│   └── common.hrl
	└── src
		├── erlang_upg_test_app.erl
		├── erlang_upg_test.appup
		├── erlang_upg_test_sup.erl
		├── m1.erl
		└── m2.erl

	3 directories, 11 files
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/erlang_upg_test(master)> 

Then I changed the version to 0.0.2

	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/erlang_upg_test(master)> cat Makefile 
	PROJECT = erlang_upg_test
	PROJECT_DESCRIPTION = Example for how to upgrade Erlang/OTP application
	PROJECT_VERSION = 0.0.2

	# List of Erlang/OTP applications this project depends on, excluding erts, 
	# kernel and stdlib, or list of dependencies local to this repository.
	LOCAL_DEPS = sasl tools observer runtime_tools

	include erlang.mk
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/erlang_upg_test(master)>

I also created the appup file in the src folder

	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/erlang_upg_test(master)> cat src/erlang_upg_test.appup
	{"0.0.2",
	 [{"0.0.1", [{update, m1, {advanced, []}}]}],
	 [{"0.0.1", [{update, m1, {advanced, []}}]}]
	}.

And I copied this into the ebin

	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/erlang_upg_test(master)> cp src/erlang_upg_test.appup ebin/
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/erlang_upg_test(master)> 

Ten next, I tried create the upgrade package, but it failed, and I do not really understand what is wrong :-(

	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/erlang_upg_test(master)> V=1 make relup
	rm -f /mnt/ethrbh/private/projects/github/erlang_upg_test/.erlang.mk/apps.log
	mkdir -p /mnt/ethrbh/private/projects/github/erlang_upg_test/.erlang.mk
	for dep in  ; do \
		mkdir -p $dep/ebin || exit $?; \
	done
	for dep in  ; do \
		if grep -qs ^$dep$ /mnt/ethrbh/private/projects/github/erlang_upg_test/.erlang.mk/apps.log; then \
			:; \
		else \
			echo $dep >> /mnt/ethrbh/private/projects/github/erlang_upg_test/.erlang.mk/apps.log; \
			make -C $dep IS_APP=1 || exit $?; \
		fi \
	done
	mkdir -p /mnt/ethrbh/private/projects/github/erlang_upg_test/.erlang.mk
	if test -f /mnt/ethrbh/private/projects/github/erlang_upg_test/.erlang.mk/last-makefile-change; then \
		touch src/erlang_upg_test_app.erl src/erlang_upg_test_sup.erl src/m1.erl src/m2.erl       ; \
		touch -c erlang_upg_test.d; \
	fi
	touch /mnt/ethrbh/private/projects/github/erlang_upg_test/.erlang.mk/last-makefile-change
	erl +A0 -noinput -boot start_clean  -pz /mnt/ethrbh/private/projects/github/erlang_upg_test/.erlang.mk/rebar/ebin -eval "	E = ets:new(makedep, [bag]),	G = digraph:new([acyclic]),	ErlFiles = lists:usort(string:tokens(\"src/erlang_upg_test_app.erl src/erlang_upg_test_sup.erl src/m1.erl src/m2.erl  \", \" \")),	Modules = [{list_to_atom(filename:basename(F, \".erl\")), F} || F <- ErlFiles],	Add = fun (Mod, Dep) ->		case lists:keyfind(Dep, 1, Modules) of			false -> ok;			{_, DepFile} ->				{_, ModFile} = lists:keyfind(Mod, 1, Modules),				ets:insert(E, {ModFile, DepFile}),				digraph:add_vertex(G, Mod),				digraph:add_vertex(G, Dep),				digraph:add_edge(G, Mod, Dep)		end	end,	AddHd = fun (F, Mod, DepFile) ->		case file:open(DepFile, [read]) of			{error, enoent} -> ok;			{ok, Fd} ->				F(F, Fd, Mod),				{_, ModFile} = lists:keyfind(Mod, 1, Modules),				ets:insert(E, {ModFile, DepFile})		end	end,Attr = fun		(F, Mod, behavior, Dep) -> Add(Mod, Dep);		(F, Mod, behaviour, Dep) -> Add(Mod, Dep);		(F, Mod, compile, {parse_transform, Dep}) -> Add(Mod, Dep);		(F, Mod, compile, Opts) when is_list(Opts) ->			case proplists:get_value(parse_transform, Opts) of				undefined -> ok;				Dep -> Add(Mod, Dep)			end;		(F, Mod, include, Hrl) ->			case filelib:is_file(\"include/\" ++ Hrl) of				true -> AddHd(F, Mod, \"include/\" ++ Hrl);	false ->					case filelib:is_file(\"src/\" ++ Hrl) of						true -> AddHd(F, Mod, \"src/\" ++ Hrl);						false -> false					end			end;		(F, Mod, include_lib, \"erlang_upg_test.d/include/\" ++ Hrl) -> AddHd(F, Mod, \"include/\" ++ Hrl);		(F, Mod, include_lib, Hrl) -> AddHd(F, Mod, \"include/\" ++ Hrl);		(F, Mod, import, {Imp, _}) ->			case filelib:is_file(\"src/\" ++ atom_to_list(Imp) ++ \".erl\") of			false -> ok;				true -> Add(Mod, Imp)			end;		(_, _, _, _) -> ok	end,	MakeDepend = fun(F, Fd, Mod) ->		case io:parse_erl_form(Fd, undefined) of			{ok, {attribute, _, Key, Value}, _} ->				Attr(F, Mod, Key, Value),				F(F, Fd, Mod);			{eof, _} ->			file:close(Fd);			_ ->				F(F, Fd, Mod)		end	end,	[begin		Mod = list_to_atom(filename:basename(F, \".erl\")),		{ok, Fd} = file:open(F, [read]),		MakeDepend(MakeDepend, Fd, Mod)	end || F <- ErlFiles],	Depend = sofs:to_external(sofs:relation_to_family(sofs:relation(ets:tab2list(E)))),	CompileFirst = [X || X <- lists:reverse(digraph_utils:topsort(G)), [] =/= digraph:in_neighbours(G, X)],	ok = file:write_file(\"erlang_upg_test.d\", [		[[F, \"::\", [[\" \", D] || D <- Deps], \"; @touch \$@\n\"] || {F, Deps} <- Depend],		\"\nCOMPILE_FIRST +=\", [[\" \", atom_to_list(CF)] || CF <- CompileFirst], \"\n\"	]),	halt()" -- erlang.mk
	make --no-print-directory app-build
	erlc -v -Werror +debug_info +warn_export_vars +warn_shadow_vars +warn_obsolete_guard  -o ebin/ -pa ebin/ -I include/ src/erlang_upg_test_app.erl src/erlang_upg_test_sup.erl src/m1.erl src/m2.erl
	printf '{application, erlang_upg_test, [\n	{description, "Example for how to upgrade Erlang/OTP application"},\n	{vsn, "0.0.2"},\n	{modules, ['\''erlang_upg_test_app'\'','\''erlang_upg_test_sup'\'','\''m1'\'','\''m2'\'']},\n	{registered, [erlang_upg_test_sup]},\n	{applications, [kernel,stdlib,sasl,tools,observer,runtime_tools]},\n	{mod, {erlang_upg_test_app, []}},\n	{env, []}\n]}.' \
		> ebin/erlang_upg_test.app
	:
	for dep in  ; do make -C $dep; done
	/mnt/ethrbh/private/projects/github/erlang_upg_test/.erlang.mk/relx -c /mnt/ethrbh/private/projects/github/erlang_upg_test/relx.config  -o _rel release relup tar
	===> Starting relx build process ...
	===> Resolving OTP Applications from directories:
			  /mnt/ethrbh/private/projects/github/erlang_upg_test/ebin
			  /home/ethrbh/tools/erlang_otp_18.3/lib/erlang/lib
			  /mnt/ethrbh/private/projects/github/erlang_upg_test/apps
			  /mnt/ethrbh/private/projects/github/erlang_upg_test/deps
			  /mnt/ethrbh/private/projects/github/erlang_upg_test/_rel
	===> Resolving available OTP Releases from directories:
			  /mnt/ethrbh/private/projects/github/erlang_upg_test/_rel
	===> Resolved erlang_upg_test-0.0.1
	===> Including Erts from /home/ethrbh/tools/erlang_otp_18.3/lib/erlang
	===> release successfully created!
	===> No earlier release for relup found
	erlang.mk:6432: recipe for target 'relx-relup' failed
	make: *** [relx-relup] Error 127
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/erlang_upg_test(master)> 

What I can see, it looks the version 0.0.2 does not used, still 0.0.1 is can be seen "===> Resolved erlang_upg_test-0.0.1", and I do not get what does the "erlang.mk:6432: recipe for target 'relx-relup' failed" error test means. In the erlang-mk source, this line looks like this:
	
	$(verbose) $(RELX) -c $(RELX_CONFIG) $(RELX_OPTS) release relup tar

If you have time please try help me.

thanks for your help,
/Robi

**Comment by essen** [comment]
What does relx.config say for the version? Did you change it?

**Comment by ethrbh** [comment]
hello Essen,

Yes, I was blind, and I forgot update the version in relx.config. Now I fixed this, and tried perform the upgrade, but still there is at least one issue. Please see more detailes below.

Make the release package for version 0.0.1

	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/erlang_upg_test(master)> make
	===> Starting relx build process ...
	===> Resolving OTP Applications from directories:
			  /mnt/ethrbh/private/projects/github/erlang_upg_test/ebin
			  /home/ethrbh/tools/erlang_otp_18.3/lib/erlang/lib
			  /mnt/ethrbh/private/projects/github/erlang_upg_test/apps
			  /mnt/ethrbh/private/projects/github/erlang_upg_test/deps
	===> Resolved erlang_upg_test-0.0.1
	===> Including Erts from /home/ethrbh/tools/erlang_otp_18.3/lib/erlang
	===> release successfully created!
	===> tarball /mnt/ethrbh/private/projects/github/erlang_upg_test/_rel/erlang_upg_test/erlang_upg_test-0.0.1.tar.gz successfully created!
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/erlang_upg_test(master)> 

Change the version to 0.0.2 and make upgrade package

	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/erlang_upg_test(master)> 
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/erlang_upg_test(master)> cp src/erlang_upg_test.appup ebin/
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/erlang_upg_test(master)> make relup
	 DEPEND erlang_upg_test.d
	 ERLC   erlang_upg_test_app.erl erlang_upg_test_sup.erl m1.erl m2.erl
	 APP    erlang_upg_test
	===> Starting relx build process ...
	===> Resolving OTP Applications from directories:
			  /mnt/ethrbh/private/projects/github/erlang_upg_test/ebin
			  /home/ethrbh/tools/erlang_otp_18.3/lib/erlang/lib
			  /mnt/ethrbh/private/projects/github/erlang_upg_test/apps
			  /mnt/ethrbh/private/projects/github/erlang_upg_test/deps
			  /mnt/ethrbh/private/projects/github/erlang_upg_test/_rel
	===> Resolving available OTP Releases from directories:
			  /mnt/ethrbh/private/projects/github/erlang_upg_test/_rel
	===> Resolved erlang_upg_test-0.0.2
	===> Including Erts from /home/ethrbh/tools/erlang_otp_18.3/lib/erlang
	===> release successfully created!
	===> relup successfully created!
	===> tarball /mnt/ethrbh/private/projects/github/erlang_upg_test/_rel/erlang_upg_test/erlang_upg_test-0.0.2.tar.gz successfully created!
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/erlang_upg_test(master)> 

I "installed" version 0.0.1 into /mnt/ethrbh/private/projects/github/erlang_upg_test/installed, and started the application, which is running well

Then following the instruction in "https://erlang.mk/guide/relx.html", copy the upgrade package for 0.0.2 into the installed area
	
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/erlang_upg_test/installed(master)> cp -r ../_rel/erlang_upg_test/erlang_upg_test-0.0.2.tar.gz releases/0.0.2/

The instruction does say to use the same name ofthe tar ball as it was generated
	
	"$ mv path/to/example-2.tar.gz releases/2/"

So I did this, and tried to perform the upgrade

	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/erlang_upg_test/installed(master)> ls -la /mnt/ethrbh/private/projects/github/erlang_upg_test/installed/releases/0.0.2/total 15728
	drwxrwxrwx 1 root root        0 Nov  7 09:05 .
	drwxrwxrwx 1 root root     4096 Nov  7 09:02 ..
	-rwxrwxrwx 1 root root 16101119 Nov  7 09:05 erlang_upg_test-0.0.2.tar.gz
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/erlang_upg_test/installed(master)> 

	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/erlang_upg_test/installed(master)> bin/erlang_upg_test upgrade 0.0.2/erlang_upg_test
	Release 0.0.2 not found, attempting to unpack releases/0.0.2/erlang_upg_test.tar.gz
	Installed versions:
	* 0.0.1	permanent
	Unpack failed: {no_such_file,"/mnt/ethrbh/private/projects/github/erlang_upg_test/installed/releases/0.0.2/erlang_upg_test.tar.gz"}

Above error shows the file name of the tar ball is not that what is expected. The tool expects the name without version "suffix". I renamed the file
	
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/erlang_upg_test/installed(master)> mv /mnt/ethrbh/private/projects/github/erlang_upg_test/installed/releases/0.0.2/erlang_upg_test-0.0.2.tar.gz  /mnt/ethrbh/private/projects/github/erlang_upg_test/installed/releases/0.0.2/erlang_upg_test.tar.gz

	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/erlang_upg_test/installed(master)> ls -la /mnt/ethrbh/private/projects/github/erlang_upg_test/installed/releases/0.0.2/total 15728
	drwxrwxrwx 1 root root        0 Nov  7  2016 .
	drwxrwxrwx 1 root root     4096 Nov  7 09:02 ..
	-rwxrwxrwx 1 root root 16101119 Nov  7 09:05 erlang_upg_test.tar.gz
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/erlang_upg_test/installed(master)> 

And tried the upgrade with this

	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/erlang_upg_test/installed(master)> bin/erlang_upg_test upgrade "0.0.2/erlang_upg_test"Release 0.0.2 not found, attempting to unpack releases/0.0.2/erlang_upg_test.tar.gz
	Unpacked successfully: "0.0.2"
	Installed Release: 0.0.2
	Made release permanent: "0.0.2"
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/erlang_upg_test/installed(master)> 

The upgrade itself went done well, at least I can see on the running side, the code change went done well, 

	(erlang_upg_test@127.0.0.1)2> 
	=INFO REPORT==== 7-Nov-2016::09:09:49 ===
		"Upgrade"
		module: m1
		fromVer: "0.0.1"
		toVer: 2149050263743356189825075652870143560
		module: m1
		line: 234

	(erlang_upg_test@127.0.0.1)2> 

but the above appeared "Release 0.0.2 not found, attempting to unpack releases/0.0.2/erlang_upg_test.tar.gz" text looks bad to me. Now I don't know what did I wrong.

thansk for your help,
/Robi

**Comment by essen** [comment]
Curious. Normally relx looks for name-version.tar.gz, not sure why it didn't work for you. Then if that fails, it prints the message you're worried about, and looks for name.tar.gz.

**Comment by ethrbh** [comment]
hello Essen,

Can I get more debug info when I do the upgrade, what might help to understand why this does not work for me?

thanks for your help,
/Robi

**Comment by essen** [comment]
"make V=1" will print all commands/output (can be large).

Relx probably has a verbose option but I don't think we enable it with V=1. Leave the ticket open so i can fix that.

**Comment by ethrbh** [comment]
hello Essen,

I did V=1, and I did not see more info, what might be related to this.

Ok, lets keep open the ticket open.

thanks for your help,
/Robi

**Comment by ethrbh** [comment]
hello Essen,

If you are interested, here is the printout with V=1

	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/erlang_upg_test(master)> V=1 make reluprm -f /mnt/ethrbh/private/projects/github/erlang_upg_test/.erlang.mk/apps.log
	mkdir -p /mnt/ethrbh/private/projects/github/erlang_upg_test/.erlang.mk
	for dep in  ; do \
		mkdir -p $dep/ebin || exit $?; \
	done
	for dep in  ; do \
		if grep -qs ^$dep$ /mnt/ethrbh/private/projects/github/erlang_upg_test/.erlang.mk/apps.log; then \
			:; \
		else \
			echo $dep >> /mnt/ethrbh/private/projects/github/erlang_upg_test/.erlang.mk/apps.log; \
			make -C $dep IS_APP=1 || exit $?; \
		fi \
	done
	mkdir -p /mnt/ethrbh/private/projects/github/erlang_upg_test/.erlang.mk
	if test -f /mnt/ethrbh/private/projects/github/erlang_upg_test/.erlang.mk/last-makefile-change; then \
		touch src/erlang_upg_test_app.erl src/erlang_upg_test_sup.erl src/m1.erl src/m2.erl       ; \
		touch -c erlang_upg_test.d; \
	fi
	touch /mnt/ethrbh/private/projects/github/erlang_upg_test/.erlang.mk/last-makefile-change
	erl +A0 -noinput -boot start_clean  -pz /mnt/ethrbh/private/projects/github/erlang_upg_test/.erlang.mk/rebar/ebin -eval "	E = ets:new(makedep, [bag]),	G = digraph:new([acyclic]),	ErlFiles = lists:usort(string:tokens(\"src/erlang_upg_test_app.erl src/erlang_upg_test_sup.erl src/m1.erl src/m2.erl  \", \" \")),	Modules = [{list_to_atom(filename:basename(F, \".erl\")), F} || F <- ErlFiles],	Add = fun (Mod, Dep) ->		case lists:keyfind(Dep, 1, Modules) of			false -> ok;			{_, DepFile} ->				{_, ModFile} = lists:keyfind(Mod, 1, Modules),				ets:insert(E, {ModFile, DepFile}),				digraph:add_vertex(G, Mod),				digraph:add_vertex(G, Dep),				digraph:add_edge(G, Mod, Dep)		end	end,	AddHd = fun (F, Mod, DepFile) ->		case file:open(DepFile, [read]) of			{error, enoent} -> ok;			{ok, Fd} ->				F(F, Fd, Mod),				{_, ModFile} = lists:keyfind(Mod, 1, Modules),				ets:insert(E, {ModFile, DepFile})		end	end,Attr = fun		(F, Mod, behavior, Dep) -> Add(Mod, Dep);		(F, Mod, behaviour, Dep) -> Add(Mod, Dep);		(F, Mod, compile, {parse_transform, Dep}) -> Add(Mod, Dep);		(F, Mod, compile, Opts) when is_list(Opts) ->			case proplists:get_value(parse_transform, Opts) of				undefined -> ok;				Dep -> Add(Mod, Dep)			end;		(F, Mod, include, Hrl) ->			case filelib:is_file(\"include/\" ++ Hrl) of				true -> AddHd(F, Mod, \"include/\" ++ Hrl);	false ->					case filelib:is_file(\"src/\" ++ Hrl) of						true -> AddHd(F, Mod, \"src/\" ++ Hrl);						false -> false					end			end;		(F, Mod, include_lib, \"erlang_upg_test.d/include/\" ++ Hrl) -> AddHd(F, Mod, \"include/\" ++ Hrl);		(F, Mod, include_lib, Hrl) -> AddHd(F, Mod, \"include/\" ++ Hrl);		(F, Mod, import, {Imp, _}) ->			case filelib:is_file(\"src/\" ++ atom_to_list(Imp) ++ \".erl\") of			false -> ok;				true -> Add(Mod, Imp)			end;		(_, _, _, _) -> ok	end,	MakeDepend = fun(F, Fd, Mod) ->		case io:parse_erl_form(Fd, undefined) of			{ok, {attribute, _, Key, Value}, _} ->				Attr(F, Mod, Key, Value),				F(F, Fd, Mod);			{eof, _} ->			file:close(Fd);			_ ->				F(F, Fd, Mod)		end	end,	[begin		Mod = list_to_atom(filename:basename(F, \".erl\")),		{ok, Fd} = file:open(F, [read]),		MakeDepend(MakeDepend, Fd, Mod)	end || F <- ErlFiles],	Depend = sofs:to_external(sofs:relation_to_family(sofs:relation(ets:tab2list(E)))),	CompileFirst = [X || X <- lists:reverse(digraph_utils:topsort(G)), [] =/= digraph:in_neighbours(G, X)],	ok = file:write_file(\"erlang_upg_test.d\", [		[[F, \"::\", [[\" \", D] || D <- Deps], \"; @touch \$@\n\"] || {F, Deps} <- Depend],		\"\nCOMPILE_FIRST +=\", [[\" \", atom_to_list(CF)] || CF <- CompileFirst], \"\n\"	]),	halt()" -- erlang.mk
	make --no-print-directory app-build
	erlc -v -Werror +debug_info +warn_export_vars +warn_shadow_vars +warn_obsolete_guard  -o ebin/ -pa ebin/ -I include/ src/erlang_upg_test_app.erl src/erlang_upg_test_sup.erl src/m1.erl src/m2.erl
	printf '{application, erlang_upg_test, [\n	{description, "Example for how to upgrade Erlang/OTP application"},\n	{vsn, "0.0.5"},\n	{modules, ['\''erlang_upg_test_app'\'','\''erlang_upg_test_sup'\'','\''m1'\'','\''m2'\'']},\n	{registered, [erlang_upg_test_sup]},\n	{applications, [kernel,stdlib,sasl,tools,observer,runtime_tools]},\n	{mod, {erlang_upg_test_app, []}},\n	{env, []}\n]}.' \
		> ebin/erlang_upg_test.app
	:
	for dep in  ; do make -C $dep; done
	/mnt/ethrbh/private/projects/github/erlang_upg_test/.erlang.mk/relx -c /mnt/ethrbh/private/projects/github/erlang_upg_test/relx.config  -o _rel release relup tar
	===> Starting relx build process ...
	===> Resolving OTP Applications from directories:
			  /mnt/ethrbh/private/projects/github/erlang_upg_test/ebin
			  /home/ethrbh/tools/erlang_otp_18.3/lib/erlang/lib
			  /mnt/ethrbh/private/projects/github/erlang_upg_test/apps
			  /mnt/ethrbh/private/projects/github/erlang_upg_test/deps
			  /mnt/ethrbh/private/projects/github/erlang_upg_test/_rel
	===> Resolving available OTP Releases from directories:
			  /mnt/ethrbh/private/projects/github/erlang_upg_test/_rel
	===> Resolved erlang_upg_test-0.0.5
	===> Including Erts from /home/ethrbh/tools/erlang_otp_18.3/lib/erlang
	===> release successfully created!
	===> relup successfully created!
	===> tarball /mnt/ethrbh/private/projects/github/erlang_upg_test/_rel/erlang_upg_test/erlang_upg_test-0.0.5.tar.gz successfully created!
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/erlang_upg_test(master)> 

thanks for your help,
/Robi

**Comment by essen** [comment]
There's a separate ticket for verbose relx. Closing, thanks!
