### ISSUE TITLE
Unable to detect platform (MINGW uname)

### ISSUE THREAD

**Issue by wuhkuh** [ninenines/erlang.mk#632]
Good afternoon,
as I was trying to build ranch in Elixir this error popped up:

> P:\Elixir\Testbed>iex -S mix
> Eshell V8.0  (abort with ^G)
> ==> ranch
> uname: invalid option -- o
> Try `uname --help' for more information.
> erlang.mk:73: *** Unable to detect platform. Please open a ticket with the output of uname -a..  Stop.
> ==> testbed
> ** (Mix) Could not compile dependency :ranch, "make" command failed. You can recompile this dependency with "mix deps.c
> ompile ranch", update it with "mix deps.update ranch" or clean it with "mix deps.clean ranch"

running uname -a yields in:
> MINGW32_NT-6.2 MY-PC 1.0.8(0.46/3/2) 2002-12-09 07:58 i686 unknown

I suppose you need them, so here are my basic system specs:
```
Proc: i7-3930k
Mobo: Asus Rampage IV Extreme
OS: Windows 10 Pro, 64-bit, updated to latest version
```

Where to go from here? Thanks in advance!

**Comment by essen** [comment]
What does this run in? Mingw, MSYS, MSYS2?

**Comment by essen** [comment]
Cygwin maybe?

**Comment by wuhkuh** [comment]
MINGW, according to the prefix in the output `MINGW32_NT-6.2 MY-PC 1.0.8(0.46/3/2) 2002-12-09 07:58 i686 unknown`

**Comment by essen** [comment]
Sure but there are a few different projects that share a similar uname as this.

Either way, none of the older Mingw/Cygwin/.. are supported. We support MSYS2 (https://msys2.github.io/) as documented in https://erlang.mk/guide/installation.html#_on_windows

I am not sure if the project would work under other environments at this point. You are welcome to try, by setting PLATFORM yourself, for example `make PLATFORM=msys2` would act as if you were running MSYS2, or `make PLATFORM=linux` would act as if it was Linux. If either of these work, or almost work, then it's worth investigating proper support. If not, the task is probably too big for me to take on right now.

**Comment by essen** [comment]
Out of scope at the moment.
