### ISSUE TITLE
amqp_client deps are broken

### ISSUE THREAD

**Issue by nestor5** [ninenines/erlang.mk#636]
with amqp_client in DEPS, built release can't start:

{{function_clause,[{amqp_gen_connection,terminate,[{undef,[{erl_syntax,form_list,[[{attribute,1,file,{\"src/time_compat.erl\",1}},...

after adding syntax_tools into LOCAL_DEPS:

{{function_clause,[{amqp_gen_connection,terminate,[{undef,[{compile,forms,[[{attribute,1,file,{\"src/time_compat.erl\",1}},...

adding compiler into LOCAL_DEPS and it works

**Comment by essen** [comment]
I meant open this on https://github.com/rabbitmq/rabbitmq-erlang-client :-)

**Comment by essen** [comment]
Closing in favor of https://github.com/rabbitmq/rabbitmq-erlang-client/issues/72
