### ISSUE TITLE
make failed!

### ISSUE THREAD

**Issue by umgeher** [ninenines/erlang.mk#640]
My OS: FreeBSD 11

![2016-11-29-211934_537x562_scrot](https://cloud.githubusercontent.com/assets/224185/20729375/a377d556-b679-11e6-8222-79c2269ba670.png)

**Comment by essen** [comment]
Yes it requires GNU Make, on FreeBSD "make" is BSD make. You need to install/use gmake, see https://erlang.mk/guide/installation.html#_freebsd

Cheers,
