### ISSUE TITLE
Turning off progress reports ?

### ISSUE THREAD

**Issue by jhw** [ninenines/erlang.mk#644]
Hi,

Wondering how to best turn off shell progress reports. 

The only logger I have installed is syslog, configured as follows [sys.config] - 

 {syslog, [{dest_host, "XXX.papertrail.com"},
	   {dest_port, 12345},
	   {no_progress, true},
	   {verbose, false}]}].

This works very nicely - all Erlang CRASH reports are sent to Papertrail, along with any custom logging messages I send using the syslog functions.

Progress reports are not sent to Papertrail - they are dumped to shell which is a pain for development / interactive work. I presume there's a way to turn them off, but I get confused about the morass of different error_logger/sasl/whatever logging options in Erlang. I presume the Erlang.mk release- building process is starting / configuring some of these but not others.

Can anyone give me the magic solution to turning off the shell progress reports ?

Thanks!

**Comment by essen** [comment]
Erlang.mk leaves everything as default as far as logging is concerned.

To turn off sasl, all you need in sys.config is:

```
{sasl, [
    {sasl_error_logger, false}
]},
```

**Comment by jhw** [comment]
That certainly works but I'm slightly worried that syslog may have some kind of sasl dependency and configuring it this way means crashes are no longer routed to Papertrail. Maybe I should be asking the syslog library creator ?

**Comment by jhw** [comment]
>>> The syslog application will not touch the standard SASL report handlers attached to the error_logger when SASL starts. However, having SASL progress reports on TTY can be quite annoying when trying to use the shell. The correct way to disable this output is to configure the SASL application in the sys.config of a release, for example the following line will instruct SASL not to attach any TTY handlers to the error_logger:

**Comment by jhw** [comment]
Closed; thx!
