### ISSUE TITLE
erlang-history support ?

### ISSUE THREAD

**Issue by jhw** [ninenines/erlang.mk#645]
Hi,

Does/could erlang.mk support erlang-history ?

https://github.com/ferd/erlang-history

Seems like a very useful thing, as least for dev shell debugging

Tried it in my erlang.mk Makefile, but release building failed :-(

Am guessing you would want it in a dev build but not a prod build ?

Thoughts ?

Thank you :-)

**Comment by essen** [comment]
It's an unofficial patch to Erlang/OTP. I have no plans to support it.
