### ISSUE TITLE
Setting common tests config file not working

### ISSUE THREAD

**Issue by dnldd** [ninenines/erlang.mk#65]
Hi, I'm trying to run a test suite with my existing app config. Going through the erlang.mk options , CT_OPTS seemed like the way to go with this so I did try `CT_OPTS = -config debug.config` in my makefile. I still can't get access to my config file after doing this. How do you set external config files for common tests with erlang.mk? Thanks.

**Comment by rlipscombe** [comment]
`CT_OPTS = -erl_args -config test/app.config` was sufficient in my case.
