### ISSUE TITLE
Too many open files error

### ISSUE THREAD

**Issue by jordanchaitin** [ninenines/erlang.mk#650]
Using erlang.mk with the hello_world example from the getting started guide for Cowboy. 

The directory structure is: `hello_erlang/deps/cowboy/examples/hello_world`. 

Running `make` in `hello_world` gives an error `/../../erlang.mk: Too many open files/`.
Running `make -d` (for debugging info) prints a few thousand messages to the screen which look like:
```
Trying pattern rule with stem 'xxxFilename' 
Trying implicit prerequisite 'xxxFilename'
Looking for a rule with intermediate file 
Avoiding implicit rule recursion.
```

The `Makefile` in `hello_world` contains a line `include ../../erlang.mk`. Two directories up, the `cowboy` directory contains `erlang.mk` with only one line `include ../../erlang.mk`. The parent `hello_erlang` contains the real `erlang.mk` file.  

The output of `ulimit -n` on the system is 4864. But I am not sure if changing the max number of open file descriptors is a good idea since the directory structure cannot be predicted. The workarounds I found are:
1. Replacing the line in `Makefile` in `hello_world` which says `include ../../erlang.mk` with `include ../../../../erlang.mk`
2. Copying the original/actual file erlang.mk from the parent directory `hello_erlang` to the current `hello_world` and changing the `Makefile` code in `hello_world` to `include erlang.mk` instead of `include ../../erlang.mk`.

**Comment by essen** [comment]
I have no problem with a limit of 1024 on Linux so probably not the issue.

What's the OS/version? And what's the Make version? (`make -v`) Thanks.

**Comment by jordanchaitin** [comment]
OS is macOS Sierra 10.12.2 (16C67), Darwin Kernel Version 16.3.0. 
Make is GNU Make 3.81. 

I think that could be the issue since make -v also gives a message saying "This program built for i386-apple-darwin11.3.0" 

But that would be odd since Xcode is the latest version and Make is part of xcode command line utilities. I'm trying to install again now using homebrew..

**Comment by essen** [comment]
OSX ships with a prehistoric Make version. You might want to install a recent one, see if that fixes it: https://erlang.mk/guide/installation.html#_on_unix

**Comment by jordanchaitin** [comment]
sadly, strangely, no. 

I got a new version of gmake using homebrew
GNU Make 4.2.1
Built for x86_64-apple-darwin16.3.0

Running `gmake` gives the same `too many open files` error and `gmake -d` in hello_world gives `Reading makefile '../../erlang.mk' (search path) (no ~ expansion)` a few thousand times..

**Comment by essen** [comment]
Alright sounds like a legitimate bug. :-) Thanks I'll check when I get more time.

**Comment by jordanchaitin** [comment]
And I'll have my special workaround in the meantime ;) 

Cheers

**Comment by andrAnat-b** [comment]
I have same problem when i try make examples. For example rest_pastebin 
../../erlang.mk:1: *** Too many open files.  Stop.
GNU Make 4.1
Ubuntu 16.04.3 LTS

Please check when you have a time :angel: :smile:

**Comment by terry-xiaoyu** [comment]
Same issue, do you have any update on this?

Mac OSX 10.13.4
GNU Make 3.81

**Comment by essen** [comment]
Does this happen if you fetch Cowboy directly (via git clone) or only if Cowboy is fetched as a dependency?

**Comment by terry-xiaoyu** [comment]
@essen Not the Cowboy, it is the erlang.mk. 

The project what I'm trying to build is one of the dependencies in the "deps" directory of [emqttd](https://github.com/emqtt/emqttd), after I've changed some code of it.

I'm just trying to make that dependency project after I've suspended my laptop for about 2 days. But it works fine before that.

If I ran 'make' in the top level dir of 'emqttd' to build the whole project and all the dependencies, it would work as expected.

I've seen this issue several times.

**Comment by essen** [comment]
Can anyone who has this issue try again with the most recent Erlang.mk and put somewhere the full output using `make V=1`?

**Comment by jordanchaitin** [comment]
Hi @essen, sorry about the delay; I'll do it soon and update here..

**Comment by jordanchaitin** [comment]
Took me a while to get around to this, but it seems to work fine now. 

Running gmake in the examples dir creates the archive, and running gmake run starts the server too. So it seems all good :-) just in time for Christmas! 

The output using gmake V=1 is pasted here https://pastebin.com/cqXj4NMB

**Comment by essen** [comment]
Thanks!
