### ISSUE TITLE
 Tarball generation error for error reason {badmatch,555}

### ISSUE THREAD

**Issue by jhw** [ninenines/erlang.mk#651]
Just tried upgrading another existing project as follows

$ make erlang-mk; make distclean; make

almost works; but then following

===> release successfully created!

the system waits forever and then I get

===> Tarball generation error for error reason {badmatch,555}

This sounds like a permissions / chmod +x error. Has something changed ? What should I do ? Thanks!

**Comment by essen** [comment]
The release building now includes generating a tar file by default. I didn't expect an issue to happen, and I got no idea why it does this. It's Relx generating the tarball so please open an issue there (or check if one exists).

**Comment by essen** [comment]
Relx is used like this: https://github.com/ninenines/erlang.mk/blob/master/plugins/relx.mk#L40

**Comment by jhw** [comment]
Can I turn off the release building tarball generating option for now ?

**Comment by essen** [comment]
Only by editing erlang.mk, find the same line I highlighted and remove "tar".

**Comment by jhw** [comment]
Thx

**Comment by jhw** [comment]
https://github.com/erlware/relx/issues/555

**Comment by jhw** [comment]
Probably a stupid question, but if erlang.mk now asks relx to create a release tar file, where is that tar file found ?

(because have found that manually creating a .tgz file by tar'ing the _rel directory no longer works, but causes my .tgz file to grow to unimaginable size and never complete; so am guessing the _rel structure has changed somewhat; and I probably no longer need this manual tar step for deployment, but can use the tar file auto- created by relx)

Thank you

**Comment by essen** [comment]
In _rel/$relname.tgz. But you don't really need it for Erlang.mk to function, unless you're using self-extracting archives (make SFX=1). Otherwise it's just there as convenience.

**Comment by jhw** [comment]
It's absolutely massive! 256Mb compared to the 17Mb I have been getting when formerly tar'ing _rel. Does it use relx.config when creating _rel/$relname.tgz ? Because I specify {include_src, false} there  ..?

**Comment by jhw** [comment]
Never mind, I will just delete it. Thx

**Comment by essen** [comment]
It should *definitely* not be 256MB *unless* you have a really, really big project. Something is wrong there. It's Relx creating it so if it does something wrong, they would know. I haven't seen this problem myself.

**Comment by jhw** [comment]
ok thx
