### ISSUE TITLE
Can no longer build erlware_commons/src/ec_plists.erl

### ISSUE THREAD

**Issue by jhw** [ninenines/erlang.mk#652]
Last one for tonight

One of my erlang-mk deps (qdate) pulls in erlware_commons.

This used to build fine but now with Erlang 19 am getting

>>> src/ec_plists.erl:220: syntax error before: '/'

actually a whole load of similar errors. The offending line seems to be as follows

>>> -spec sort/3 :: (fun(), list(), malt()) -> list().

Am guessing maybe something changed in annotations in Erlang 19.

Anyway what's the strategy I should be employing to fix this ? Clone erlware_commons and fix ? Ask them to fix ?

Thank you

**Comment by essen** [comment]
It's a very old spec notation that's been deprecated for a while now. It's also already been fixed apparently: https://github.com/erlware/erlware_commons/commit/6d63ffde5710b8e258f4e473d6e8778e3b9f8047

So just use a more recent version.

**Comment by jhw** [comment]
Thx
