### ISSUE TITLE
Deps with Apps

### ISSUE THREAD

**Issue by obi458** [ninenines/erlang.mk#653]
If deps contains apps, it seems not to work(does not compile apps in deps)!

Example:
deps 
---dep1
----apps
-----app1
-----app2
---dep2
 .....

How to compile app1 and app2 in apps?

APPS_DIR works only if apps is a subfolder of the release app!

Hint: If it was compiled, then with LOCAL_DEPS the release works!

**Comment by essen** [comment]
It's not currently supported. You can probably make it work by adding some `ln -s` for example to make them appear in deps.

**Comment by essen** [comment]
I've just added `dep_mydep = git-subfolder https://github.com/blah/my_git_repo master path/to/mydep` to my local copy. It'll be pushed soon. Closing, thanks!
