### ISSUE TITLE
how compilation of files with include_lib dep includes works?

### ISSUE THREAD

**Issue by comtihon** [ninenines/erlang.mk#664]
Hi,
I was investigating why I am not able to compile `src/file1.erl` if it has `include_lib deps/dep/include/file2.hrl`.
I tried with `erlc -I deps/dep/include` with no effect.
So I decided to look in erlang.mk `compile_erl`, log the call, but when I repeate the call in the same console - I got the same error about missing include.
Cmd is `erlc -v -Werror +debug_info +warn_export_vars +warn_shadow_vars +warn_obsolete_guard -o ebin/ -pa ebin/ -I include/ Modules`
How did you make it working?

Regards.

**Comment by essen** [comment]
`-include_lib("app_name/include/file2.hrl").`

Don't include "deps".

**Comment by comtihon** [comment]
yes, I know it is a bad practice of exposing hrls from one project to another.
But how did you solve this problem of calling `erlc` to compile this issue?
I found only one desicion of calling erlc with `-pa path/to/dep/ebin` for every dep.

**Comment by essen** [comment]
The deps folder is in the `ERL_LIBS` environment variable that Erlang uses to locate applications when using include_lib and others. If you want to do otherwise you should use `-include` instead.

**Comment by comtihon** [comment]
Oh. That was so simple.
Thanks!
