### ISSUE TITLE
nif building wrong linker

### ISSUE THREAD

**Issue by ingwinlu** [ninenines/erlang.mk#666]
When using erlang.mk to build nifs `CC` is used to link the files. this is fine as long as you use only c files. When using cpp you will get undefined symbol errors on load.

https://github.com/ninenines/erlang.mk/blob/master/plugins/c_src.mk#L102

Not sure on the way forward.

**Comment by ingwinlu** [comment]
Probably splitting up SOURCES and OBJECTS in _C and _CPP and testing if _CPP is empty should work out

**Comment by essen** [comment]
Wouldn't using `ld` be enough? I think I have a branch somewhere with the start of a fix.

**Comment by ingwinlu** [comment]
We can probably use ld directly yes. However I am not sure on how we would be able to get all the required args.
Replacing CC with c++ -v echos out a call to `collect2` (which should is just an alias for ld). However there are quite a lot of arguments added by c++ as well:

**Comment by essen** [comment]
Just replacing `$(CC)` with `$(LD)` doesn't seem to break anything, however I'd like to see a failing test that gets fixed by this. Could you send a small example or test case that fails? I tried modifying current tests adding some classes but could not see any failure. Additionally projects like jiffy have some C++ and do not fail either, though that's perhaps because of `extern "C"` statements.

**Comment by ingwinlu** [comment]
> Just replacing $(CC) with $(LD) doesn't seem to break anything, however I'd like to see a failing test that gets fixed by this.

did you try loading them as well? it built fine for me as far as I can remember but the problem was 'runtime' only.

> Could you send a small example or test case that fails?

code was from an ex employer and I do not have it anymore.

**but**

If I remember right it was the following construction that triggered the problem:
`erlang wrapper module -> c(pp) file with #include "original.cpp"`

The original.ccp file used some c++ features like maps. It also had an mysql part that was not used in the *erlangified* version anymore but still needed to be linked against:
`g++ -Wno-write-strings -L/usr/lib64/mysql -lmysqlclient -o original original.cpp`

The solution was to remove most of the code from `original` so I could build it with cc.

**Comment by essen** [comment]
The tests load the modules yes. If you know of a project like this then Erlang.mk can test it quickly via `make check p=jiffy`.

It must be something specific that makes the failure. Maybe also platform-specific? Since compilers/options may differ.

**Comment by essen** [comment]
Closing for now, if problem comes back please open a new issue. Thanks!
