### ISSUE TITLE
Pin dependencies to specific tags

### ISSUE THREAD

**Issue by mdevilliers** [ninenines/erlang.mk#670]
Hey,

I'm having difficulty pinning my dependencies to a specific tag - 

In my Makefile - https://github.com/mdevilliers/rabbitmq-stamp/blob/new-structure-mk/Makefile

```
DEPS = rabbit_common rabbit amqp_client
dep_rabbit_common_commit = rabbitmq_v3_6_6
dep_rabbit_commit = rabbitmq_v3_6_6
dep_amqp_client_commit = rabbitmq_v3_6_6
```

```
ubuntu@ubuntu-xenial:/vagrant/rabbitmq-stamp$ make show-branch
rabbit_common:                     master
rabbit:                            master
amqp_client:                       master
rabbitmq_stamp:                    new-structure-mk
```

I have also tried 

```
DEPS = rabbit_common rabbit amqp_client
dep_rabbit_common = git https://github.com/rabbitmq/rabbitmq-common rabbitmq_v3_6_6
dep_rabbit = git https://github.com/rabbitmq/rabbitmq-server rabbitmq_v3_6_6 
dep_amqp_client = git https://github.com/rabbitmq/rabbitmq-erlang-client rabbitmq_v3_6_6
```

with the same results?

The version of erlang.mk is copied from the repo - https://github.com/rabbitmq/rabbitmq-metronome

Probably user error but I'd love to know how to debug it further from my end?

**Comment by essen** [comment]
The rabbitmq-components.mk file sets various things including versions of components, so try to put yours after including it to override them. Either way this would be better as a ticket to RabbitMQ where @dumbbell can more readily see your issues. Cheers!

**Comment by mdevilliers** [comment]
Perfect - just what I needed to find out - thanks for the pointer.
