### ISSUE TITLE
make eunit exit 0 even if one application has fallen tests in multi-application repository

### ISSUE THREAD

**Issue by headcrabmeat** [ninenines/erlang.mk#675]
#### Lets say I have following layout of my project repository ("*multi-apps with no root app*")
```
.
├── apps
│   ├── app1
│   │   ├── include
│   │   ├── Makefile
│   │   ├── src
│   │   └── test
│   ├── app2
│   │   ├── include
│   │   ├── Makefile
│   │   ├── src
│   │   └── test
...
│   ├── appN
│   │   ├── ebin
│   │   ├── include
│   │   ├── Makefile
│   │   ├── src
│   │   └── test
...
```

#### Let's say `app2` has a broken test
```shell
cd app2 
make
make eunit
# ... falling tests inside ...
echo $?  # returns 2
```

#### User runs eunit from the root of the project
```shell
make
make eunit
# ... falling tests inside ...
echo $? # returns 0
```
However expected exit code of `make` is 2

**Comment by essen** [comment]
Thanks! Please try to provide a test case, this PR should be a good example of doing that: https://github.com/ninenines/erlang.mk/pull/626/files

**Comment by headcrabmeat** [comment]
ok. it's done in my fork. Should I create a pull request with title like `WIP: eunit multi apps no root check eunit exit code`

**Comment by essen** [comment]
Sure! Thanks.

**Comment by headcrabmeat** [comment]
#676 I think I was also able to fix it
