### ISSUE TITLE
building releases on different erlang platforms

### ISSUE THREAD

**Issue by ingwinlu** [ninenines/erlang.mk#680]
Hi,

trying to piggyback on the CI stuff to build releases:
![virtualbox_centos7_21_03_2017_13_21_29](https://cloud.githubusercontent.com/assets/4435962/24147278/c4fc7f20-0e39-11e7-8997-d8bdfedc1df7.png)
![virtualbox_centos7_21_03_2017_13_21_10](https://cloud.githubusercontent.com/assets/4435962/24147279/c620c2f8-0e39-11e7-98df-30d841537189.png)
Any idea on why it might fail? I based the rule on https://github.com/ninenines/erlang.mk/blob/9e9b7d2caa42c701f76efff06286ed046dc3fe90/plugins/ci.mk#L48.

**Comment by essen** [comment]
The `$(CI_INSTALL_DIR)/$(1)` results in `/OTP-18.2` because CI_INSTALL_DIR is not defined. Move those rules after include erlang.mk I guess?

**Comment by ingwinlu** [comment]
thanks, works now.
