### ISSUE TITLE
[multi-app] edoc fails

### ISSUE THREAD

**Issue by ingwinlu** [ninenines/erlang.mk#681]
`make edoc` fails to detect apps and just tries to read everything in `basedir` when no src directory exists.

a proposed solution would be to build edocs for each app in apps into the same out dir and then (if necessary) modify the index.html file for a nicer listing.

edoc also might need to run in the right order, so maybe we can build on top of #673

**Comment by essen** [comment]
Turns out it's already working, just you gotta configure it. At the end of your Makefile, do:

```
EDOC_SRC_DIRS = $(ALL_APPS_DIRS)
```

I'll just add it to the documentation. I don't think it should do this by default, gotta let people decide if they want a global edoc or do it per app.

Closing, thanks!
