### ISSUE TITLE
SP variable not only for templates.

### ISSUE THREAD

**Issue by 6aKa** [ninenines/erlang.mk#683]
Use SP variable for $(PROJECT).app file and rebar.config indentation.

**Comment by essen** [comment]
Don't think the rebar.config has any indentation (correct me if I'm wrong). Otherwise sure, why not.

**Comment by 6aKa** [comment]
rebar.config and $(PROJECT).app contains only erlang structures. Indentations in this files only for pretty.
I want "make SP=2" generate pretty with indentations $(PROJECT).app file.
And want "make rebar.config SP=2" generate pretty with indentations rebar.config file.

**Comment by essen** [comment]
It's not feasible for rebar.config, we can't pretty print since we don't use Erlang to generate it. It's doable for the .app file but my time is probably better spent elsewhere. I'll happily merge a PR with this change though. Closing, thanks!
