### ISSUE TITLE
callback modules not found

### ISSUE THREAD

**Issue by comtihon** [ninenines/erlang.mk#684]
Hi.
If I have a callback module:
```
-module(some_module_int).
-callback common_stuff() -> ok.
```
and it is situated not in `src`, but in some subfolder: `src/handlers/some_module_int`
I have got compilation error:
```
ERLC  endless list of my modules here + some_module_int.erl
src/some_module_int.erl: no such file or directory
make[1]: *** [erlang.mk:4998: ebin/my.app] Error 1
make: *** [erlang.mk:4815: app] Error 2
```
To make it working I have to copy all the callback modules to src, and this is not what I want.

**Comment by essen** [comment]
Please try again, this should be fixed.

**Comment by essen** [comment]
Reopen if needed.

**Comment by essen** [comment]
Use `make erlang-mk` to easily update.
