### ISSUE TITLE
XYRL targets are run more often than they should be

### ISSUE THREAD

**Issue by darkling** [ninenines/erlang.mk#685]
For example:

hrm@damon:~/nightglass/software/childe $ make clean
 XYRL   childe_parser.yrl

*** Conflicts resolved by operator precedences:

Parse action conflict scanning symbol '(' in state 81:
[...]
Resolved in favor of shift.

*** End of resolved conflicts

 DEPEND childe.d
 GEN    clean-app
 GEN    coverdata-clean

**Comment by darkling** [comment]
The only thing that might be unusual here is that I have some extra dependencides defined in my Makefile (included in its entirety here):

PROJECT = childe
DEPS = erlsom

dep_erlsom_commit = v1.4.1

ebin/childe.app:: src/lex_tokens.hrl
ebin/childe_lexer.beam:: src/lex_tokens.hrl

include erlang.mk

src/lex_tokens.hrl:: gen_lex_tokens
        ./gen_lex_tokens >src/lex_tokens.hrl

.PHONY: doc
doc:
        (cd doc; make html)

**Comment by darkling** [comment]
It's only the _second_ "make clean" that rebulids the grammar.

$ make   # builds the project as expected, including the grammar
$ make clean  # cleans the project as expected
$ make clean  # builds the grammar and then cleans

**Comment by essen** [comment]
Thanks. I will add a test tomorrow.

**Comment by essen** [comment]
Well that was easy to reproduce.

**Comment by essen** [comment]
Please try this patch and report back:

``` patch
diff --git a/core/erlc.mk b/core/erlc.mk
index 65ef71b..8a8aea0 100644
--- a/core/erlc.mk
+++ b/core/erlc.mk
@@ -238,7 +238,7 @@ $(ERL_FILES) $(CORE_FILES) $(ASN1_FILES) $(MIB_FILES) $(XRL_FILES) $(YRL_FILES):
 ebin/$(PROJECT).app:: $(ERLANG_MK_TMP)/last-makefile-change
 endif
 
--include $(PROJECT).d
+include $(wildcard $(PROJECT).d)
 
 ebin/$(PROJECT).app:: ebin/
 
```

**Comment by essen** [comment]
I got to this solution again thanks to http://make.mad-scientist.net/papers/advanced-auto-dependency-generation/ - works against the tests I tried so far but I'll be sure to double check the nightly builds after merging.

**Comment by darkling** [comment]
It's not looking good here, I'm afraid:

    hrm@amelia:~/nightglass/software/childe (master)$ make clean
     GEN    clean-app
     GEN    coverdata-clean
    hrm@amelia:~/nightglass/software/childe (master)$ make
     ERLC   childe.erl childe_app.erl childe_instance.erl childe_lexer.erl childe_parser_tests.erl childe_pretty.erl childe_proc.erl childe_report.erl childe_roster.erl childe_semantic.erl childe_sup.erl childe_trace.erl childe_types.erl tmp.erl childe_parser.erl
    src/childe_parser.erl:1: no module definition
    erlang.mk:5044: recipe for target 'ebin/childe.app' failed
    make: *** [ebin/childe.app] Error 1

Note that it's not building the XYRL target at all. The `src/childe_parser.erl` file is automatically generated, but empty. I can manually make `childe.d`, which does build the XYRL target, and I can then run `make` for the app, but `make clean` takes us back to the state above.

However, at least repeated `make clean`s are OK now.

**Comment by essen** [comment]
You might need to `make distclean` to get back to a good state after applying the patch.

**Comment by darkling** [comment]
No, that looks like it's broken deps as well:

    hrm@amelia:~/nightglass/software/childe (master)$ make distclean
     GEN    clean-app
     GEN    coverdata-clean
     GEN    distclean-tmp
     GEN    distclean-deps
     GEN    distclean-asciidoc
     GEN    distclean-ct
     GEN    distclean-plt
     GEN    distclean-edoc
     GEN    distclean-escript
     GEN    distclean-relx-rel
     GEN    distclean-relx
     GEN    distclean-xref
     GEN    cover-report-clean
    hrm@amelia:~/nightglass/software/childe (master)$ make
     ERLC   childe.erl childe_app.erl childe_instance.erl childe_lexer.erl childe_parser.erl childe_parser_tests.erl childe_pretty.erl childe_proc.erl childe_report.erl childe_roster.erl childe_semantic.erl childe_sup.erl childe_trace.erl childe_types.erl tmp.erl
    src/childe_instance.erl:5: can't find include lib "erlsom/src/erlsom_sax.hrl"
    erlang.mk:5044: recipe for target 'ebin/childe.app' failed
    make: *** [ebin/childe.app] Error 1

**Comment by essen** [comment]
OK I'll double check, thanks.

**Comment by darkling** [comment]
OK, the issue was in my additions to the Makefile. This is wrong:

    ebin/childe.app:: src/lex_tokens.hrl
    ebin/childe_lexer.beam:: src/lex_tokens.hrl

and should be:

    app:: src/lex_tokens.hrl

With the latter line in place instead of the former two, and with the proposed patch to erlang.mk, it all seems to behave correctly.

**Comment by essen** [comment]
Fixed, thanks!
