### ISSUE TITLE
Luerl pluggin

### ISSUE THREAD

**Issue by jchassoul** [ninenines/erlang.mk#686]
It would be awesome to have build in support for Luerl I notice erlang.mk have pluggins for LFE and Elixir.

There is probably and easy way to enable this in erlang.mk but I can't found how to pass a -pa with the luerl ebin path with it.

Here is the makefile that I'm currently using that enable luerl support on make https://gist.github.com/jchassoul/c79db8802097ed42f2107e744e304f43 I think only the lines 27 and 40 are needed for this.

**Comment by essen** [comment]
If you add luerl as a `DEPS` then its ebin/ directory will be included in the paths, no need for -pa. Just `DEPS = luerl` should be enough I think, IIRC luerl does not have a compiler so you can just use it as a normal dependency.

**Comment by jchassoul** [comment]
I try that and fail before open the issue, the same code base compile correctly with that Makefile from Robert that include the -pa

this is my Makefile with DEPS = luerl

I'm trying to finally use the erlang.mk that I love with luerl but I get this error that really does not help much.

erlang.mk:5055: recipe for target 'ebin/treehouse.app' failed
make[1]: *** [ebin/treehouse.app] Error 1
erlang.mk:4859: recipe for target 'app' failed
make: *** [app] Error 2

**Comment by essen** [comment]
Hmm luerl compiles fine in the nightly builds. What's the full error?

**Comment by jchassoul** [comment]
It's not that erlang.mk does not compile luerl as dependency it does, I get all my dependencies for the project with it, but I can't use erlang.mk to build and compile luerl code no the project luerl but source that use it, because to compile those .erl files erlc need's to have access to luerl.

example: erlc -pa ~/work/structures/treehouse/deps/luerl/ebin -o ./ebin src/luerl_ship.erl

I'm going to paste the complete log first trying to compile the same codebase with the Makefile that use erlang.mk and then the original Makefile from Robert.

**Comment by essen** [comment]
Ah I misunderstood then. Nevertheless it should be there, that's how parse_transform are detected for example. Can you put a small repo online somewhere? That'd be better.

**Comment by jchassoul** [comment]
Sure thing, btw thanks for your response and messages.

This is the log with and without erlang.mk doing "make all"

https://gist.github.com/jchassoul/f2e9392120a9d25e00dea003a863a79d

Yes I can upload the repo, one sec.

**Comment by essen** [comment]
Ah well that's because of `compile: warnings being treated as errors` not because of the path. It should work once these are fixed or you disable the warnings as error (define `ERLC_OPTS = +debug_info` at the top of your Makefile for example).

**Comment by jchassoul** [comment]
Awesome!! ERLC_OPTS = +debug_info did the job! I'm so happy! finally I can use use erlang.mk to build releases that include luerl, thank you very much for your help! 

Was like you said a n00b mistake from my side and nothing wrong with erlang.mk
