### ISSUE TITLE
Cannot build latest version on Fedora 25

### ISSUE THREAD

**Issue by benjamin-bergia** [ninenines/erlang.mk#688]
Just tried to get erlang.mk running on my laptop and I get the following error:

```
$make
git clone https://github.com/ninenines/erlang.mk .erlang.mk.build
Cloning into '.erlang.mk.build'...
remote: Counting objects: 6799, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 6799 (delta 2), reused 0 (delta 0), pack-reused 6787
Receiving objects: 100% (6799/6799), 3.22 MiB | 605.00 KiB/s, done.
Resolving deltas: 100% (4267/4267), done.
Checking connectivity... done.
if [ -f build.config ]; then cp build.config .erlang.mk.build; fi
cd .erlang.mk.build && make
make[1]: Entering directory '/************/.erlang.mk.build'
/bin/sh: -c: line 0: unexpected EOF while looking for matching `''
/bin/sh: -c: line 1: syntax error: unexpected end of file
export LC_COLLATE=C; \
awk 'FNR==1 && NR!=1{print ""}1'  \
        | sed 's/^ERLANG_MK_VERSION = .*/ERLANG_MK_VERSION = 2016.01.12-2-g7a200f5/' > erlang.mk
```

I am using fedora 25. I have erlang, make, gcc and git installed. I looked at the `Makefile` but I didn't notice anything wrong. Could it be a problem with my `make` version ?

Edit: Here is my make version
```
GNU Make 4.1
Built for x86_64-redhat-linux-gnu
```

**Comment by essen** [comment]
I'm not sure what the `make[1]: Entering directory '/************/.erlang.mk.build'` is about.

I don't know if your Make version is the problem, could be if they have custom patches that break things, but otherwise should be fine. I was using it for a long time (am now on 4.2.1).

Do you perhaps have an environment variable that can messes things up?

**Comment by benjamin-bergia** [comment]
@essen Mystery solved !
For some unknown reason I had the stupid idea to stick a " ' " in the name of my project directory.
Apparently the first step of the script ( a `cd` into `.erlang.mk.build` ) use the full path of the `.erlang.mk.build` directory and there is no escaping of special characters in the path.

Renamed my directory and everything works fine.
Sorry to waste your time.

**Comment by essen** [comment]
Good to hear!
