### ISSUE TITLE
 Dependency cf is specified as a dependency but is not reachable by the system - please help!

### ISSUE THREAD

**Issue by jhw** [ninenines/erlang.mk#690]
Hi,

Getting the above when building an existing Erlang project on a new machine.

The project requires qdate, which in turn requires erlware-commons, which in turn seems to require cf. cf seems to be a project which highlights syntax, and which is pulled in when the erlware-commons rebar file detects you are using rebar2 rather than rebar3. Perhaps I need to upgrade to rebar3 ? 

Please help!

Thank you

**Comment by essen** [comment]
I think there is a bug currently where the dependencies of hex dependencies are not fetched. Could this be it? Was erlware_commons fetched via hex?

**Comment by essen** [comment]
Scratch that. It *is* fetched, but it is *not* compiled for some reasons.

**Comment by essen** [comment]
And the reason it is not compiled is because autopatch is not applied. I can't fix it right away but I will look closer soon.

**Comment by jhw** [comment]
No probs; thank you

**Comment by jhw** [comment]
Apologies but do you have any timescale for this ? Just trying to figure out workarounds / manage upstream expectations :-)

**Comment by essen** [comment]
You posted at a bad time, I'll see tonight or tomorrow if I can fix it, but might be next week only.

**Comment by essen** [comment]
Pushed a fix that works with qdate for me. I'll have to see what the nightly build says tomorrow about other projects though. Thanks!

**Comment by jhw** [comment]
Works; thanks!
