### ISSUE TITLE
compile error for dependency "brod"

### ISSUE THREAD

**Issue by kansi** [ninenines/erlang.mk#691]
The dep fails to compile with following error.
```
GEN    escript-zip

WARNING: No more files
elvis_mk/ebin

make[1]: *** [../../erlang.mk:6297: escript-zip] Error 1
```

**Comment by essen** [comment]
For me it fails a little after that because they have a `rel` target that gets executed when it shouldn't be. I do not have your specific issue. Is this with the most recent Erlang.mk and brod?

**Comment by kansi** [comment]
My erlang.mk version is `2017.04.25-6-g5922969` and my project is bare bones just added a few deps and tried to compile and it failed on brod

**Comment by kansi** [comment]
@essen is there a way I can temporarily bypass this error untill the issue is fixed ?

**Comment by essen** [comment]
I haven't managed to reproduce your issue but for mine, opening the Makefile and remove the rel:: target should be enough. Not sure it'll help you though.

**Comment by kansi** [comment]
Ok, that helped, was able to get to the error you are seeing and then removed the rel:: target

**Comment by essen** [comment]
It would be good to tell brod developers that they should do something in their Makefile:

```
ifeq ($(IS_APP)$(IS_DEP),)
rel:: ....
endif
```

This way it will work for everyone.

**Comment by kansi** [comment]
Raising an issue on their repo

**Comment by essen** [comment]
It looks like there's no compile error anymore upstream so I'll be closing this. Thanks!
