### ISSUE TITLE
configurable include/ebin directories for protobuffs plugin

### ISSUE THREAD

**Issue by kevinwilson541** [ninenines/erlang.mk#692]
When the `protobuffs` plugin is used, it searches for .proto files recursively in the `src/` directory. Before compiling .proto files, this code runs (https://github.com/ninenines/erlang.mk/blob/master/plugins/protobuffs.mk#L12). The directory to place the compiled .proto files is on a per-file basis, so when a .proto file exists several directories down under the `src/` directory, compilation will fail since the directory it's pointing to doesn't exist (namely, this code will crash the build https://github.com/ninenines/erlang.mk/blob/master/plugins/protobuffs.mk#L20-L23). For example, if a .proto file is under `src/model/proto_model.proto`, `Dir` will be calculated to `src`, which doesn't have an `include/` or `ebin/` directory.

Three possible solutions I can think of off the top of my head are:
- Make the include/src directories configurable that `protobuffs_compile:generate_source/2` call reads from.
- Make them inputs to the `compile_proto.erl` function.
- Don't even compute the `Dir` variable, since the working directory is the same between creating `ebin/`/`include/` and running `compile_proto`; then change the `output_include_dir` and `output_src_dir` options to "./include" and "./ebin" respectively.

Whichever is preferable to the community, I can make a PR for a fix.

**Comment by essen** [comment]
Third one sounds good.

**Comment by kevinwilson541** [comment]
Will do, I'll make a PR soon. Thanks!
