### ISSUE TITLE
Tag 2016.01.12 disappeard

### ISSUE THREAD

**Issue by fenollp** [ninenines/erlang.mk#703]
Hey there, it seems at least one of your tags is no longer there.
We have pretty frequent builds relying on https://github.com/2600hz/kazoo/blob/1871e74ff799c254ca967b95d86123f5b0c4e232/Makefile#L58
and since today our builds fail due to this.

We're resolving this by relying on the latest tag but I thought that's something you should be aware of.

**Comment by essen** [comment]
It was an error to name it 2016.01.12 and should have been 2017.01.12 and I have corrected this. I realized when I pushed that I forgot to push the tags when I did that change and didn't give anyone any time to update before I deleted it, my bad. Sorry about that.

**Comment by fenollp** [comment]
All good! We found/fixed this pretty quickly anyway.
