### ISSUE TITLE
`make ct-$SUITE t=$TEST` conflicts with dependencies autopatching

### ISSUE THREAD

**Issue by dumbbell** [ninenines/erlang.mk#707]
Running `make ct-$SUITE t=$TEST` (which runs a particular Common Test tescase) conflicts with the [`dep_authpatch_erlang_mk` macro which is also using the `$t` variable](https://github.com/ninenines/erlang.mk/blob/master/core/deps.mk#L175).

Because the value on the command line takes precedence, autopatching fails with a somewhat cryptic error. Here is an example:
```
$ gmake ct-partitions-on-concourse t=cluster_size_3:partial_false_positive
 DEP    cth_fail_fast
/bin/sh: Syntax error: "do" unexpected (expecting "fi")
gmake: *** [erlang.mk:5125: .../deps/cth_fail_fast] Error 2
```

If I run the same command with the `t=cluster_size_3:partial_false_positive` argument, it succeeds.

**Comment by essen** [comment]
What is this $t doing in dep_autopatch_erlang_mk? I don't recall...

**Comment by essen** [comment]
I've removed it. Seems it was added by mistake in https://github.com/ninenines/erlang.mk/commit/3f8688e0d0526b74993d64a166e9ba8559c687e4

Thanks!
