### ISSUE TITLE
Managing Erlang/OTP with erlang.mk

### ISSUE THREAD

**Issue by benjamin-bergia** [ninenines/erlang.mk#712]
I recently had issues working on the same project from different machines and I wonder if we could use erlang.mk to fetch and manage the runtime for each project. This way we could keep different versions of Erlang/OTP for different projects and don't depend on the user to set his own system.

I noticed that kerl is already used in the the `ci` plugin but didn't find much info regarding this plugin

**Comment by essen** [comment]
Yeah I still need to document. Basically you specify which OTP versions you want to use for CI testing and then when you run `make ci -k` it will build and use all these versions (the `-k` flag will run all versions even if one fails). Cowboy uses it if you want an example, but it's really simple.

I have long wanted to allow users to specify an exact OTP version to be used for a project. I probably wrote about it in a ticket somewhere. I don't require it personally so that's why it's still not done, but if you're willing to be the guinea pig I can probably cook up something next week for you to try.

**Comment by benjamin-bergia** [comment]
I will take a look into Cowboy config.

Thanks, that would be really cool.
If you need some help to write doc/tests/other let me know.

**Comment by essen** [comment]
So switching to an already compiled Erlang/OTP is not too difficult. Compiling it a little more, I'll have to scour the Make documentation again for a way to do it that covers all cases.

**Comment by essen** [comment]
Oh well I probably have a solution already. :-) The old "write it to figure it out"

**Comment by essen** [comment]
Check the most recent commit, experiment and tell me what you think.

b908a7a79aea70f3e7226570f243a99643b55cdd

**Comment by benjamin-bergia** [comment]
Thanks.

I am still trying to get it to work. For some reasons the git clone fails. I replaced the `git clone` by `curl` and I get the same issue. When running the `git clone` / `curl` manually there is no issue.

> make: erlang.mk:66: pipe: Too many open files
> make: erlang.mk:84: pipe: Too many open files
> erlang.mk:87: *** Unable to detect platform. Please open a ticket with the output of uname -a..  Stop.
> Cloning into '/home/user/test/.erlang.mk/kerl'...
> fatal: unable to access 'https://github.com/kerl/kerl/': Problem with the SSL CA cert (path? access rights?)
> make: *** [/home/user/test/.erlang.mk/kerl/kerl] Error 128
> fatal: destination path '/home/user/test/.erlang.mk/kerl' already exists and is not an empty directory.


One thing is that if the download fails, like in my case, you will get this error
> make: *** [/home/user/test/.erlang.mk/kerl/kerl] Error 128
> fatal: destination path '/home/user/test/.erlang.mk/kerl' already exists and is not an empty directory.

And it will loop forever. I was expecting it to just fail and stop.

**Comment by benjamin-bergia** [comment]
By the way my `uname -s` returns `Linux` which should work fine.

**Comment by essen** [comment]
I suspect your issue comes from this "too many open files" warning. Can you try increasing the limit and see if it helps?

**Comment by benjamin-bergia** [comment]
So I gave a try with 4096, 8192, 16384 still the same error it just takes longer to show up.
At 32768 I changes to

> make: erlang.mk:66: fork: Resource temporarily unavailable
erlang.mk:87: *** Unable to detect platform. Please open a ticket with the output of uname -a..  Stop.
make: erlang.mk:5274: fork: Resource temporarily unavailable
/bin/sh: fork: retry: No child processes
make: erlang.mk:5274: fork: Resource temporarily unavailable
make: erlang.mk:5274: fork: Resource temporarily unavailable
/bin/sh: fork: retry: No child processes
fatal: destination path '/home/user/test/.erlang.mk/kerl' already exists and is not an empty directory.
make: *** [/home/user/test/.erlang.mk/kerl/kerl] Error 128
make: erlang.mk:4947: fork: Resource temporarily unavailable
make: erlang.mk:5274: fork: Resource temporarily unavailable
make: fork: Resource temporarily unavailable
make: erlang.mk:5274: fork: Resource temporarily unavailable
/bin/sh: fork: retry: No child processes
/bin/sh: fork: retry: No child processes
/bin/sh: fork: retry: No child processes
fatal: destination path '/home/user/test/.erlang.mk/kerl' already exists and is not an empty directory.
make: *** [/home/user/test/.erlang.mk/kerl/kerl] Error 128
make: erlang.mk:5274: fork: Resource temporarily unavailable
/bin/sh: fork: retry: Resource temporarily unavailable

Apparently `ps` show 9000 or so 'make /home/user/erlang/20.0` and keep increasing until it fails
Looks like this line https://github.com/ninenines/erlang.mk/commit/b908a7a79aea70f3e7226570f243a99643b55cdd#diff-fa8602c3d98b1df5613e8eba758ae1cfR74 is running in a loop.

**Comment by essen** [comment]
OK let me add a safeguard then... I'll get back to you.

**Comment by essen** [comment]
I've pushed a commit that I'm hoping will fix your issue. Please give it a try!

**Comment by benjamin-bergia** [comment]
It does fix the issue.
Unfortunately I am not able to the build otp. 
I can manually run `KERL_DEFAULT_INSTALL_DIR=../erlang .erlang.mk/kerl/kerl build git https://github.com/erlang/otp.git OTP-20.0.2 OTP-20.0.2` and it works.

But when adding `ERLANG_OTP = OTP-20.0.2` and `KERL_INSTALL_DIR = ../erlang` to my Makefile and running `make`, I get:

> Building Erlang/OTP OTP-20.0.2... Please wait...
make: *** [../erlang/OTP-20.0.2] Error 1
 DEPEND test.d
Building Erlang/OTP OTP-20.0.2... Please wait...
make[1]: *** [../erlang/OTP-20.0.2] Error 1
 ERLC   test_app.erl test_sup.erl
 APP    test

I am still trying to get more information about the issue

**Comment by benjamin-bergia** [comment]
Just out of curiosity, `kerl_otp_target` doesn't output anything.
Is it due to the way it is called (`$(eval $(call ...`) ?

Is there any way for me to get the output of the kerl calls in `kerl_otp_target` ?

**Comment by essen** [comment]
The eval is just there to add a dynamically generated rule to the Makefile. The output is not there because the build is called via `$(shell ...)`, it would probably be better with output, I'll check if there's a better way.

As for your issue, I'll try again and see... :-)

**Comment by crownedgrouse** [comment]
I tried the feature (great !) and get same issue than benjamin. BTW I did not see ~/erlang/{version} been created at all.

**Comment by essen** [comment]
OK I have pushed it again. It should work better, and if not, it'll print what it's doing and I'll have a clearer idea of what's going on. Try again, thanks!

**Comment by crownedgrouse** [comment]
works now, but issue was maybe that I wrongly set ERLANG_OTP = 19.3   instead OTP-19.3 . The log output gave me clue that the issue was the unknown erlang git tag.

**Comment by essen** [comment]
Ah then you probably did not have the same issue as his version is correct. But I'll look into providing a better error if necessary.

**Comment by crownedgrouse** [comment]
documentation will need a warning regarding erlang tags format, too :  OTP**_**R16B03  but OTP**-**19.3 . 
other question : Is CI target usable as well ?

**Comment by essen** [comment]
Right. Yes I've been using `make ci -k` for maybe a year now? It works really well.

**Comment by benjamin-bergia** [comment]
Seems alright now

> Building Erlang/OTP OTP-20.0.2... Please wait...
>  GEN    /home/user/test/.erlang.mk/kerl/kerl
> Cloning into '/home/user/test/.erlang.mk/kerl'...
> remote: Counting objects: 10, done.
> remote: Compressing objects: 100% (7/7), done.
> remote: Total 10 (delta 0), reused 6 (delta 0), pack-reused 0
> Unpacking objects: 100% (10/10), done.
> Checking connectivity... done.
> Already on 'master'
> Your branch is up-to-date with 'origin/master'.
> MAKEFLAGS="" /home/user/test/.erlang.mk/kerl/kerl build git https://github.com/erlang/otp OTP-20.0.2 > OTP-20.0.2
> Checking Erlang/OTP git repository from https://github.com/erlang/otp...
> Building Erlang/OTP OTP-20.0.2 from git, please wait...
> APPLICATIONS DISABLED (See: /home/user/.kerl/builds/OTP-20.0.2/otp_build_git.log)
>  * jinterface     : No Java compiler found
>  * odbc           : ODBC library - link check failed
> 
> DOCUMENTATION INFORMATION (See: /home/user/.kerl/builds/OTP-20.0.2/otp_build_git.log)
>  * documentation  : 
>  * fop is missing.
>  *  Using fakefop to generate placeholder PDF files.
> 
> Erlang/OTP OTP-20.0.2 from git has been successfully built
> /home/user/test/.erlang.mk/kerl/kerl install OTP-20.0.2 ../erlang/OTP-20.0.2
> Installing Erlang/OTP git (OTP-20.0.2) in /home/user/erlang/OTP-20.0.2...
> You can activate this installation running the following command:
> . /home/user/erlang/OTP-20.0.2/activate
> Later on, you can leave the installation typing:
> kerl_deactivate

Should we use the project directory as the default directory for `KERL_BASE_DIR` and `KERL_CONFIG` to keep the whole project self-contained ?

**Comment by essen** [comment]
I would rather not change defaults, one could easily set these themselves if they need it.

**Comment by benjamin-bergia** [comment]
Understood. I will keep using it for few days see if I get in any issues.

**Comment by benjamin-bergia** [comment]
Currently make is installing OTP but after that, activation is still needed in order to it to the `PATH`.

I guess if a user specify `KERL_INSTALL_DIR` and `ERLANG_OTP` he or she doesn't intend to use it  for this specific project, (but maybe not system wide). Could we add `${KERL_INSTALL_DIR}/${ERLANG_OTP}/bin` to the `PATH` used by make and maybe avoid running the `activate` script.

**Comment by essen** [comment]
We already do. https://github.com/ninenines/erlang.mk/blob/master/core/kerl.mk#L56

**Comment by benjamin-bergia** [comment]
Is the PATH supposed to be updated every time I run make ? 
Currently, if I start a new shell and run `make run` it will not work.
I have to run the activate script in each new shell.

**Comment by essen** [comment]
Curious, I'm not seeing this. What's your Makefile/environment for these values?

**Comment by benjamin-bergia** [comment]
I created an empty project to test.
Makefile
```
PROJECT = test
PROJECT_DESCRIPTION = New project
PROJECT_VERSION = 0.1.0

ERLANG_OTP = OTP-20.0.2
KERL_INSTALL_DIR = ./erlang

include erlang.mk
```
Building
```
~/test$ make 
Building Erlang/OTP OTP-20.0.2... Please wait...
MAKEFLAGS="" /home/user/test/.erlang.mk/kerl/kerl build git https://github.com/erlang/otp OTP-20.0.2 OTP-20.0.2
Checking Erlang/OTP git repository from https://github.com/erlang/otp...
Building Erlang/OTP OTP-20.0.2 from git, please wait...
APPLICATIONS DISABLED (See: /home/user/.kerl/builds/OTP-20.0.2/otp_build_git.log)
 * jinterface     : No Java compiler found
 * odbc           : ODBC library - link check failed

DOCUMENTATION INFORMATION (See:  /home/user/.kerl/builds/OTP-20.0.2/otp_build_git.log)
 * documentation  : 
 *                  fop is missing.
 *                  Using fakefop to generate placeholder PDF files.



Erlang/OTP OTP-20.0.2 from git has been successfully built
 /home/user/test/.erlang.mk/kerl/kerl install OTP-20.0.2 ./erlang/OTP-20.0.2
Installing Erlang/OTP git (OTP-20.0.2) in  /home/user/test/erlang/OTP-20.0.2...
You can activate this installation running the following command:
. /home/user/test/erlang/OTP-20.0.2/activate
Later on, you can leave the installation typing:
kerl_deactivate
 DEPEND test.d
 ERLC   test_app.erl test_sup.erl
 APP    test
```
And the env (part of it) after building
```
HOSTNAME=mycomputer
SHELL=/bin/bash
PWD=/home/user/test
HOME=/home/user
USERNAME=user
PATH=/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/user/.local/bin:/home/user/bin
LANG=en_US.UTF-8
MODULEPATH=/etc/scl/modulefiles:/usr/share/Modules/modulefiles:/etc/modulefiles:/usr/share/modulefiles
LOADEDMODULES=
MODULESHOME=/usr/share/Modules
BASH_FUNC_module()=() {  eval `/usr/bin/modulecmd bash $*`
}
BASH_FUNC_scl()=() {  local CMD=$1;
 if [ "$CMD" = "load" -o "$CMD" = "unload" ]; then
 eval "module $@";
 else
 /usr/bin/scl "$@";
 fi
}
SHLVL=2
OLDPWD=/home/user
_=/usr/bin/env
```
Sorry I had to remove few things from the env output.

**Comment by essen** [comment]
Does it work if you do `KERL_INSTALL_DIR = $(CURDIR)/erlang` instead? I'm guessing the `./` is to blame.

**Comment by benjamin-bergia** [comment]
Yeah seems to to work.

**Comment by essen** [comment]
Right then I'll have to be careful to document this too. Cheers.

**Comment by benjamin-bergia** [comment]
Just converted one of my projects to use the new erlang.mk. I had errors about the erl command. I managed to get it work by changing:
```
ERL = erl +A0 -noinput -boot start_clean
```
to
```
ifneq ($(strip $(ERLANG_OTP)),)
ERL = $(KERL_INSTALL_DIR)/$(ERLANG_OTP)/bin/erl +A0 -noinput -boot start_clean
else
ERL = erl +A0 -noinput -boot start_clean
endif
```

Sorry it's pretty ugly, hopefully you can come up with something a more elegant.

**Comment by essen** [comment]
It shouldn't be needed because we set the PATH, though. Unless there's a command that runs before we do. What's the error you got?

**Comment by crownedgrouse** [comment]
For relative  path  in `KERL_INSTALL_DIR`  it might be better to always apply `$(realpath names…)`  on it instead write a warning in documentation ?

**Comment by essen** [comment]
Not sure it's worth it.

**Comment by benjamin-bergia** [comment]
Unfortunately, it looks like the erl command is evaluated before everything else

```
/home/user/myapp$ make run V=3
/bin/sh: erl: command not found
Database already running
rm -f /home/user/myapp/.erlang.mk/deps.log
rm -f /home/user/myapp/.erlang.mk/apps.log
mkdir -p //home/user/myapp/.erlang.mk
set -e; for dep in  ; do \
	mkdir -p $dep/ebin; \
done
set -e; for dep in  ; do \
	if grep -qs ^$dep$ /home/user/myapp/.erlang.mk/apps.log; then \
		:; \
	else \
		echo $dep >> /home/user/myapp/.erlang.mk/apps.log; \
		make -C $dep IS_APP=1; \
	fi \
done
```

The `Database already running` is from one of my targets that I included in `run::`.

**Comment by essen** [comment]
Probably the `RELX_REL` variable creation then.

It looks like adding `SHELL := env PATH=$(PATH) $(SHELL)` after defining PATH is the way to go.

**Comment by essen** [comment]
I have pushed that. Please try it. :-)

**Comment by benjamin-bergia** [comment]
Sorry for the troubles...

```
/home/user/myapp$ make run
make: env PATH=/home/user/myapp/erlang/OTP-20.0.2/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/user/.local/bin:/home/user/bin /bin/sh: Command not found
database/Makefile:14: recipe for target 'start_instance' failed
make: *** [start_instance] Error 127
```

But I can run the command manually:
```
/home/user/myapp$ env PATH=/home/user/myapp/erlang/OTP-20.0.2/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/user/.local/bin:/home/user/bin /bin/sh
sh-4.3$ echo $PATH
home/user/myapp/erlang/OTP-20.0.2/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/user/.local/bin:/home/user/bin
```

Ok so I just found out. With this new change, using `.ONESHELL:` causes the error above.

**Comment by essen** [comment]
Sigh... OK I'll take a look again.

**Comment by benjamin-bergia** [comment]
Honestly I don't know if it is worth the troubles. You don't seem to be using `.ONESHELL:` anywhere and I can easily do without it. Your call

**Comment by essen** [comment]
I'll leave it aside for now and add a note to the documentation then.

**Comment by benjamin-bergia** [comment]
Ok thanks.
This addition of KERL is really great, I can now just run git clone + make in my CI runner on gitlab.
The last little thing I am trying to improve is being able to pass any KERL_* variable in my Makefile.
I will update my PR if I can get it to work.

**Comment by essen** [comment]
Export them.

`export KERL_THING := this`

That's all!

**Comment by benjamin-bergia** [comment]
Didn't think about it, in this case I can close my PR. It is not needed.

**Comment by crownedgrouse** [comment]
tried `ci` target ok. reminder : still a 'placeholder' chapter in documentation. that's the reason intially why I was wondering if it was working.

**Comment by essen** [comment]
I will document both this and ci today.

**Comment by essen** [comment]
* This: https://erlang.mk/guide/kerl.html
* CI: https://erlang.mk/guide/ci.html

I believe we're done here! Thanks for the help!
