### ISSUE TITLE
erlang.mk cannot use package indexes of dependent packages

### ISSUE THREAD

**Issue by KrzysiekJ** [ninenines/erlang.mk#713]
Let’s say we have an erlang.mk package `foo` which has `bar` as a dependency and that `bar` depends on `baz`. Let’s also say that `foo` has erlang.mk built without `index/*` and `core/index` modules. Then `make app` in `foo` fails on installing `baz` because the package is unknown to `foo`, despite it being a dependency of `bar`.

I know that commenting out core modules is discouraged, so it may not be even a bug, though it would be handy if bundling package index into every erlang.mk project was not necessary.

**Comment by essen** [comment]
Yeah I don't disagree. I do think it's a bug. I want to go toward another solution eventually.

**Comment by essen** [comment]
The long term plan is to use hex for packages so I'll be closing this. Just waiting for the hex_erl project to get to the point where packages can be published.
