### ISSUE TITLE
Run command before make run and make tests

### ISSUE THREAD

**Issue by benjamin-bergia** [ninenines/erlang.mk#714]
What would be the recommend way to run some shell commands before every make run/tests ?
I find myself starting dependencies such as database and cache instance before running or testing my project.

**Comment by essen** [comment]
You can add more commands to some targets, for example:

```
tests::
    start_db

include erlang.mk
```

If it's placed before it'll run before, after/after. All targets in Erlang.mk that have the two colons `::` can be extended like this.

**Comment by benjamin-bergia** [comment]
Cool exactly what I wanted. I will take a look into it

**Comment by benjamin-bergia** [comment]
@essen I just noticed that the run target doesn't have two colons. I updated my erlang.mk to add a second colon and I tested with a `run::` before and after the include. Both seem to work. Can I open a PR to update the `run` target ? 

If yes do you need additional tests for it ?
