### ISSUE TITLE
`git` should be always called with a `C` locale

### ISSUE THREAD

**Issue by binarin** [ninenines/erlang.mk#720]
This simple Makefile fails to fetch dependencies on my machine as my default locate is `ru_RU.UTF-8`, and detached HEAD message looks like `(HEAD отделён на rabbitmq_v3_6_9)`

    PROJECT = amqp_test
    PROJECT_DESCRIPTION = New project
    PROJECT_VERSION = 0.1.0

    DEPS = amqp_client

    dep_amqp_client_commit = rabbitmq_v3_6_9
    dep_rabbit_common_commit = rabbitmq_v3_6_9
    dep_rabbitmq_codegen = rabbitmq_v3_6_9

    include erlang.mk

So I need to do `LANG=C make` to fetch the deps. But it'd be better if `erlang.mk` will always call `git` with `LANG=C`.

**Comment by essen** [comment]
Sounds reasonable, curious what error you get though? I don't think we check the HEAD messages.

**Comment by binarin** [comment]
Here it is:

     DEP    amqp_client
    make[1]: вход в каталог «/home/binarin/personal-workspace/amqp_test/deps/amqp_client»
    /bin/sh: -c: строка 0: синтаксическая ошибка рядом с неожиданным маркером «(»
    /bin/sh: -c: строка 0: `echo " DEP   " rabbit_common;   fetch_url1='https://github.com/rabbitmq/rabbitmq-common.git'; fetch_url2='https://github.com/rabbitmq/rabbitmq-common.git'; if test "$fetch_url1" != 'https://github.com/rabbitmq/rabbitmq-erlang-client.git' && git clone -q -n -- "$fetch_url1" /home/binarin/personal-workspace/amqp_test/deps/rabbit_common; then fetch_url="$fetch_url1"; push_url='https://github.com/rabbitmq/rabbitmq-common.git'; elif git clone -q -n -- "$fetch_url2" /home/binarin/personal-workspace/amqp_test/deps/rabbit_common; then fetch_url="$fetch_url2"; push_url='git@github.com:rabbitmq/rabbitmq-common.git'; fi; cd /home/binarin/personal-workspace/amqp_test/deps/rabbit_common && (  git checkout -q (HEAD >/dev/null 2>&1 ||   git checkout -q отделён >/dev/null 2>&1 ||   git checkout -q на >/dev/null 2>&1 ||   git checkout -q rabbitmq_v3_6_11) >/dev/null 2>&1 ||   git checkout -q master >/dev/null 2>&1 ||   git checkout -q master >/dev/null 2>&1 ||  (echo "error: no valid pathspec among:  (HEAD отделён на rabbitmq_v3_6_11) master master" 1>&2 && false) ) && (test "$fetch_url" = "$push_url" || git remote set-url --push origin "$push_url")'
    make[1]: *** Нет правила для сборки цели «/home/binarin/personal-workspace/amqp_test/deps/rabbit_common», требуемой для «deps».  Останов.
    make[1]: выход из каталога «/home/binarin/personal-workspace/amqp_test/deps/amqp_client»
    make: *** [erlang.mk:4223: deps] Ошибка 2

**Comment by binarin** [comment]
I think there is some magic that prevents following from happening on detached head when C locale is being used (note that `(` in the first command):

    git checkout -q (HEAD >/dev/null 2>&1 || 
    git checkout -q отделён >/dev/null 2>&1 || 
    git checkout -q на >/dev/null 2>&1 ||   
    git checkout -q rabbitmq_v3_6_11)

**Comment by essen** [comment]
Ah it must be something RabbitMQ does then, fair enough. Patch welcome, you got the environment to test it after all. :-)

**Comment by essen** [comment]
Yes this command is from RabbitMQ though so nothing I can do (not today at least).

**Comment by binarin** [comment]
Should be fixed by https://github.com/rabbitmq/rabbitmq-common/pull/219

**Comment by essen** [comment]
Cheers!
