### ISSUE TITLE
erlang.mk tries to compile c_src before building dependencies

### ISSUE THREAD

**Issue by imgrey** [ninenines/erlang.mk#734]
Hello

I have a port implementation written in C, that is in c_src.
erlang.mk fails to build it, as it requires libBERT, that is listed in dependencies.

**Comment by essen** [comment]
Is it listed as a DEPS or BUILD_DEPS? I have no problem doing this with the latter: https://github.com/rabbitmq/lz4-erlang/blob/master/Makefile

**Comment by imgrey** [comment]
DEPS = bert cowboy erlydtl jsx p1_utils
BUILD_DEPS = bert  # that one is required for building c_src
LOCAL_DEPS = inets xmerl

dep_cowboy_commit = 2.0.0-rc.4
dep_bert = git https://github.com/postmodern/libBERT master
dep_p1_utils = git https://github.com/processone/eimp master

**Comment by essen** [comment]
You can't have bert in both DEPS and BUILD_DEPS. What's bert? Is it a C library?

**Comment by imgrey** [comment]
libBERT: https://github.com/postmodern/libBERT

**Comment by essen** [comment]
You'll have to provide more details. I do have code and tests that depend on C libraries and can build just fine so the problem is most likely somewhere else.

**Comment by imgrey** [comment]
% cat Makefile

DEPS = bert cowboy erlydtl jsx p1_utils
LOCAL_DEPS = inets xmerl

dep_cowboy_commit = 2.0.0-rc.4
dep_bert = git https://github.com/postmodern/libBERT master
dep_p1_utils = git https://github.com/processone/eimp master

include erlang.mk


% rm -rf deps/bert
% make
 DEP    bert
make[1]: Entering directory '/home/user/src/middleware/deps/bert'
 DEPEND bert.d
 APP    bert
make[1]: Leaving directory '/home/user/src/middleware/deps/bert'
make[1]: Entering directory '/home/user/src/middleware/deps/cowboy'
make[2]: Entering directory '/home/user/src/middleware/deps/cowlib'
make[2]: Leaving directory '/home/user/src/middleware/deps/cowlib'
make[2]: Entering directory '/home/user/src/middleware/deps/ranch'
make[2]: Leaving directory '/home/user/src/middleware/deps/ranch'
 GEN    rebar.config
make[1]: Leaving directory '/home/user/src/middleware/deps/cowboy'
make[1]: Entering directory '/home/user/src/middleware/deps/erlydtl'
make[1]: Leaving directory '/home/user/src/middleware/deps/erlydtl'
make[1]: Entering directory '/home/user/src/middleware/deps/jsx'
make[1]: Leaving directory '/home/user/src/middleware/deps/jsx'
make[1]: Entering directory '/home/user/src/middleware/deps/p1_utils'
make -f c_src/Makefile.erlang.mk
make[2]: Entering directory '/home/user/src/middleware/deps/p1_utils'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/user/src/middleware/deps/p1_utils'
make[1]: Leaving directory '/home/user/src/middleware/deps/p1_utils'
 DEPEND middleware.d
 ERLC   action_log.erl base16.erl bert.erl copy_handler.erl delete_handler.erl ec_date.erl erlcloud_http.erl erlcloud_xml.erl first_page_handler.erl img.erl img_app.erl img_sup.erl img_worker.erl js_handler.erl keystone_api.erl list_handler.erl middleware_app.erl middleware_sup.erl mkdir_handler.erl move_handler.erl object_handler.erl riak_api.erl riak_crypto.erl search_handler.erl slughifi.erl solr_api.erl upload_handler.erl utils.erl
 APP    middleware
make -C /home/user/src/middleware/c_src
make[1]: Entering directory '/home/user/src/middleware/c_src'
Compiling image manupulation plugin..
cc `pkg-config --cflags MagickWand` -c -O2 -Wall -g -Wall -fPIC -MMD -I../deps/bert/include img.c -o img.o
In file included from ../deps/bert/include/bert/data.h:8:0,
                 from ../deps/bert/include/bert/encoder.h:5,
                 from img.c:6:
../deps/bert/include/bert/regex.h:4:10: fatal error: bert/config.h: No such file or directory
 #include <bert/config.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
Makefile:7: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/home/user/src/middleware/c_src'
erlang.mk:5932: recipe for target 'app-c_src' failed
make: *** [app-c_src] Error 2

**Comment by essen** [comment]
Right. Well cmake is not supported at this time. Erlang.mk currently requires dependencies to have a Makefile, makefile or GNUmakefile file in order to be built.

Sorry if I'm a bit slow today, been sick.
