### ISSUE TITLE
erlang.mk basic usage

### ISSUE THREAD

**Issue by ssow** [ninenines/erlang.mk#739]
Hi,

What are the statements required to compile a butch of .erl files in the src without generating the .app file (my project is not an otp compliant one) ?
I get the following error "erlang.mk:4932: recipe for target 'app' failed"

**Comment by essen** [comment]
Look at the getting started chapter, all you should need is the PROJECT variable set. https://erlang.mk/guide/getting_started.html

**Comment by ssow** [comment]
I did that.

**Comment by essen** [comment]
Then you might want to provide the complete error because what you get is not enough to figure things out.

**Comment by ssow** [comment]
make LEGACY=0
 DEPEND nnbase.d
 ERLC   simplest_nn.erl
compile: warnings being treated as errors
src/simplest_nn.erl:7: export_all flag enabled - all functions will be exported
erlang.mk:5141: recipe for target 'ebin/nnbase.app' failed
make[1]: *** [ebin/nnbase.app] Error 1
erlang.mk:4932: recipe for target 'app' failed
make: *** [app] Error 2

**Comment by essen** [comment]
It tells you that warnings are treated as errors and then gives you a warning about export_all which is in turn treated as error. Either remove export_all or configure `ERLC_OPTS` so that warnings are no longer treated as error.

**Comment by ssow** [comment]
Thank you for the error output translation. It was not obvious to understand the collation between the warning treated as error and the failed recipe.

**Comment by essen** [comment]
Yep. Nothing I can do about that, they're coming from the Erlang compiler itself.
