### ISSUE TITLE
ASN.1 with 'maps' option not supported

### ISSUE THREAD

**Issue by vanrein** [ninenines/erlang.mk#743]
When compiling ASN.1 with the `+maps` option, no .hrl is produced.  This is currently unacceptable to Erlang.mk.

I plunged in and tried to fix core/erlc's compile_asn1 with
```
$(verbose) $(foreach HRL,$(wildcard asn1/*.hrl),mv $(HRL) include/;)
```
but I cannot get it to work.  A second run works, so it is appears to be a matter of when the `$(wildcard asn1/*.hrl)` is expanded.  I tried indirectly, with another macro, also didn't work.  This is where my knowledge of GNU Make ends, I fear... all I can do is report the problem.

**Comment by essen** [comment]
Can you copy the `asn1` test in `test/core_app.mk` and create a new test called `asn1-maps` that uses this option and submit a PR showing the failure? I can then take a look. Not too familiar with ASN1.

**Comment by essen** [comment]
I've fixed this in my local copy and that will be pushed later today. Thanks!
