### ISSUE TITLE
tar: Error opening archive: Failed to open '.../.erlang.mk/hex/...

### ISSUE THREAD

**Issue by peffis** [ninenines/erlang.mk#747]
Hi, 

Without modifying any code in a repo, a nightly build that used to build fine has all of a sudden started failing with errors like the following: 

```
tar: Error opening archive: Failed to open '.../.erlang.mk/hex/lager.tar'
 DEP    jsx
tar: Error opening archive: Failed to open '/.../.erlang.mk/hex/jsx.tar'
 DEP    ranch
tar: Error opening archive: Failed to open '.../.erlang.mk/hex/ranch.tar'
 DEP    ranch_proxy_protocol
tar: Error opening archive: Failed to open '/.../.erlang.mk/hex/ranch_proxy_protocol.tar'
 DEP    recon
tar: Error opening archive: Failed to open '.../.erlang.mk/hex/recon.tar'
```

, where ... is the folder of my project. 

The Makefile for this project is very simple. It has one dependency to amqp_client and looks like this: 
```
PROJECT = mq
PROJECT_DESCRIPTION = Rabbit Message queue conveniance lib
PROJECT_VERSION = 0.0.1

DEPS = amqp_client

include erlang.mk
```

Any thoughts on why this has started to fail all of a sudden? And these tar files in the hex folder. Should they come from some external repository perhaps and that repository has changed its structure, or? If so, can I instead make the build actually build the packages by itself rather than relying on a prebuilt package?

**Comment by peffis** [comment]
I changed the Makefile now to 
```
PROJECT = mq
PROJECT_DESCRIPTION = Rabbit Message queue conveniance lib
PROJECT_VERSION = 0.0.1

DEPS = amqp_client
dep_amqp_client = git https://github.com/jbrisbin/amqp_client master
include erlang.mk
```

, which I guess will build the code rather than relying on a tar file. But I'm still curious about the reason why the old build stopped working. Is it simply that the archive for amqp_client went missing all of a sudden?

**Comment by essen** [comment]
Looks like they changed the hex.pm packages location https://github.com/ninenines/erlang.mk/pull/748

I'll merge the change after some breakfast.

**Comment by essen** [comment]
This has been fixed. Update erlang.mk using `make erlang-mk` and it should work again. Thanks!

**Comment by peffis** [comment]
Thank you! Great work!

**Comment by BadriRamesh** [comment]
Hi 
I am trying to build the Rabbitmq source code, but download the dependencies by executing the command "**make deps**" are failed with below error.

**tar: /home/z003z7wp/rabbitmq-server-release/.erlang.mk/hex/lager.tar: Cannot open: No such file or directory**

and i have also tried **make erlang-mk** command but same error is throwing, please find attached text file for detailed information.


[Rabbitmq_build_error.txt](https://github.com/ninenines/erlang.mk/files/3054344/Rabbitmq_build_error.txt)

Can you please help me to resolve this issue ?
Thanks in advance.

**Comment by essen** [comment]
Can you try again with `make deps V=1` instead? Maybe a more informative error was hidden.

**Comment by BadriRamesh** [comment]
Hi Essen,

 I have tried by run the cmd :  **make deps V=1** and please find the attached test file for more information .
Please help me to resolve it.


[RMQ_Build_Error_log.txt](https://github.com/ninenines/erlang.mk/files/3058605/RMQ_Build_Error_log.txt)

Best Regards,
Badri.

**Comment by essen** [comment]
You have a timeout on trying to fetch `https://repo.hex.pm/tarballs/lager-3.6.5.tar`, maybe a firewall or something?

Also you'll need to install Elixir or you will experience failures later on.

**Comment by BadriRamesh** [comment]
Hi Essen,
 Thanks for the update, Yes it was a firewall issue, the error is resolved now and one more error occured while building the code
I am using Rabbitmq 3.7.12 and Erlang 21.3 versions and when i run **make deps** command below error thorwn

**c:/tools/msys64/home/z003z7wp/rabbitmq-server-release/deps/rabbitmq_aws/include/rabbitmq_aws.hrl:75: type ssl_option() undefined
src/rabbitmq_aws.erl:400: type path() undefined
make[3]: *** [erlang.mk:5177: ebin/rabbitmq_aws.app] Error 1
make[2]: *** [erlang.mk:4967: app] Error 2
make[2]: Leaving directory '/home/z003z7wp/rabbitmq-server-release/deps/rabbitmq_aws'
make[1]: *** [erlang.mk:4322: deps] Error 2
make[1]: Leaving directory '/home/z003z7wp/rabbitmq-server-release/deps/rabbitmq_peer_discovery_aws'
make: *** [erlang.mk:4322: deps] Error 2**

-- i have found similar issue(Bug ID : 680736) here: https://gentoobrowse.randomdan.homeip.net/packages/net-misc/rabbitmq-server

Please help me

Thanks.

**Comment by essen** [comment]
At this point this is a question better asked to the RabbitMQ people I think.

**Comment by BadriRamesh** [comment]
Sure essen, Thanks for you support
  -- I will do ask to The RabbitMQ Team.

Thanks a lot :)
