### ISSUE TITLE
Use --depth in erlang.mk, git clone command to speed up download.

### ISSUE THREAD

**Issue by aknrdureegaesr** [ninenines/erlang.mk#750]
The current `erlang.mk` as obtained from [https://erlang.mk/erlang.mk](https://erlang.mk/erlang.mk)  clones the entire erlang.mk repo, including all its history, uses it for one call, and then deletes the whole repo.

Using the switch `--depth 1` considerably speeds this up, as not the entire history is downloaded.

**Comment by essen** [comment]
True. Also for `make erlang-mk` I suppose.

**Comment by aknrdureegaesr** [comment]
Ah yes. You and `grep` tells me you do this in more than one place. - Changed my pull request #751 .

**Comment by essen** [comment]
Done, thanks!
