### ISSUE TITLE
Runtime dependency but not Erlang application

### ISSUE THREAD

**Issue by sammyraul** [ninenines/erlang.mk#752]
I wanted to include a library from which some of the functions will be used. The BULD_DEPS is for buidling compile time dependency and it will not work in my case. If I add the library to DEPS then it will try to start the application but the library is not an Erlang application. How can such a library be included?
With BUILD_DPES when I run my application the functions are undefined.

Thanks.

**Comment by essen** [comment]
What do you mean by "not an Erlang application"?

**Comment by sammyraul** [comment]
What I mean was does not have -behaviour(application) anywhere defined. Basically the question is how to include an external module of course I can copy the external module in my src directory and all works. Is there any other way I can do  this using Makefile.

**Comment by essen** [comment]
There's two types of application in Erlang, those with the application behavior (for example cowboy), and those without (for example cowlib). If you just have plain modules then do the latter, it works the same except it doesn't use this behavior nor does it have a supervisor.

**Comment by sammyraul** [comment]
The only problem is when I include this in DEPS, it tries to start it as an application and since start() is not defined, my application does not start and fails

**Comment by essen** [comment]
There's no need for a start() to be defined, whatever that means. `application:start/1` works on all types of applications, it just doesn't use the application behavior if there are none.

It would help if you could show the code in question then I could point out where your error lies.

**Comment by sammyraul** [comment]
```
DEPS = cowboy lager qrcode
dep_cowboy_commit = 2.2.2
dep_lager_commit = 3.6.1
dep_qrcode= master

```
When I do make run it crashes with

```
application: qrcode
    exited: {bad_return,
                {{qrcode,start,[normal,[]]},
                 {'EXIT',
                     {undef,
                         [{qrcode,start,[normal,[]],[]},
                          {application_master,start_it_old,4,
                              [{file,"application_master.erl"},
                               {line,273}]}]}}}}

```
Removing qrcode from DEPS works without problem, not sure what I do in my Makefile

**Comment by essen** [comment]
You probably want `dep_qrcode_commit = master` instead of the line you got there.

And if that's not enough please link to `qrcode` so I can take a look.

**Comment by sammyraul** [comment]
[](https://github.com/komone/qrcode)

Same problem with dep_qrcode_commit = master

**Comment by essen** [comment]
Well it's because this application is incorrect, it has this line in the .app file: https://github.com/komone/qrcode/blob/master/ebin/qrcode.app#L5

And this line is the one that informs Erlang that there is an application behavior, which is clearly missing. No choice there unfortunately, you have to fork and fix the dependency.

Cheers.

**Comment by essen** [comment]
The fix is just to remove the line in question.

**Comment by sammyraul** [comment]
Thanks Essen
