### ISSUE TITLE
Q: How to run dialyzer in beam analysis mode to produce warning with full path

### ISSUE THREAD

**Issue by stchar** [ninenines/erlang.mk#754]
I found a strange behavior of dialyzer when I was running `dialyzer --fullpath -r ebin` in my application. 
I expected to get full path of erl files in warning messages however I got only relative path like `src/mymodule.erl` 

It looks like dialyzer just reads the `file` attribute of abstract code and pass it to the warning message formatter. 

If you compile a module with `erlc +debug_info ... ` then abstract code of this beam file will contain `file` attribute with the path of `.erl` file relative to the folder where you call erlc

I'm not sure if it's a bug of erlc but the question is how can I compile my sources to have full path in AST?

There is a `compile_erl` macro in `core/erlc.mk` I guess I can override it however i'm not sure with what.

**Comment by essen** [comment]
Let's try.

Replace

```
... $(filter-out $(ERLC_EXCLUDE_PATHS),$(COMPILE_FIRST_PATHS) $(1))
```

with

```
... $(realpath $(filter-out $(ERLC_EXCLUDE_PATHS),$(COMPILE_FIRST_PATHS) $(1)))
```

**Comment by stchar** [comment]
Full path to sources does't solve it. AST still contain the relative path to the app folder
  
I tried to play around with it. Looks only following chunk works:
```make
define compile_erl
	cd /var/tmp; \
	$(erlc_verbose) erlc -v $(if $(IS_DEP),$(filter-out -Werror,$(ERLC_OPTS)),$(ERLC_OPTS)) -o $(realpath ebin/) \
		-pa $(realpath ebin/) -I $(realpath include/) $(realpath $(filter-out $(ERLC_EXCLUDE_PATHS),$(COMPILE_FIRST_PATHS) $(1)))
endef
```
 my git repository is in /home,  `cd /var/tmp` is needed to force erlc to use full path. This is weird =)

**Comment by essen** [comment]
Hm maybe realpath doesn't give the full path. Try

```
$(addprefix $(CURDIR),$(realpath ...))
```

**Comment by stchar** [comment]
it does
```
cd /var/tmp;  erlc -v +debug_info -o /home/ovcharsa/git/hcm/erlang.mk/test/test_dialyzer_beam_fullpath/ebin -pa /home/ovcharsa/git/hcm/erlang.mk/test/test_dialyzer_beam_fullpath/ebin -I  /home/ovcharsa/git/hcm/erlang.mk/test/test_dialyzer_beam_fullpath/src/test_dialyzer_beam_fullpath_app.erl /home/ovcharsa/git/hcm/erlang.mk/test/test_dialyzer_beam_fullpath/src/test_dialyzer_beam_fullpath_sup.erl /home/ovcharsa/git/hcm/erlang.mk/test/test_dialyzer_beam_fullpath/src/warn_me.erl
/home/ovcharsa/git/hcm/erlang.mk/test/test_dialyzer_beam_fullpath/src/warn_me.erl:2: Warning: function doit/0 is unused
/home/ovcharsa/git/hcm/erlang.mk/test/test_dialyzer_beam_fullpath/src/warn_me.erl:2: Warning: no clause will ever match
printf '{application, '\''test_dialyzer_beam_fullpath'\'', [\n	{description, "New project"},\n	{vsn, "0.1.0"},\n	{modules, ['\''test_dialyzer_beam_fullpath_app'\'','\''test_dialyzer_beam_fullpath_sup'\'','\''warn_me'\'']},\n	{registered, [test_dialyzer_beam_fullpath_sup]},\n	{applications, [kernel,stdlib]},\n	{mod, {test_dialyzer_beam_fullpath_app, []}},\n	{env, []}\n]}.' \
	> ebin/test_dialyzer_beam_fullpath.app
```

here is the branch I created to test it
https://github.com/ninenines/erlang.mk/pull/755

**Comment by stchar** [comment]
hmm look `-I` is empty. Looks like realpath return nothing if target is does't exist. 
adding `$(if $(realpath include/),-I $(realpath include/))` solves empty `-I` flag.

**Comment by essen** [comment]
Ah oops.

**Comment by stchar** [comment]
@essen, thanks for help.
btw what do you think is it a bug of `erlc`?

**Comment by essen** [comment]
I don't think it's a bug, it uses what you give it. I think we can add an option to Erlang.mk to force absolute paths if that's useful.

**Comment by stchar** [comment]
Actually I started to dig in as I'd like to enable [Pronto](https://github.com/prontolabs/pronto) to report dialyzer issues to our gitlab. 
Pronto uses [pronto-dialyzer](https://github.com/iurifq/pronto-dialyzer runner) which expects `dialyzer.out` to store absolute path of files with warnings. As it compares your git diff and reports only line you changed.

This all work great with dialyzer reports based on source analysis. However source analysis have issues if we use lager because of compile-time functions, and so on...

I'm not sure if pronto widely used by erlang community. So let say if this would be required I can submit the pull request.

**Comment by essen** [comment]
Never heard about pronto.To make lager not complain you can do something like `_ = lager:...` on each line though.

**Comment by essen** [comment]
OK I suppose this is solved. If you think this should be in upstream Erlang.mk please send a PR. Closing, thanks!
