### ISSUE TITLE
Q: Vagrantbox/Dockerfile to run erlang.mk tests

### ISSUE THREAD

**Issue by stchar** [ninenines/erlang.mk#759]
@essen,
Erlang.mk includes plugins which may require users to install additional system packages.
So I'm wondering if you have any draft solutions to describe test environment.

**Comment by essen** [comment]
`erlang git gmake autoconf automake gcc` should get you most of the way. It's possible something is missing I am unfortunately not doing a good job of maintaining that list. Feel free to point me to failing tests and I'll guide you toward the packages necessary.

**Comment by stchar** [comment]
I have some tests that does not work. 
The some look outdated, some broken,  I can delete/comment-out them in a separate commit.
BTW how do you run any CI builds for erlang.mk PRs?

**Comment by essen** [comment]
I have permanent Arch Linux, Ubuntu, FreeBSD, OSX (and previously, Windows, temporarily halted due to bs) on real servers and/or VMs. Some BuildKite configuration for what to run (below) and its agent does the rest.

```
make check -j 8 -k
make check LEGACY=1 -j 8 -k
```

**Comment by essen** [comment]
Oh and note that when you push it doesn't currently run the tests for PRs, it's behind a lock and I have to click it manually to make it really run. So if it says successful here it doesn't mean the tests ran successfully.

**Comment by stchar** [comment]
Yep, I noticed that. 
That's why I'd like to have a kind of dev env to verify that my PR does't break the regression.

**Comment by essen** [comment]
Yep no worries I'll test the PR soon.

**Comment by stchar** [comment]
`-k ` means keep going, so you run as much tests as possible.
How do you analyze what test failed?

**Comment by stchar** [comment]
```
grep -i error
```

**Comment by essen** [comment]
Actually yes that's how. Though I do this on the output log file rather than via pipes (Erlang + pipes is not the best combination).

**Comment by stchar** [comment]
cool, thanks/
