### ISSUE TITLE
unable to use PROJECT_ENV

### ISSUE THREAD

**Issue by t0il3ts0ap** [ninenines/erlang.mk#761]
I have a line in makefile
`PROJECT_ENV = [{app_env, development}]`

On executing `make run`, I see contents correctly in `ebin/grid_server.app`
```
{application, 'grid_server', [
	{description, "New project"},
	{vsn, "0.1.0"},
	{modules, ['array_2d','change_username_handler','grid','grid_leaderboard','grid_server_app','grid_server_match_handler','grid_server_match_lib','grid_server_match_maker','grid_server_request_handler','grid_server_sup','grid_store','grid_user','guest_signup_handler','leaderboard_handler','snake','snakelib','wordlist']},
	{registered, [grid_server_sup]},
	{applications, [kernel,stdlib,mnesia,cowboy,sync,lager,jiffy,trie,migresia,heap]},
	{mod, {grid_server_app, []}},
	{env, [{app_env, development]}
]}.
```

But, when I execute `application:get_all_env()` or other similar methods in the shell launched by above command, It results in `[]` or `undefined`. 

I tried putting in wrong values of env to break the app ( like missing braces ), but that has no effect either.
FYI, I am using latest version of erlang.mk

**Comment by t0il3ts0ap** [comment]
I got the result with `application:get_all_env(grid_server).`
This is quite strange that I have to pass my application name for trivial stuff.

I hope that I don't have to change application name in future. Any pro work around this is appreciated. 
Please close this issue.

**Comment by essen** [comment]
You have to pass the application name if you're not calling from a process belonging to that application. There's some little magic going on, done by OTP.

Not sure why it doesn't fail when messing up the contents of PROJECT_ENV but I'm not against adding some check for it.
