### ISSUE TITLE
erlang.mk incorrectly patch rebar pre_hooks

### ISSUE THREAD

**Issue by kostyushkin** [ninenines/erlang.mk#763]
When I try to use this [dependency](https://github.com/Ledest/otpbp), I get error message:

> make[2]: Entering directory '/home/kostyushkin/sandboxes/ecache/deps/otpbp'
> CC=cc make -f Makefile.orig.mk -s -C src/uc_spec unicode_util.erl
> make[3]: Entering directory '/home/s.kostyushkin/sandboxes/ecache/deps/otpbp/src/uc_spec'
> make[3]: Makefile.orig.mk: No such file or directory
> make[3]: *** No rule to make target 'Makefile.orig.mk'.  Stop.

It looks like the issue is here: [deps.mk#L337](https://github.com/ninenines/erlang.mk/blob/master/core/deps.mk#L337)
The problem occurs because real life rebar [pre_hooks](https://github.com/Ledest/otpbp/blob/master/rebar.config.script#L199) does not match this pattern.

**Comment by essen** [comment]
Done! Thanks!
