### ISSUE TITLE
dialyzer --built_plt and native code compilation

### ISSUE THREAD

**Issue by benjamin-bergia** [ninenines/erlang.mk#765]
I am having some issues with dialyzer native code compilation on my computer. Using --no_native solves the issues. I noticed that `--no_native` is already used during analyses: https://github.com/ninenines/erlang.mk/blob/b20df2d7fb690181d10393c97d6103bf2fd0aa86/plugins/dialyzer.mk#L60 but not when building the plt file: https://github.com/ninenines/erlang.mk/blob/b20df2d7fb690181d10393c97d6103bf2fd0aa86/plugins/dialyzer.mk#L47

I don't really know the reason for it but it would be nice to have it on both or being able to pass options to the plt build command.

**Comment by essen** [comment]
What issues do you have?

**Comment by benjamin-bergia** [comment]
Here is the error I get:
`Compiling some key modules to native code...{"init terminating in do_boot",{{badmatch,ok},[{dialyzer_cl,hc_cache,1,[{file,"dialyzer_cl.erl"},{line,572}]},{lists,foreach,2,[{file,"lists.erl"},{line,1338}]},{dialyzer_cl,hipe_compile,2,[{file,"dialyzer_cl.erl"},{line,516}]},{dialyzer_cl,do_analysis,4,[{file,"dialyzer_cl.erl"},{line,382}]},{dialyzer,'-cl/1-fun-0-',1,[{file,"dialyzer.erl"},{line,153}]},{dialyzer,doit,1,[{file,"dialyzer.erl"},{line,243}]},{dialyzer,plain_cl,0,[{file,"dialyzer.erl"},{line,84}]},{init,start_em,1,[]}]}}
init terminating in do_boot ()`

It doesn't seem to be related to erlang.mk.
I tried to run dialyzer manually using `dialyzer --build_plt --apps stdlib` and I get the exact same error.
But `dialyzer --no_native --build_plt --apps stdlib` does work.

I use erlang and dialyzer packages from Fedora repository. Here is the version that I use
https://fedora.pkgs.org/27/fedora-updates-x86_64/erlang-dialyzer-19.3.6.7-1.fc27.x86_64.rpm.html

**Comment by essen** [comment]
Ah alright. I suppose we can do an option for that. Something like `DIALYZER_PLT_OPTS` I don't think it should be disabled by default considering it's speeding things up very much.

**Comment by benjamin-bergia** [comment]
Ok. An option would be fine. Out of curiosity, why are you using `--no_native` when running the tests ?

**Comment by essen** [comment]
It takes time to compile to native if the VM isn't built with HiPE so it ends up being longer to run Dialyzer with it than without for most projects.

**Comment by essen** [comment]
I've added a `DIALYZER_PLT_OPTS` to my local copy. I will push soon.

Tomorrow please do `make erlang-mk`, then define `DIALYZER_PLT_OPTS = --no_native` and tell me if that fixes your problem. Thanks!
