### ISSUE TITLE
relx pretar hook

### ISSUE THREAD

**Issue by lego12239** [ninenines/erlang.mk#767]
Hi.

I'm not relx expert and may be i try to solve problem in a wrong place, but some changes like https://github.com/lego12239/erlang.mk/commit/2bda96e4de9a79be854991de272cd284ea7de694  would be nice. This is needed for placing rel hooks(which are supported by relx) to rel before relx make a tar.gz file. For example, after this changes by Makefile contain:

relx-hook-pretar:
        mkdir _rel/app_release/bin/hooks
        cp rel/empd_conf _rel/app_release/bin/hooks/

**Comment by essen** [comment]
I'm OK with the change, please send a PR and name the target `relx-post-rel` as the tar will not necessarily happen. Also make it a double colon target (`relx-post-rel::`).

**Comment by lego12239** [comment]
Done.
