### ISSUE TITLE
make dialyze fails with duplicate modules

### ISSUE THREAD

**Issue by rlipscombe** [ninenines/erlang.mk#768]
I've got a project that uses `erlware_commons` (9eae901e) and `rabbit_common` (rabbitmq_v3_6_9), both of which provide `ec_semver_parser` and `ec_semver` modules.

When I run `make dialyze`, it fails with the following:

```
dialyzer: Analysis failed with error:
Duplicate modules: [["/home/roger/Source/foo/bar/deps/erlware_commons/ebin/ec_semver_parser.beam",
                     "/home/roger/Source/foo/bar/deps/rabbit_common/ebin/ec_semver_parser.beam"],
                    ["/home/roger/Source/foo/bar/deps/erlware_commons/ebin/ec_semver.beam",
                     "/home/roger/Source/foo/bar/deps/rabbit_common/ebin/ec_semver.beam"]]
```

How do I tell erlang.mk to tell dialyzer to ignore the duplicates?

**Comment by rlipscombe** [comment]
> you should probably just delete one

Can you suggest a target that I can effect this from?

**Comment by essen** [comment]
I've added this to the guide (it'll appear later today). Closing, thanks!
