### ISSUE TITLE
How do I add extra beam files to the modules list?

### ISSUE THREAD

**Issue by rlipscombe** [ninenines/erlang.mk#769]
I followed the instructions at https://erlang.mk/guide/building.html#_generating_erlang_source for building custom .erl files, and that works fine.

However, I've got a couple of other custom build steps that build `.beam` files directly. If I add them as dependencies (`$(PROJECT).d:: $(GENERATED_BEAMS)`), they get built correctly, but they don't get added to the `modules` list in the application resource file, which means that they don't get loaded in the release startup script.

What am I missing?

**Comment by essen** [comment]
This: https://github.com/ninenines/erlang.mk/blob/master/plugins/erlydtl.mk#L25

**Comment by rlipscombe** [comment]
:+1:
