### ISSUE TITLE
Can I have LOCAL_TEST_DEPS?

### ISSUE THREAD

**Issue by rlipscombe** [ninenines/erlang.mk#770]
I've got a multi-app repository, where one of the apps is `apps/eunit_helpers`. In order to get my unit tests to work, I need to specify this in `LOCAL_DEPS`, otherwise it's not compiled early enough, or the include files are not found when compiling tests.

But that then either includes it in the release, or fails with `Error: Dependency eunit_helpers (eunit_helpers) conflicts with application found in /home/roger/Source/foo/bar/apps/eunit_helpers`.

Does erlang.mk have a `LOCAL_TEST_DEPS` variable or some way of achieving something similar?

**Comment by rlipscombe** [comment]
The "conflicts" error might be because I included the application in its own `LOCAL_DEPS`; ignore that bit.

It also occurs that I could exclude the application from the release explicitly, per my comment in #768. I'd still prefer a `LOCAL_TEST_DEPS` variable, though.

**Comment by essen** [comment]
It doesn't have this but I'm not sure it's necessary? If it's already in apps/* it should be available from the tests. Isn't it? Or is it that it's not compiled in the right order?

**Comment by rlipscombe** [comment]
> If it's already in apps/* it should be available from the tests. Isn't it?

Hmmm. Now it's working fine. Originally it was complaining that it couldn't find a header file from the helper. Closing this; will reopen if I can reproduce the problem.

**Comment by rlipscombe** [comment]
OK. So I can reproduce it with my current system. I'm not sure I can do an MVCE yet, though.

I have a target, "jenkins", at the very end of my top-level Makefile:

```
jenkins: apps eunit ct
```

Starting from `make distclean`...

If I run `make jenkins`, the build fails, complaining that it can't find include files from my test helper app. This seems a little odd, since include files are include files; they exist _anyway_.

That suggests that my test helper app is missing from `ERL_LIBS`. I think.

On the other hand, if I run `make apps` and _then_ run `make eunit`, as separate commands, the `eunit` target works correctly.

**Comment by KrzysiekJ** [comment]
`LOCAL_TEST_DEPS` may be also helpful for dialyzing tests (refs #487).

**Comment by rlipscombe** [comment]
Hi @essen, I'm still snowed under with a bunch of other stuff. I'm not going to get to this for a while. Please feel free to park it, or even close it if @KrzysiekJ doesn't have any further thoughts.

**Comment by essen** [comment]
Alright. Please reopen when/if you get around to it, thanks!
