### ISSUE TITLE
put proper-test module files in 'test' directory

### ISSUE THREAD

**Issue by refactor** [ninenines/erlang.mk#772]
proper test file must be put in 'src' dir, otherwise (such as 'test' dir) will be ignored when 'make tests'.
can they be put in 'test' dir, just like eunit files?

**Comment by essen** [comment]
It's probably just missing a path somewhere.

**Comment by refactor** [comment]
6587 proper: test-build
6588     $(eval MODULES := $(patsubst %,'%',$(sort $(notdir $(basename $(wildcard ebin/*.beam))))))
6589     $(gen_verbose) $(call erlang,$(call proper_check.erl,all,undefined,$(MODULES)))

**Comment by essen** [comment]
Added the path in the right place on my local copy, push later today. Thanks!
