### ISSUE TITLE
How to add new recursive target?

### ISSUE THREAD

**Issue by rlipscombe** [ninenines/erlang.mk#774]
I've got an `apps`-styled repository, and I'd like to be able to invoke `make deb` from the top-level, and have it invoke the `deb` target in any Makefile that implements it.

Is there an easy way to add custom recursive targets with erlang.mk?

**Comment by essen** [comment]
This is the closest I can give you: https://github.com/ninenines/erlang.mk/blob/master/core/deps-tools.mk

**Comment by rlipscombe** [comment]
Thanks. I'll start there.

**Comment by rlipscombe** [comment]
I've got this in my `top.mk`, immediately after including `erlang.mk`:

```
deb: $(if $(IS_APP),,apps-deb)

ifneq ($(ALL_APPS_DIRS),)
apps-deb:
	$(verbose) for app in $(ALL_APPS_DIRS); do $(MAKE) -C $$app deb IS_APP=1; done
endif
```

I don't know if it's 100% sufficient, but it works for me. Feedback appreciated, if you have time.
