### ISSUE TITLE
Incorrect application path to run eunit for a specific app in multi-apps project

### ISSUE THREAD

**Issue by stchar** [ninenines/erlang.mk#777]
### Project structure:
.
│── apps
│   ├── app1
│   │   ├── Makefile
│   │   ├── src
│   │   └── test
│   ├── app2
│   │   ├── include
│   │   ├── Makefile
│   │   └── src
├── erlang.mk
├── Makefile

### Let's say `app1` depends on `app2`
```
# app1/Makefile:
LOCAL_DEPS = app2
```

### User want to run eunit for `app1`
```
cd apps/app1
make eunit 
```
As a result eunit fails to find any modules in app2 

Debug shows that application path contains `<project_root>/apps/app1/[apps/*/ebin]` 

While It is expected application path to contain `<project_root>/apps/*/ebin`

**Comment by stchar** [comment]
As a workaround I tired to define `APPS_DIR` in `app1/Makefile` but it force erlang.mk to run all eunit tests in the project

**Comment by essen** [comment]
I think what you need is `ERL_LIBS` to be set to include `..` or `$(dirname $(PWD))`. But maybe only if `IS_APP` is not defined. I think this is something we want documented rather than done on all projects though. Or documented + added to app templates when creating with this folder structure.

**Comment by essen** [comment]
I think your workaround is the way to go, it just needs a way to prevent running eunit tests everywhere in that case.

**Comment by essen** [comment]
I've implemented this on my local copy. Push soon. Closing, thanks!
