### ISSUE TITLE
Failed to make Erlang/OTP app by erlang.mk

### ISSUE THREAD

**Issue by ethrbh** [ninenines/erlang.mk#778]
hello,

I met with the problem when I tried make and Erlang/OTP app -following the Erlang.mk user's guide (https://erlang.mk/guide/getting_started.html#_getting_started_with_otp_applications)- on my Raspberry Pi, where Erlang/OTP 20.2 is running. I tried the same on my Ubuntu and I did not see this problem, so I think something is missing on my Pi, or ... Thus, I would like to get some help/direction.

Below the steps on the Pi can be see, what I did, and the "fatal: No names found, cannot describe anything." error text can be see when I tried generate Erlang/OTP app by erlang.mk.

Create a folder for the project
-----------------------------------------------------------
	pi@raspberrypi:~/dev> mkdir igs_tmp
	pi@raspberrypi:~/dev> cd igs_tmp/
	
Get erlang.mk
-----------------------------------------------------------
	pi@raspberrypi:~/dev/igs_tmp> wget https://erlang.mk/erlang.mk
	--2018-05-10 06:25:58--  https://erlang.mk/erlang.mk
	Resolving erlang.mk (erlang.mk)... 104.28.20.247, 104.28.21.247, 2400:cb00:2048:1::681c:15f7, ...
	Connecting to erlang.mk (erlang.mk)|104.28.20.247|:443... connected.
	HTTP request sent, awaiting response... 200 OK
	Length: 454 [application/octet-stream]
	Saving to: ‘erlang.mk’

	erlang.mk         100%[============>]     454  --.-KB/s    in 0s

	2018-05-10 06:25:59 (2.44 MB/s) - ‘erlang.mk’ saved [454/454]

	pi@raspberrypi:~/dev/igs_tmp> ls
	erlang.mk
	pi@raspberrypi:~/dev/igs_tmp> ls -la
	total 12
	drwxr-xr-x 2 pi pi 4096 May 10 06:25 .
	drwxr-xr-x 8 pi pi 4096 May 10 06:25 ..
	-rw-r--r-- 1 pi pi  454 Mar 14 15:47 erlang.mk
	
Generate Erlang/OTP app by erlang.mk - failing
-----------------------------------------------------------
	pi@raspberrypi:~/dev/igs_tmp> make -f erlang.mk bootstrap
	git clone --depth 1 https://github.com/ninenines/erlang.mk .erlang.mk.build
	Cloning into '.erlang.mk.build'...
	remote: Counting objects: 592, done.
	remote: Compressing objects: 100% (586/586), done.
	remote: Total 592 (delta 4), reused 473 (delta 3), pack-reused 0
	Receiving objects: 100% (592/592), 209.86 KiB | 0 bytes/s, done.
	Resolving deltas: 100% (4/4), done.
	if [ -f build.config ]; then cp build.config .erlang.mk.build; fi
	cd .erlang.mk.build && make
	make[1]: Entering directory '/home/pi/dev/igs_tmp/.erlang.mk.build'
	fatal: No names found, cannot describe anything.
	export LC_COLLATE=C; \
	awk 'FNR==1 && NR!=1{print ""}1' core/core.mk core/kerl.mk index/*.mk core/index.mk core/deps.mk plugins/protobuffs.mk core/erlc.mk core/docs.mk core/rel.mk core/test.mk core/compat.mk plugins/asciidoc.mk plugins/bootstrap.mk plugins/c_src.mk plugins/ci.mk plugins/ct.mk plugins/dialyzer.mk plugins/edoc.mk plugins/erlydtl.mk plugins/escript.mk plugins/eunit.mk plugins/proper.mk plugins/relx.mk plugins/shell.mk plugins/sphinx.mk plugins/syntastic.mk plugins/triq.mk plugins/xref.mk plugins/cover.mk plugins/sfx.mk core/plugins.mk core/deps-tools.mk \
			| sed 's/^ERLANG_MK_VERSION =.*/ERLANG_MK_VERSION = /' \
			| sed 's:^ERLANG_MK_WITHOUT =.*:ERLANG_MK_WITHOUT = :' > erlang.mk
	make[1]: Leaving directory '/home/pi/dev/igs_tmp/.erlang.mk.build'
	cp .erlang.mk.build/erlang.mk ./erlang.mk
	rm -rf .erlang.mk.build
	
Checking the generated files
-----------------------------------------------------------
	pi@raspberrypi:~/dev/igs_tmp> ls -la
	total 248
	drwxr-xr-x 3 pi pi   4096 May 10 06:26 .
	drwxr-xr-x 8 pi pi   4096 May 10 06:25 ..
	-rw-r--r-- 1 pi pi 236277 May 10 06:26 erlang.mk
	-rw-r--r-- 1 pi pi     95 May 10 06:26 Makefile
	drwxr-xr-x 2 pi pi   4096 May 10 06:26 src
	
Try update erlang.mk - failing
-----------------------------------------------------------
	pi@raspberrypi:~/dev/igs_tmp> make erlang-mk
	git clone --depth 1 https://github.com/ninenines/erlang.mk .erlang.mk.build
	Cloning into '.erlang.mk.build'...
	remote: Counting objects: 592, done.
	remote: Compressing objects: 100% (586/586), done.
	remote: Total 592 (delta 4), reused 473 (delta 3), pack-reused 0
	Receiving objects: 100% (592/592), 209.86 KiB | 0 bytes/s, done.
	Resolving deltas: 100% (4/4), done.
	if [ -f build.config ]; then cp build.config .erlang.mk.build/build.config; fi
	make -C .erlang.mk.build WITHOUT=''
	make[1]: Entering directory '/home/pi/dev/igs_tmp/.erlang.mk.build'
	fatal: No names found, cannot describe anything.
	export LC_COLLATE=C; \
	awk 'FNR==1 && NR!=1{print ""}1' core/core.mk core/kerl.mk index/*.mk core/index.mk core/deps.mk plugins/protobuffs.mk core/erlc.mk core/docs.mk core/rel.mk core/test.mk core/compat.mk plugins/asciidoc.mk plugins/bootstrap.mk plugins/c_src.mk plugins/ci.mk plugins/ct.mk plugins/dialyzer.mk plugins/edoc.mk plugins/erlydtl.mk plugins/escript.mk plugins/eunit.mk plugins/proper.mk plugins/relx.mk plugins/shell.mk plugins/sphinx.mk plugins/syntastic.mk plugins/triq.mk plugins/xref.mk plugins/cover.mk plugins/sfx.mk core/plugins.mk core/deps-tools.mk \
			| sed 's/^ERLANG_MK_VERSION =.*/ERLANG_MK_VERSION = /' \
			| sed 's:^ERLANG_MK_WITHOUT =.*:ERLANG_MK_WITHOUT = :' > erlang.mk
	make[1]: Leaving directory '/home/pi/dev/igs_tmp/.erlang.mk.build'
	cp .erlang.mk.build/erlang.mk ./erlang.mk
	rm -rf .erlang.mk.build
	pi@raspberrypi:~/dev/igs_tmp>

Running Erlang/OTP version on the Raspberry Pi
-----------------------------------------------------------
	1> pi@raspberrypi:~/dev/igs_tmp> erl
	1> Erlang/OTP 20 [erts-9.2] [source] [smp:4:4] [ds:4:4:10] [async-threads:10] [kernel-poll:false]
	1>
	1> Eshell V9.2  (abort with ^G)
	1> 1>

thanks for your help,
/Robi

**Comment by essen** [comment]
What distribution is it using? What about the version of git?

**Comment by essen** [comment]
For example you say you don't have the problem on Ubuntu, what do you have installed on the Pi? On my Pis I have Arch Linux just like on my laptop and servers.

**Comment by ethrbh** [comment]
hello,

I am using Rasbian

	pi@raspberrypi:~> uname -a
	Linux raspberrypi 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux
	pi@raspberrypi:~> cat /etc/os-release
	PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
	NAME="Raspbian GNU/Linux"
	VERSION_ID="9"
	VERSION="9 (stretch)"
	ID=raspbian
	ID_LIKE=debian
	HOME_URL="http://www.raspbian.org/"
	SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
	BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
	pi@raspberrypi:~> 
	
	pi@raspberrypi:~> lsb_release -a
	No LSB modules are available.
	Distributor ID:	Raspbian
	Description:	Raspbian GNU/Linux 9.1 (stretch)
	Release:	9.1
	Codename:	stretch
	pi@raspberrypi:~> 
	pi@raspberrypi:~> 

thanks,
/Robi

**Comment by essen** [comment]
Please try again. I can't test it but the fatal error should go away.

**Comment by ethrbh** [comment]
hello,

I did it, and I can confirm the error goes away. Do you have any idea what could be the problem when I tried first?

thanks,
/Robi

**Comment by essen** [comment]
https://github.com/ninenines/erlang.mk/commit/ca7fcc22e1eae294a2a05f89b2f95c20f7e2ceb6 is what fixed the issue but I'm not sure why it was doing this on Raspbian and not on other platforms in the first place.
