### ISSUE TITLE
erlang.mk gen relx failed

### ISSUE THREAD

**Issue by ehelaya** [ninenines/erlang.mk#783]
Hi,

I have try to use  erlang.mk to build my application and I have relx.config in my project root.
```
{release, {my_app, "0.0.1"}, [my_app]}.
{extended_start_script, true}.

{overlay, [
    {copy, "config/vm.args", "releases/\{\{release_version\}\}/vm.args"},
    {copy, "config/sys.config", "releases/\{\{release_version\}\}/sys.config"}
]}.
```
but when i try ```make``` it'll compile all sources but did not complete the process.
please see the below log
``` 
=ERROR REPORT==== 22-May-2018::11:59:56 ===
Loading of /Users/Udayanga/Work/my_app/.erlang.mk/relx/relx/ebin/relx.beam failed: badfile

=ERROR REPORT==== 22-May-2018::11:59:56 ===
beam/beam_load.c(1287): Error loading module relx:
  mandatory chunk of type 'Atom' not found


escript: exception error: undefined function relx:main/1
  in function  escript:run/2 (escript.erl, line 760)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1
  in call from init:do_boot/3
make: *** [erlang.mk:6746: relx-rel] Error 127
```
Erlang version : 19.3
MacOS: 10.13.4

any idea how to solve this issue?

Thanks,
Udaya.

**Comment by essen** [comment]
I've updated Relx a few days ago, maybe I did it wrong. Let me check that I did it correctly.

**Comment by essen** [comment]
Seems like I didn't. Let me do it again.

**Comment by ehelaya** [comment]
Thanks @essen .

**Comment by essen** [comment]
Should be better. Delete `.erlang.mk/relx` and try again. Thanks!

**Comment by ehelaya** [comment]
great. it worked. Thanks @essen

**Comment by eugene-panferov** [comment]
i am having this message now. (freshly downloaded soft, walking through the "getting started") no idea what to do.

**Comment by essen** [comment]
Can you put the whole output you get in a new ticket? Also try deleting `.erlang.mk`.
