### ISSUE TITLE
Test dependencies do not have precedence over subdependencies

### ISSUE THREAD

**Issue by KrzysiekJ** [ninenines/erlang.mk#786]
> In tree traversal terms, where the list of dependencies is a tree, Erlang.mk fetches everything using the pre-order traversal method. The steps can be summarized like this, starting from the root application:
> 
> 1. Fetch all dependencies for the application
> 2. Build first dependency
> 3. Build Nth dependency
> 4. Build last dependency 
>
> Every time a dependency is built, these same steps are followed, recursively.

In reality, `TEST_DEPS` are fetched later than `DEPS` of dependencies. For example, [commit `32188c16e00b` in Ercoin](https://gitlab.com/Ercoin/ercoin/tree/32188c16e00b1a69b2fd47597dd9626dcb689752) has:

* Triq in `TEST_DEPS`;
* a version of gb_merkle_trees in `DEPS` which has:
  * Triq in `DEPS`.

When building project, the version of Triq specified by gb_merkle_trees is used. (In a newer version of gb_merkle_trees, Triq has been moved to `TEST_DEPS`, so in this case this will not be an issue anymore).

This may be actually a documentation issue.

I guess the same applies to `SHELL_DEPS`.

**Comment by essen** [comment]
I've added something to my local copy.
