### ISSUE TITLE
How to ignore erl files in subdirs of TEST_DIR in testing?

### ISSUE THREAD

**Issue by gomoripeti** [ninenines/erlang.mk#793]
I have a use case when there are erlang modules in sub-directories of the `test/` directory which are actually test data for negative tests and they don't compile.
When running eg `make eunit` all the `.erl` files are compiled and all of them are also included to be run by `eunit:test`.

Is there a way to only compile and test `test/*.erl` files? (Either by giving an exclude pattern to the test targets, or by explicitly declaring which erlang files are test files)

**Comment by essen** [comment]
I would say the simplest way would be to not name those `.erl` at all.

Looking at the code there doesn't seem to be an easy way not to compile those at the moment. That could be arranged though.

**Comment by gomoripeti** [comment]
thanks Loic,

In my particular case files can have any name, renaming will just work.
Closing issue until there is a stronger use case to support this in some way.
