### ISSUE TITLE
Chicken/egg problem with -include_lib and dependencies

### ISSUE THREAD

**Issue by darkling** [ninenines/erlang.mk#797]
I have this in `src/childe_instance.erl`:

`-include_lib("erlsom/src/erlsom_sax.hrl").`

and now, having removed `deps/`, in the hope of refreshing them, I get:

`make: *** No rule to make target '/home/hrm/nightglass/software/childe/deps/erlsom/src/erlsom_sax.hrl', needed by 'src/childe_instance.erl'.  Stop.`

when running most of the targets that I usually use, including `make deps`, and `make clean`.

Makefile attached (as .txt).
[Makefile.txt](https://github.com/ninenines/erlang.mk/files/2134775/Makefile.txt)

**Comment by essen** [comment]
Delete the .d file if `make distclean` doesn't work.

**Comment by essen** [comment]
Seems there's a solution. I'll experiment tomorrow after I write a test.

http://make.mad-scientist.net/papers/advanced-auto-dependency-generation/#advanced

**Comment by essen** [comment]
I'm failing to reproduce at the moment. Maybe some changes I did recently fixed it. Please update and try again and reopen if the issue still exists. A failing test case would of course be another solution. Thanks!
