### ISSUE TITLE
Escript plugin tries to match files from non-existent ebin/ directories

### ISSUE THREAD

**Issue by KrzysiekJ** [ninenines/erlang.mk#798]
Let’s say that I have:

```
BUILD_DEPS = lfe.mk
```

Then there is no `$(DEPS_DIR)/lfe.mk/ebin` directory, however [the escript plugin tries to include all files from that directory](https://github.com/ninenines/erlang.mk/blob/af32c4f56709195e51a06f0f8586ae5c4d2c0f7f/plugins/escript.mk#L34-L37), which results with the following warning and status code 1 when using 7zip:

```
WARNING: No more files
lfe.mk/ebin
```

When using zip, there is only a warning:

```
zip warning: name not matched: lfe.mk/ebin/*
```

**Comment by essen** [comment]
Makes sense, I suppose we ought to filter those paths to make sure they point to an actual directory then.

**Comment by essen** [comment]
I've fixed this on my local copy. Will push later today. Thanks!
