### ISSUE TITLE
Problem with relx.config

### ISSUE THREAD

**Issue by thebestclass** [ninenines/erlang.mk#804]
I have this error when execute `make run` in my working dir:
> Dependency erlang is specified as a dependency but is not reachable by the system.

This error are associated with my relx.config:
```
{release, {erlang, "0.0.1"},
 [erlang]}.
```

I think I've badly organized my folders or something with these fi. See my structure: https://github.com/thebestclass/erlang

**Comment by essen** [comment]
You called the project `'erlang-rms'` in the Makefile, not `erlang`. That's why it can't find it.

**Comment by essen** [comment]
The second line of your snippet needs to be `['erlang-rms']}.` or the name be fixed.
