### ISSUE TITLE
make check doesn’t treat warnings as errors

### ISSUE THREAD

**Issue by KrzysiekJ** [ninenines/erlang.mk#809]
It is therefore possible that `make check` succeeds, but `make app` fails (as it treats warnings as errors by default).

**Comment by essen** [comment]
Yes.

**Comment by essen** [comment]
I suppose check could finish by rebuilding the app normally. But tests should not treat warnings as errors because that's annoying when you're just trying to print or fix something and it prevents testing because of unused variables/functions.

**Comment by KrzysiekJ** [comment]
It depends on the context. If one runs `make check` as a last step before making a commit or in a CI process, he may want it to fail early, not after possibly lengthy tests and Dialyzer checks. Maybe there should be an environment variable named like `IGNORE_WARNINGS`? It would help also in a situation when one wants to do manual testing and runs `make app shell`. For example, currently if there is a `-compile(export_all).` directive in a file, then `make app` will fail (compilation from the shell has to be used instead).

**Comment by essen** [comment]
I'd say just use `make test-build shell` in that case. And I suppose the same could apply with check, even if check included app at the end, you could change the order by running `make app check`.

**Comment by essen** [comment]
So what's the verdict, is there anything that needs fixing? I'm still undecided.

**Comment by essen** [comment]
I think I will recommend adding this at the end of Makefiles:

``` make
check::
    $(verbose) $(MAKE) --no-print-directory app
```

The problem being that if this isn't the last thing that runs it's not going to work properly. Can't switch too easily between normal/test builds.

For CI someone can just add a command, no big issue. Before commit, then adding the snippet above would do. Closing, thanks!
