### ISSUE TITLE
c_src/env.mk should probably have a "don't edit this file" warning in it

### ISSUE THREAD

**Issue by rlipscombe** [ninenines/erlang.mk#811]
I didn't initially notice that `make distclean` removes `c_src/env.mk`, which means that I lost (modulo git) my modifications.

**Comment by essen** [comment]
Sorry about that.

I suppose the same applies to the .d file or to the generated rebar.config file for those that use this functionality.

**Comment by rlipscombe** [comment]
I was less suprised by the `.d` file, because I'm long familiar with the idea of them as build artifacts. I hadn't even noticed the `rebar.config` file.

The reason I found it surprising is that I'd done `make new-nif n=foo` and `make`, so it wasn't obvious which step had generated the `env.mk`, so it looked ripe for adding `CXXFLAGS += -std=c++17`, for example.

**Comment by essen** [comment]
Right.

**Comment by rlipscombe** [comment]
```
diff --git a/erlang.mk b/erlang.mk
index fb33c5d..db865fb 100644
--- a/erlang.mk
+++ b/erlang.mk
@@ -6101,6 +6101,7 @@ ifneq ($(wildcard $(C_SRC_DIR)),)
 $(C_SRC_ENV):
        $(verbose) $(ERL) -eval "file:write_file(\"$(call core_native_path,$(C_SRC_ENV))\", \
                io_lib:format( \
+                       \"# Managed by erlang.mk; DO NOT EDIT~n\" \
                        \"ERTS_INCLUDE_DIR ?= ~s/erts-~s/include/~n\" \
                        \"ERL_INTERFACE_INCLUDE_DIR ?= ~s~n\" \
                        \"ERL_INTERFACE_LIB_DIR ?= ~s~n\", \
```

**Comment by essen** [comment]
Done locally, push soon. Thanks!
