### ISSUE TITLE
make deps && -j option

### ISSUE THREAD

**Issue by dinama** [ninenines/erlang.mk#812]
can i use -j option for build deps or is not correct? 

ps. example - hackney is not build  with option -j :

`Error: No Makefile to build dependency ..../hackney.`
`make: *** [erlang.mk:4339: deps] Error 2`

like here: https://github.com/ninenines/erlang.mk/issues/384

**Comment by essen** [comment]
Does it build without the `-j` option?

**Comment by dinama** [comment]
>Does it build without the -j option?

yes, if i move it to end of DEPS list - then broken some over depend, example:

`Error:` No Makefile to build dependency ..../deps/epgsql.`
`make: *** [erlang.mk:4339: deps] Error 2`

**Comment by essen** [comment]
I mean try from scratch and just do make, like `make distclean; make`. You probably have some leftover that creates more issues. I have no problem with these deps without `-j` so it's probably an issue with that.

**Comment by dinama** [comment]
> I have no problem with these deps without -j so it's probably an issue with that.

a have long depend list,  can you try 4 and more depends ?

`DEPS=hackney ibrowse epgsql mochiweb`

**Comment by essen** [comment]
Yes it works for me when I do `make distclean; make` with these deps. It doesn't work when I do `make -j 8`.

**Comment by dinama** [comment]
>make distclean; make with these deps. It doesn't work when I do make -j 8.

yes 

`make distclean && make deps`  - work perfect
`make deps -j[N]`  - is broken

can i use -j option for build deps or is not correct?

**Comment by essen** [comment]
It seems to be broken at the moment, although it used to work. I'll have to look into it again. Thanks for the report!

**Comment by dinama** [comment]
Thank you! I temporary select worked N jobs

**Comment by essen** [comment]
I'm finishing a fix for this at the moment. It should work out of the box on both Linux and FreeBSD via the flock/lockf commands. But I don't have a silver bullet for OSX. This can however be installed via Homebrew so that should be fine: https://github.com/discoteq/flock

**Comment by essen** [comment]
The fix is a success, closing, thanks!

**Comment by segachan** [comment]
@essen 
Hello. 
I'm facing the similar thing to this issue reported. That is... `make` command is complete but `make -j2` leads the error.

- OS: `Poky (Yocto Project Reference Distro) 1.7.2`, precisely say Docker.
using `FROM devhub-docker.cisco.com/iox-docker/ie4k/base-rootfs@sha256:8360103d3c71b2c17e5e7cc78d6c2cf435cc83e270e0c1cd2f41a4f2e38f061a` in Dockerfile.

- Erlang Version:24.0
- deps in Makefile`DEPS = cowboy lager jsone`
- make -v : `GNU Make 4.0`

**Comment by essen** [comment]
Please open a new ticket and include the output, errors, etc.
