### ISSUE TITLE
make run && {extended_start_script, false}

### ISSUE THREAD

**Issue by dinama** [ninenines/erlang.mk#813]
When option extended_start_script is  false - relx  generate simple script  `erlexec -boot ...  $ARGS`,
and `make run` calling  `erlexec -boot...  console`  - and erlang starting is broken

**Comment by essen** [comment]
Yes.

**Comment by dinama** [comment]
its a feature?

**Comment by essen** [comment]
I've fixed this in my local copy, I'll push it tomorrow. Thanks!
