### ISSUE TITLE
make dialyze doesn't pick up parse transforms within the same app

### ISSUE THREAD

**Issue by ECrownofFire** [ninenines/erlang.mk#814]
Example error on a single app project build:
```
  Checking whether the PLT /home/ecrownoffire/ecf/.ecf.plt is up-to-date... yes
  Proceeding with analysis...
dialyzer: Analysis failed with error:
Could not scan the following file(s):
/home/ecrownoffire/ecf/src/ecf_perms.erl:none: undefined parse transform 'ecf_perm_pt'

Last messages in the log cache:
  Reading files and computing callgraph...
make: *** [erlang.mk:6416: dialyze] Error 1
```

Just adding `-pa ebin` to the Dialyzer arguments fixes it for my single app build.

I'm not sure how it acts with multiple apps.

**Comment by ECrownofFire** [comment]
The most immediate problem that I can think of is that if you don't `make` beforehand I'm pretty sure it'll grab an old compiled version of your parse transform since it wouldn't be from source.

**Comment by essen** [comment]
I've fixed this in my local copy. I'll push later today. Thanks!

To update Erlang.mk tomorrow do `make erlang-mk`.
