### ISSUE TITLE
`make escript` requires `FULL=1`

### ISSUE THREAD

**Issue by dumbbell** [ninenines/erlang.mk#815]
`make escript` depends on the content of `.erlang.mk/deps.log` to determine the list of applications to add to the final zip archive. However, with the new behavior to save some time (i.e. not visit indirect dependencies), those indirect dependencies are absent from `deps.log` and thus missing from the resulting escript.

Running `make escript FULL=1` works around the problem.

**Comment by essen** [comment]
Thanks! I'll have a fix up before next week probably.

**Comment by essen** [comment]
Fixed locally, will be pushed later today. Closing, thanks!
