### ISSUE TITLE
Question: how to include only one service for inets?

### ISSUE THREAD

**Issue by jeromedes** [ninenines/erlang.mk#819]
As an example, I would like to have
```
{inets, [{services, [{httpc, []}]}
```
instead of just
```
inets
```
in my `.app` file, but I can't make that happen from LOCAL_DEPS in the Makefile.
Is it possible, or do I have to switch to the "old" way with an `.app.src` file?
Thanks!

**Comment by essen** [comment]
If there's a way to achieve this using `PROJECT_ENV` that could be used, if not then you'll need the .app.src file. I'm unfamiliar with this form though, could you point me to the relevant documentation?

**Comment by jeromedes** [comment]
Sure: [2 Inets — 2.1  Service Concept](http://erlang.org/doc/apps/inets/inets_services.html#service-concept)

**Comment by jeromedes** [comment]
It's for the `applications` entry in the `.app` file, I think `PROJECT_ENV` is for the `env` entry. I'll switch to an `.app.src` file. But you're right, it would be great if the `applications` entry could be parsed as the `env` entry is. Thanks for erlang.mk!

**Comment by essen** [comment]
Yes I understand what you're saying but the OTP documentation disagrees. :-) The code also seems to disagree, see: https://github.com/erlang/otp/blob/master/lib/inets/src/inets_app/inets_sup.erl#L52

`PROJECT_ENV` as I've written it above should work.

**Comment by jeromedes** [comment]
Wow, thanks! You're so helpful as always!
Note for my future self and maybe others, the Makefile entry to copy/paste is:
```
PROJECT_ENV = [{inets, [{services, [{httpc, []}]}]}]
```
Thanks again Loïc.

**Comment by essen** [comment]
Actually now that I think about it that's a bad advice, this should instead go in the `sys.config` file. `PROJECT_ENV` is supposed to be for the current application only.

**Comment by jeromedes** [comment]
Yes, you're right, the above doc says it clearly:

> are to be put into the Erlang node configuration file

Sorry for the waste of your time.

**Comment by essen** [comment]
Cheers.
