### ISSUE TITLE
Compiling NIF with 3rd party C project headers

### ISSUE THREAD

**Issue by jhw** [ninenines/erlang.mk#823]
(Apologies in advance as this really just shows my lack of C knowledge ..)

I'm building my first NIF and want to include it as part of an `erlang-mk` project.

Following the instructions here -

https://erlang.mk/guide/ports.html

Works very nicely with a custom `c_src/Makefile`, which looks like this -

```
all:
	gcc -fPIC -shared -o hello.so hello.c -I ~/kerl/20.3/usr/include/ -I ~/packages/sunvox_lib/headers
clean:
	rm hello.so 
```

However I'd like to avoid the custom Makefile if I can, and just have `erlang-mk` build the NIF automatically.

Predictably, if I remove `c_src/Makefile`, I get the following -

```
/home/justin/work/hello/c_src/hello.c:7:10: fatal error: sunvox.h: No such file or directory
 #include "sunvox.h"
          ^~~~~~~~~~
```

How do I pass `-I  ~/packages/sunvox_lib/headers` to the C compiler within my standard `Makefile` so that `hello.c` compiles to `hello.so` ?

Many thanks.

**Comment by jhw** [comment]
OK thanks - that *seems* to have worked  - but a couple of questions - 

- my c file was actually called `sunbeam_sv_demo.c`; compilation seems to have generated both `c_src/sunbeam_sv_demo.so` and `priv/sunbeam.so` - why the two outputs and why the name truncation in the second ? (I guess it's the app name in the second ?)

- will the NIF code be automatically available in the release on `make app` or `make run` ? I can see `priv/sunbean.so` in the release, will that do the trick ?

Many thanks

**Comment by jhw** [comment]
Ah okay the one in `c_src` probably was a `.o` file, am away from my computer, will check later. This all sounds great and am looking forward to trying it out.

One final question. My project relies on a `sunvox.so` being available at runtime - `sunbeam_sv_demo.c` is really just a wrapper around the stuff in `sunvox.so`, making it available to Erlang. How should I make `sunvox.so` available to my release? Thus far (non - otp) I've just been symlinking it into my project root directory. Am guessing there is a better way, maybe using some C stuff of which I am not familiar, maybe LD_LIBRARY_PATH. What would you advise as best practice here? Many thanks.

**Comment by essen** [comment]
Yes set the environment variable and the OS will find and load it. Alternatively it could be installed on the target system, or it could be statically compiled in your NIF. Which is best is up to your situation.

**Comment by jhw** [comment]
The environment variable - so LD_LIBRARY_PATH would be the the right one in this situation, for looking up a `.so` file?

**Comment by essen** [comment]
Yes at least on Linux and I suppose BSD. Not sure on other systems.

**Comment by jhw** [comment]
The `LD_LIBRARY_PATH` option failed  -

```
./sunvox.so: cannot open shared object file: No such file or directory
                                                                      Segmentation fault (core dumped)
```

I think because of this in `sunvox.h` -

```
#if defined(__linux__) || defined(linux)
    #define LINUX
    #define LIBNAME "./sunvox.so"
#endif
```

which suggests to me that Sunvox requires `sunvox.h` and `sunvox.so` to be in the same place :-/

Any thoughts on how to deal with this ? (I realise we're not necessarily C or Sunvox experts here, but just in case).

Thank you -

**Comment by essen** [comment]
`./sunvox.so` probably means it needs to be in the working directory so that's not very nice. I guess it loads it dynamically at runtime? So it'd have to be located in the correct location. Symbolic links might help.

**Comment by jhw** [comment]
OK thank you

**Comment by jhw** [comment]
This all works - which is great - and was pretty easy to get working, so :+1: :+1: :+1: 

One slight issue - I had to reference the NIF as follows within the release -

```
erlang:load_nif("./lib/sunbeam-0.1.0/priv/sunbeam", 0)])
```

is there a way to do this without specifying/hardcoding the full path (inc version number) ?

**Comment by essen** [comment]
`code:priv_dir(sunbeam)` gives you most of the path, as I mentioned previously.

**Comment by jhw** [comment]
Apologies I read too quickly and missed that bit. Many thanks again. Erlang Mk is amazing!
