### ISSUE TITLE
appup file missing in ebin and 'make relup' throws error 

### ISSUE THREAD

**Issue by scribnar** [ninenines/erlang.mk#826]
Making a release using 'make relup' command fails to make a release. The complication succeeds however the relup file is not made as relx throws error stating the relup could not be found.

The exact error is "Errors generating relup, Could not open file .../*.appup"

The suggested solution is to copy <app>.appup file to ebin directory after the compilation finishes. Its suggested by @essen that we can copy the below line as last line in Makefile which takes care of it.

app:: ; cp src/app.appup ebin/

This ticket is created as per Essen's advice. erlang.mk has to add this line to Makefile while creating new project or better solution to be used.

**Comment by essen** [comment]
Thanks!

**Comment by essen** [comment]
Most recent commit b6b3111b338b7e1d3ad9a1476e90ea106b7d73ef will do this automatically without having to modify the Makefile. Thanks!
