### ISSUE TITLE
PROJECT_ENV_FILE = src/env.src env variables not avaiable

### ISSUE THREAD

**Issue by opunix** [ninenines/erlang.mk#830]
the [Makefile](https://github.com/opunix/oauth2_example/blob/master/Makefile) and the project are also on github so you can build it yourself if you want to check it directly.

After ```make run``` if you run ```appllication:get_all_env()``` in the erlc it returns an empty list on debian burst AMD64 with Erlang/OTP 21 [erts-10.2.4]

**Comment by essen** [comment]
In the shell `application:get_all_env()` returns the environment for `kernel`. The app name must be given explicitly to check that it worked.
