### ISSUE TITLE
make packages failing

### ISSUE THREAD

**Issue by stephb9959** [ninenines/erlang.mk#832]
Just tried a git clone and make packages straight this morning and it looks like the build fails with:

```

The last 20 or so lines are ...
...
Loading application ranch
  Loading module ranch
  Loading module ranch_acceptor
  Loading module ranch_acceptors_sup
  Loading module ranch_app
  Loading module ranch_conns_sup
  Loading module ranch_listener_sup
  Loading module ranch_protocol
  Loading module ranch_server
  Loading module ranch_ssl
  Loading module ranch_sup
  Loading module ranch_tcp
  Loading module ranch_transport
pkg-aberth: Check that no erl_crash.dump file exists
pkg-aberth: OK; delete the build directory
pkg-active: Bootstrap a new OTP library in packages/active_pkg
pkg-active: Add package active to the Makefile
pkg-active: Compile package active
make[1]: *** [Makefile:245: pkg-active] Error 1
make[1]: Leaving directory '/Users/stephb/Desktop/Dropbox/dhcp/erlang.mk/test'
make: *** [Makefile:63: packages] Error 2
```

Don't know if I am doing something wrong or this should work straight out?  

Thanks

**Comment by essen** [comment]
Try `make packages -k`. It's normal that some builds fail due to missing system dependencies, unsupported environment or just plain lack of support from Erlang.mk.

Alternatively build a single project as `make check p=cowboy`, potentially with verbose options to figure things out, like `make check p=cowboy V=4`.

**Comment by stephb9959** [comment]
Thanks Loïc…

Trying this right now. I was trying to add a ne wpackage last night and it failed in make check p=my_new_package..

Just want to say thank you for all this hard work. I come from the C/C++ side and been living in makefiles for 20 years. So this is the perfect environment for me to live in.

Hopefully I can contribute one day.

Thanks again for this hard work. Truly appreciated. 

BTW, looks like this command is working so far...

**Comment by essen** [comment]
Yeah then the last command is best, though I don't remember if `V=4` is what you want, maybe start with lower and increase. I'm mostly checking tests these days, though I'll soon be able to enable building everything every night! :-)
