### ISSUE TITLE
escript-zip packs all dependencies in multi-apps project

### ISSUE THREAD

**Issue by stchar** [ninenines/erlang.mk#842]
Hi, one of my application in multi-apps project should be shipped as escript.

`escript-zip` packs all decencies of the project, while I expect it would pack only dependencies of this particular application.

I can provide a patch and testcases if you confirm that my expectations are correct.

**Comment by essen** [comment]
It's possible that it's too naive. A test case would be great, you can probably adapt one of those in `test/plugin_escript.mk`.
