### ISSUE TITLE
Failed to build Prometheus.erl v4.4.0

### ISSUE THREAD

**Issue by picaoao** [ninenines/erlang.mk#844]
Hi, I'm having issues building https://github.com/deadtrickster/prometheus.erl (v4.4.0) as a dependency of a project with erlang.mk.

If I clone the dependency and compile it without Erlang.mk, and with rebar3, it works.
Can you help ?

Here is the error I get:

```
DEP    prometheus (v4.4.0)
gmake[1]: Entering directory '/Users/riol/dev/td/presence-mqtt/deps/prometheus'
 DEPEND prometheus.d
 PROTO  prometheus_model.proto
{"init terminating in do_boot",{undef,[{protobuffs_compile,generate_source,["src/model/prometheus_model.proto",[{output_include_dir,"./include"},{output_src_dir,"./src"}]],[]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,670}]},{erl_eval,eval_lc1,6,[{file,"erl_eval.erl"},{line,696}]},{erl_eval,eval_generate,7,[{file,"erl_eval.erl"},{line,725}]},{erl_eval,eval_lc,6,[{file,"erl_eval.erl"},{line,682}]},{erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,122}]},{init,start_it,1,[]},{init,start_em,1,[]}]}}
init terminating in do_boot ({undef,[{protobuffs_compile,generate_source,[[_],[_]],[]},{erl_eval,do_apply,6,[{_},{_}]},{erl_eval,eval_lc1,6,[{_},{_}]},{erl_eval,eval_generate,7,[{_},{_}]},{erl_eval,ev

Crash dump is being written to: erl_crash.dump...done
```

**Comment by essen** [comment]
Try adding this to your Makefile:

```
BUILD_DEPS = protobuffs
```

And report back.

**Comment by picaoao** [comment]
it works ! :) 

How come I need to put it explicitly ? and it doesn't understand that from rebar.config ?

**Comment by essen** [comment]
Probably fails to detect it for rebar3 projects. Keep the ticket open I'll fix it later. Thanks!

**Comment by essen** [comment]
It appears that the correct fix for this is to not compile the proto files if there are neither `gpb` or `protobuffs`. I am testing the fix and will push it soon.

**Comment by essen** [comment]
Pushed. The workaround should no longer be necessary. Thanks!
