### ISSUE TITLE
include_lib does not see DEP from app in APPS_DIR 

### ISSUE THREAD

**Issue by picaoao** [ninenines/erlang.mk#846]
Hi

I have several applications in the APPS_DIR (apps).
In one of them, lets say I call it `my_app`, I declare in the Makefile the following:

```
DEPS_DIR ?= $(CURDIR)../../deps

DEPS = my_dep
dep_my_dep = git my_dep_location
...
include erlang.mk
...
```

The idea is that I can run `make` directly from the `apps/my_app` folder to compile it or run tests.

However, in `my_app` src I use `include_lib("my_dep/some_path/some_file.hrl")`.
When I try to run `make ct` to run the `ct` tests, it fails to locate the header file when compiling.

So the deps are being fetched and compiled in ../../deps, but somehow when running/compiling  the tests it is not able to locate the file.

If I copy manually the `deps` to the `apps/my_app`, it works.

Am I doing something wrong ?

**Comment by essen** [comment]
You probably need more than just `DEPS_DIR`. Try also adding those:

```
ROOT_DIR ?= ../..
APPS_DIR ?= ..
```

That's what the bootstrapping does in the most recent Erlang.mk. Create a new app with `make new-app` for an example.

**Comment by essen** [comment]
Oh and `include $(ROOT_DIR)/erlang.mk` if you don't want the file in all apps.

**Comment by picaoao** [comment]
Unfortunately I still have the same issues if I add those... 

Also I need to add the `$(CURDIR)`, otherwise it won't resolve well the generation of the lib paths.

```
ROOT_DIR ?= $(CURDIR)/../..
APPS_DIR ?= $(CURDIR)/..
DEPS_DIR ?= $(CURDIR)../../deps
```

**Comment by picaoao** [comment]
I think I found the root cause...

Everything is working ! 
I had a cuttlefish helper that was using "deps" (hardcoded) to load some configuration for the tests.
After I changed it to use the $(DEPS_DIR) env from OS, it started working well !

Sorry for the hassle, and thanks for the prompt feedback !

**Comment by essen** [comment]
Cheers, glad to hear!
