### ISSUE TITLE
make eunit, apps and include_lib don't play nicely

### ISSUE THREAD

**Issue by rlipscombe** [ninenines/erlang.mk#849]
I generated an 'apps'-style repo with two projects, 'top' and 'mid'. 'mid' depends on 'amqp_client' and uses 'include_lib' to pull in a file from it.

`make distclean && make` results in a successful build.

`make distclean && make eunit` results in failure:

> src/mid_app.erl:7: can't find include lib "amqp_client/include/amqp_client.hrl"

See https://github.com/rlipscombe/erlang-mk-include-prob

**Comment by essen** [comment]
Must be missing some paths somewhere, I'll try to add a test tomorrow once I'm done fixing up Windows.

**Comment by essen** [comment]
On your test project this seems to fix it:

``` patch
diff --git a/erlang.mk b/erlang.mk
index ef500ed..8336566 100644
--- a/erlang.mk
+++ b/erlang.mk
@@ -5468,7 +5468,7 @@ endif
 # We only care about compiling the current application.
 ifdef IS_APP
 test-build-app:: ERLC_OPTS=$(TEST_ERLC_OPTS)
-test-build-app:: test-deps
+test-build-app:: deps test-deps
 ifneq ($(wildcard $(TEST_DIR)),)
    $(verbose) $(MAKE) --no-print-directory test-dir ERLC_OPTS="$(call escape_dquotes,$(TEST_ERLC_OPTS))"
 endif
```

**Comment by essen** [comment]
Merged, thanks!
