### ISSUE TITLE
relx.beam failed: badfile

### ISSUE THREAD

**Issue by eugene-panferov** [ninenines/erlang.mk#852]
deleted everything.
walk by the "getting started"

wget https://erlang.mk/erlang.mk
2019-07-03 18:42:30 (11.6 MB/s) - 'erlang.mk' saved [454/454]

make -f erlang.mk bootstrap bootstrap-rel
git clone --depth 1 https://github.com/ninenines/erlang.mk .erlang.mk.build
Cloning into '.erlang.mk.build'...
remote: Enumerating objects: 604, done.
remote: Counting objects: 100% (604/604), done.
remote: Compressing objects: 100% (598/598), done.
remote: Total 604 (delta 6), reused 477 (delta 3), pack-reused 0
Receiving objects: 100% (604/604), 227.24 KiB | 0 bytes/s, done.
Resolving deltas: 100% (6/6), done.
if [ -f build.config ]; then cp build.config .erlang.mk.build; fi
cd .erlang.mk.build && make
make[1]: Entering directory '/home/silly/fertiledating/app/.erlang.mk.build'
2018/12/03: Changelog introduced.

2018/12/03: Relx has been updated to v3.27.0.

2018/12/03: Dependencies are no longer always rebuilt by
            default. Please check the documentation for
            information. A quick fix if this causes an
            issue is to add `FULL = 1` at the top of your
            Makefile.

2018/12/06: Change the default COVER_DATA_DIR to be the
            same as COVER_REPORT_DIR.

2019/06/20: `list-deps` now includes local applications
            found in the `APPS_DIR` directory.
make[1]: Leaving directory '/home/silly/fertiledating/app/.erlang.mk.build'
cp .erlang.mk.build/erlang.mk ./erlang.mk
rm -rf .erlang.mk.build

 make run
 DEPEND app.d
 ERLC   app_app.erl app_sup.erl
 APP    app

=ERROR REPORT==== 3-Jul-2019::18:42:51 ===
Loading of /home/silly/fertiledating/app/.erlang.mk/relx/relx/ebin/relx.beam failed: badfile

=ERROR REPORT==== 3-Jul-2019::18:42:51 ===
beam/beam_load.c(1287): Error loading module relx:
  mandatory chunk of type 'Atom' not found

escript: exception error: undefined function relx:main/1
  in function  escript:run/2 (escript.erl, line 757)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1 
  in call from init:do_boot/3 
erlang.mk:6989: recipe for target 'relx-rel' failed
make: *** [relx-rel] Error 127

**Comment by essen** [comment]
What Erlang version are you using?

**Comment by eugene-panferov** [comment]
oh! sorry, i always forget to report versions.
Erlang/OTP 19 [erts-8.2.1] [source] [64-bit] [smp:4:4]

**Comment by essen** [comment]
Looks like it has been compiled for Erlang/OTP 20+.

**Comment by essen** [comment]
I have uploaded a corrected version of the file. If you restart again it should work. Let me know, thanks!

**Comment by eugene-panferov** [comment]
which file? restart what?
i removed everything.
and repeat "getting started" from wget https://erlang.mk/erlang.mk
same result.

i am afraid i am doing something unrelated to your corrected file.

**Comment by essen** [comment]
Hm it works for me with OTP-19.0.7. are you sure you removed everything? Including `.erlang.mk`?

**Comment by eugene-panferov** [comment]
"rm -rf ./*"
maybe some weird cache screwed my wget...

**Comment by eugene-panferov** [comment]
ah! i made it wget https://erlang.mk/erlang.mk?xxx=1
and now it works :)
thanks
