### ISSUE TITLE
tutorial: passing args to "erl"

### ISSUE THREAD

**Issue by eugene-panferov** [ninenines/erlang.mk#854]
reading the erlang.mk tutorial, I am failing to find out how to pass command line arguments to the "erl" command, OR OTHERWISE set a node-name to the erlang system associated with the release.

P.S. Or maybe i am missing the whole idea how to run erlang.mk releases.

**Comment by essen** [comment]
Because they're Relx releases, so the documentation is light in Erlang.mk. You'll need to edit the `config/vm.args` file.

**Comment by eugene-panferov** [comment]
but this file was generated by erlang.mk -- is it legit to edit it?
(it was a natural expectation: there must be a Makefile variable that erlang.mk passes into this file)

**Comment by essen** [comment]
Those two files are configuration files that Relx includes in the release. They're definitely OK to edit. The other relevant file is `relx.config`. At this time you can't configure these things from the Makefile itself.

**Comment by eugene-panferov** [comment]
Thanx.
