### ISSUE TITLE
Dependencies not compiling (interdependent dependencies)

### ISSUE THREAD

**Issue by stephb9959** [ninenines/erlang.mk#857]
Hi,

I am building a complex with multiple libraries and applications. I am coming across a pattern and do not know how to address this and allow it to compile. Here is the problem:

APPA depends on some structures in APPB and APPC and LIBD
LIBD depends also on APPB

When compiling LIBD on its own, no issues. It is saved in github and I added some fake entries in my local erlang.mk to fetch this from github. 

I can compile APPB and APPC.

When it comes to compiling APPA, is can compile APPB and APPC. But when it comes to compiling LIBD, it fails, not being able to find the include files needed from APPB. 

Now of course, when I look at APPA, in the deps dir, I can find LIBD, but under LIBD, I cannot find its dependencies. So the relative include path I was using in the .erl file "-include("../deps/appb/include/blah.hrl") fails. So I added a compile flag in LIBD's makefile so it still compiles on its own. But that still fails when compiling APPA. When I add the same ERLC_OPTS flag to at the top, it does not seem that that ERLC_OPTS flag gets passed to the lower deps. So the LIBD compile fails. 

Now, if I was able to force erlang.mk to download the dependencies of the lib as deps under the top ;evel deps, then this would work. If I could pass ERLC_OPTS to the lowe compiles, that would work. 

I am kind of baffled by all this. 

Anything I am missing in settings in erlang.mk? I have been going back and forth in the documentation but I cannot seem to find the solution.

Thanks

**Comment by essen** [comment]
I'm not totally sure I understand the question, but to include files from a different library or application named `appb` you need to use `-include_lib("appb/include/blah.hrl").` so that it looks for the application wherever it is located.

**Comment by stephb9959** [comment]
Hi Loïc,

It never occurred to me to use include_lib() with my own apps. That did solve the problem. I did not realize that the whole make system would remap include_lib() to the deps/ dir for example. So, thank you for educating me. I have changed all my code now and everything compiles and works just fine. 

Thanks again.
