### ISSUE TITLE
crash: bin/server ping

### ISSUE THREAD

**Issue by pankajsoni19** [ninenines/erlang.mk#864]
I am using erlang.mk. The system is under high load.

When I execute the command, I keep getting this.

```
root@host:/opt/server# bin/server ping
Failed to write to erl_child_setup: 32

Crash dump is being written to: erl_crash.dump...done
```

the hosts file is correct, so is the cookie.  Can you give me pointers on what to look fro..

**Comment by essen** [comment]
You are getting `EPIPE: 32 - Broken pipe` with description `The local end has been shut down on a connection oriented socket.`. I'm not sure where to go from here, that's a question better asked on the Erlang mailing lists.

This is not an issue specific to Erlang.mk as Erlang.mk uses Relx for releases handling. But I don't think this is an issue specific to Relx either considering the error occurs in `erts/emulator/sys/unix/sys_drivers.c`.

Good luck!
