### ISSUE TITLE
HOWTO: Need to run additional makefile after make rel

### ISSUE THREAD

**Issue by stephb9959** [ninenines/erlang.mk#865]
Hi,

This is not a bug. I would like to understand how I can run another make after make rel. For example, I need to do Debian packaging after make rel. I have built a packaging directory with its own Makefile. What is the best way to do this with erlang.mk? I have tried a few things and I am not ending up with the desired outcome. 

btw, if there is a better place to ask for such questions, please let me know. 

Thanks

**Comment by essen** [comment]
At the end of your Makefile, add something like:

``` make
rel::
    $(MAKE) -C packaging/
```

**Comment by stephb9959** [comment]
Beautiful! That does it!

Thanks again Loïc!
