### ISSUE TITLE
Build fails with {"init terminating in do_boot"...

### ISSUE THREAD

**Issue by stephb9959** [ninenines/erlang.mk#868]
Hi,

I have a project that builds just fine on Catalina and fails on Debian 10. Same version of Erlang, same checkout, same exact code. I am using the latest erlang.mk file. 

I have tried to remove almost anything in the makefile to no avail, checked permissions, removed all deps, ... a bit lost where to go from here. 

So the build stops just before the final ERLC command to compile the project .erl files. So all deps compile, then I get:
DEPEND dpaas_mgr.d

Then the crash.

```
{"init terminating in do_boot",{{case_clause,{error,emfile}},[{erl_eval,case_clauses,6,[{file,"erl_eval.erl"},{line,968}]},{erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,126}]},{erl_eval,eval_lc1,6,[{file,"erl_eval.erl"},{line,706}]},{erl_eval,eval_generate,7,[{file,"erl_eval.erl"},{line,735}]},{erl_eval,eval_lc,6,[{file,"erl_eval.erl"},{line,692}]},{erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,126}]},{init,start_it,1,[]}]}}
init terminating in do_boot ({{case_clause,{error,emfile}},[{erl_eval,case_clauses,6,[{_},{_}]},{erl_eval,exprs,5,[{_},{_}]},{erl_eval,eval_lc1,6,[{_},{_}]},{erl_eval,eval_generate,7,[{_},{_}]},{erl_e
```

I have looked at other problems with do_boot and I could not find a solution.

Thanks for the help.

**Comment by essen** [comment]
`emfile` means it ran out of file descriptors, you need to increase the limit probably, via `ulimit -n` or similar.

**Comment by stephb9959** [comment]
Hmmm...

Well, that was about the only thing I did not check... and that was the problem. I changed the /etc/security/limits.conf file and she compiles again...

Thanks again Loïc, super fast and accurate answer, as usual.
