### ISSUE TITLE
BestPractice: How to include multiple apps as library  in build

### ISSUE THREAD

**Issue by stephb9959** [ninenines/erlang.mk#870]
Hi,

Just wondering how to do this the right way...

I project depends on code from multiple applications. If I include in DEPS, then the applications are included in the build, code is in the release, all good. However, when the project is started, it will start all the applications it depends on. I just want to be able to use the code in the applications as libraries. If I only include in BUILD_DEPS, the compiled code does not make it to the release. 

Just looking for your wisdom on how to do this the right way: basically, use the code from an application as a library.

Thanks

**Comment by essen** [comment]
You have to include in BUILD_DEPS and add the applications to the list in relx.config:

``` erlang
{release, {hello_world_example, "1"}, [hello_world, my_other_app]}.
{extended_start_script, true}.
```
