### ISSUE TITLE
Faster $(ERL)

### ISSUE THREAD

**Issue by essen** [ninenines/erlang.mk#874]
`+SDio 1 +S 1 -mode minimal` might be better in some cases. The latter in particular should not be applied across the board but on a case by case basis since it doesn't start distribution, `inet_db` and such.

**Comment by crownedgrouse** [comment]
-noshell   even faster

**Comment by crownedgrouse** [comment]
Documentation may  recommand to set this in ESCRIPT_EMU_ARGS in most case ...

**Comment by essen** [comment]
Erlang.mk already uses `-noinput`.

**Comment by crownedgrouse** [comment]
I just saw '-start_epmd false' which spare a bit more time, but not sure if available on all release...

**Comment by essen** [comment]
I have just merged a change that now disables the distribution (entirely, not just epmd) and reduces the maximum ports/processes to 1024. `-mode minimal` was just too much in some cases so I didn't apply it to not be too disruptive. Also the benefits from it are not huge anyway as far as noticeable improvements go.
