### ISSUE TITLE
Package missing from release

### ISSUE THREAD

**Issue by pankajsoni19** [ninenines/erlang.mk#891]
this is my make file. 
there is a dependency `fcm` which depends on `shotgun`. 

In the release that is generated `make rel` in folder `_rel/server/ilb/` the dependency is not included.

below project :: `server` makefile
```
PROJECT = server
PROJECT_VERSION = $(shell head -n 1 relx.config | awk '{split($$0, a, "\""); print a[2]}')

COMPILE_FIRST = gen_mod

LOCAL_DEPS = inets mnesia os_mon
DEPS = lager fcm

dep_lager = git https://github.com/erlang-lager/lager 3.8.0
dep_fcm = git https://github.com/pankajsoni19/fcm-erlang.git 1.1.0

include erlang.mk

ERLC_OPTS := $(filter-out -Werror,$(ERLC_OPTS))

ERLC_COMPILE_OPTS= +'{parse_transform, lager_transform}'
ERLC_OPTS += $(ERLC_COMPILE_OPTS)
TEST_ERLC_OPTS += $(ERLC_COMPILE_OPTS)

```

**Comment by essen** [comment]
Which dependency is not included?

**Comment by pankajsoni19** [comment]
`shotgun` is missing included that is specified in `fcm` makefile

https://github.com/pankajsoni19/fcm-erlang/blob/master/Makefile

**Comment by essen** [comment]
Well your `fcm` application has a `.app.src` file that does not include `shotgun`. See https://github.com/pankajsoni19/fcm-erlang/blob/master/src/fcm.app.src

**Comment by pankajsoni19** [comment]
ahh.. i do not create those files. I think rebar plugin added that file, and I never really remembered. Sorry for this.

**Comment by essen** [comment]
No problem. If there is a `.app.src` then you need to update it. If you remove it then Erlang.mk will take care of everything on its own.
