### ISSUE TITLE
Easily add custom templates

### ISSUE THREAD

**Issue by benjamin-bergia** [ninenines/erlang.mk#899]
Hi,
I have a bunch of templates that I would like to use instead the the gen_* shipping with erlang.mk. Is there any simple way to use my own templates? From what I understand, I should write a plugin and use it to my `DEP_PLUGINS`, am I right? Or is there a better way to do it?

**Comment by essen** [comment]
Plugin if a separate project (like Cowboy master currently does), or just put/include them in your Makefile directly.

**Comment by benjamin-bergia** [comment]
Thanks.
I managed to get it to work with a plugin. I will just write it her if somebody else look for it in the future:
```makefile
define tpl_yourtemplatename
....
endef
```
To define a template

**Comment by essen** [comment]
Yes it's just a variable. Recent Make versions could also do this if you have template files:

``` make
tpl_yourtemplatename = $(file <yourtemplatefile)
```
