### ISSUE TITLE
Application names with custom characters

### ISSUE THREAD

**Issue by pinicarus** [ninenines/erlang.mk#904]
Applications names are restricted to `[a-z0-9_]*` by the check on the [bootstrap](https://github.com/ninenines/erlang.mk/blob/master/plugins/bootstrap.mk#L414) and [bootstrap-lib](https://github.com/ninenines/erlang.mk/blob/master/plugins/bootstrap.mk#L431) rules.

If properly quoted, application names as atoms could contain any character.

Is there a particular reason why only those characters are allowed ?
If not, I can work on a PR to lift this restriction.

**Comment by essen** [comment]
Not any character no, for example `-` is not allowed because Erlang considers everything after the dash to be the version number in the application's path. Which special characters do you have in mind?

**Comment by pinicarus** [comment]
I wanted to use dots to prefix my applications names by a kind of namespacetto avoid collisions.

There are probably other use cases that could benefit a relaxed rule here : upper case letters, colon, @ (which is valid in unquoted atoms).

Obviously not all characters should be allowed : dash (as you mentioned), slash and backslash (because the application name also appears in its directory name).

I would be happy to contribute this change, but just want to be sure it would be any worth.

**Comment by essen** [comment]
Right but the application name is also used for the `_app` and `_sup` module and those do not accept dots.

Note that Erlang.mk doesn't mind if your application has a special character in its name, it will only refuse to create it. You can still create it manually.

**Comment by pinicarus** [comment]
Ah ! Yes indeed, renaming the application afterwards works fine. I can deal with this.

Thanks for your time and help, `erlang.mk` is really great !
