### ISSUE TITLE
the command: make relup doesn't create all  .appup configs 

### ISSUE THREAD

**Issue by chunkitX** [ninenines/erlang.mk#912]
here is my .appup file:

{"0.9.0",
 [
  {"0.7.0",[{update,echo_protocol,soft}]},
  {"0.8.0",[{restart_application, ranch},{restart_application, uptest}]}
 ],
 [
  {"0.7.0",[{update,echo_protocol,soft}]},
  {"0.8.0",[{restart_application,ranch},{restart_application,uptest}]}
 ]
}.

when I make relup successful, but the relup contents are:

%% coding: utf-8
{"9",
 [{"8",[],
   [{load_object_code,{ranch,"1.2.1",
                             [ranch,ranch_acceptor,ranch_acceptors_sup,
                              ranch_app,ranch_conns_sup,ranch_listener_sup,
                              ranch_protocol,ranch_server,ranch_ssl,ranch_sup,
                              ranch_tcp,ranch_transport]}},
    {load_object_code,{uptest,"0.9.0",[echo_protocol,uptest_app,uptest_sup]}},
    point_of_no_return,
    {apply,{application,stop,[ranch]}},
    {remove,{ranch,brutal_purge,brutal_purge}},
    {remove,{ranch_acceptor,brutal_purge,brutal_purge}},
    {remove,{ranch_acceptors_sup,brutal_purge,brutal_purge}},
    {remove,{ranch_app,brutal_purge,brutal_purge}},
    {remove,{ranch_conns_sup,brutal_purge,brutal_purge}},
    {remove,{ranch_listener_sup,brutal_purge,brutal_purge}},
    {remove,{ranch_protocol,brutal_purge,brutal_purge}},
    {remove,{ranch_server,brutal_purge,brutal_purge}},
    {remove,{ranch_ssl,brutal_purge,brutal_purge}},
    {remove,{ranch_sup,brutal_purge,brutal_purge}},
    {remove,{ranch_tcp,brutal_purge,brutal_purge}},
    {remove,{ranch_transport,brutal_purge,brutal_purge}},
    {purge,[ranch,ranch_acceptor,ranch_acceptors_sup,ranch_app,
            ranch_conns_sup,ranch_listener_sup,ranch_protocol,ranch_server,
            ranch_ssl,ranch_sup,ranch_tcp,ranch_transport]},
    {load,{ranch,brutal_purge,brutal_purge}},
    {load,{ranch_acceptor,brutal_purge,brutal_purge}},
    {load,{ranch_acceptors_sup,brutal_purge,brutal_purge}},
    {load,{ranch_app,brutal_purge,brutal_purge}},
    {load,{ranch_conns_sup,brutal_purge,brutal_purge}},
    {load,{ranch_listener_sup,brutal_purge,brutal_purge}},
    {load,{ranch_protocol,brutal_purge,brutal_purge}},
    {load,{ranch_server,brutal_purge,brutal_purge}},
    {load,{ranch_ssl,brutal_purge,brutal_purge}},
    {load,{ranch_sup,brutal_purge,brutal_purge}},
    {load,{ranch_tcp,brutal_purge,brutal_purge}},
    {load,{ranch_transport,brutal_purge,brutal_purge}},
    {apply,{application,start,[ranch,permanent]}},
    {apply,{application,stop,[uptest]}},
    {remove,{echo_protocol,brutal_purge,brutal_purge}},
    {remove,{uptest_app,brutal_purge,brutal_purge}},
    {remove,{uptest_sup,brutal_purge,brutal_purge}},
    {purge,[echo_protocol,uptest_app,uptest_sup]},
    {load,{echo_protocol,brutal_purge,brutal_purge}},
    {load,{uptest_app,brutal_purge,brutal_purge}},
    {load,{uptest_sup,brutal_purge,brutal_purge}},
    {apply,{application,start,[uptest,permanent]}}]}],
[{"8",[],
   [{load_object_code,{ranch,"1.2.1",
                             [ranch,ranch_acceptor,ranch_acceptors_sup,
                              ranch_app,ranch_conns_sup,ranch_listener_sup,
                              ranch_protocol,ranch_server,ranch_ssl,ranch_sup,
                              ranch_tcp,ranch_transport]}},
    {load_object_code,{uptest,"0.8.0",[echo_protocol,uptest_app,uptest_sup]}},
    point_of_no_return,
    {apply,{application,stop,[ranch]}},
    {remove,{ranch,brutal_purge,brutal_purge}},
    {remove,{ranch_acceptor,brutal_purge,brutal_purge}},
    {remove,{ranch_acceptors_sup,brutal_purge,brutal_purge}},
    {remove,{ranch_app,brutal_purge,brutal_purge}},
    {remove,{ranch_conns_sup,brutal_purge,brutal_purge}},
    {remove,{ranch_listener_sup,brutal_purge,brutal_purge}},
    {remove,{ranch_protocol,brutal_purge,brutal_purge}},
    {remove,{ranch_server,brutal_purge,brutal_purge}},
    {remove,{ranch_ssl,brutal_purge,brutal_purge}},
    {remove,{ranch_sup,brutal_purge,brutal_purge}},
    {remove,{ranch_tcp,brutal_purge,brutal_purge}},
    {remove,{ranch_transport,brutal_purge,brutal_purge}},
    {purge,[ranch,ranch_acceptor,ranch_acceptors_sup,ranch_app,
            ranch_conns_sup,ranch_listener_sup,ranch_protocol,ranch_server,
            ranch_ssl,ranch_sup,ranch_tcp,ranch_transport]},
    {load,{ranch,brutal_purge,brutal_purge}},
    {load,{ranch_acceptor,brutal_purge,brutal_purge}},
    {load,{ranch_acceptors_sup,brutal_purge,brutal_purge}},
    {load,{ranch_app,brutal_purge,brutal_purge}},
    {load,{ranch_conns_sup,brutal_purge,brutal_purge}},
    {load,{ranch_listener_sup,brutal_purge,brutal_purge}},
    {load,{ranch_protocol,brutal_purge,brutal_purge}},
    {load,{ranch_server,brutal_purge,brutal_purge}},
    {load,{ranch_ssl,brutal_purge,brutal_purge}},
    {load,{ranch_sup,brutal_purge,brutal_purge}},
    {load,{ranch_tcp,brutal_purge,brutal_purge}},
    {load,{ranch_transport,brutal_purge,brutal_purge}},
    {apply,{application,start,[ranch,permanent]}},
    {apply,{application,stop,[uptest]}},
    {remove,{echo_protocol,brutal_purge,brutal_purge}},
    {remove,{uptest_app,brutal_purge,brutal_purge}},
    {remove,{uptest_sup,brutal_purge,brutal_purge}},
    {purge,[echo_protocol,uptest_app,uptest_sup]},
    {load,{echo_protocol,brutal_purge,brutal_purge}},
    {load,{uptest_app,brutal_purge,brutal_purge}},
    {load,{uptest_sup,brutal_purge,brutal_purge}},
    {apply,{application,start,[uptest,permanent]}}]}]}.

I can upgrade  from 8 to 9, but don't do it  from 7 to 9
I saw the code in sys_tools:

make_relup(ReleaseName, UpNameList, DownNameList) ->
    systools_relup:mk_relup(ReleaseName, UpNameList, DownNameList, []).
make_relup(ReleaseName, UpNameList, DownNameList, Opts) ->
    systools_relup:mk_relup(ReleaseName, UpNameList, DownNameList, Opts).
whether is there  arguments NameList I need config?

**Comment by essen** [comment]
@juhlig Can you take a look?

**Comment by juhlig** [comment]
@chunkitX The `make relup` of `erlang.mk` delegates this task to [`relx`](https://github.com/erlware/relx):
```
$(verbose) $(RELX) $(if $(filter 1,$V),-V 3) -c $(RELX_CONFIG) $(RELX_OPTS) release
...
$(verbose) $(RELX) $(if $(filter 1,$V),-V 3) -c $(RELX_CONFIG) $(RELX_OPTS) relup $(if $(filter 1,$(RELX_TAR)),tar)
```
which boils down to something like
```
.erlang.mk/relx -c relx.config release
...
.erlang.mk/relx -c relx.config relup
```
That is, it builds a release using the current `relx.config` file and then a `relup`. `relx` tries to find the previous release and builds the `relup` considering only this last one, not any of the earlier ones. In essence, this means that you can only up-/downgrade from one release version to an adjacent one.

**Comment by chunkitX** [comment]
> @chunkitX The `make relup` of `erlang.mk` delegates this task to [`relx`](https://github.com/erlware/relx):
> 
> ```
> $(verbose) $(RELX) $(if $(filter 1,$V),-V 3) -c $(RELX_CONFIG) $(RELX_OPTS) release
> ...
> $(verbose) $(RELX) $(if $(filter 1,$V),-V 3) -c $(RELX_CONFIG) $(RELX_OPTS) relup $(if $(filter 1,$(RELX_TAR)),tar)
> ```
> 
> which boils down to something like
> 
> ```
> .erlang.mk/relx -c relx.config release
> ...
> .erlang.mk/relx -c relx.config relup
> ```
> 
> That is, it builds a release using the current `relx.config` file and then a `relup`. `relx` tries to find the previous release and builds the `relup` considering only this last one, not any of the earlier ones. In essence, this means that you can only up-/downgrade from one release version to an adjacent one.

Thanks for your reply 😊, It’s seems unnecessary to up/downgrade beyond adjacent version which easy to make mistake.
