### ISSUE TITLE
Recursive dependency resolution fails with rebar.lock version 1.2.0

### ISSUE THREAD

**Issue by philipcristiano** [ninenines/erlang.mk#922]
Adding a dependency that uses a rebar.lock version of `1.2.0` appears to fail to resolve recursive dependencies. [Deps parsing](https://github.com/ninenines/erlang.mk/blob/579e9f397bd3487777c19dd0fe85694b98ecd231/core/deps.mk#L385) appears to be set for only `1.1.0`. 

Discovered while trying to use [grpcbox v0.12.0](https://github.com/tsloughter/grpcbox/blob/v0.12.0/rebar.lock) while [v0.11.0](https://github.com/tsloughter/grpcbox/blob/v0.11.0/rebar.lock) (which has version `1.1.0` for rebar.lock) does resolve dependencies.

**Comment by essen** [comment]
Is there documentation showing the difference between 1.1.0 and 1.2.0 somewhere?

**Comment by philipcristiano** [comment]
Not that I've found, unfortunately. Old issues mention the lack of lockfile docs, but that seems like it hasn't really changed. I've found little information about 1.2.0 at all even.

**Comment by essen** [comment]
I've fixed that a while back. Closing, thanks!
