### ISSUE TITLE
erlang_decimal dep missing/private

### ISSUE THREAD

**Issue by ruanpienaar** [ninenines/erlang.mk#930]
980:PACKAGES += decimal
981:pkg_decimal_name = decimal
982:pkg_decimal_description = An Erlang decimal arithmetic library
983:pkg_decimal_homepage = https://github.com/tim/erlang-decimal
984:pkg_decimal_fetch = git
985:pkg_decimal_repo = https://github.com/tim/erlang-decimal
986:pkg_decimal_commit = master

This library has gone missing/private now..

**Comment by essen** [comment]
Probably more like this. I will remove most of the index at some point.

**Comment by ruanpienaar** [comment]
Cheers

**Comment by essen** [comment]
I've replaced it with https://github.com/egobrain/decimal for now. Closing, thanks!
