### ISSUE TITLE
bug: vsn replacement with file syntax in app.src from rebar is not applied 

### ISSUE THREAD

**Issue by benoitc** [ninenines/erlang.mk#933]
rebar3 allows a new way to replace the version in the `app.src` file by the content of another file.  The `vsn` value  is set to  `{file, "<NAMEOFFILE>"}` where the content is replaced at compile time by the content of the file `<NAMEOFFILE>`. Exeple with the [opentelemetry_ap](https://github.com/open-telemetry/opentelemetry-erlang/tree/main/apps/opentelemetry_api) application?. 

The app.src is:
```
{application,opentelemetry_api,
             [{description,"OpenTelemetry API"},
              {vsn,{file,"VERSION"}},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[]},
              {licenses,["Apache-2.0"]},
              {links,[{"GitHub",
                       "https://github.com/open-telemetry/opentelemetry-erlang-api"}]}]}.
```

The `.app` file should be:
```
{application,opentelemetry_api,
             [{description,"OpenTelemetry API"},
              {vsn,"1.0.0-rc.2"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules, ['opentelemetry','otel_baggage','otel_ctx','otel_propagator','otel_p
ropagator_http_b3','otel_propagator_http_w3c','otel_span','otel_tracer','otel_tracer_noop','
otel_tracer_provider']},
              {licenses,["Apache-2.0"]},
              {links,[{"GitHub",
                       "https://github.com/open-telemetry/opentelemetry-erlang-api"}]}]}.

```
 But with erlang.mk the `vsn` is still  `{file,"VERSION"}` after the compilation.

**Comment by lhoguin** [comment]
Thanks. In the meantime you may use a patch as we discussed. Here's an example Makefile doing an autopatch (in this case it creates a file in the dep's directory, you'll want to do the patch command instead):

```
PROJECT = z
PROJECT_DESCRIPTION = New project
PROJECT_VERSION = 0.1.0

DEPS = opentelemetry_api
dep_opentelemetry_api = git-subfolder https://github.com/open-telemetry/opentelemetry-erlang main apps/opentelemetry_api

include erlang.mk

autopatch-opentelemetry_api::
	touch $(DEPS_DIR)/opentelemetry_api/HELLO
```

You need to put the autopatch target after the include.

**Comment by essen** [comment]
`opentelemetry_api` no longer uses `{file, ...}` so I'll be closing this. Should anyone find another project that uses it I will fix it. Thanks!
