### ISSUE TITLE
git-subfolder only takes the folders on first level ?

### ISSUE THREAD

**Issue by benoitc** [ninenines/erlang.mk#934]
I tried to get the `opentelemetry` apllication from the subfolder `apps/opentelemetry` using this dependency line:

```
dep_opentelemetry git-subfolder https://github.com/open-telemetry/opentelemetry-erlang ac4bae7fbcb019a1c704ae5adda2e7d1b00befd9 apps/opentelemetry
``` 

But the makefile failed. and the dependency is not extracted. Is this expected. Is my line wrong?

**Comment by lhoguin** [comment]
You are missing a `=` after the `dep_opentelemetry`.

```
dep_opentelemetry = git-subfolder https://github.com/open-telemetry/opentelemetry-erlang ac4bae7fbcb019a1c704ae5adda2e7d1b00befd9 apps/opentelemetry
```

**Comment by benoitc** [comment]
Indeed I mistyped the example. With the suggested line I get the following
error though:

```
make[1]: Entering directory '/home/centos/kazoo_nga911-2/deps'
 DEP   opentelemetry_api (ac4bae7fbcb019a1c704ae5adda2e7d1b00befd9)
Error: Unknown or invalid dependency: opentelemetry_api.
make[1]: *** [../erlang.mk:4867:
/home/centos/kazoo_nga911-2/deps/opentelemetry_api] Error 78
make[1]: Leaving directory '/home/centos/kazoo_nga911-2/deps'
make: *** [Makefile:91: deps] Error 2
```

**Comment by essen** [comment]
The example Makefile I gave in the other ticket can build it just fine, at least on main. You might just need to `rm -rf deps/opentelemetry_api`.

**Comment by essen** [comment]
Well, minus the `file` tuple issue.

**Comment by essen** [comment]
If you still have a problem despite this please provide the git version, maybe it's related to that.

**Comment by essen** [comment]
Closing, thanks!
