### ISSUE TITLE
Auto-patching rebar project fails when version string starts with ">="

### ISSUE THREAD

**Issue by lukebakken** [ninenines/erlang.mk#938]
To demonstrate, clone https://github.com/lukebakken/gt-eq-dep-version and run `make`. When `gen_smtp` is auto-patched, this configuration in `deps/gen_smtp/rebar.config` trips up `erlang.mk`:

```
{deps, [{ranch, ">= 1.8.0"},
        {hut, "1.3.0"}]}.
```

...because it is turned into this in the generated `Makefile`

```
DEPS += ranch
dep_ranch = hex >= 1.8.0 ranch
```

I believe I need to expand the semver strings parsed by [this code](https://github.com/ninenines/erlang.mk/blob/d80984c1036ea81eb1f44b8d7cde85fc09b5e3c0/core/deps.mk#L413-L425).

Found while working on https://github.com/gotthardp/rabbitmq-email/issues/45

**Comment by essen** [comment]
Yes it just hasn't been implemented. You can add an `autopatch-gen_smtp::` target after `include erlang.mk` to correct this after autopatch has run.

**Comment by lukebakken** [comment]
Thanks @essen. If you haven't yet started on supporting additional semver strings let me know, I could spend some time on that.

**Comment by essen** [comment]
I have nothing in progress but there is probably some hacky support in the autopatch code.

**Comment by essen** [comment]
This should be done now.
