### ISSUE TITLE
Fast compile

### ISSUE THREAD

**Issue by GeorgiouJohn** [ninenines/erlang.mk#939]
Hi, 
I notice on command "make run" we have a delay when makes the tarball release. Is there a flag not to make the tarball release and having fast compiles and saving development time?
Thanks for your time.

**Comment by essen** [comment]
`make run RELX_TAR=0`

You can also set it in your Makefile, and we should probably set it automatically on `run`.

**Comment by GeorgiouJohn** [comment]
Thanks.
