### ISSUE TITLE
Set RELX_TAR=0 on "run" target

### ISSUE THREAD

**Issue by essen** [ninenines/erlang.mk#940]
Should not be necessary to generate it there.

**Comment by GeorgiouJohn** [comment]
Hi, 
I was looking yesterday all day for this flag in erlang.mk site and ninenines site and I was not able to find it. Where do you like to ask for this kind of questions?

**Comment by essen** [comment]
Ticket is fine for the time being.

**Comment by essen** [comment]
Done in https://github.com/ninenines/erlang.mk/pull/1019.
