### ISSUE TITLE
Struggling to manage deps with an Umbrella application

### ISSUE THREAD

**Issue by artman41** [ninenines/erlang.mk#944]
Hey,

I'm currently trying to setup my application to be an umbrella due to `code:priv_dir/1` not correctly finding the priv dir when running `make shell` (directory name =/= application name)

I'm trying to have it so that my Deps are downloaded & autopatched at the `ROOT_DIR` level which my umbrella app(s) can then use implicitly.

Is it possible to have all of the `DEPS` configuration in the `$(ROOT_DIR)/Makefile`?

I'm finding that if I export my `DEPS` var, it causes issues when grabbing the deps.

I've also tried defining my `DEPS` var in a separate Makefile that is included by both my `$(ROOT_DIR)/Makefile` and my `$(APPS_DIR)/app/Makefile` but that seems to cause an issue where the deps aren't fetched and my application can't compile because it can't see the deps.

Is there an example of an Umbrella configuration anywhere that does what I'm trying to accomplish?

My directory structure currently looks like

```
apps/
    app/
        src/
        include/
        priv/
        test/
        Makefile
Makefile
erlang.mk
relx.config
relx.config.script
```

Apologies if this is too vague, I can add more information where necessary.

**Comment by essen** [comment]
Shouldn't you just make the directory name be the application name instead? That sounds much easier than otherwise.

You can have DEPS (or BUILD_DEPS) in the top-level Makefile with umbrella but you will need to have them in LOCAL_DEPS in your application as well so they're added to the .app file. In any case this might still break in subtle ways depending on what you are doing, I'm not clear on that.

**Comment by artman41** [comment]
> You can have DEPS (or BUILD_DEPS) in the top-level Makefile with umbrella but you will need to have them in LOCAL_DEPS in your application as well so they're added to the .app file. In any case this might still break in subtle ways depending on what you are doing, I'm not clear on that.

Will give it a go and report back, ref the
> Shouldn't you just make the directory name be the application name instead? That sounds much easier than otherwise.

We have 3 repositories that began life as the same repo; the app name hasn't changed but the name it's stored under in git is different leading to this issue 😞

**Comment by pjk25** [comment]
The directory name for a git repo locally does not have to match the name of the repository. For instance, `git clone https://github.com/ninenines/erlang.mk.git erlang-mk`. I believe the same goes for git submodules.

**Comment by pjk25** [comment]
Oh, I see, I think I understood this backwards. So it sounds like there are multiple erlang apps with the same name (as in the second value of the outer tuple inside the `.app` file), but each sitting in differently named directories? I don't see how those could be loaded at the same time in erlang, but I suppose I never tried it.

**Comment by artman41** [comment]
So, couldn't get it to work by adding them to `LOCAL_DEPS`, solution ended up being defining `DEPS` at the base makefile level alongside the fetch definitions and also defining `DEPS` at the app makefile level

top-level
```
dep_dep1 = git git_repo_link vsn
dep_dep2 = git git_repo_link vsn

DEPS = dep1 dep2

include erlang.mk
```

app-level
```
DEPS = dep1 dep2
```

for `TEST_DEPS`, I had to add a `test-build::` target before including erlang.mk in the base makefile so that it was ran before erlang.mk attempted to build the project, I then had that target call `test-deps` to actually fetch them. At the app makefile level, I just defined the `TEST_DEPS` variable.

top-level
```
dep_dep1 = git git_repo_link vsn
dep_dep2 = git git_repo_link vsn

TEST_DEPS = dep1 dep2

test-build:: test-deps

include erlang.mk
```

app-level
```
TEST_DEPS = dep1 dep2
```

----

> Oh, I see, I think I understood this backwards. So it sounds like there are multiple erlang apps with the same name (as in the second value of the outer tuple inside the `.app` file), but each sitting in differently named directories? I don't see how those could be loaded at the same time in erlang, but I suppose I never tried it.

You're understanding correctly; using different names, here's an example

Orig. Project: `Fruit`, Erlang app name: `fruit`

Project Fork 1:  `Fruit-Apple`, Erlang app name: `fruit` 
Project Fork 2:  `Fruit-Apple`, Erlang app name: `fruit`
Project Fork 3:  `Fruit-Apple`, Erlang app name: `fruit`

What @essen is trying to say isn't specific to my use-case; he's explaining standard erlang behaviour.

When you execute `code:priv_dir(APP)`, erlang will look at it's code paths and search for a dir structure of either `.../$(APP)-*/priv` or `.../$(APP)/priv`.

His suggestion makes sense without context of my situation in that, if it's just a single project, it makes no sense to try and complicate the directory structure when you can just stick to the standards that are expected by Erlang.

What you'll find if you make a release using relx is that your application will end up in the `lib/` directory with the name `$(APP)-$(VERSION)` anyway so any solution you come up with is likely to be broken in some way.

I feel like my situation likely isn't a common one but the only way around it realistically is to have the project as an Umbrella where your top-level 'app' is differently named to the apps and/or libraries you have within your  `apps/` directory.

**Comment by artman41** [comment]
@pjk25 the projects aren't packaged and executed together but based on how `code:priv_dir/1` works, I'd imagine it would return the first element matching the pattern. From memory, it uses `filename:wildcard` to find the app directories - though, since you'll generally only land in the situation of multiple apps with the same name when doing an upgrade, I wonder whether it searches the list in reverse so that the first element is a later version.

Either way though, I think this issue can be closed unless @essen wants to use this as a reason to add support to erlang.mk for fetching deps in Umbrella Apps using the `dep_fetch` vars defined in the Top-Level Makefile 😉

**Comment by essen** [comment]
`LOCAL_DEPS` are applications found in `ERL_LIBS` that may not be otherwise known by Erlang.mk.

Closing, thanks!
