### ISSUE TITLE
Share include directory for multi app projects

### ISSUE THREAD

**Issue by benjamin-bergia** [ninenines/erlang.mk#951]
Hi,

I have noticed that when creating new apps in a project, the following bit is added to the Makefile of each of the apps:
```Makefile
DEPS_DIR ?= ../../deps
```
After working a bit with gpb in the past few days, I often endup compiling proto files and having to include the resulting hrl files in few of my apps.

I wonder if it wouldn't be nice to automatically add the following to the Makefile of local apps:
```Makefile
ERTS_INCLUDE_DIR += ../../include
```
So that all this files get automatically included in all the apps of the release.
I don't have enough experience to know if this could cause any kind of issues on production but if you are interested, I could try to open a PR for it.

**Comment by benjamin-bergia** [comment]
I guess the following config for gpb should also be altered a bit:
```
{output_include_dir, "./include"}
```

**Comment by essen** [comment]
If your includes are in `apps/my_app/include` then to include them from any other app in the project you can use `include_lib("my_app/include/proto.hrl")` is that not sufficient?

**Comment by benjamin-bergia** [comment]
I guess that would do it.
so for example having:
```bash
apps/
  a/
    include/
  b/
```
I would just use `include_lib("a/include/proto.hrl").` and add `a` to `LOCAL_DEPS` to ensure that it will be there?

**Comment by essen** [comment]
Yup.
