### ISSUE TITLE
How to customize name of output tarball?

### ISSUE THREAD

**Issue by 9812h** [ninenines/erlang.mk#959]
How can I do if I want the output tarball name to contain git commit ID?
For example: `project_release-<commit id>.tar.gz` instead of `project_release-1.tar.gz`.
Thank you for helping!

**Comment by essen** [comment]
The `1` comes from the release version in relx.config. You can probably set `"1"` to `{git, short}` instead (or `{git, long}` if you prefer). Not sure it's going to work with everything though as I haven't tested it.

**Comment by essen** [comment]
OK then I guess the code must be modified to support it, sorry.

**Comment by essen** [comment]
I suppose you can always edit the file automatically and put the commit as a string one way or another, perhaps extending `rel::`. But it's not built-in currently.

**Comment by 9812h** [comment]
I'll try your suggestion. Thank you for your helping!
