### ISSUE TITLE
Outdated plugin listed 

### ISSUE THREAD

**Issue by ahron1** [ninenines/erlang.mk#961]
In the [list of plugins page](https://erlang.mk/guide/plugins_list.html ) , it lists [reload.mk](https://github.com/bullno1/reload.mk ). 

Unfortunately, after the breaking changes in relx few weeks back, this no longer works. This module has been inactive for many years now, so it is unlikely to be updated. Better remove it from the list. This was the easiest to use, but maybe it can be replaced by another of the many hot reload modules available.

**Comment by ahron1** [comment]
[Sync](https://github.com/rustyio/sync) seems to work nicely. Might make sense to include that instead.

**Comment by essen** [comment]
Erlang.mk has a built-in reload feature now anyway. IIRC you just need to add `RELOAD=1`  when (re-)compiling.
