### ISSUE TITLE
make RELOAD=1 does not work

### ISSUE THREAD

**Issue by robinchew** [ninenines/erlang.mk#969]
Hello,

As subject describes, `make RELOAD=1` does not work. The output ends with:

```
{error, "Incomplete form (missing .<cr>)??"}
```

Tested on fresh install of Ubuntu Jammy on LXC container. Steps to reproduce while inside Ubuntu:
```
apt install erlang-nox wget git make curl

mkdir erlserver
cd erlserver
wget https://erlang.mk/erlang.mk
make -f erlang.mk bootstrap
make bootstrap-rel
make run
```
Do reload on separate terminal:
```
make RELOAD=1
```

**Comment by essen** [comment]
I can reproduce.

**Comment by essen** [comment]
OK it was because of the upgrade to Relx 4 changing things a little. Fixed, thanks! You can update Erlang.mk via `make erlang-mk` in your project if necessary.
