### ISSUE TITLE
Feature: Additional template modifiers

### ISSUE THREAD

**Issue by artman41** [ninenines/erlang.mk#970]
Currently, we're limited to templates that will create files under either `src/` or `$app/src/`

I think it'd be useful if templates could have a defined relative path and file extension so that we could create hrl templates & test templates.

e.g

**Template**
```
tpl_hrl_dir = include/
tpl_hrl_ext = .hrl
define tpl_hrl
-ifndef(HRL_$(n)).
-define(HRL_$(n), 1).

-endif.
endef
```

**Execution**
```
make new t=hrl n=my_file
```

`include/my_file.hrl`
```
-ifndef(HRL_my_file).
-define(HRL_my_file, 1).

-endif.
```

**Comment by essen** [comment]
That's a good idea. Not sure about how it should be implemented but patch is welcome!

**Comment by essen** [comment]
Closing in favor of the PR. Templates have been reworked, now all that's needed is updating the PR to include the few extra templates and template changes.
