### ISSUE TITLE
is Getting started instruction correct?

### ISSUE THREAD

**Issue by 221V** [ninenines/erlang.mk#971]
https://erlang.mk/guide/getting_started.html
```
2.2.1. Bash completion

If your preferred shell is Bash, a completion script is available. In order to install it, use the following commands:

$ mkdir ~/.bash_completion.d/
$ cd ~/.bash_completion.d/
$ wget -O erlang_mk https://raw.githubusercontent.com/ninenines/erlang.mk/master/etc/bash_completion

Then edit the file ~/.bash_completion and add:

for bcfile in ~/.bash_completion.d/* ; do
    . $bcfile
done
```
there are no any .bash_completion in my /home/user/
there are only /home/user/.bash_completion.d and file erlang_mk inside this directory..
so what to do?
how correct to begin work with erlang.mk ?
thank you

p.s. (l)ubuntu 22.04 lts

**Comment by essen** [comment]
If you don't have .bash_completion yet then create it and put the few lines given in it.
