### ISSUE TITLE
autopatching is overly verbose (missing $(verbose))

### ISSUE THREAD

**Issue by artman41** [ninenines/erlang.mk#981]
Somewhere in the spree of commits you merged @essen, a change to remove autopatching for rabbitmq also removed the `$(verbose)` preceding the bash

Before
https://github.com/ninenines/erlang.mk/blob/a1d7135f1349735569016adcb3e185be58c44042/core/deps.mk#L768-L788

After
https://github.com/ninenines/erlang.mk/blob/e1e3d15a1b211fc60b83557a2ea54ea3741f3e80/core/deps.mk#L841-L847

This results in a lot of debug info being printed to the terminal during the `deps` step as all the autopatching is executed

**Comment by artman41** [comment]
@essen done 👍

**Comment by essen** [comment]
Thanks!
