### ISSUE TITLE
example to run escript ininside a makefile

### ISSUE THREAD

**Issue by benoitc** [ninenines/erlang.mk#998]
Do you have an example on how to create an escript directly embedded  in a makefile?  How to point to it some dependencies and other stuffs?

**Comment by essen** [comment]
Not an escript per se but for embedding Erlang and using deps the following file is a good example: https://github.com/ninenines/erlang.mk/blob/master/plugins/proper.mk#L49

This uses code:addpath but alternatively you can specify flags when calling `$(erlang...)`: https://github.com/ninenines/erlang.mk/blob/master/plugins/erlydtl.mk#L59-L60

**Comment by benoitc** [comment]
thanks! this is very helpful :)
